### ISSUE TITLE
refine Users ❤️  🚀 

### ISSUE THREAD

**Issue by omeraplak** [refinedev/refine#1143]
We appreciate your support if you or your organization is using refine. You are welcome to leave replies about your product and organization here, which could become the confidence of maintainers, communication, and undecided watchers.

Recommended reply format:
```
- Product：
- Company or Organization: (if any)
- Link: (if any)
- Screenshot: (if any)
```

**Comment by kalib-code** [comment]
- Product: Prototype on Ecommerce using (admin (refine ), ecom (next.js)  ,  strapi (BE) , stripe (payment) )
- Company or Organization: Worshipsong Band
- Link: (not yet deployed)
- Youtube : https://youtu.be/5f8GTzu_h-Y

**Comment by Danjavia** [comment]
Product: SaaS for startups (Under construction Right now) (hasura, paddle, react) and obviously, Refine!
Company or Organization: Treecho Corp
Link: (not yet deployed)
Screenshot : [see image](https://ibb.co/dmy7V9p)

**Comment by KrishnaPG** [comment]
- Product：Credit Risk Rating Banking Application
- Company or Organization: Latize Pte Ltd
- Link: http://ulysses2.ddns.net/ (demo version)
- Screenshot: 
![image](https://user-images.githubusercontent.com/4610831/181876166-9fe4707b-2693-45b6-ba46-89ab0f251e5d.png)

**Comment by hridaya423** [comment]
@omeraplak does this count as an hacktoberfest contrib if we create a tutorial for refine?

**Comment by omeraplak** [comment]
> @omeraplak does this count as an hacktoberfest contrib if we create a tutorial for refine?

Creating a document will definitely count as a contribution. What kind of thing are you planning to do?

**Comment by hridaya423** [comment]
Getting Started / Creating a project vid tutorials

**Comment by hridaya423** [comment]
@omeraplak Here's my video: https://youtu.be/9pfmJV8JZfU

My Blog: https://dev.to/learnearnfun/introduction-to-refine-5c0h

**Comment by hridaya423** [comment]
Hope that counts!

**Comment by hridaya423** [comment]
@omeraplak Do the above count? Will i get swag?

**Comment by omeraplak** [comment]
Hey @hridaya423 ,
Thank you! We'll send a swag kit! Can you reach us on [Discord](https://discord.gg/refine)?

**Comment by hridaya423** [comment]
I already have joined the refine server :-)
