### ISSUE TITLE
[BUG] Clearing filter through the clear button in filterDropdown resets operator to eq with no way to switch it back

### ISSUE THREAD

**Issue by IgnusG** [refinedev/refine#1386]
**Describe the bug**
The clear button in the filterDropdown resets not just the value but also the operator always to "eq". This makes it impossible to use any other operator after clearing the filter.

**To Reproduce**
1. Go to a record list with filters other than `eq` (for example `contains`)
2. Filter items by something
3. Observe that the set filter operator (eg. `contains`) worked properly
4. Now click the clear button in the dropdown and then filter to get back all results
5. Observe that this works as well
6. Now open the filter again and filter by the same thing as in step 2
7. Observe that the results are now different since the filter operator switched from `contains` to `eq`

**Expected behavior**
The operator defined in `initialFilter` should not be reset when clearing a filter query. This is somewhat related to https://github.com/pankod/refine/issues/1373. Without the support for that the developer is unable to switch the operator manually so it's impossible to work around this behaviour.

**Screenshots**
![refine-double-filter-contains-bug](https://user-images.githubusercontent.com/6438760/147409745-76efabac-c9c1-4550-afc2-71b6c9f87255.gif)

React Query Debugging Window showing the 2 requests with the changed operator:

![image](https://user-images.githubusercontent.com/6438760/147409794-a72db6d9-57d3-4f7c-bd75-9c6ba1b02507.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Edge
 - Version: 2.4.11
 - Used dataProvider: Airtable

**Comment by omeraplak** [comment]
Hey @IgnusG ,
Thank you very much for the bug report! Let's see what we can do!

**Comment by spatialvlad** [comment]
+1

**Comment by leapful** [comment]
@IgnusG  @omeraplak 

Could you please help to review the pull request https://github.com/refinedev/refine/pull/3224 ?
