### ISSUE TITLE
[FEAT] nestjs-query support

### ISSUE THREAD

**Issue by dzcpy** [refinedev/refine#1550]
Hi, thanks for making such an awesome tool. Is it possbile to also add nestjs-query support? I saw there is nest-crud which is great, but IMHO a GraphQL API has many advantages over REST. It would be great if refine can support both nest-crud and nestjs-query.
Many thanks!

**Comment by omeraplak** [comment]
Hey @dzcpy ,
Thanks so much for contacting us! I think it would be great too! Frankly, I don't have any predictions about when we can add it. 
If you try to do it and you need help, we will be happy to help you. 
btw, if you haven't been to our [Discord](https://discord.gg/UuU3XCc3J5) yet, we are waiting for you!

**Comment by AyushK-101** [comment]
I would like to work on this

**Comment by omeraplak** [comment]
> I would like to work on this

Happy hacking! 🚀

**Comment by aliemir** [comment]
Unassigned @AyushK-101 due to inactivity on this issue. Is there anyone wants to work on this issue? 🙏

**Comment by sevkioruc** [comment]
Hey @omeraplak @aliemir, Could you please some info about this feature? How can i work on it?

**Comment by yildirayunlu** [comment]
Hi @sevkioruc, thank you for your interest. [nestjs-query](https://doug-martin.github.io/nestjs-query/) is a back-end library with graphql and crud implementations. A data provider needs to be prepared using this project. [Strapi graphql](https://github.com/refinedev/refine/tree/next/packages/strapi-graphql) would be a good example.

You temporarily run a nestjs-query application locally and integrate it there. Then we will deploy it to the refine subdomain.

**Comment by sevkioruc** [comment]
Hey @yildirayunlu, i have two questions. How to test this package behaviour is correct? and which should i use url for unit test?

**Comment by yildirayunlu** [comment]
Hey @sevkioruc, first of all, you should test the provider you made manually. For this, create a `Post` end-point and make sure that the crud operations are working correctly.

Then you have to cover it with unit tests. Use [nock](https://github.com/nock/nock) library for this.

We will help you prepare the API. We'll deploy and give you a URL. You can open PR.

**Comment by sevkioruc** [comment]
Hi @yildirayunlu, I have just started manual testing. I will write tests later, too. Thank you so much!

**Comment by sevkioruc** [comment]
Hey @yildirayunlu, should I create nestjs-query backend project for manual testing?

**Comment by yildirayunlu** [comment]
> Yes @sevkioruc, you have to create a project and perform post crud operations. If you are not experienced with back-end and nestjs I can help with this.

**Comment by sevkioruc** [comment]
I haven't used nestjs or nestjs-query before but i use nodejs/express. I will try it but i can ask a question when i encounter any problem.  Thank you @yildirayunlu :)

**Comment by sevkioruc** [comment]
Hi @yildirayunlu, this week i am a little bit busy. Is it okay if can i work on backend in the weekend? or is it late?

**Comment by yildirayunlu** [comment]
Hey @sevkioruc let's do this if you want. We'll take care of the back-end and give you an api url. You focus on data provider.

**Comment by sevkioruc** [comment]
Thank you @yildirayunlu better for me :)

**Comment by omeraplak** [comment]
Since the nestjs-query project is not actively maintained, we have given up on developing this data provider. But if the community wants to make it, we will provide our best support. Thank you for your understanding

**Comment by omeraplak** [comment]
Hey @dzcpy @sevkioruc @AyushK-101 ,
Good news for today, we have released our `@refinedev/nestjs-query` package! 
Release: https://github.com/refinedev/refine/releases/tag/%40refinedev%2Fnestjs-query%401.0.2 
Demo: https://example.crm.refine.dev/
