### ISSUE TITLE
[BUG] Disable pagination when use useTable hooks

### ISSUE THREAD

**Issue by markuz899** [refinedev/refine#2028]
I am trying to use useTable hooks in a collection without paging, since through the ANT library it is possible to disable pagination, to date is there a way to disable it even when it tries to fetch resources?

**_Error_**
**Cannot read properties of undefined (reading 'pagination')**

good work

**Comment by omeraplak** [comment]
Hey @markuz899 ,
Thank you for contacting us. I'm sorry but I don't fully understand :( is it possible for you to give some more details?

**Comment by markuz899** [comment]
![Schermata 2022-06-22 alle 13 06 09](https://user-images.githubusercontent.com/52067713/175014369-081d5ad2-45d9-4775-82e2-1e6bbc6826c6.png)

hello thanks for the prompt reply.

I am trying to create a table through an api which returns only the data, (ex: [{name: "user"}]) without pagination information.

when the useTable hook looks for the resource it returns an error on pagination undefined

**Comment by omeraplak** [comment]
Which data provider are you using? Is it `@pankod/refine-strapi-v4`?

**Comment by omeraplak** [comment]
> yes i am using v4

Ok now we have all the answers. @mlhekinci will take care of it tomorrow and we will release it soon (probably tomorrow)!

**Comment by markuz899** [comment]
Wao! thank you very much for your prompt viewing

**Comment by ozkalai** [comment]
Hey @markuz899! We have finally released a new version with the ability to disable pagination in `useTable`. If you want to disable pagination you can pass `hasPagination: false` to `useTable`.  This also disables pagination elements in `<Table>` of `@pankod/refine-antd`.

You can refer to [@pankod/refine-antd's useTable](https://refine.dev/docs/ui-frameworks/antd/hooks/table/useTable/#listing) docs.
Also check out [@pankod/refine-core's useTable](https://refine.dev/docs/core/hooks/useTable/#pagination) docs.

You need to update your data provider, UI Framework and also `@pankod/refine-core`.
```
npm i @pankod/refine-strapi-v4@latest @pankod/refine-antd@latest @pankod/refine-core@latest
```
### Usage

```ts
const { tableProps, searchFormProps } = useTable<IUser>({
    resource: "users",
    hasPagination: false,
});
```
