### ISSUE TITLE
[FEAT] handleNotification for data hook's callbacks should allow more customization for the notification message

### ISSUE THREAD

**Issue by gerardosabetta** [refinedev/refine#2042]
**Is your feature request related to a problem? Please describe.**
Hooks like [useCreate](https://github.com/pankod/refine/blob/next/packages/core/src/hooks/data/useCreate.ts#L154) trigger notistack in a way that makes it imposible to fully customize the content of the toast.

**Describe the solution you'd like**
I'd like the callbacks that trigger these toasts to use the err.message as the notification message. They are currently passing that as the notification description. It would also be nice to get the description to be a part of the notification.

**Describe alternatives you've considered**
I could find a way to trigger a 2nd notification with the err.message but that would make 2 notifications for each request

**Comment by gerardosabetta** [comment]
That was hella fast! thanks <3

**Comment by ozkalai** [comment]
Thanks a lot for your contribution, stay with Refine 😎🥳
