### ISSUE TITLE
[BUG] useNavigation's show prop does no interaction.

### ISSUE THREAD

**Issue by emehmet** [refinedev/refine#2464]
Describe the bug
useNavigation's show prop does no interaction.

Expected behavior
When called show('resource',id) it should go to show page
```
"@pankod/refine-antd": "^3.41.0",
"@pankod/refine-core": "^3.69.0",
```

```javascript
onMutationSuccess: (data) => {
      show('reports', data.id);
    }
```

**Comment by emehmet** [comment]
Hey @aliemir 

Thank you for your reply.

Yes, it worked when I set it to redirect:false. But 
```javascript
const { queryResult } = useShow({ resource: 'getReport' }); 
```
still not working.

**Comment by emehmet** [comment]
Only show prop did navigation. Data is still not coming.

**Comment by aliemir** [comment]
Nice to hear that! Since we have this issue explained in another one, can we close this one and continue on that on its own issue? 😅

**Comment by emehmet** [comment]
Yes. Thank you! 👍
