### ISSUE TITLE
[FEAT] add Showguesser component

### ISSUE THREAD

**Issue by vehas** [refinedev/refine#2531]
**Is your feature request related to a problem? Please describe.**
react-admin has a really cool feature called the guesser component here https://marmelab.com/react-admin/ShowGuesser.html
basically this component try guesses (by print js code out to console) what should be show base on the type of prop that passed in,
It would be cool if refine.dev has this component, I use it all the time when I use react-admin, I plan to use refine.dev on a new project and one of the few things I miss from react-admin is the "guesser" feature.
this will enable refine to really do rapid development

**Describe the solution you'd like**
component similar to  this code  https://github.com/marmelab/react-admin/blob/dbd036f812/packages/ra-ui-materialui/src/detail/ShowGuesser.tsx and this example  https://marmelab.com/react-admin/ShowGuesser.html

**Describe alternatives you've considered**
another guester component that base on  data provider schema not just prop type

thank you for your project

**Comment by omeraplak** [comment]
Hey @vehas ,
Thank you for contacting us! The guesser feature is in our backlog but will be slightly different from react-admin's approach. Are there any situations where you are happy or dissatisfied with react-admin's approach? 👀

**Comment by Prabesh-Shrestha** [comment]
hey i'd like to work on this

**Comment by salihozdemir** [comment]
Hey @vehas,

We are still discussing among ourselves about the guesser feature. If you create a PR for this, it probably will not merge because of it's a big feature. We want to add some game changer things, so we've decided to remove the hactoberfest label. 

If you are looking for an issue for hacktoberfest, I can recommend to you #2127. 🚀

**Comment by aliemir** [comment]
Hey @vehas, we're happy to announce that we've released `@pankod/refine-inferencer` package 🎉 🎉 It's generating components and lets you preview it with a formatted code ready to get you started 🚀 🚀 

You can start by checking out this https://refine.dev/docs/packages/documentation/inferencer/ in documentation. We would love to hear your feedback if you try it out 🙏 🙏
