### ISSUE TITLE
[FEAT] integrate e2e ui test

### ISSUE THREAD

**Issue by depapp** [refinedev/refine#2633]
**Is your feature request related to a problem? Please describe.**
since this awesome project doesn't have e2e ui test and software quality is matter

**Describe the solution you'd like**
I have suggestion to add it on this awesome project using Playwright (https://playwright.dev/)

**Comment by RachitGarg-12** [comment]
Hey , could you assign me this feature .

**Comment by omeraplak** [comment]
> Hey , could you assign me this feature .

I did it. Good lucks 👊

**Comment by omeraplak** [comment]
Hey @RachitGarg-12 ,
by the way, we have one Cypress example, https://refine.dev/docs/examples/e2e-testing/

**Comment by salihozdemir** [comment]
Hey @RachitGarg-12,

We look forward to this PR, how is progress in your work? If you need a help please feel free to get in touch us.

**Comment by chaiwattsw** [comment]
Any update on this? if not I would like to take

**Comment by salihozdemir** [comment]
Hey @chaiwattsw,

@RachitGarg-12 is not giving an answer. So, I've assigned to you this issue. Enjoy! 🥳

**Comment by chaiwattsw** [comment]
Thanks! @salihozdemir

**Comment by chaiwattsw** [comment]
@salihozdemir @omeraplak Could you please explain in more detail what should be done?
from what I understand is to add playwright to examples?

**Comment by alicanerdurmaz** [comment]
@chaiwattsw Hi, Thank you for your interest 🙏 

We discussed with the core team and we think Cypress will be more suitable on this case.

You can add e2e test to Finefoods examples.
[Finefoods repositories](https://github.com/pankod/refine/tree/master/examples/fineFoods)
[MUI Admin App](https://example.mui.admin.refine.dev/)
[Antd Admin App](https://example.admin.refine.dev/)
[Storefront App](https://example.refine.dev/)

For example:

```
Feature: User login
Scenario: User wants to login
  Given I visit "/login"
    When I enter "xxx@xxx.xxx" in the "email" field
      And I enter "xxx" in the "password" field
      And I press the "login" button
  Then I should see the "dashboard" page
```

```
Feature: User login form validations
Scenario: User wants to login
  Given I visit "/login"
  When I enter "" in the "email" field
    And I enter "" in the "password" field
  Then I should see the "'email' is required" and "'password' is required" error
```

```
Feature: Localization
Scenario: User wants change language to German
  Given I visit "/"
  When I hovered language dropdown on top right
  Then I should see available languages with country flag and and label
  And I click on "German"
  Then I should see app in German
```

**Comment by chaiwattsw** [comment]
@alicanerdurmaz I got it. Thanks!

**Comment by alicanerdurmaz** [comment]
Hey @chaiwattsw, Is there any progress on this issue?

**Comment by aliemir** [comment]
Due to inactivity and unclarity of the changes to be made, closing this issue and marking as stale. ☹️
