### ISSUE TITLE
[FEAT]change the opacity of the slider buttons in mobile mode.

### ISSUE THREAD

**Issue by ShravaniAK** [refinedev/refine#2739]
<img width="1440" alt="Screenshot 2022-10-13 at 1 36 09 PM" src="https://user-images.githubusercontent.com/97099574/195538918-95e88c60-3a90-49a0-ad07-239052c3670d.png">

**Comment by abhay-ag** [comment]
Hii, I would like to work on this.

Can you please elaborate a little bit more

**Comment by ShravaniAK** [comment]
i am already in queue for getting this issue assigned to me

**Comment by aliemir** [comment]
@ShravaniAK Thank you for the issue, maybe we can do half the opacity + smaller size for the buttons? Can you work on this like that? If so, let me assign this issue to you 🚀

**Comment by ShravaniAK** [comment]
yes i can  work on this

**Comment by aliemir** [comment]
@abhay-ag Thank you for your interest in this issue but looks like @ShravaniAK wants to work on this one as well. You can check out other issues and maybe you can find something you might want to look at 🚀 🚀

**Comment by prakhar-198** [comment]
Hey @abhay-ag is still something left to do. If so please assign me.

**Comment by aliemir** [comment]
@ShravaniAK any progress on this one?

**Comment by aliemir** [comment]
Looks like @ShravaniAK is not responding 😞 Anyone here want to work on this one?

**Comment by ShravaniAK** [comment]
i am working on it

**Comment by ShravaniAK** [comment]
please reasign

**Comment by ShravaniAK** [comment]
i will finish it today

**Comment by s-vamshi** [comment]
@aliemir Can I work on this Issue?

**Comment by omeraplak** [comment]
Hey @ShravaniAK,
Any updates on this issue?

**Comment by AbhishekTiwari23** [comment]
If the issue still exists, please let me know. My setup is ready.

**Comment by Vishrut19** [comment]
Hey @ShravaniAK do you need any help ??

**Comment by AbhishekTiwari23** [comment]
Should I start working on this?

**Comment by aliemir** [comment]
@s-vamshi @AbhishekTiwari23 @Vishrut19 Anyone still interested in this? Due to inactivity unassigned @ShravaniAK from this issue.

**Comment by s-vamshi** [comment]
Yes i would like to work on this issue.

**Comment by ShravaniAK** [comment]
actually my exams were going on , i will anyhow make a pr today ,please give me some hours

**Comment by ShravaniAK** [comment]
i have finished the work

**Comment by ShravaniAK** [comment]
i am not able to push , please help

**Comment by omeraplak** [comment]
Hey @ShravaniAK ,
You can follow this document 

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from- a-fork

**Comment by ShravaniAK** [comment]
i am not able to make multiple commits
<img width="1440" alt="Screenshot 2022-10-24 at 2 16 13 PM" src="https://user-images.githubusercontent.com/97099574/197486066-2ad168ef-cda4-4c12-931a-1ca64228a9f2.png">

**Comment by omeraplak** [comment]
refine uses [commit-lint](https://commitlint.js.org/#/). You can visit here to commit-lint rules -> https://cheatography.com/albelop/cheat-sheets/conventional-commits/
