### ISSUE TITLE
[FEAT] Enhancement of the footer section

### ISSUE THREAD

**Issue by CodeWAdi** [refinedev/refine#2776]
### Is your feature request related to a problem? Please describe.

![2022-10-16](https://user-images.githubusercontent.com/110481392/196015218-9bd98ba9-9f3a-4997-921b-46b9919659dc.png)

The footor section of the website looks kinda simple and not upto the par with the entire website , the overall webite looks so amazing but the links section in the footor is simple incomparison to the overall website. 

### Describe the thing to improve

Assign me so that I'll made some changes in the footer to make it look good

**Comment by CodeWAdi** [comment]
#self-assign

**Comment by AbhishekTiwari23** [comment]
I would like to contribute.

**Comment by aliemir** [comment]
Hey @CodeWAdi thank you for your interest! We'd love to see your PR, have fun! 🚀

**Comment by aliemir** [comment]
> I would like to contribute.

Hey @AbhishekTiwari23, thank you for your interest but @CodeWAdi already got this one assigned. You can check other issues or maybe check the codebase for potential issues and features? 🙏

**Comment by AbhishekTiwari23** [comment]
If this issue still exists. Can I work over this?

**Comment by CodeWAdi** [comment]
already working on this issue

**Comment by AbhishekTiwari23** [comment]
Can I work on this now?

**Comment by yildirayunlu** [comment]
Hey @CodeWAdi, Is there any progress on this issue?

**Comment by aliemir** [comment]
Due to inactivity and unclarity of the changes to be made; I'm closing this issue by marking it as a won't fix. ☹️ Thanks to everyone interested on this issue, if you want to contribute to refine, check out this page https://refine.dev/docs/contributing/#ways-to-contribute and check the latest open issues, maybe you can find some issues you can help with 🚀 🚀
