### ISSUE TITLE
[BUG] Updating the my profile icon

### ISSUE THREAD

**Issue by CodeWAdi** [refinedev/refine#2777]
### Describe the bug

![2022-10-16 (2)](https://user-images.githubusercontent.com/110481392/196017980-02b3ea0e-d277-4960-9f26-592bb4417df6.png)

The  Profile Icon looks so simple and the icon need to something that tells the user that its the profile icon and the current icon lacks that

### Steps To Reproduce

Go to "https://store.refine.dev/"
The top uppermost right corner

### Expected behavior

Need Enhancement

**Comment by vcvedika** [comment]
Could you please assign this issue to me?

**Comment by AbhishekTiwari23** [comment]
I am also ready with my setup.

**Comment by aliemir** [comment]
@CodeWAdi thank you for the issue. Do you want to work on this one or can we assign this to @vcvedika or @AbhishekTiwari23?

**Comment by CodeWAdi** [comment]
I wanna work on this one kindly assign me to this , thank you

**Comment by omeraplak** [comment]
> I wanna work on this one kindly assign me to this , thank you

Done! Happy hacking! 🎯

**Comment by s-vamshi** [comment]
@omeraplak As it has been 3 days, if this issue is available can you assign this to me?

**Comment by AbhishekTiwari23** [comment]
Can I take it over now?

**Comment by yildirayunlu** [comment]
Hey @CodeWAdi, Is there any progress on this issue?

**Comment by s-vamshi** [comment]
@yildirayunlu @omeraplak @aliemir Can I work on this issue?

**Comment by s-vamshi** [comment]
@omeraplak Should i use react icons or can you please guide me for choosing an icon?
In react-icons we can use this icon
![image](https://user-images.githubusercontent.com/62489114/197777823-3ffa24a8-dd71-4b78-a9a8-69dbbb9b82b9.png)

**Comment by s-vamshi** [comment]
@aliemir we are not using Avatar.tsx at all in any other component ig we can give option for users to upload profile pic and use Avatar.tsx to display profile image after login.
Any thoughts on this?
