### ISSUE TITLE
[FEAT] Add smooth scroll effect on icons 

### ISSUE THREAD

**Issue by AnshuPathak-88825** [refinedev/refine#2803]
### Is your feature request related to a problem? Please describe.

It's not looking good

### Additional context

![Screenshot (71)](https://user-images.githubusercontent.com/78332454/196244463-612f89b2-0694-40e0-9d03-899454be2f50.png)
pls

### Describe the thing to improve

I'll increase it's transition time that made it smooth

**Comment by AnshuPathak-88825** [comment]
pls assign me this issue

**Comment by aliemir** [comment]
Hey @AnshuPathak-88825, assigned the issue on you! Do you have any progress on this one? 🙏

**Comment by AnshuPathak-88825** [comment]
I'm starting it now

**Comment by omeraplak** [comment]
> @aliemir I want to made some changes in footer section of the this website but I'm not able to find in which file footer section code available pls help

Hey @AnshuPathak-88825 ,
You can find it here: https://github.com/refinedev/refine/blob/next/examples/store/src/components/common/Footer/Footer.tsx

Also you can check out "Contributing" doc: https://refine.dev/docs/contributing/

**Comment by AnshuPathak-88825** [comment]
![image](https://user-images.githubusercontent.com/78332454/196937034-34e62dee-cc8a-4217-92b5-6d8efacda75e.png)
I'm looking made changes in this is section

**Comment by AnshuPathak-88825** [comment]
pls tell me where's it present @aliemir

**Comment by aliemir** [comment]
Hey @AnshuPathak-88825 sorry for late response, the footer for the documentation is at `refine/documentation/src/theme/Footer/Layout/index.js`

**Comment by AnshuPathak-88825** [comment]
Where's css of this footer section

**Comment by aliemir** [comment]
Mostly done with TailwindCSS in `className` prop, if you have any other styles you want to add by css, you can use `src/css/custom.css` but I think its better to use classes since we provided the hover colors by class (you can see at lines 186, 189, 192, 195 and 198 of `src/theme/Footer/Layout/index.js`)

**Comment by AnshuPathak-88825** [comment]
![image](https://user-images.githubusercontent.com/78332454/198364159-d026ad5a-49c3-4ab3-8733-cb85eda8aba0.png)
where's  the css of this button available
