### ISSUE TITLE
[FEAT] Keycloak Auth Provider

### ISSUE THREAD

**Issue by omeraplak** [refinedev/refine#2815]
### Is your feature request related to a problem? Please describe.

[Keycloak](https://www.keycloak.org/) is an open-source identity and access management solution. Writing [Auth](https://refine.dev/docs/api-reference/core/providers/auth-provider/) Provider for refine would be great!

### Describe the thing to improve

We can simplify the life of users using keycloak.

**Comment by hridaya423** [comment]
Hi can i work on this?

**Comment by hridaya423** [comment]
I'm sorry, I can't do this

**Comment by Alcadeus0** [comment]
I'd like to give this a shot

**Comment by chirdeeptomar** [comment]
I can work on this.

**Comment by omeraplak** [comment]
> @omeraplak I can work on this.

Happy hacking! :)

**Comment by omeraplak** [comment]
Hey @chirdeeptomar ,
I've created a keycloak example 🎯
