### ISSUE TITLE
[BUG] Save button doesn't appear on Add Address form in Store

### ISSUE THREAD

**Issue by sevkioruc** [refinedev/refine#2821]
### Describe the bug

Save button doesn't appear until hover over it

### Steps To Reproduce

1. Go to Store page
2. Login
3. Click user avatar in top right corner
4. Click My Adresses option
5. Click `+` sign in New Address area

### Expected behavior

The save button should appear

### Not hovered
![add_address_1](https://user-images.githubusercontent.com/33834689/196550651-f90f2d01-a134-44f3-9d73-17206504ca9f.png)

### Hovered
![add_address_2](https://user-images.githubusercontent.com/33834689/196550798-d04b4fd3-be90-4383-ae14-816198defa00.png)

**Comment by aliemir** [comment]
Hey @sevkioruc thank you for the issue 🙏 Even there's a bigger issue on this screen (#2822) we can still fix this without conflicting with that issue. If you want, we can assign this one on you or maybe someone else here want to take this 👀

**Comment by sevkioruc** [comment]
Hey @aliemir, if someone wants to work on it, it's fine by me :)

**Comment by 3t8** [comment]
I'd like to work on it 😄

**Comment by aliemir** [comment]
Hey @3t8, thank you for your interest! Assigning the issue on you 🚀

**Comment by aliemir** [comment]
@3t8, we've encountered this issue in the login modal couple weeks back, it's resolved with some class fixes but we want to have a better solution to not have this in the future again. Would you please try to have a more general solution than to just have this fixed in the address modal? 🙏

**Comment by s-vamshi** [comment]
@aliemir As I have worked on similar issue in login modal, I have actually found the source of this issue. Can I create a new PR or should I wait until @3t8 PR on this issue?

**Comment by 3t8** [comment]
Working on it

**Comment by 3t8** [comment]
@aliemir I tried to implement a more general solution. This also means most of the buttons will need to be checked if the proper css is applied #2859 
@s-vamshi Let me know if you have a better solution

**Comment by s-vamshi** [comment]
@3t8 I have some academic work so I will create PR by tonight.

**Comment by s-vamshi** [comment]
@aliemir @omeraplak  can you please check our PR?
