### ISSUE TITLE
[BUG] My profile section is blank in refine store

### ISSUE THREAD

**Issue by s-vamshi** [refinedev/refine#2823]
### Describe the bug

1. When we route to account/profile, profile section is blank, ig it needs to have fields which change email and name.
2. Account text on the left looks like a button but it is not. To distinguish it from other buttons below can we make the account text as bold or increase the size of font?

### Steps To Reproduce

1. Go to https://store.refine.dev/
2. Login in with your account
3. Click on login icon
4. Click on My Profile button
5. Page looks blank

### Expected behavior

My profile page should show necessary information.

### Screenshot

![image](https://user-images.githubusercontent.com/62489114/196577038-51bf511c-2335-4fb5-8fc5-5063adb2a1d2.png)

**Comment by s-vamshi** [comment]
@aliemir @omeraplak I would like to work on this. Can you assign this to me?

**Comment by omeraplak** [comment]
Hey @s-vamshi ,
I've fixed this issue (#2824). The problem is that medusa is using cookies for authorization. `store.refine.dev` was used for the auth domain, while `api.store.refine.dev` was used for other requests. This prevented the sharing of cookies.

**Comment by s-vamshi** [comment]
> 2. Account text on the left looks like a button but it is not. To distinguish it from other buttons below can we make the account text as bold or increase the size of font?

@omeraplak Any thoughts on this?

**Comment by omeraplak** [comment]
> > 2. Account text on the left looks like a button but it is not. To distinguish it from other buttons below can we make the account text as bold or increase the size of font?
> 
> @omeraplak @aliemir Any thoughts on this?

Hey @s-vamshi ,
Sorry, I missed that. Yes, we can do this
