### ISSUE TITLE
[FEAT] Add useInfiniteList support

### ISSUE THREAD

**Issue by omeraplak** [refinedev/refine#2854]
### Is your feature request related to a problem? Please describe.

For resources that cannot be paginated, the `useInfiniteList` hook will be useful. This hook can use the data provider's "getList" function like the [`useList`](https://refine.dev/docs/api-reference/core/hooks/data/useList/) hook. Unlike this hook, [`useInfiniteQuery`](https://tanstack.com/query/v4/docs/reference/useInfiniteQuery) should be used instead of [`useQuery`](https://tanstack.com/query/v4/docs/reference/useQuery?from=reactQueryV3&original=https://react-query-v3.tanstack.com/reference/useQuery).

### Describe the thing to improve

For resources that cannot be paginated, the `useInfiniteList` hook will be useful.

**Comment by TheLearneer** [comment]
Hi @omeraplak 👋 

I would definitely look to try it out 😄

**Comment by PriyanshuRj** [comment]
Please assign this issue to me @omeraplak

**Comment by omeraplak** [comment]
> Please assign this issue to me @omeraplak

Done! Happy hacking 💥

**Comment by aliemir** [comment]
Hey @PriyanshuRj, any progress on this one? We're excited to see your changes here 👀 👀

**Comment by yildirayunlu** [comment]
Due to inactivity unassigned @PriyanshuRj from this issue. Anyone still interested in this?

**Comment by sevkioruc** [comment]
Hey @omeraplak , can you assign me to the issue? I don't know how i can do it for now but i want to try :D

**Comment by sevkioruc** [comment]
Hey @omeraplak,
I couldn't it for now. If you want you can unassign it from me.
I will be follow its solution for the next features :)

**Comment by omeraplak** [comment]
We've released the `useInfiniteList` hook 💥 https://refine.dev/docs/api-reference/core/hooks/data/useInfiniteList/
