### ISSUE TITLE
[DOC] Fix grammatical errors in Readme

### ISSUE THREAD

**Issue by biswadeep25** [refinedev/refine#2878]
### Documentation issue

There are grammatical errors in Readme

### Describe the thing to improve

Readme.md

**Comment by biswadeep25** [comment]
Please add the hacktoberfest label and assign this to me.

**Comment by simran2002** [comment]
Hi @omeraplak 
Could you please assign this issue to me?
Regards

**Comment by metabiswadeep** [comment]
A PR has already been raised by me for this issue
