### ISSUE TITLE
[FEAT] Adding Gitpod Dev environment feature

### ISSUE THREAD

**Issue by Smartmind12** [refinedev/refine#2879]
### Is your feature request related to a problem? Please describe.

Gitpod allows you to observe and interact with the project code directly in the browser instead of cloning it into user's local machine.

### Describe the thing to improve

Gitpod can provide fully initialized, perfectly set-up developer environments for any kind of software project. If users want to make changes in the project that would lead to a PR, then fork the repository and use Gitpod button in the forked readme.

Every PR too has access to Gitpod to help users use the dev environment and make modifications to the code in a faster and easier manner!

**Comment by Smartmind12** [comment]
Can you assign this to me so that i can start working on it right away!

**Comment by omeraplak** [comment]
Hey @Smartmind12 ,
Thank you for contacting us! What are the advantages of GitPod over [GitHub dev](https://github.dev/github/dev)?

**Comment by Smartmind12** [comment]
> Hey @Smartmind12 , Thank you for contacting us! What are the advantages of GitPod over [GitHub dev](https://github.dev/github/dev)?

1. Gitpod is opensource platform which is faster, more resource efficient and also integrateable withindividual stack
2. Gitpod offers easy collaboration by sharing of snapshots of workspace which Github dev does not provide
3. Provides secure containers with scalable workspace on high power cloud servers
4. Supports(I believe Github dev does not support the following):
a. Multiple IDE
b. Self host on AKS, GKE & EKS

**Comment by omeraplak** [comment]
LGTM @Smartmind12. We are waiting for your PR 👊
