### ISSUE TITLE
[FEAT]show image names in related products

### ISSUE THREAD

**Issue by saimaheshtaduri** [refinedev/refine#2881]
### Is your feature request related to a problem? Please describe.

When I select any item in store, There are no names to the related products. 

![Screenshot (51)](https://user-images.githubusercontent.com/53844369/197357178-0a326e73-e5b7-46ce-969b-e743df450c15.png)

### Describe the thing to improve

I would like to add names to the images, atleast when hovered on them

**Comment by nooras** [comment]
Hi @saimaheshtaduri I am interested please assign me

**Comment by saimaheshtaduri** [comment]
Sorry @nooras , I already implemented it and waiting for their approval to raise a pr.

**Comment by omeraplak** [comment]
Hey @saimaheshtaduri ,
Thank you for your interest. We discussed with the core team and decided that this feature is not needed. Thanks again for your interest 🚀
