### ISSUE TITLE
[BUG] TimePicker.RangePicker gives error

### ISSUE THREAD

**Issue by zgajo** [refinedev/refine#2885]
### Describe the bug

Trying to use <TimePicker.RangePicker /> returns error
Property RangePicker does not exist on the type...

It should have the possibility to use Ant Design RangePicker
https://ant.design/components/time-picker/#components-time-picker-demo-range-picker

### Steps To Reproduce

import {  TimePicker } from '@pankod/refine-antd';

Use <TimePicker.RangePicker /> in the code

### Expected behavior

Possibility to use RangePicker when using TimePicker

### Screenshot

![Screenshot 2022-10-23 at 14 20 52](https://user-images.githubusercontent.com/7017451/197405526-d427b3a6-9d9a-4571-8d40-339b69f63273.png)

**Comment by alicanerdurmaz** [comment]
Hi @zgajo Thanks for the issue 🙏 . We will release fix soon.
Until that time you can use this component `<DatePicker.RangePicker picker="time" />`

**Comment by alicanerdurmaz** [comment]
This issue happens because we convert moment to dayjs. [antd doc](https://ant.design/docs/react/replace-moment#TimePicker.tsx)

All `<TimePicker.RangePicker />` features can be used like this `<DatePicker.RangePicker picker="time" />`

I'm closing issue, Thans again @zgajo  🙏
