### ISSUE TITLE
Code Of Conduct Typographical enhancement

### ISSUE THREAD

**Issue by Arkaroy147** [refinedev/refine#2898]
The last sentence in the code of conduct(Translation link) is in the same line as the previous sentence. It is not looking good with the rest of the code. I wish to separate them. Can you assign me?

**Comment by Arkaroy147** [comment]
Also, can I request a hacktoberfest tag in this issue?

**Comment by aliemir** [comment]
Added! Thank you for your interest in refine, waiting for your PR 🚀
