### ISSUE TITLE
[FEAT] Add cursor pointer to scroll down button 

### ISSUE THREAD

**Issue by AnshuPathak-88825** [refinedev/refine#2904]
### Is your feature request related to a problem? Please describe.

yes button should be in cursor pointer 

### Describe the thing to improve

![image](https://user-images.githubusercontent.com/78332454/197824460-3c994556-b70d-4312-b086-ccc1ec50131c.png)
made this button cursor pointer

**Comment by aliemir** [comment]
Hey @AnshuPathak-88825, thank you for the issue, we can accept this change if you want to create a PR for it! 🪄  It look like you already have an issue assigned on you, is there a progress on that one? We're trying to keep the issue list clean and I'll be glad if you try to tackle that down before you move on to this 🙏 🙏

**Comment by AnshuPathak-88825** [comment]
I'll try to complete that issue by today

**Comment by AnshuPathak-88825** [comment]
you can assign this issue to me

**Comment by AnshuPathak-88825** [comment]
do you guys have any discord or community where I can some doubt

**Comment by alicanerdurmaz** [comment]
Hey, @AnshuPathak-88825 [Refine Discord](https://discord.gg/refine) 👊

**Comment by ckragarwal** [comment]
Can I do this if this is still pending?

**Comment by AnshuPathak-88825** [comment]
@ckragarwal I'm working on it
