### ISSUE TITLE
[FEAT]show alert message when user chooses more than 6 items

### ISSUE THREAD

**Issue by saimaheshtaduri** [refinedev/refine#2916]
### Is your feature request related to a problem? Please describe.

Now If I select a product 6 times in a cart, I'm not getting any alert on 7th time 

### Describe the thing to improve

Its better if user is awarded that 6 is the max

**Comment by saimaheshtaduri** [comment]
@omeraplak

**Comment by omeraplak** [comment]
Hey @saimaheshtaduri ,
I guess it has to do with the total stock of the product. An alert would be nice 🎉

**Comment by omeraplak** [comment]
Hey @saimaheshtaduri ,
Any updates on this one? We're waiting for your PR 🚀

**Comment by saimaheshtaduri** [comment]
@omeraplak I'm facing issues setting up the project. I don't think I can implement this.

**Comment by alicanerdurmaz** [comment]
Hi @saimaheshtaduri, what is the problem you are facing ?

`npm run bootstrap -- --scope refine-store`
`npm run start -- --scope refine-store`

after running these commands you can see the project at `http://localhost:8000/`

**Comment by sevkioruc** [comment]
Hey @omeraplak, can i work on it if @saimaheshtaduri has stopped working?
