### ISSUE TITLE
Add Dark Mode

### ISSUE THREAD

**Issue by Saikatssd** [refinedev/refine#2922]
### Is your feature request related to a problem? Please describe.

Dark may even be easier on your eyes than a traditional screen setting.

### Describe the thing to improve

Adding a dark mode feature will help to make your website cool.

**Comment by Saikatssd** [comment]
Please assign me to work on this issue.

**Comment by alicanerdurmaz** [comment]
Hi @Saikatssd, Dark mode would be great 🚀 

We are working on design updates on landing page. [PR](https://github.com/refinedev/refine/pull/2933)

We will merge in 2-3 days.
After PR merged, you can work on dark mode 🙏. 
When PR merged, we will let you know.

**Comment by alicanerdurmaz** [comment]
@Saikatssd Hi again 👋. We merged new design on landing page.

Do you want to work on the dark mode feature?

**Comment by alicanerdurmaz** [comment]
Closed due to inactivity.
