### ISSUE TITLE
[BUG] Issue on redirect url after user is logged out on jwt refresh token expiration.

### ISSUE THREAD

**Issue by dipbazz** [refinedev/refine#2927]
### Describe the bug

I am using the JWT authentication on my project and it works fine when I log in and save the access token in my local or session storage. But whenever my refresh token is expired and the server responds with 401 status the user gets logged out which is fine. When the user is logged out the redirect URL must be the resource that the user is trying to access instead the redirect URL will be `/login`.  

### Steps To Reproduce

https://stackblitz.com/edit/refinedev-refine-voibwj?file=src/App.tsx

The steps to reproduce the issues is on the above link.

### Expected behavior

For example:
Let us say I am trying to access the **users** resource from the menu but my refresh token is expired then I will be redirected to the login page with the URL as `<domain>/login?to=/login` instead of `<domain>/login?to=/users`

### Screenshot

![login-redirect](https://user-images.githubusercontent.com/33461005/198755653-366b70a1-1094-44d0-9b0b-a4e8d9215915.png)

**Comment by alicanerdurmaz** [comment]
Hi @dipbazz, Than you for reporting the issue 🙏 

We started to working on this 👊

**Comment by alicanerdurmaz** [comment]
Hi @dipbazz thank you for the issue, we opened [PR](https://github.com/refinedev/refine/pull/2953).

But, there are also some problems with the code you reproduced.

You need to reject or resolve with failedRequest.
```tsx
const refreshAuthLogic = async (failedRequest: AxiosError) => {
     ...

    return Promise.reject(failedRequest)
}
```

You need to change status field to `error.response.status`.
```tsx
checkError: (error) => {
      if (error.response.status === 401) {
        return Promise.reject(new Error('Your login sessoin expired. Please login again'))
      }
      return Promise.resolve()
}
```


If you have any more questions, please don't hesitate to ask. 🙏
