### ISSUE TITLE
[BUG] Request api two times

### ISSUE THREAD

**Issue by tranvantriet** [refinedev/refine#2978]
### Describe the bug

When requesting API, always request API two times

### Steps To Reproduce

1. Open firebug Network
2. Open posts list: https://zzmiwzvxm--github--3000.local.webcontainer.io/posts 
=> request API posts list two times

### Expected behavior

Request one times

### Desktop

-Ubuntu 21.10
-Chrome: Version 106.0.5249.91 (Official Build) (64-bit)

### Additional Context

Link demo: https://zzmiwzvxm--github--3000.local.webcontainer.io/posts

**Comment by salihozdemir** [comment]
With React 18, StrictMode throws requests twice on development enviroment. You can ignore or disable it. Refer to the react documentation for more information in [here](https://reactjs.org/docs/strict-mode.html).
