### ISSUE TITLE
[BUG] Close Datagrid filter make a call to backend with an empty string

### ISSUE THREAD

**Issue by dj-fiorex** [refinedev/refine#2992]
### Describe the bug

Following [this discussion ](https://github.com/refinedev/refine/discussions/2946)
when i click on the cross icon to close the filter on a MUI Datagrid a call with an empty string is made to my backend.

### Steps To Reproduce

1. Have a Datagrid with a Select filter
2. open the filter and select a value
3. Click the cross icon to close the filter
4. A call to backend is made with an empty string

### Expected behavior

When i close a filter no call is made to the backend and all rows is showed in the Datagrid

**Comment by omeraplak** [comment]
Hey @dj-fiorex ,
Thank you for contacting us! We've fixed it with [@pankod/refine-mui@3.55.2](https://github.com/refinedev/refine/releases/tag/%40pankod%2Frefine-mui%403.55.2). Could you approve this fix?

**Comment by dj-fiorex** [comment]
Bug resolved! Thank you!
