### ISSUE TITLE
[DOC] Typo in documentation

### ISSUE THREAD

**Issue by dzcpy** [refinedev/refine#3022]
### Documentation issue

https://refine.dev/docs/examples/tutorial/antd-tutorial/
![image](https://user-images.githubusercontent.com/203980/202846140-d5afeb3f-7585-4097-9d4d-e0c404f82a31.png)

### Describe the thing to improve

Fix typo

**Comment by omeraplak** [comment]
Hey @dzcpy ,
Thank you for contacting us. Would you like to create a PR? ⚡️

**Comment by dzcpy** [comment]
> Hey @dzcpy , Thank you for contacting us. Would you like to create a PR? ⚡️

Done!
