### ISSUE TITLE
[FEAT] add queryOptions to useShow hook

### ISSUE THREAD

**Issue by jsbrain** [refinedev/refine#3023]
### Is your feature request related to a problem? Please describe.

Conditionally show an item / trigger the query based on props.

Currently, I don't think there's a way to disable the show query!?

While almost all other query hooks have that option.

### Describe the thing to improve

Add `queryOptions` to `useShow` hook.

**Comment by omeraplak** [comment]
Hey @jsbrain ,
Thank you for contacting us! Would you like to create a PR?

**Comment by omeraplak** [comment]
Hey @jsbrain ,
We've released [`@pankod/refine-core@3.90.0`](https://github.com/refinedev/refine/releases/tag/%40pankod%2Frefine-core%403.90.0). Could you approve this feature? Thank you! 🎉
