### ISSUE TITLE
[BUG] I can add 7th item to cart in store

### ISSUE THREAD

**Issue by sevkioruc** [refinedev/refine#3024]
### Describe the bug

I can add seventh item when there are 6 items in cart. 
How? Firstly I added 6 items to cart and then close cart. When i click `Add To Cart` button in the picture above, i can add seventh item.
![Screenshot 2022-11-19 183940](https://user-images.githubusercontent.com/33834689/202859295-4989204d-dbdb-47bf-8dd2-473e20ac6bb9.png)

### Steps To Reproduce

1. Go to the Store page
2. Select an item
3. Increase the count of the item until its reach 6th
4. Close Cart
5. Click Add To Cart button
6. You will see that you can increase count (but you shouldn't able to increase it) 

### Expected behavior

You shouldn't able to increase after there are 6 items in cart

**Comment by sevkioruc** [comment]
Hey @omeraplak , Couldn't you reproduce it?

**Comment by omeraplak** [comment]
Hey @sevkioruc ,
We've closed this issue as it will be resolved with #2916. Is there anything we overlooked?

**Comment by sevkioruc** [comment]
Thanks for your clarification @omeraplak. No i agree with you. i just wondered it :)
