### ISSUE TITLE
[BUG] Duplicate data requests

### ISSUE THREAD

**Issue by janlisse** [refinedev/refine#3069]
### Describe the bug

I have followed along the MUI tutorial using latest version of refine. 
Everything works as expected but when I open Chrome dev tools I see for both the list view and the show view duplicate
XHR requests are being fired.

### Steps To Reproduce

1. git clone git@github.com:refinedev/refine.git
2. cd refine/examples/tutorial/mui
3. npm install
4. npm run start
5. Open Chrome and check dev tools network requests for listing posts and showing a single post

### Expected behavior

When the list view is loaded only a single request GET /posts should be fired.
When the show view is loaded only a single request GET /posts/1 should be fired.

### Desktop

- OS: Mac OS monterey
- Browser: Chrome 107.0.5304.87
- refine-core 3.90.0
- refine-simple-rest: 3.35.2

**Comment by omeraplak** [comment]
Hey @janlisse ,
Thank you for contacting us. This is because of React's Strict mode behavior. In development mode it renders everything twice.  For more details, https://reactjs.org/docs/strict-mode.html

**Comment by janlisse** [comment]
Thanks for the clarification @omeraplak
