### ISSUE TITLE
[BUG] React router extract incorrect resource in encoded pathname

### ISSUE THREAD

**Issue by thaihuynhxyz** [refinedev/refine#3125]
### Describe the bug

When the `recordItemId` has some symbol like `:` the pathname will be encoded to `%3A`. Therefore, the `RouterProvider.useParams` will work incorrectly.

### Steps To Reproduce

1. Go to the Show of resource that has contained `:` id.
2. Cannot show the resource

### Expected behavior

Show the resource successfully.

**Comment by omeraplak** [comment]
Hey @thaihuynhxyz ,
Thank you for your contribution. We've released [@pankod/refine-react-router-v6@3.36.6](https://github.com/refinedev/refine/releases/tag/%40pankod%2Frefine-react-router-v6%403.36.6) and [@pankod/refine-react-location@3.36.2](https://github.com/refinedev/refine/releases/tag/%40pankod%2Frefine-react-location%403.36.2)
