### ISSUE TITLE
[BUG] env: node\\r: No such file or directory when run refine cli

### ISSUE THREAD

**Issue by 0xuhe** [refinedev/refine#3127]
### Describe the bug

There is an error when run refine cli `npm run refine create-resource`,

The error message is:
```

 shortMessage: 'Command failed with exit code 127: /Users/john/learning/panel/node_modules/jscodeshift/bin/jscodeshift.js ./ --extensions=ts,tsx,js,jsx --parser=tsx --transform=/Users/john/learning/panel/node_modules/@pankod/refine-cli/dist/../src/transformers/resource.ts --ignore-pattern=**/.cache/** --ignore-pattern=**/node_modules/** --ignore-pattern=**/build/** --ignore-pattern=**/.next/** --__actions=list,create,edit,show --__pathAlias=../src/components --__resourceFolderName=providers --__resource=Provider --__resourceName=provider',

 exitCode: 127,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: 'env: node\\r: No such file or directory',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
```

### Steps To Reproduce

1. npm run refine create-resource
2. input provider as name
3. enter

### Expected behavior

Fill resource attribute in <Refine> tag.
Create providers/xxx.ts

**Comment by aliemir** [comment]
Hey @0xuhe sorry for the issue 🙏 Can you also share the full error message and the output of `rpm run refine whoami`? I'm not sure if this is an access issue or an issue from the line endings 🤔 We'll identify the issue and release a fix as soon as possible 🚀 🚀

**Comment by aliemir** [comment]
I was finally able to get a reproduction in a simulated way. I was suspecting the end of line characters; an issue https://github.com/npm/npm/issues/4607 here on NPM. We're running `jscodeshift` from its executable and when i edit the file manually and change end of line character from `LF` to `CRLF` I was able to get the same error 😅 

Looking for a quick fix for this but also checking for other possibilities 🤔 It will be great if you can share the `whoami` output as I mentioned above 🙏 

(If there's no quick way to fix this, we can change our way of using `jscodeshift` from `bin` to `JS` 🚀

**Comment by 0xuhe** [comment]
> Hey @0xuhe sorry for the issue 🙏 Can you also share the full error message and the output of `rpm run refine whoami`? I'm not sure if this is an access issue or an issue from the line endings 🤔 We'll identify the issue and release a fix as soon as possible 🚀 🚀

```
npm WARN ignoring workspace config at /Users/xxx/learning/panel/packages/frontend/.npmrc 

> frontend@0.1.0 refine
> refine


## System:
 - OS: macOS 10.15.7
 - CPU: (4) x64 Intel(R) Core(TM) i7-4578U CPU @ 3.00GHz
## Binaries:
 - Node: 16.17.0 - ~/.volta/tools/image/node/16.17.0/bin/node
 - Yarn: 1.22.19 - ~/.volta/tools/image/yarn/1.22.19/bin/yarn
 - npm: 8.15.0 - ~/.volta/tools/image/node/16.17.0/bin/npm
## Browsers:
 - Chrome: 106.0.5249.119
 - Firefox: 96.0.3
 - Safari: 15.6.1

## Refine Packages:


/Users/xxx/learning/panel/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^
FetchError: request to https://telemetry.refine.dev/cli failed, reason: getaddrinfo ENOTFOUND telemetry.refine.dev
    at ClientRequest.<anonymous> (/Users/xxx/learning/panel/node_modules/node-fetch/lib/index.js:1491:11)
    at ClientRequest.emit (node:events:513:28)
    at TLSSocket.socketErrorListener (node:_http_client:481:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  type: 'system',
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND'
}
npm ERR! Lifecycle script `refine` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: frontend@0.1.0 
npm ERR!   at location: /Users/xxx/learning/panel/packages/frontend 
```

**Comment by yildirayunlu** [comment]
Hey @0xuhe,
It was [released](https://github.com/refinedev/refine/releases/tag/%40pankod%2Frefine-cli%401.13.0) to solve these problems. Can you update `@pankod/refine-cli@1.13.0` and try again?

**Comment by 0xuhe** [comment]
> Hey @0xuhe, It was [released](https://github.com/refinedev/refine/releases/tag/%40pankod%2Frefine-cli%401.13.0) to solve these problems. Can you update `@pankod/refine-cli@1.13.0` and try again?


It works well on MacOS.
