### ISSUE TITLE
[BUG] DatePicker is not working properly under Table.column filterDropdown.

### ISSUE THREAD

**Issue by emehmet** [refinedev/refine#3142]
### Describe the bug

Cannot select date when I use DatePicker under Table.column filterDropdown. In my local, I get index.tsx:5 Uncaught TypeError: Cannot read properties of undefined (reading 'value') error, while on stackblitz I get Uncaught TypeError: u is undefined in console. 

### Steps To Reproduce

You can check the example I made on stackblitz. You will see it when you use the DatePicker in the Published At field in the table.

https://stackblitz.com/edit/refinedev-refine-5i5gwr?file=src%2Fpages%2Fposts%2Flist.tsx&preset=node

### Expected behavior

DatePicker will mark the selection and close when the date is selected.

**Comment by leapful** [comment]
@omeraplak @salihozdemir @aliemir 

If "filterDropdown" is planned to support Date Picker with filter value as ISO string just like other date filter dropdown example, could you please help to review this pull request https://github.com/refinedev/refine/pull/3195 ?

**Comment by omeraplak** [comment]
Hey @emehmet ,
We've released [`@pankod/refine-antd@3.68.0`](https://github.com/refinedev/refine/releases/tag/%40pankod%2Frefine-antd%403.68.0). Could you approve this fix?

Thank you again @leapful 💥

**Comment by emehmet** [comment]
Thanks @omeraplak @leapful.
Yes it works great 🎉
