### ISSUE TITLE
[FEAT] Export react-router-v6 Search Params in @pankodrefine-react-router-v6

### ISSUE THREAD

**Issue by capsloq** [refinedev/refine#3155]
### Is your feature request related to a problem? Please describe.

Make [React Router's useSearchParams](https://reactrouter.com/en/main/hooks/use-search-params) hook available through @pankodrefine-react-router-v6. This helps with parsing and setting searchparams.

Maybe even consider exporting everything from react router package? (by Ömer in Discord)

Help Thread in Discord: https://discordapp.com/channels/837692625737613362/1049862807786623048

### Describe alternatives you've considered

Parsing and formatting of search params would be possible by a third party package however its more convenient to use the built in hook.

### Describe the thing to improve

import { useSearchParams } from @pankodrefine-react-router-v6

**Comment by omeraplak** [comment]
Hey @capsloq ,
Thank you for contacting us. We've released [@pankod/refine-react-router-v6@3.38.0](https://github.com/refinedev/refine/releases/tag/%40pankod%2Frefine-react-router-v6%403.38.0). Could you approve this feature?
