### ISSUE TITLE
[fix] Replace git urls for react-live

### ISSUE THREAD

**Issue by drewbitt** [refinedev/refine#3161]
### Describe the bug

As a dependency react-live is listed as a git url instead of the registry. This is not ideal for those in corporate environments that have github blocked or some CI/CD environments without ssh. It currently breaks for me.

### Steps To Reproduce

Clone

### Expected behavior

Downloads all packages from registry

**Comment by aliemir** [comment]
Hey @drewbitt, sorry for the issue 🙏 Thank you for the resolving PR but we're using and maintaining a fork of `react-live` with Typescript support. I closed your PR #3162 and opened #3166 with the published version of that fork. This issue will be resolved after we merge and release a new version 🚀 🚀

**Comment by omeraplak** [comment]
Hey @drewbitt ,
We've released [@pankod/refine-mui@3.61.0](https://github.com/refinedev/refine/releases/tag/%40pankod%2Frefine-mui%403.61.0) 💥
