### ISSUE TITLE
[FEAT] Use next.js default compiler SWC

### ISSUE THREAD

**Issue by drewbitt** [refinedev/refine#3174]
### Is your feature request related to a problem? Please describe.

The next.js template currently uses babel. Babel is slow. 

### Describe alternatives you've considered

Vite, but next.js will not support vite natively as they are all-in on swc. 

### Describe the thing to improve

Since next.js 12, the default compiler is swc. https://nextjs.org/docs/advanced-features/compiler This has:

* 3x faster refresh
* 5x faster builds for production
* 17x faster than Babel for compilation

Additionally, it is the main compiler going forward for next.js.

**Comment by omeraplak** [comment]
Hey @drewbitt ,
Thank you for contacting us! We've removed the `.babelrc` file.
