### ISSUE TITLE
[BUG] Ctrl+c not killing running dev; leaving ports open

### ISSUE THREAD

**Issue by drewbitt** [refinedev/refine#3175]
### Describe the bug

In the default next.js template from superplate, after I run the server with `pnpm run dev` and use ctrl+c to stop it from running, upon re-running dev later, I see:

`warn  - Port 3000 is in use, trying 3001 instead.`

This is because the first dev run was on 3000 and the node.exe process is still running. This problem never resolves.

### Steps To Reproduce

Included

### Expected behavior

Kills node process. Run on same port as before without having to go +1

### Desktop

node v18.12.1 LTS
Windows 10

**Comment by alicanerdurmaz** [comment]
Hi @drewbitt, Please, can you share `package.json` with us ?

**Comment by alicanerdurmaz** [comment]
@drewbitt We couldn't reproduce the issue.

**Comment by yasnbouz** [comment]
Hi @alicanerdurmaz
could you look at that [https://github.com/sindresorhus/execa#windowshide](url)

**Comment by yasnbouz** [comment]
Hi @alicanerdurmaz
Could you look at that https://github.com/sindresorhus/execa#windowshide

**Comment by omeraplak** [comment]
Hey @yasnbouz ,
Probably so. We don't use the `windowsHide` property

**Comment by yasnbouz** [comment]
Hey @omeraplak,
I've patched **@pankod/refine-cli** and it works well with `windowsHide:false`
also, I notice the terminal has no color, it works well with `FORCE_COLOR=1 pnpm dev`
Could you make the env variable `FORCE_COLOR` enable by default
These is **execa** options i've used:
`{
stdio:"pipe",windowsHide:false,env:{FORCE_COLOR:1,...process.env}
}`

**Comment by omeraplak** [comment]
Wow cool! Do you want to create PR? 🎉

**Comment by yasnbouz** [comment]
Thank you,
I wish could do it, but I have a slow network

**Comment by yasnbouz** [comment]
@omeraplak Yes, let's do it
