### ISSUE TITLE
[BUG] create refine-app EXDEV: cross-device link not permitted

### ISSUE THREAD

**Issue by asule90** [refinedev/refine#3180]
### Describe the bug

i have separated partition between root and home directory in my ubuntu 22.

and i got this error when i want to start refine project

```
Remote source found. Downloading...node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: EXDEV: cross-device link not permitted, rename '/home/path/directory/1670582808831-862229917806892/superplate-core-plugins-master' -> '/tmp/d-2022119-408232-p6iijn.ucncd'
Emitted 'error' event on GithubDownloader instance at:
    at /home/user dir/.npm/_npx/678fa4c4b5e44e85/node_modules/github-download/lib/github-download.js:131:26
    at FSReqCallback.oncomplete (node:fs:192:23) {
  errno: -18,
  code: 'EXDEV',
  syscall: 'rename',
  path: '/home/path/directory/1670582808831-862229917806892/superplate-core-plugins-master',
  dest: '/tmp/d-2022119-408232-p6iijn.ucncd'
}
```

what should i do?

thanks

### Steps To Reproduce

1. separated home directory and root
2. run `npm create refine-app my-app`

### Expected behavior

refine installed successfully

### Desktop

- OS ubuntu 22
- node v16.18.0
- npm 9.2.0

**Comment by zubSero** [comment]
I am a completely new user and just followed the quickstart steps, i got the exact same error! I will include a screenshot .

![image](https://user-images.githubusercontent.com/14299039/206706461-dba0c5ed-bb9f-40a1-90b0-103ccdb4a013.png)

**Comment by omeraplak** [comment]
Hey @asule90 @zubSero ,
Thank you for contacting us! Could you try with the `download` argument?
```sh
npm create refine-app my-project -- --download git
```

**Comment by asule90** [comment]
awesome!
yes that solved the problem..

thanks..
