### ISSUE TITLE
[DOC] Material UI Tutorial

### ISSUE THREAD

**Issue by cboydstun** [refinedev/refine#3184]
### Documentation issue

The [Material UI Tutorial](https://refine.dev/docs/tutorials/material-ui-tutorial/) has incorrect directory references for the boilerplate project. 

At ["Create a List Page"](https://refine.dev/docs/tutorials/material-ui-tutorial/#creating-a-list-page), the instructions say to create a directory "interfaces" under "/src". However, the "list.tsx" file calls the interface like it's a library `import { IPost } from "interfaces"` not a relative directory. 

Later in the step, when adding `import { PostList } from "pages/posts"` it's the same issue - that's not a relative file or directory. It's calling it like a library. 

### Describe the thing to improve

Inside "src/pages/posts/list.tsx" revise from `import { IPost } from "interfaces"` to `import { IPost } from "../../interfaces"`.

Inside "src/App.tsx" revise from `import { PostList } from "pages/posts"` to `import { PostList } from "./pages/posts/list"`.

**Comment by salihozdemir** [comment]
Hey @cboydstun,

At "[Setting Up](https://refine.dev/docs/tutorials/material-ui-tutorial/#setting-up)", you can see the following warning in the `use create-react-app` section:

> Warning: This tutorial assumes your project is configured for absolute imports. Since CRA does not configure it by default, you should configure it yourself to be able to use absolute imports. You should configure a `tsconfig.json` with `baseUrl` setting pointing to the `/src` directory in your project.

We will update the tutorials to be more descriptive for all the steps. Thanks for the feedback! 🙏🏻
