### ISSUE TITLE
[BUG] The folder name doesn't follow the project name input

### ISSUE THREAD

**Issue by liao02x** [refinedev/refine#3186]
### Describe the bug

I changed the auto generated name when creating a new project, but it still created a folder with the generated name.

### Steps To Reproduce

run `pnpm create refine-app`
then follow the prompt

### Expected behavior

I changed the project name so it should be available in the project config and the folder name. The project config did follow the new name. The folder is still using the old one.

**Comment by omeraplak** [comment]
Hey @liao02x ,
Thank you for reporting the issue. We've fixed it with the latest version. Could you approve this fix?

`npm create refine-app@latest`
