### ISSUE TITLE
[BUG] unhandled error event

### ISSUE THREAD

**Issue by ssakib4040** [refinedev/refine#3215]
### Describe the bug

I am trying to use CLI wizard but it is throwing error. 

### Steps To Reproduce

1. Go to a specific location
2. `npm create refine-app my-project` running this command

### Expected behavior

Work properly & not throw any error

### Screenshot

![Screenshot_1](https://user-images.githubusercontent.com/101496701/207205082-fed56216-f1e6-4b42-a72d-cc0bca841abf.png)

**Comment by omeraplak** [comment]
Hey @ssakib4040 ,
Thank you for reporting the issue! Could you try again with the `download` arg?

```
npm create refine-app my-project -- -d git
```

**Comment by ssakib4040** [comment]
@omeraplak thanks. It worked
![Screenshot_1](https://user-images.githubusercontent.com/101496701/207368189-7b23d8f2-d6e7-4b49-a6db-2ddfef55ed76.png)
