### ISSUE TITLE
export 'experimental_sx' (reexported as 'experimental_sx') was not found in '@mui/material/styles'

### ISSUE THREAD

**Issue by emmanuelpineda** [refinedev/refine#3225]
### Describe the bug

The following error occurs when starting the project (tutorial: https://refine.dev/docs/tutorials/material-ui-tutorial):

export 'experimental_sx' (reexported as 'experimental_sx') was not found in '@mui/material/styles'

### Steps To Reproduce

yarn run start

### Expected behavior

Start the project without errors

### Screenshot

![image](https://user-images.githubusercontent.com/45979790/207534301-b2ded326-2aec-45dd-bc76-66ff790085c6.png)

### Desktop

- OS: macOS Big Sur
- Browser: Edge
- Package Manager: yarn

**Comment by emmanuelpineda** [comment]
Sorry, I forgot to specify it, these are the versions of the libraries:
![image](https://user-images.githubusercontent.com/45979790/207535373-88dfe1cf-0f9a-4d9e-9579-43ebe9c57aa0.png)

**Comment by omeraplak** [comment]
Hey @emmanuelpineda ,
Thank you for contacting us! We'll fix it soon 🎯

**Comment by omeraplak** [comment]
Hey @emmanuelpineda ,
We've fixed this issue with [`@pankod/refine-mui@3.61.2`](https://github.com/refinedev/refine/releases/tag/%40pankod%2Frefine-mui%403.61.2). Could you approve this fix?

**Comment by emmanuelpineda** [comment]
It's working fine now, thank you so much @omeraplak!

**Comment by omeraplak** [comment]
Cool @emmanuelpineda  👊 If you like refine and want to support it don't forget to star it on GitHub 🌟
