### ISSUE TITLE
[BUG] Build failed with exit code 0

### ISSUE THREAD

**Issue by Moinax** [refinedev/refine#3234]
### Describe the bug

For some reasons the build always exit with code 0 even if it failed to compile.

### Steps To Reproduce

Type anything wrong in your code.
Run `yarn build`

### Expected behavior

Expect to exit with code 1

**Comment by omeraplak** [comment]
Hey @Moinax ,
Thank you for contacting us. Could you share the output of the `npm run fine whoami` command?

**Comment by Moinax** [comment]
@omeraplak Sure thing, here you are


> backoffice@0.1.0 refine
> refine whoami


## System:
 - OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
 - CPU: (24) x64 12th Gen Intel(R) Core(TM) i9-12900K
## Binaries:
 - Node: 18.12.1 - ~/.volta/tools/image/node/18.12.1/bin/node
 - Yarn: 1.22.19 - ~/.volta/tools/image/yarn/1.22.19/bin/yarn
 - npm: 9.1.2 - ~/.volta/tools/image/npm/9.1.2/bin/npm
## Browsers:
 - Chrome: Not Found
 - Firefox: Not Found

## Refine Packages:
 - @pankod/refine-antd: 3.70.0
 - @pankod/refine-cli: 1.9.0
 - @pankod/refine-core: 3.90.4
 - @pankod/refine-inferencer: 1.2.0
 - @pankod/refine-kbar: 0.8.0
 - @pankod/refine-react-router-v6: 3.38.0
 - @pankod/refine-simple-rest: 3.37.4

**Comment by omeraplak** [comment]
Hey @Moinax ,
I've created #3239 . We'll release it soon ⚡️

**Comment by omeraplak** [comment]
Hey @Moinax ,
We've released [`@pankod/refine-cli@1.13.2`](https://github.com/refinedev/refine/releases/tag/%40pankod%2Frefine-cli%401.13.2). Could you approve this fix?

**Comment by Moinax** [comment]
It works like a charm. Thanks guys.
