### ISSUE TITLE
[BUG] simple rest package needs jest types

### ISSUE THREAD

**Issue by dfberry** [refinedev/refine#3244]
### Describe the bug

If I grab the simple rest package to use as a starter for my own data provider, I need the @types/jest. Please include it. Submitting PR. 

### Steps To Reproduce

1. Clone this repo.
2. Copy the simple rest package into separate directory to use as boilerplate for my own data provider.
3. Copy over base tsconfig file from root - kind of expect a few of these steps so I don't consider it a bug. 
4. Install, and build work.
5. Run test. Fails with AfterAll not defined. 
6. Add @types/jest and tests run. 

### Expected behavior

1. There should be a base boilerplate project for data providers that I can grab and go. 
2. Since there isn't, I'm following the documentation and fixing up. The package is close but it would be nice to have any dev dependencies needed to build and test successfully.

**Comment by omeraplak** [comment]
Hey @dfberry ,
Thank you for contacting us. Actually there is a much cooler way 😅 We recently announced our `swizzle` feature and it can swizz our simple-rest package.

https://refine.dev/docs/packages/documentation/cli/#swizzle

**Comment by omeraplak** [comment]
In fact, if you want to make a data provider package, swizzle will not help you ⚡️ Do you want to create a PR? 👀

**Comment by dfberry** [comment]
@omeraplak Your first comment is the opposite of your second, correct? A PR for jest types or a PR for a base data provider?

**Comment by omeraplak** [comment]
PR for jest/type would be great ⚡️

Min data provider contract:
`getMany`, `createMany`, `updateMany` and `deleteMany` properties are optional. If you don't implement them, Refine will use `getOne`, `create`, `update` and `deleteOne` methods to handle multiple requests. If your API supports these methods, you can implement them to improve performance.

**Comment by omeraplak** [comment]
Hey @dfberry ,
I've created #3247 💥

**Comment by omeraplak** [comment]
We've fixed this issue. Thank you agaion ⚡️
