### ISSUE TITLE
[FEAT] Pass more variable in useTable Antd

### ISSUE THREAD

**Issue by rajaomariajaona** [refinedev/refine#3246]
### Is your feature request related to a problem? Please describe.

I want to use these methods and variable.
```
current
setCurrent
pageSize
setPageSize
pageCount
```
These variables are used to manipulate the pagination system

### Describe the thing to improve

These methods should be passed to response of `useTable (AntD)` the same way `setFilters` and `setSorter` has been passed

**Comment by omeraplak** [comment]
Thank you @rajaomariajaona 🚀
