### ISSUE TITLE
[BUG] live examples not working

### ISSUE THREAD

**Issue by ozgunmustafa** [refinedev/refine#3278]
### Describe the bug

![image](https://user-images.githubusercontent.com/34939878/208704747-a21ccc39-35a1-47b8-8b9d-e85d7d9b07ab.png)
![image](https://user-images.githubusercontent.com/34939878/208704834-e6ebef4c-2c7e-4aa6-a86e-f71ede7e083d.png)

Stackblitz refused connection error. 

### Steps To Reproduce

I was refine examples page.
I want to see calendar example. 
I clicked it.
Started to install dependencies but couldn't complete. 

### Expected behavior

I want to see example component

### Screenshot

![image](https://user-images.githubusercontent.com/34939878/208705657-571b21eb-8f9b-4a06-a80f-1a680c93bc81.png)
![image](https://user-images.githubusercontent.com/34939878/208705721-fd5dae41-6c17-4073-85ba-bddd544292f0.png)

**Comment by omeraplak** [comment]
Hey @ozgunmustafa ,
Thank you for contacting us! We've fixed the "installing dependencies" issue. The other issue is directly related to Stackblitz. I reported this to them.
