### ISSUE TITLE
[BUG] Hasura Data Provider - Allow remote schemas and possibility to change ID type

### ISSUE THREAD

**Issue by diegoarda** [refinedev/refine#3308]
### Describe the bug

When a remote schema is imported into Hasura, the grouping relationships are called as {table}_aggregated instead of {table}_aggregate. Right now the Hasura dataProvider always expects that the name of the aggregation table is suffixed with aggregated.

![image](https://user-images.githubusercontent.com/116877667/209162163-66df2b72-bd9a-4a90-9904-2c33e32d1c9c.png)

We can see this in https://github.com/refinedev/refine/blob/next/packages/hasura/src/dataProvider/index.ts#L215
Aggregate Problem

```
const hasuraFilters = generateFilters(filters);

            const operation = metaData?.operation ?? resource;

            const aggregateOperation = `${operation}_aggregate`;

            const hasuraSortingType = `[${operation}_order_by!]`;
            const hasuraFiltersType = `${operation}_bool_exp`;
```

The same goes for the Hasura id field, which is forced by the data provider to be a uuid and cannot be of the numeric or string type.

https://github.com/refinedev/refine/blob/next/packages/hasura/src/dataProvider/index.ts#L162

UUID Problem

```
        getOne: async ({ resource, id, metaData }) => {
            const operation = `${metaData?.operation ?? resource}_by_pk`;

            const { query, variables } = gql.query({
                operation,
                variables: {
                    id: { value: id, type: "uuid", required: true },
                    ...metaData?.variables,
                },
                fields: metaData?.fields,
            });

            const response = await client.request(query, variables);

            return {
                data: response[operation],
            };
        },
```

Is it possible to parameterize these cases in some way or give a solution to the problem?

### Steps To Reproduce

**For aggregated problem:**

1. Go to Hasura and export a remote Schema
2. Try to get the list through Hasura Data Provider with useList hook.
3. Try to execute the next query generated by the dataProvider: 

query: "query ($limit: Int, $offset: Int, $where: users_test_bool_exp) { users_test (limit: $limit, offset: $offset) { id, name, lastname, email, genre, role } users_test_aggregate (where: $where) { aggregate { count } } }"
variables: {limit: 20, offset: 0}

**For uuid problem:**

You could find this problem is your example case of Hasura DataProvider when you try to access to the detail of a post:
1. Install your hasura data provider sample: npm create refine-app@latest -- --example data-provider-hasura
2. access to: http://localhost:3000/posts 
![image](https://user-images.githubusercontent.com/116877667/209164144-45ae56ea-e5fb-42ab-9cc2-cab82c658e29.png)

3. Access to the detail of a post:
![image](https://user-images.githubusercontent.com/116877667/209164234-01157fe4-7fe3-4bbe-929f-b99582690556.png)

4. See the network error
{"errors":[{"extensions":{"code":"validation-failed","path":"$.selectionSet.posts_by_pk.args.id"},"message":"variable 'id' is declared as 'uuid!', but used where 'Int!' is expected"}]}

### Expected behavior

Give the possibility of defining these use cases for different data schemas by parameterization.

### Desktop

- OS
- Browser: Last Chrome
- Data Provider: @pankod/refine-hasura

**Comment by yildirayunlu** [comment]
Hey @diegoarda for the UUID problem, you can solve it temporarily.

```
import { useParams } from "@pankod/refine-react-router-v6";

....

const { id } = useParams();
const { queryResult } = useShow<IPost>({
  metaData: {
    fields: [
      "id",
      "title",
      {
        category: ["title"],
      },
      "content",
    ],
    // override variables
    variables: {
      id: { value: id, type: "Int", required: true },
    },
  },
});
```

However, as a definitive solution, `dataProvider` can only be added to `client` as well as `idType`.

Can you open a pr for solving these problems to support us? 🙏

**Comment by diegoarda** [comment]
I don't understand at all your answer. Do you see better that the option is added to Hasura's `GraphQLClient`? It's constructor could be `new GraphQLClient(url, options, config)` where config could be `{ idType: 'Int' }`.

About remote schemas problem, could you fix it?

Thanks a lot!

**Comment by yildirayunlu** [comment]
Hey @diegoarda 

I think the temporary solution is not for you. Let me explain my solution in more detail.

You can copy the data provider files to your project and make changes as follows. You can solve this quickly.

```
const dataProvider = (client: GraphQLClient, options?: { idType: string } }): Required<DataProvider> => {
```
https://github.com/refinedev/refine/blob/next/packages/hasura/src/dataProvider/index.ts#L154

If you want to contribute to the **refine** for this topic, you can create a PR 🙏

**Comment by zulianrizki** [comment]
> Hey @diegoarda
> 
> I think the temporary solution is not for you. Let me explain my solution in more detail.
> 
> You can copy the data provider files to your project and make changes as follows. You can solve this quickly.
> 
> ```
> const dataProvider = (client: GraphQLClient, options?: { idType: string } }): Required<DataProvider> => {
> ```
> 
> https://github.com/refinedev/refine/blob/next/packages/hasura/src/dataProvider/index.ts#L154
> 
> If you want to contribute to the **refine** for this topic, you can create a PR 🙏

i will try to create PR for this issue

**Comment by BatuhanW** [comment]
Hey @zulianrizki, thanks! We are looking forward to it.
