### ISSUE TITLE
[DOC] The image not present under the heading "Quick Start".

### ISSUE THREAD

**Issue by FidalMathew** [refinedev/refine#3312]
### Documentation issue

The image is not present in the read.MD file under the heading "Quick Start".

![image](https://user-images.githubusercontent.com/84982038/209321469-5090ef27-118b-45d9-ad71-160f162fbbd0.png)

### Describe the thing to improve

An image of the landing page of the website present at [localhost:3000](http://localhost:3000/) can be used as the image.

**Comment by omeraplak** [comment]
Hey @FidalMathew ,
Thank you for contacting us! We've fixed ⚡️
