### ISSUE TITLE
[BUG] i18n notification message

### ISSUE THREAD

**Issue by omeraplak** [refinedev/refine#3328]
### Discussed in https://github.com/refinedev/refine/discussions/3325

<div type='discussions-op-text'>

<sup>Originally posted by **EugeneKostin** December 30, 2022</sup>
Hi everyone,
I use default i18n namespace instead "common" and find untranslated notifications. In the refine-core src files, the useList hook notification uses a message with a common namespace when other hooks use the default. Is this an issue or am I missing something?

useList
```
...
message: translate(
    "common:notifications.error",
    { statusCode: err.statusCode },
    `Error (status code: ${err.statusCode})`,
),
```

useOne
```
...
message: translate(
    "notifications.error",
    { statusCode: err.statusCode },
    `Error (status code: ${err.statusCode})`,
),
```
Thanks for your help!</div>

**Comment by sevkioruc** [comment]
Hi @omeraplak,
Could you please assign me it?

**Comment by sevkioruc** [comment]
Hey @omeraplak @aliemir,
I changed useList hook but i couldn't test it.
How can i test it?

**Comment by omeraplak** [comment]
Hey @sevkioruc ,
Congrats! You can follow the contribution docs

https://refine.dev/docs/contributing/#running-in-development-mode
