### ISSUE TITLE
[BUG] Material-UI createTheme does not expose MuiDataGrid

### ISSUE THREAD

**Issue by derTuca** [refinedev/refine#3332]
### Describe the bug

If one wants to customize the DataGrid via the main theme, Typescript throws an error because MuiDataGrid is not present in the components object of the Theme object. The @mui/x-data-grid docs recommend [adding a type augmentation](https://mui.com/x/react-data-grid/getting-started/#typescript), but since the createTheme that we get is from the refine library and not mui directly, we can't use the augmentation.

As a workaround, setting the object passed to createTheme as any allows us to style the DataGrid, but we lose Typescript for it.

### Steps To Reproduce

1. Create a theme via the `@pankod/refine-mui`-exposed `createTheme`
2. Use the following structure:
 ```
 components: { 
  MuiDataGrid: {
    styleOverrides: {
      cell: {
        borderBottom: "1px solid black !important"
      }
    }
  }
}
```

### Expected behavior

To get Typescript autocomplete for the MuiDataGrid object

**Comment by alicanerdurmaz** [comment]
Hi @derTuca, Thanks for the issue. we will look into it immediately 🙏

**Comment by derTuca** [comment]
Removing the ol' node_modules, yarn.lock and removing/readding the type augmentation seems to do the trick, sorry for the noise!

Still, I am left wondering, considering the fact that x-data-grid is part of refine-mui anyways, would it not be a better idea to include this type augmentation from refine's DataGrid export?

I am leaving the issue open just in case the question above is of any interest but you can close it anytime. Thank you for your time!

**Comment by alicanerdurmaz** [comment]
I'm glad to hear that 🥳 

You are right but we couldn't figure out how we can export `typeAugmentation` from the `refine` package. We would be very pleased if you would like to open PR 🙏
