### ISSUE TITLE
[BUG] Font family override does not work

### ISSUE THREAD

**Issue by mantasmas** [refinedev/refine#3345]
### Describe the bug

Typography override does not work - when trying to change fontFamily from Monserrat to Roboto only, it does not work, when inspecting elements, same `Montserrat,-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol"` stays.

### Steps To Reproduce

1. In src/App.tsx define theme override:
```
export const typography: TypographyVariantsOptions = {
  fontFamily: ["Roboto", "Arial", "sans-serif"].join(","),
};

const overridenLightTheme = {
  ...LightTheme,
  palette: {
    ...LightTheme.palette,
    primary: {
      main: "#1976D2",
      contrastText: "#FFFFFF",
    },
    secondary: {
      main: "#363A47",
    },
  },
  ...typography,
};
```
2. Pass it to the ThemeProvider
3. Inspect page texts

### Expected behavior

`font-family` properties to be changed to the one defined in the typography override

### Screenshot

<img width="1874" alt="image" src="https://user-images.githubusercontent.com/14222839/210533742-c6ea76c6-476e-47c7-b9dc-28ac615e713c.png">

### Desktop

- Browser: Chromium
- "@pankod/refine-cli": "^1.2.0",
- "@pankod/refine-core": "^3.18.0",
- "@pankod/refine-inferencer": "^1.2.0",
- "@pankod/refine-mui": "^3.30.0",

**Comment by omeraplak** [comment]
Hey @mantasmas ,
Thank you for contacting us! I'm not sure this bug is related to refine. Does everything work as expected when you try it with the MUI?

**Comment by alicanerdurmaz** [comment]
Hi @mantasmas, I try to reproduce the issue and font customization works as expected.

You need to use `createTheme()` and you should nest `fontFamily` inside the `typography` object.

```ts
import {
  LightTheme,
  ThemeProvider,
  createTheme,
} from '@pankod/refine-mui';

export const typography: TypographyVariantsOptions = {
  fontFamily: ['Roboto', 'Arial', 'sans-serif'].join(','),
};

const overridenLightTheme = {
  ...LightTheme,
  palette: {
    ...LightTheme.palette,
    primary: {
      main: '#1976D2',
      contrastText: '#FFFFFF',
    },
    secondary: {
      main: '#363A47',
    },
  },
  typography: typography,
};

const theme = createTheme({
  ...overridenLightTheme,
});

<ThemeProvider theme={theme}>
```


https://stackblitz.com/edit/refinedev-refine-t9znrb?file=src/App.tsx

**Comment by mantasmas** [comment]
Hi @alicanerdurmaz Yeah, I think I've found what was wrong with my code - I was following the https://refine.dev/docs/api-reference/mui/customization/mui-custom-theme/#overriding-variables code which spreads the typography property whereas it should be passed as typography property. Could you update the documentation to remove wrong syntax?
