### ISSUE TITLE
[BUG] Warning "Something went wrong when trying to get installed 'refine' packages."

### ISSUE THREAD

**Issue by vanflux** [refinedev/refine#3348]
### Describe the bug

When a refine project is created inside a monorepo with workspace feature enabled, the following warning appear when `refine dev` is executed: `Something went wrong when trying to get installed refine packages.`.

### Steps To Reproduce

- Create a blank project (not refine, but npm init)
- Go to the package.json and add the following key:
```
"workspaces": [
  "apps/*"
]
```
- Create and go to apps dir
- Create a refine project with `npm create refine-app@latest refine-app` using next.js + yarn
- Go to refine-app dir
- Run `yarn dev`
- See `Something went wrong when trying to get installed 'refine' packages.` on the console

### Expected behavior

Get the package list correctly and don't see the warning.

### Desktop

OS: Linux Mint
CLI version = 1.13.0

### Additional Context

When refine project is created inside a monorepo, some packages are hoisted to the root and `npm ls` command throws an error marking some packages as `UNMET DEPENDENCY`, but the json with all the packages is returned. When you run `refine dev` an warning appear: `Something went wrong when trying to get installed refine packages.`. `yarn list` doesn't throw this, but yarn isn't an viable option for all the projects, we could ignore the npm error and get the package list.

**Comment by alicanerdurmaz** [comment]
Hi @vanflux, thanks for the issue 🙏 

But your project is running isn't it ? 

I mean, Is throwing an error and stopping your `refine dev` command or just printing `Something went wrong when trying to get installed refine packages.` and continuing to running the app?

**Comment by vanflux** [comment]
> Hi @vanflux, thanks for the issue pray
> 
> But your project is running isn't it ?
> 
> I mean, Is throwing an error and stopping your `refine dev` command or just printing `Something went wrong when trying to get installed refine packages.` and continuing to running the app?

The project is running because refine ignores the error, but shows this annoying message, even when npm ls returns all packages.
