### ISSUE TITLE
[FEAT] Update axios for @pankod/refine-strapi-v4

### ISSUE THREAD

**Issue by dzcpy** [refinedev/refine#3350]
### Is your feature request related to a problem? Please describe.

Hi, currenty @pankod/refine-strapi-v4 is using axios v0.26 which is a pretty old version. The most current one is v1.2.x. Is it possible to update the dependency to the most current one? I'm having problems after upgrading axios, there is a typescript error.

### Describe the thing to improve

Use axios 1.2.x

**Comment by yildirayunlu** [comment]
Hey @dzcpy let's check and try to update. What is the error?

**Comment by dzcpy** [comment]
> Hey @dzcpy let's check and try to update. What is the error?

Thanks for your quick reply!
Here is the typescript error, I'm using axios 1.2.2
![Uploading image.png…]()

**Comment by yildirayunlu** [comment]
It is necessary to update `axios` in all our packages. We've added this issue to the to do list.

For a quick solution, you can fork `@pankod/refine-strapi-v4`, include it in your project and update it 🚀

**Comment by BatuhanW** [comment]
Hello 👋🏼 

Closing the issue due to inactivity. Please feel free to re-open it if needed.
