### ISSUE TITLE
[BUG] The color configuration of the sidebar is out of sync with the theme

### ISSUE THREAD

**Issue by qianxuanyon** [refinedev/refine#3365]
### Describe the bug

The color configuration of the sidebar is out of sync with the theme

### Steps To Reproduce

The theme of the sidebar does not match the specified theme
The sidebar does not change synchronously after modifying the color parameter in the example customization-theme-mui
I used the default mui theme Settings but the sidebar was not applied

customization-theme-mui/src/contexts/index.tsx
```js

import React, {
    PropsWithChildren,
    createContext,
    useEffect,
    useState,
} from "react";
import { ThemeProvider } from "@pankod/refine-mui";
import { DarkTheme } from "@pankod/refine-mui";

import { createTheme } from "@mui/material";

const LightTheme = createTheme({

    components: {
        MuiAppBar: {
            styleOverrides: {
                colorDefault: {
                    backgroundColor: "#4f3cc9",
                },
            },
        },
    
        MuiTypography: {
            styleOverrides: {
                h5: {
                    fontWeight: 800,
                    lineHeight: "2rem",
                },
            },
        },
    },
});


type ColorModeContextType = {
    mode: string;
    setMode: () => void;
};

export const ColorModeContext = createContext<ColorModeContextType>(
    {} as ColorModeContextType,
);

export const ColorModeContextProvider: React.FC<PropsWithChildren> = ({
    children,
}) => {
    const colorModeFromLocalStorage = localStorage.getItem("colorMode");
    const isSystemPreferenceDark = window?.matchMedia(
        "(prefers-color-scheme: dark)",
    ).matches;

    const systemPreference = isSystemPreferenceDark ? "dark" : "light";
    const [mode, setMode] = useState(
        colorModeFromLocalStorage || systemPreference,
    );

    useEffect(() => {
        window.localStorage.setItem("colorMode", mode);
    }, [mode]);

    const setColorMode = () => {
        if (mode === "light") {
            setMode("dark");
        } else {
            setMode("light");
        }
    };

    return (
        <ColorModeContext.Provider
            value={{
                setMode: setColorMode,
                mode,
            }}
        >
            <ThemeProvider theme={mode === "light" ? LightTheme : DarkTheme}>
                {children}
            </ThemeProvider>
        </ColorModeContext.Provider>
    );
};

```

### Expected behavior

Expect the theme of the sidebar to match the theme configuration

For example, I want to change the sidebar to black text on a white background

There is currently no way to adjust the color of the sidebar font

### Screenshot

<img width="1480" alt="image" src="https://user-images.githubusercontent.com/29041881/211208075-eeacd24e-17f9-42ce-841d-db7918c08582.png">

**Comment by qianxuanyon** [comment]
You can refer to https://bareynol.github.io/mui-theme-creator/#
The theme fonts color in the sidebar are consistent with the whole thing

<img width="893" alt="image" src="https://user-images.githubusercontent.com/29041881/211243881-1ff41818-ecfa-4a28-8115-9f66d37965ac.png">

<img width="1487" alt="image" src="https://user-images.githubusercontent.com/29041881/211243851-278ea699-e070-4453-9fbb-000cdaad1859.png">

**Comment by omeraplak** [comment]
Hey @qianxuanyon ,
Thank you for contacting us! We will investigate and resolve the issue as soon as possible.

**Comment by yildirayunlu** [comment]
Hey @qianxuanyon 

`refine` has default color palettes for [dark](https://github.com/refinedev/refine/blob/next/packages/mui/src/theme/palette/darkPalette.ts) and [light](https://github.com/refinedev/refine/blob/next/packages/mui/src/theme/palette/lightPalette.ts). It is used in the whole project. If these are not defined mui shows strange colors 😅  

You can extend or customize it all.

```import { LightTheme, ThemeProvider } from "@pankod/refine-mui";
import { DarkTheme, createTheme } from "@pankod/refine-mui";

const custom = createTheme({
    palette: {
        ...LightTheme.palette,
    },
    components: {
        MuiAppBar: {
            styleOverrides: {
                colorDefault: {
                    backgroundColor: "#4f3cc9",
                },
            },
        },
    },
});
```

<img width="1361" alt="image" src="https://user-images.githubusercontent.com/3484713/211306728-4a17158d-73e6-49d1-8f21-982988ab7d4c.png">

**Comment by yildirayunlu** [comment]
Hey @qianxuanyon Thank you for the detailed explanation. We will review it and release an update 🚀

**Comment by yildirayunlu** [comment]
This is the theme that is prepared with refine colors by default for the MUI. We support personalized theme. You can check [here](https://refine.dev/docs/api-reference/mui/customization/mui-custom-theme/#create-custom-theme) for details.
