### ISSUE TITLE
[BUG] btoa is not defined

### ISSUE THREAD

**Issue by narendra087** [refinedev/refine#3366]
### Describe the bug

Hi, I encountered an error while deploying my project on the server.
I'm using refine + remix with antd design using create-refine-app.

It says that `ReferenceError: btoa is not defined`
Here the screenshot:
![image](https://user-images.githubusercontent.com/19150149/211231951-d40ca660-1bfb-43d4-ab4b-0ee856052ee5.png)

did anyone experience something similar?
if so, how to fix the error.
thank you

### Steps To Reproduce

1. Deploy the project to the server

### Expected behavior

No error on the build process

### Screenshot

![image](https://user-images.githubusercontent.com/19150149/211232022-d79206a6-1e18-498c-9e7a-9948836158cc.png)

### Desktop

Refine Packages:
 - @pankod/refine-antd: ^3.18.0
 - @pankod/refine-cli: ^1.2.0
 - @pankod/refine-core: ^3.58.0
 - @pankod/refine-inferencer: ^1.2.0
 - @pankod/refine-remix-router: ^1.0.2
 - @pankod/refine-simple-rest: ^3.18.0
 - @remix-run/node: ^1.6.8
 - @remix-run/react: ^1.6.8
 - @remix-run/serve: ^1.6.8

**Comment by duttabhishek0** [comment]
The exception is due to the fact that node.js doesn't supports `btoa` method. An alternative is to use the buffer class. Seems like the codebase already has that code to handle such case.
Can you comment out the following lines in your version of code, and then try running it?
https://github.com/refinedev/refine/blob/836aa12f344209ea86e687f962b18f301ccee079/packages/core/src/components/telemetry/index.tsx#L10-L12

**Comment by narendra087** [comment]
Sorry, it's my first project using refine and It seems that I can't find the code that you mention.
can you explain more about that code?

I'm using refine + remix, with create-refine-app..

**Comment by duttabhishek0** [comment]
Just open the `index.tsx` file present in `refine/packages/core/src/components/telemetry/` path. Comment out line 10-12, and then check.

**Comment by duttabhishek0** [comment]
I thought you were building directly from the codebase.My bad.

**Comment by alicanerdurmaz** [comment]
Hi @narendra087, sorry for your trouble. what is your node.js version?

**Comment by narendra087** [comment]
> Hi @narendra087, sorry for your trouble. what is your node.js version?

Hi. I'm using node.js v16.15.1

**Comment by alicanerdurmaz** [comment]
`v16.15.1` is in the server, am I right?

**Comment by narendra087** [comment]
Yes, is in the server.

**Comment by alicanerdurmaz** [comment]
we should change `btoa` to `Buffer.from("string").toString('base64')`.
sorry for your trouble again, we will release a fix as soon as possible.

if we can find a faster solution without release. I will let you know.

**Comment by narendra087** [comment]
> we should change `btoa` to `Buffer.from("string").toString('base64')`. sorry for your trouble again, we will release a fix as soon as possible.
> 
> if we can find a faster solution without release. I will let you know.

Okay, thank you @alicanerdurmaz for the solution.

**Comment by omeraplak** [comment]
Hey @narendra087 ,
We've released [@pankod/refine-cli@1.17.0](https://github.com/refinedev/refine/releases/tag/%40pankod%2Frefine-cli%401.17.0). Could you approve this fix?
