### ISSUE TITLE
[BUG] DataGrid not changing loading state when mutating or invalidating data

### ISSUE THREAD

**Issue by MetaMmodern** [refinedev/refine#3374]
### Describe the bug

I am using a DataGridPro with row reordering functionality. Whenever I reorder rows I store new order into state and show a "Save new order" button. When user clicks this button I do the following:
1. Run a customMutation using `useCustomMutation` to send new row order to backend.
2. After that I invalidate query result using "useInvalidate". This way I'm trying to tell refine that this data needs to be refetched.

<details>
<summary>Overall screenshot</summary>

![image](https://user-images.githubusercontent.com/42899786/211651052-d5c504a0-3931-403e-a3fe-b6f295b9eb2d.png)

Pleaase don't mind red lines, it was about another issue.
</details>

What happens is that when I call `invalidate` I expect `useDataGridProps().dataGridProps.isLoading` property to switch from false to true, but this does not happen. Instead, my DataGrid simply gets silently updated without any loading indication.

I've asked this in Discord(https://discord.com/channels/837692625737613362/1062412321642786816), and @omeraplak helped and pointed that it might be a bug here: 
https://github.com/refinedev/refine/blob/next/packages/mui/src/hooks/useDataGrid/index.ts#L310

Probably that "else" block in ternary should be `isFetching` instead of `!isFetched`.
I could make a PR, but it can be a wrong assumption, so I'd better not.

### Steps To Reproduce

Described in description.

Except you don't really need to have DataGridPro component, simply add some invalidation to your resource list by button click, that would be enough to see the behaviour.

### Expected behavior

DataGrid shows loading progress when data (or resource) it's using get's invalidated and (re-)fetched.

### Screenshot

Added above.

### Desktop

Not platform-specific.

### Mobile

Not platform-specific.

**Comment by aliemir** [comment]
Hey @MetaMmodern, thank you for opening the issue. We will investigate the issue but looks like the line causing this issue is already found 🙏 i will try to deploy a fix soon 🚀🚀

**Comment by MetaMmodern** [comment]
Well, it might break some integration in existing apps out there, so Idk if it counts as a fix or as a major update))

**Comment by omeraplak** [comment]
more details: https://discord.com/channels/837692625737613362/1062412321642786816

**Comment by omeraplak** [comment]
Hey @MetaMmodern ,
We discussed this issue. If we use `isFetching`, the loading state is active again in every pagination. I think everyone likes the way it is now :)

**Comment by MetaMmodern** [comment]
> Hey @MetaMmodern ,
> We discussed this issue. If we use `isFetching`, the loading state is active again in every pagination. I think everyone likes the way it is now :)

Okay, that's good) thank you, I'll update my code accordingly
