### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by barrynerd** [refinedev/refine#3386]
### Describe the bug

vscode reports missing tsconfig.build.json file in refine-antd in "extends" line

### Steps To Reproduce

- create generic antd application as explained in Discussion #3343
- start server

### Expected behavior

no problems listed in the problems tab

### Additional Context

my workaround (may not work for everyone) is to simply delete the extends line, since I don't have a tsconfig.build.json to extent.

**Comment by aliemir** [comment]
Hey @barrynerd please update the issue with a more descriptive title and provide a detailed description on what's happening, thank you 🙏

**Comment by liusida** [comment]
I think @barrynerd meant this line:
https://github.com/refinedev/refine/blob/d0ace600bacadc22b749bc8f479d266abe83929a/packages/core/tsconfig.json#L3

VSCode is complaining about this line, saying 'Cannot read file `tsconfig.build.json`.' When he simply deletes this line, everything is fine.

So the question is, what is this line for?
