### ISSUE TITLE
[BUG] [Typing] useTable does return unknown error type

### ISSUE THREAD

**Issue by capsloq** [refinedev/refine#3395]
### Describe the bug

```js
import { useTable } from "@pankod/refine-react-table"
...
   const useTableMethods = useTable<ExpenseLaborAPI, HttpError>({
      refineCoreProps: {
         resource: ExpensesEnum.Labor,         
     
      },
      columns,
   })

   const {
      refineCore: {
         tableQueryResult: { data: tableData, error, isLoading, isSuccess, refetch },
      },
   } = useTableMethods
```

`tableData`, `isLoading`, `isSuccess `and `refetch `are correctly typed. `error `is `unkown`. 

### Steps To Reproduce

see above

### Expected behavior

error should be correctly typed

### Screenshot

![image](https://user-images.githubusercontent.com/73945900/212489803-552eb0f6-cfdc-43e5-a9c2-b7ab29a27b11.png)

### Additional Context

@omeraplak  added in discord:
"Ömer — Today at 18:44
It seems we don't use generic error type in return type"
[https://github.com/refinedev/refine/blob/next/packages/react-table/src/useTable/index.ts#L19](https://github.com/refinedev/refine/blob/next/packages/react-table/src/useTable/index.ts#L19)

**Comment by yildirayunlu** [comment]
Hey @capsloq Thank you for reporting this issue 🙏🏼 We will solve it as soon as possible 🚀
