### ISSUE TITLE
[FEAT] Support cursor based pagination in table component

### ISSUE THREAD

**Issue by buremba** [refinedev/refine#3408]
### Is your feature request related to a problem? Please describe.

The underlying data that I have with my `dataProvider` periodically changes and the current offset-based pagination doesn't provide any guarantee of consistency. Instead of offset-based pagination, I want to pick a column (usually PK but not always integer / long) and filter based on that column with a cursor in the table component. Here are some use-cases where offset pagination is considered harmful. [1])(https://uxdesign.cc/why-facebook-says-cursor-pagination-is-the-greatest-d6b98d86b6c0), [2](https://dev.to/appwrite/this-is-why-you-should-use-cursor-pagination-4nh5)use cases

### Describe alternatives you've considered

If my table has a primary column that is integer/long, I can use `offset` in a way similar to cursor pagination but this approach doesn't work if the primary key is timestamp, string or a composite key. Also, even if the primary key is integer/long, the UX is not good as the values might be sparse instead of being incremental and continuous.

### Describe the thing to improve

An interface in `dataProvider` that lets me provide a cursor value. Material UI already supports it out of the box: https://mui.com/x/react-data-grid/pagination/#cursor-implementation

**Comment by buremba** [comment]
Oh, I guess I'm lucky today. Thanks folks!

**Comment by yildirayunlu** [comment]
Hey @buremba 

I prepared a sample application about [MUI Cursor Pagination](https://github.com/refinedev/refine/tree/next/examples/table-mui-cursor-pagination).

Use `metaData` method of the `useDataGrid` hook and the Github API. Send the last row's creation date to the data provider with `metaData.next`, overriding the page changes with `onPageChange`.

```tsx
onPageChange={(page, details) => {
    // Github API returns the latest commit date as the next cursor
    const lastRow = data?.data[data.data.length - 1];
    const next = lastRow?.commit.committer.date;
    if (next) {
        setNext(next);
    }
    dataGridProps.onPageChange?.(page, details);
}}
```

Also, Send a request by reading this `next` value in the data provider.

I hope this sample application will help you 🚀
