### ISSUE TITLE
[BUG] Ant Design's AuthPage doesn't send user's email

### ISSUE THREAD

**Issue by dzcpy** [refinedev/refine#3418]
### Describe the bug

When using Ant Design's Auth Page for the admin backend, no matter what you input in the form, it will always ignore the email which leads to incorrect login.

### Steps To Reproduce

1. Build an admin backend using Refine, set `<Refine LoginPage={AuthPage} />`
2. Login using any user account
3. Email is not sent to the server

### Expected behavior

Being able to login using AuthPage

### Screenshot

![image](https://user-images.githubusercontent.com/203980/213067645-55481051-6ac5-4964-a70f-01b9dc76782d.png)
![image](https://user-images.githubusercontent.com/203980/213067688-f3c084e6-c5c7-4f43-9374-ae5332f7c806.png)

### Desktop

- Strapi: 4.5.6
- @pankod/refine-antd: 4.7
- @pankod/refine-strapi-v4: 3.39.6

**Comment by yildirayunlu** [comment]
Hey @dzcpy

We don't have support for changing fields yet. But you can [swizzle](https://refine.dev/docs/packages/documentation/cli/#swizzle) and change it as you wish.

**Comment by dzcpy** [comment]
Hi @yildirayunlu, thanks for your quick reply! I've already found the code from github so I manually replaced the auth page. swizzle looks like a very cool feature!
