### ISSUE TITLE
[DOC] How to do a mutation from authProvider

### ISSUE THREAD

**Issue by MetaCorp** [refinedev/refine#3421]
### Documentation issue

I can't use `useCreate()` in `authProvider` since we're not in a React component.
How to do a mutation to the db table from `authProvider` ?

I'm using supabase as a back-end and I need to have more fields saved on the `user` table of supabase, so I created a `profile` table which is linked to the `user` table. Now I need to create that `profile` record after the user is registered, so I though of adding this to the `authProvider.ts`. But as I said earlier, I don't know how to make a mutation from that `register` function.

### Describe the thing to improve

Is doing this from the `authProvider` a good thing ? And how can I do so ?

**Comment by omeraplak** [comment]
Hey @MetaCorp ,
You can use directly supabaseClient on AuthProvider

example: https://github.com/refinedev/refine/blob/next/examples/pixels/src/auth-provider.ts#L5

**Comment by MetaCorp** [comment]
Thank you, I'm able to update supabase using supabaseClient this way :
```typescript
await supabaseClient.from("profiles").insert({
  id: user.id,
});
```
