### ISSUE TITLE
[BUG] Can't test a component that uses useCustomMutation

### ISSUE THREAD

**Issue by MetaMmodern** [refinedev/refine#3432]
### Describe the bug

Components that are using refine hooks are impossible to test.

One of the examples is a component making a custom request to server. 

<details>
<summary>Here is my component code.</summary>

```tsx
import { FileUpload, UploadOutlined } from '@mui/icons-material';
import { useApiUrl, useCustomMutation } from '@pankod/refine-core';
import {
  Button,
  Card,
  CardActions,
  CardContent,
  CardMedia,
  LoadingButton,
  Modal,
  SxProps,
  Typography,
} from '@pankod/refine-mui';
import { FC, useState } from 'react';
import { ThumbnailUploadResponse } from 'types';

const cardStyle = {
  position: 'absolute',
  top: '50%',
  left: '50%',
  transform: 'translate(-50%, -50%)',
  maxWidth: 400,
};

type ThumbnailUploaderProps = {
  handleThumbnailUploadSuccess: (link: string) => any;
  sx?: SxProps;
};
const ThumbnailUploader: FC<ThumbnailUploaderProps> = ({
  handleThumbnailUploadSuccess,
  sx,
}) => {
  const [modalOpen, setModalOpen] = useState(false);
  const [fileValue, setFileValue] = useState<File | null>(null);
  const [fileUrl, setFileUrl] = useState('');
  const { mutate, isLoading } = useCustomMutation<ThumbnailUploadResponse>();
  const API_URL = useApiUrl();

  const handleOpen = () => setModalOpen(true);
  const handleClose = () => setModalOpen(false);

  const handleInputChange: React.ChangeEventHandler<HTMLInputElement> = (
    event
  ) => {
    if (!event.target.files?.length) return;
    const file = event.target.files[0];
    setFileValue(file);
    setFileUrl(URL.createObjectURL(file));
    handleOpen();
    event.target.value = '';
  };

  const handleCancelUpload = () => {
    URL.revokeObjectURL(fileUrl);
    setFileUrl('');
    handleClose();
  };
  const handleSubmitUpload = () => {
    if (!fileValue) {
      return;
    }
    const formData = new FormData();
    formData.append('file', fileValue);
    mutate(
      {
        url: `${API_URL}/thumbnail`,
        values: formData,
        method: 'post',
        successNotification: {
          message: 'Succesfully uploaded thumbnail.',
          type: 'success',
        },
        errorNotification: {
          message: 'Could not save thumbnail. Please try again later.',
          type: 'error',
        },
      },
      {
        onSuccess: (data) => {
          handleCancelUpload();
          handleThumbnailUploadSuccess(data.data.url);
        },
      }
    );
  };
  return (
    <>
      <Button
        variant="outlined"
        color="primary"
        aria-label="upload picture"
        component="label"
        size="large"
        sx={sx}
      >
        <input
          hidden
          accept="image/*"
          type="file"
          onChange={handleInputChange}
          data-testid="image-input"
          id="image-input"
        />
        <FileUpload />
      </Button>
      <Modal
        open={modalOpen}
        onClose={handleClose}
        aria-labelledby="modal-modal-title"
        aria-describedby="modal-modal-description"
      >
        <Card sx={cardStyle}>
          <CardMedia
            component="img"
            image={fileUrl}
            sx={{
              maxHeight: '400px',
              objectFit: 'contain',
            }}
          />
          <CardContent>
            <Typography id="modal-modal-title" variant="h6" component="h2">
              Are you sure you want to upload this image as a thumbnail?
            </Typography>
          </CardContent>
          <CardActions sx={{ justifyContent: 'end' }}>
            <Button
              variant="outlined"
              color="error"
              disabled={isLoading}
              onClick={handleCancelUpload}
            >
              Cancel
            </Button>
            <LoadingButton
              variant="contained"
              startIcon={<UploadOutlined />}
              loading={isLoading}
              loadingPosition="start"
              onClick={handleSubmitUpload}
            >
              Upload
            </LoadingButton>
          </CardActions>
        </Card>
      </Modal>
    </>
  );
};

export default ThumbnailUploader;
```
</details>

<details>
<summary>Here is my test code.</summary>

```tsx

/**
 * @jest-environment jsdom
 */
import { fireEvent, render, waitFor } from '@testing-library/react';
import axios from 'axios';
import ThumbnailUploader from 'components/ThumbnailUploader';
import { QueryClient, QueryClientProvider } from 'react-query';
import { ThumbnailUploadResponse } from 'types';

const queryClient = new QueryClient();

jest.mock('axios');
const mockedAxios = axios as jest.Mocked<typeof axios>;

it('', async () => {
  const url = 'mockedUrlValue';
  const resp: ThumbnailUploadResponse = { url };
  mockedAxios.post.mockResolvedValue(resp);

  const file = new File(['(⌐□_□)'], 'chucknorris.png', {
    type: 'image/png',
  });

  const handleThumbnailUploadSuccess = jest.fn((link: string) => link);
  const { queryByLabelText, getByLabelText, getByTestId } = render(
    <QueryClientProvider client={queryClient} contextSharing={true}>
      <ThumbnailUploader
        handleThumbnailUploadSuccess={handleThumbnailUploadSuccess}
      />
    </QueryClientProvider>
  );

  const uploadInput = getByTestId('image-input');
  await waitFor(() =>
    fireEvent.change(uploadInput, {
      target: { files: [file] },
    })
  );

  let uploadInputFromDom = document.getElementById(
    'image-input'
  ) as HTMLInputElement | null;
  // file should be saved to state and cleared from DOM
  expect(uploadInputFromDom?.files?.length).toBe(0);
});

```
</details>

As you can see I even tried wrapping it onto QueryProvider(as suggested [here](https://stackoverflow.com/a/69376960/14301331)) but it didn't work saying:

`No QueryClient set, use QueryClientProvider to set one`
Screenshot below.

### Steps To Reproduce

Just try to use custom hook in separate component and try to run tests for it.

### Expected behavior

Should be easy to test components(Or at least documentation should have more info about how to actually unit test components).

### Screenshot

<img width="863" alt="image" src="https://user-images.githubusercontent.com/42899786/213569268-2006f8b5-382b-4062-88ff-2afd61fcb090.png">

### Desktop

-

### Mobile

-

**Comment by aliemir** [comment]
Hey @MetaMmodern, instead of just wrapping the component to `QueryClientProvider`, you probably need to prepare a test wrapper with `<Refine />` component. Let me share you our UI package tests and wrappers that might give you an idea about that,

`@pankod/refine-antd`'s test setup here: https://github.com/refinedev/refine/blob/next/packages/antd/test/index.tsx#L28
`@pankod/refine-mantine`'s here: https://github.com/refinedev/refine/blob/next/packages/mantine/test/index.tsx

`ErrorComponent`'s test here as an example of component testing https://github.com/refinedev/refine/blob/next/packages/antd/src/components/pages/error/index.spec.tsx#L21-L27

`Edit` component's test here for testing with routing https://github.com/refinedev/refine/blob/next/packages/antd/src/components/crud/edit/index.spec.tsx#L10-L55

`useTable` hook test example here: https://github.com/refinedev/refine/blob/next/packages/antd/src/hooks/table/useTable/useTable.spec.ts#L27-L29

You can check out our codebase for more details. 

Hope this helps!

**Comment by MetaMmodern** [comment]
@aliemir I'm using mui so I guess this one will help me: https://github.com/refinedev/refine/blob/next/packages/mui/test/index.tsx

Please don't close this issue, I'll see how this works and get back to you(hopefully today)

**Comment by MetaMmodern** [comment]
Ok, I see, I need to create my own wrapper. It would be nice though if you could expose those wrappers, they might bbe useful for most cases.

**Comment by MetaMmodern** [comment]
@aliemir awesome, works perfectly) I have a side question maybe you may know. As you saw above I've mocked axios post call and currently I'm trying to check what was that mock called with(with what arguments) and I see that it's being called with undefined. Do you maybe know what may be the reason for that?

I've updated the mock block so it's now like this:
```ts
  const url = 'mockedUrlValue';
  const resp: { data: ThumbnailUploadResponse } = { data: { url } };
  mockedAxios.post.mockResolvedValue(resp);

```

So in tests I see it's being called after mutate being called, but value is undefined:
<img width="558" alt="image" src="https://user-images.githubusercontent.com/42899786/213745484-a83dc1d3-c94f-43be-916c-528ccb574495.png">

**Comment by MetaMmodern** [comment]
@aliemir what if I get this error when trying to provide a custom daatProvider:
`There is no "default" data provider. Please pass dataProviderName.`
<img width="643" alt="image" src="https://user-images.githubusercontent.com/42899786/213750962-59446d5c-6df1-410a-8f9f-5fc7d8c5c1de.png">
<img width="669" alt="image" src="https://user-images.githubusercontent.com/42899786/213750993-5f582fad-5755-42a9-b565-9ad9df95064a.png">

**Comment by aliemir** [comment]
Hey @MetaMmodern sorry missed your comments but I guess the case resolved, right? 😅

**Comment by aliemir** [comment]
> Ok, I see, I need to create my own wrapper. It would be nice though if you could expose those wrappers, they might bbe useful for most cases.

Not all of the props are required and we thought exporting those mocks might lead to misunderstandings since they're just dummy placeholders and we need to mock properly when we need them in tests 😅

**Comment by MetaMmodern** [comment]
> Hey @MetaMmodern sorry missed your comments but I guess the case resolved, right? 😅 

Yes, case resolved, thanks a lot) you can close the ticket if you want

**Comment by MetaMmodern** [comment]
> > Ok, I see, I need to create my own wrapper. It would be nice though if you could expose those wrappers, they might bbe useful for most cases.
> 
> Not all of the props are required and we thought exporting those mocks might lead to misunderstandings since they're just dummy placeholders and we need to mock properly when we need them in tests 😅 

Well, according to code most of props of TestWrapper are optional. And that's pretty comfy for user tests, because in my case I just copypasted your testwrapper and used it as is. Only on test I provided my own dataProvider, I didn't have ro pass all the other providers since they were mocked by TestWrapper if props not passed.

**Comment by omeraplak** [comment]
everything seems to be solved about this issue :)

**Comment by kimsean** [comment]
> @aliemir what if I get this error when trying to provide a custom daatProvider: `There is no "default" data provider. Please pass dataProviderName.` <img alt="image" width="643" src="https://user-images.githubusercontent.com/42899786/213750962-59446d5c-6df1-410a-8f9f-5fc7d8c5c1de.png"> <img alt="image" width="669" src="https://user-images.githubusercontent.com/42899786/213750993-5f582fad-5755-42a9-b565-9ad9df95064a.png">
> 
> UPDATE: I found the reason. I had to add all methods(or some of required ones) to dataProvider so it counts as a normal dataProvider. Again, case solved) hehe

Hi. May i know your where did you get RefineTestWrapper ?
