### ISSUE TITLE
[BUG] Tutorial project not created when using yarn

### ISSUE THREAD

**Issue by wuju** [refinedev/refine#3438]
### Describe the bug

Issue occurred while following the getting started guide for version 3.xx.xx
https://refine.dev/docs/tutorial/getting-started/mui/create-project/

Creating the project with `npm` works fine, but does not work using using `yarn`, the following command and output can be observed, without any files being generated.

### Steps To Reproduce

1. Install node
2. Install yarn
3. Run CLI command to create tutorial project `yarn create refine-app -- -o refine-mui tutorial`

### Expected behavior

1. Installation wizard to start
2. Project folder and files to be created

### Screenshot

```
$ yarn create refine-app -- -o refine-mui tutorial
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed in 5s 797ms
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed
➤ YN0000: Done in 6s 66ms
```

### Desktop

Node version: 18.13.0 (installed using `n`)
Yarn version: 3.3.1
OS: Ubuntu 22.04.1 LTS

**Comment by yildirayunlu** [comment]
Hey @wuju 

Thank you for reporting this issue.

I also reproduced the problem. We'll see what we can do.

**Comment by yildirayunlu** [comment]
We currently only support yarn v1 😞 We have added this problem to our work list and we want to solve it as soon as possible. 

If you are an expert in Yarn can you help us 🙏🏼
