### ISSUE TITLE
[FEAT] Hasura naming conventions (camelCase)

### ISSUE THREAD

**Issue by kevinmichaelchen** [refinedev/refine#3482]
### Is your feature request related to a problem? Please describe.

Currently we hard-code snake-case operation and type names.

But recently Hasura released a [setting](https://hasura.io/docs/latest/schema/postgres/naming-convention/) where you can switch from snake_case to camelCase.

### Describe the thing to improve

The [Hasura DataProvider](https://github.com/refinedev/refine/blob/master/packages/hasura/src/dataProvider/index.ts) should be refactored to support camelCase.

**Comment by omeraplak** [comment]
Hey @kevinmichaelchen ,
Thank you! Do you want to create a PR?

**Comment by mattbho** [comment]
@omeraplak I can submit a PR for this if still needed!

**Comment by BatuhanW** [comment]
Hello @mattbho, assigned to you!

**Comment by austin047** [comment]
Hello, @omeraplak and @mattbho I might also need this feature for one of my upcoming projects, can I help with this feature?

**Comment by mattbho** [comment]
Hey @austin047, Yea! I'd love to spearhead this with you. Are you on the repo discord? Want to set a time to pair program?

Sorry I've been wrapped up in some interviews so this has kind have been sitting but I can show you what I have so far.

**Comment by austin047** [comment]
Hello @mattbho, Yes I am on the repo's discord. Yes, we can setup a time to talk about it and move forward from there.

**Comment by austin047** [comment]
Hey @mattbho I am still waiting on your reply on this issue.

**Comment by mattbho** [comment]
@austin047 Sorry for the late response. I messaged you on Discord.
