### ISSUE TITLE
[DOC] finefoods-mui example installation

### ISSUE THREAD

**Issue by rasitcolakel** [refinedev/refine#3515]
### Documentation issue

I **copied and run** the command to install finefoods-mui example. It threw an error which is error: unknown option '--example'.

The command I run:
npm create refine-app@latest -- --example finefoods-mui

### Describe the thing to improve

The command below solves the problem

npm create refine-app@latest --example finefoods-mui

**Comment by yildirayunlu** [comment]
Hey @rasitcolakel 

I think without `--` the parameter (--example) will not pass. What is your `node` and `npm` version?

**Comment by rasitcolakel** [comment]
Thanks @yildirayunlu, It was about the node version.
