### ISSUE TITLE
[BUG] Windows / PowerShell7 'sh' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by TimKraemer** [refinedev/refine#3534]
### Describe the bug

Hello,

running `npm run refine dev` throws error.

### Steps To Reproduce

1) within Windows 11 / PowerShell 7 I ran `npm create refine-app@latest refine-test` - after asking me some questions worked as expected created a project folder structure
2) `npm run dev` giving me:
```bash
PS D:\Projects\refine-test> npm run dev

> refine-test@0.1.0 dev
> cross-env NODE_OPTIONS=--max_old_space_size=4096 refine dev

'sh' is not recognized as an internal or external command,
operable program or batch file.
```
3) I tried different combinations of yarn / npm and powershell/cmd it's always the same error.

### Expected behavior

run dev should not expect `sh` to be installed

### Desktop

- OS: Windows 11
- node v19.5.0
- PowerShell7

### Additional Context

I wonder if this is a problem of refine or one of it's dependenies, since I can develop other related projects like next-js without any problems in the same environment.

running `npm run refine` works as expected:
```
PS D:\Projects\refine-test> npm run refine --version
9.3.1
```

btw. with WSL2 and on my linux machine everything works as expected.

**Comment by aliemir** [comment]
Hey @TimKraemer, sorry for the issue. Not sure where's the error coming from but I'll try to investigate further. Just to make sure its not `cross-env` related, can you try without it? Like, updating the `dev` command as just `refine dev` and run `npm run dev` again? While creating the app, which app template did you choose, CRA, Next.js or Remix? It will be really helpful if you can answer above questions 🙏 

BTW, I guess running this in git bash will also work as expected 🤔

**Comment by TimKraemer** [comment]
Hey @aliemir, just `refine dev` leads to the same error as above - so not cross-env related.
I chose Next.js as app template. I also tested CRA with the same result.

And yes, git bash also works as expected

**Comment by aliemir** [comment]
Thank you for the info @TimKraemer! We're investigating the issue, hopefully we will find and fix soon 🙏 I'll send more updates here when possible.

**Comment by omeraplak** [comment]
Hey @TimKraemer @aliemir ,
I couldn't reproduce the issue because I received different errors in the Windows environment. We are investigating the matter.

**Comment by omeraplak** [comment]
Hey @TimKraemer ,
I cannot reproduce the error you encountered. Everything is working as expected in the Windows environment. Maybe it was a temporary issue. Could you try removing your node_modules and package-lock.json files and running 'npm install' again?

**Comment by TimKraemer** [comment]
Hey @omeraplak,
it doesn't help to delete `node_modues` and `package-lock.json` but okay I will try to find the error on my side then, maybe try another machine with windows.

Thanks for looking into it!
