### ISSUE TITLE
tutorial: unit3, p3, query-string version issue

### ISSUE THREAD

**Issue by ngouy** [refinedev/refine#3555]
### Documentation issue

cf this discussion: https://github.com/refinedev/refine/pull/3532#discussion_r1097461343

refine codebase is using query-string 7.x.x, while if we follow the instructions of the tutorial from scratch, we end up with a "root" node-module query-string versioned 8.x.x

The issue is that version 8.x.x don't expose `{ stringify }` as a member anymore:

```ts
// works in v7.x.x, doesn't work in v 8.x.x
// this is what is suggested to do on the tutorial docs, but the
// version we end up with is 8.x.x so it errors out
import { stringify } from "query-string"

// works in v8.x.x
import queryString from "query-string"

const { stringify } = queryString;
```

### Describe the solution (optional)

A solution would be or to use the new "syntax", but maybe we should bump the version on refine alltogether to avoid any confusion

Another way would be to import stringify from `@pankod/refine-simple-rest` so we are sure it is not dependent of any version of query-string.

**Comment by omeraplak** [comment]
Thank you @ngouy!
