### ISSUE TITLE
[BUG]   Cannot create property 'title' on string ''

### ISSUE THREAD

**Issue by bradparks** [refinedev/refine#3587]
### Describe the bug

Render error on create product component when running through tutorial

### Steps To Reproduce

At [this page in the tutorial](https://refine.dev/docs/tutorial/getting-started/mantine/generate-crud-pages/), I used Inferencer to create a crud page for products.

I can browse the page, and edit existing entries fine. When I try and create a new entry, by clickign on new, it takes me to
http://localhost:3000/products/create

which works fine, until I fill in a value for all fields, and click away. Then it gives me the following error

  Cannot create property 'title' on string ''

### Expected behavior

The page would let me save a new product. It doesnt. I have to click on "Products" in the left side bar to continue.

### Screenshot

<img width="1039" alt="image" src="https://user-images.githubusercontent.com/185477/218080885-d76e7dfb-0bb0-47c4-8b89-9387e6ec393e.png">

### Desktop

- Mac, latest
- Chrome, latest
- Running through tutorial

**Comment by omeraplak** [comment]
Hey @bradparks ,
Thank you for contacting us! We'll fix it soon 🎯

**Comment by aliemir** [comment]
Looks like an issue between default values and the form item registration 🤔 I'll try to identify the issue and send a PR with the fix 🙏

**Comment by aliemir** [comment]
Hey @bradparks, I've just tried the Inferencer with Mantine. Used our API `https://api.fake-rest.refine.dev` with `products` resource. Both `edit` and `create` inferencers are working fine. 

If you're using a different endpoint or an API, please share a sample response so we can test it out. 

Just wanted to leave this as a reminder; We don't recommend using Inferencer's in production, the preview is provided just for showing the what the generated code will look like, It's best to copy the code and update the code as you like in your component. 🚀
