### ISSUE TITLE
[BUG] Cannot run refine (NextJS + AntDesign) dev server

### ISSUE THREAD

**Issue by fadhilrafiii** [refinedev/refine#3588]
### Describe the bug

Hello guys, please help me with my problem

My company decided to use [Refine.dev](https://refine.dev/) to help and speed up our internal app development. So actually I have already developed 2 features and 1 still in progress. But on my third feature, I cannot run the dev server. I have already try with 3 laptop

1. Windows laptop 1, I have successfully developed 2 features with it and on the third feature I can't run the dev server again. after running `yarn dev` it said that the app successfully compiled, but then it stuck (browser page just reloading, not giving any response) then my laptop got blue screen.
2. Windows laptop 2, I have successfully run the dev server twice until then the same thing happen like Windows laptop 1
3. MacOS laptop, I only successfully run the dev server once, but there are two conditions
    a. Using node 16.13.0 (what my team agreed on), but it shows error EMFILE: too many open files (not stuck until bluescreen) 
      
<img width="804" alt="Screen Shot 2023-02-11 at 15 45 00" src="https://user-images.githubusercontent.com/52844918/218280575-a8e85225-53f5-4b2c-bbb4-6a9ebc6cb4fd.png">
   
    b. Using node 16.15.1 (just trying), after the app compiled successfully it says DONE, just like after building the app
        <img width="686" alt="Screen Shot 2023-02-11 at 15 40 30" src="https://user-images.githubusercontent.com/52844918/218280484-e71911f6-d2a7-49dd-be41-0aca5206a2e6.png">
 Please help me with this, I can't continue my development, and others in my company also don't know why this is happen
 

**My assumption right now:**
There's a breaking changes in refine with next js and antd, so this is happens due to my new `yarn install`. Because, i see some changes in antd when trying to create new refine.dev with next js and antd

### Steps To Reproduce

**Notes**:
1. I have other team member which still successfully running the dev server
2. This is my app scripts in package.json
<img width="707" alt="Screen Shot 2023-02-11 at 15 50 53" src="https://user-images.githubusercontent.com/52844918/218280630-00b20cb9-666b-4021-87bc-ec95cbe286b4.png">
3. I can successfully run the basic refine app with NextJS and AntDesign ([please see this](https://refine.dev/docs/getting-started/quickstart/))

### Expected behavior

It should run the dev server, the browser page should give response for my app dev

**Comment by kid-three** [comment]
Same problem.

Happens on my local machine as well as trying to deploy on Azure Web Apps

Can run `npm run dev` with no issues. 

Seems to be an issue with MUI icons

I just tried it with a completely new and fresh install of Refine Next

```
➜  tests npm create refine-app@latest febtest
✔ Downloaded remote source successfully.
✔ Choose a project template · refine-nextjs
✔ What would you like to name your project?: · febtest
✔ Choose your backend service to connect: · data-provider-strapi-v4
✔ Do you want to use a UI Framework?: · mui
✔ Do you want to add example pages?: · inferencer
✔ Do you want to add dark mode support?: · mui-dark-mode
✔ Do you want to customize the Material UI theme?: · mui-extend-theme
✔ Do you want to customize the Material UI layout?: · mui-custom-layout
✔ Do you need i18n (Internationalization) support?: · no
✔ Do you want to add kbar command interface support?: · no
✔ Choose a package manager: · npm
✔ Would you mind sending us your choices so that we can improve superplate? · no

Success! Created febtest at febtest
```


And this is what happens if you try to build

```
➜  febtest git:(master) npm run build

> febtest@0.1.0 build
> refine build

info  - Linting and checking validity of types...
We detected TypeScript in your project and reconfigured your tsconfig.json file for you. Strict-mode is set to false by default.

The following suggested values were added to your tsconfig.json. These values can be changed to fit your project's needs:

	- incremental was set to true

info  - Creating an optimized production build...
Failed to compile.

HookWebpackError: EMFILE: too many open files, open '/Users/kinichbarcelo/Documents/tests/febtest/node_modules/@mui/icons-material/Wifi2Bar.js'
    at makeWebpackError (/Users/kinichbarcelo/Documents/tests/febtest/node_modules/next/dist/compiled/webpack/bundle5.js:28:308185)
    at /Users/kinichbarcelo/Documents/tests/febtest/node_modules/next/dist/compiled/webpack/bundle5.js:28:105236
    at eval (eval at create (/Users/kinichbarcelo/Documents/tests/febtest/node_modules/next/dist/compiled/webpack/bundle5.js:13:28771), <anonymous>:27:1)
    at /Users/kinichbarcelo/Documents/tests/febtest/node_modules/next/dist/compiled/webpack/bundle5.js:28:68649
    at /Users/kinichbarcelo/Documents/tests/febtest/node_modules/next/dist/build/webpack/plugins/next-trace-entrypoints-plugin.js:437:143
    at runNextTicks (node:internal/process/task_queues:61:5)
    at processTimers (node:internal/timers:499:9)
-- inner error --
Error: EMFILE: too many open files, open '/Users/kinichbarcelo/Documents/tests/febtest/node_modules/@mui/icons-material/Wifi2Bar.js'
caused by plugins in Compilation.hooks.processAssets
Error: EMFILE: too many open files, open '/Users/kinichbarcelo/Documents/tests/febtest/node_modules/@mui/icons-material/Wifi2Bar.js'


> Build failed because of webpack errors
```


I'm on Intel Mac Ventura 13.2.1 (22D68)

But same thing happens on Azure Web App on deploy.

**Comment by kid-three** [comment]
I just tried with a fresh NextJS install and adding all the Refine + Refine MUI dependencies and I get the same error.

**Comment by kid-three** [comment]
Nevermind.

I figured out it was because I was leaving in Instances of ` import { MuiInferencer } from "@pankod/refine-inferencer/mui";`

on the `_app.tsx` file.

Remove all instances of Inferencer before build and it works

**Comment by BatuhanW** [comment]
@kid-three Thanks for the details and the contribution!

**Comment by BatuhanW** [comment]
Hello @fadhilrafiii 

Do you still have this problem? If so, please feel free to re-open the issue!
