### ISSUE TITLE
[FEAT]Request for username login support

### ISSUE THREAD

**Issue by qianxuanyon** [refinedev/refine#3590]
### Is your feature request related to a problem? Please describe.

Dear Refine team,

I am writing to request a feature for the Refine project. Currently, the login system only supports email-based login, but there are cases where the backend doesn't support email login and only supports username login.

It would be greatly appreciated if you could add the capability to allow users to log in with their username in addition to the current email-based login system. This would make Refine more versatile and usable for a wider range of projects and users.

Thank you for your time and consideration. I am looking forward to your response.

Best regards,

### Describe alternatives you've considered

Added user name login support

### Additional context

Added user name login support

### Describe the thing to improve

Added user name login support

**Comment by salihozdemir** [comment]
Hey @qianxuanyon,

You can customize auth pages or create your own page. You can find more information [here](https://refine.dev/docs/tutorial/understanding-authprovider/antd/auth-pages/#customizing-auth-pages).

Btw, you can ask your question our discord server. You can join in [here](https://discord.com/invite/refine).

**Comment by BatuhanW** [comment]
Hey @qianxuanyon closing the issue since we haven't heard back from you. Feel free to re-open if needed.
