### ISSUE TITLE
[BUG] refine-graphql package unable to fetch data from custom graphql servers

### ISSUE THREAD

**Issue by Mingyang-Li** [refinedev/refine#3632]
### Describe the bug

Unable to use custom GraphQL server in refine at all, after digging deep into your tutorials...

Errors:
`POST body missing, invalid Content-Type, or JSON object has no keys.`

### Steps To Reproduce

1. Get an empty refine app as boilderplate
2. Install `@pankod/refine-graphql`
3. Provide this URL (custom graphql server) https://nest-graphql-prisma-g5s7.onrender.com/graphql to initialise `GraphQLClient` from `@pankod/refine-graphql`
4. Use the following codeblock to initialise the `List of Payments` (where `Payment` is an entity from my custom GraphQL API)

```ts
<RefineSnackbarProvider>
  <Refine
    dataProvider={dataProvider(client)}
    Layout={Layout}
    ReadyPage={ReadyPage}
    catchAll={<ErrorComponent />}
    routerProvider={routerProvider}
    notificationProvider={notificationProvider}
    resources={[
      {
        name: "Payment",
        list: MuiListInferencer,
        show: MuiShowInferencer,
      },
    ]}
  />
</RefineSnackbarProvider>
```

Then, start your refine app, you'll see on the UI it says `Something went wrong while fetching the resource data.`

### Expected behavior

I expect my app to be showing a list of `Payments` in a table

### Screenshot

![image](https://user-images.githubusercontent.com/53138432/219922699-f19cd263-ac49-4887-88e0-838d7dc22c7a.png)

### Additional Context

I suspect the issue is caused by your `dataProvider` is not using `queries` that match the GraphQL schema on my server.

For e,g:
When `refine` executed queries, the query body is `query: "query ($sort: String, $where: JSON, $start: Int, $limit: Int) { payment (sort: $sort, where: $where, start: $start, limit: $limit)  }`, but the schema on `payments` resolver has a different set of query argument which are: `where`, `orderBy`, `skip` and `take`

You can inspect my custom schema on my GraphQL playground: https://nest-graphql-prisma-g5s7.onrender.com/graphql
Feel feel to check out my code of my API if that'll help: https://github.com/Mingyang-Li/nest-graphql-prisma/

**Comment by Mingyang-Li** [comment]
@omeraplak Do you think I need to build a custom dataProvider or shall we fix something in `refine-graphql` package?

**Comment by aliemir** [comment]
Hey @Mingyang-Li, sorry for the issue 🙏 

Unfortunately, `@pankod/refine-inferencer` does not support GraphQL backends for now. But this is definitely on our list and we're working on providing a good GraphQL support to it. 🚀

**Comment by Mingyang-Li** [comment]
Hey @aliemir , no worries. Please do let me know if your team is looking for extra hands building out any reature related to GraphQL --- Refine is a great product overall and I'm more than happy to help with anything that's on your backlog 😃

**Comment by Mingyang-Li** [comment]
If I don't use `MuiListInferencer` but write up my own `ListPayment` page, what do I need to consider? Does `refine-graphql` still support this use case? Where can I find examples of refine implementations for custom GraphQL APIs? I've looked through all of your sample projects about GraphQL but I haven't found anything similar...yet

**Comment by BatuhanW** [comment]
Hello @Mingyang-Li

You need to write a custom graphql data provider to match with your API.

You can use [this file](https://github.com/refinedev/refine/blob/next/packages/graphql/src/dataProvider/index.ts) as a starting point and modify according to your API.
