### ISSUE TITLE
[UI BUG] The sponsor button doesn't look ideal.

### ISSUE THREAD

**Issue by Savio629** [refinedev/refine#3633]
### Describe the bug

![refine _ Build your React-based CRUD applications, without constraints! _ refine - Brave 19-02-2023 14_23_57 (2)](https://user-images.githubusercontent.com/91362589/219938557-6c684209-1e3a-49b4-9684-05f135b833e3.png)
### Steps To Reproduce

In the main website, inside of footer section the sponsor button is present.

### Expected behavior

The black border shouldn't be present, it should look like a pure white button with text and a icon on it.

### Desktop

- OS [Windows]
- Browser [Brave, Chrome]

**Comment by RishiThakurIN** [comment]
I have checked in chrome, **Sponser** button don't have extra black. This issue can be closed.

**Comment by Savio629** [comment]
@RishiThakurIN 
In my laptop's browser(Chrome & Brave) and in my phone's browser, it seems to have an extra black border.
![refine _ Build your React-based CRUD applications, without constraints! _ refine - Brave 19-02-2023 14_23_57 (3)](https://user-images.githubusercontent.com/91362589/219947927-140e8c01-77d0-4038-abea-506cf3fa1d41.png)
Can anyone else confirm?

**Comment by alicanerdurmaz** [comment]
`Chrome: 110.0.5481.100` also has black borders

**Comment by aliemir** [comment]
I knew that this day would come. We had this in our backlog but the fix got delayed multiple times 😅 Let me break down the issue and maybe we can find someone to send a quick fix for in in the community 🙈 The sponsors button is an embed from GitHub and its displayed inside an `iframe`. Our docs supports dark mode but the landing page and some others don't. In this case, in https://refine.dev we're showing the content with a light theme but if your system is in dark mode GitHub.com will serve the `button` inside the `iframe` in dark mode which has a dark background inside. 

You can check the issue fixing itself when you switch to light preference 😅 

So maybe we can fix this by adjusting the size of the button and hide the background with some border-radius 🤔 Or just use a custom button looks like the current one and redirect to the sponsors manually 😅 

Sorry for the issue everyone, I hope we'll fix this one soon 🙏

**Comment by Savio629** [comment]
I feel it's better to use a custom button rather than hiding the background.
