### ISSUE TITLE
[BUG] previous data in Create Audit Log api is empty when updating

### ISSUE THREAD

**Issue by phamvinhdat** [refinedev/refine#3648]
### Describe the bug

1. use auditlogProvider
2. useForm hook and submit form success
3. in create audit log: previous data is empty

### Steps To Reproduce

1. use auditlogProvider
2. in create audit log: previous data is empty

### Expected behavior

previous data is not empty

**Comment by BatuhanW** [comment]
Hello @phamvinhdat, thanks for the contribution!

Can you provide a codesandbox example with minimum reproducible steps?

**Comment by omeraplak** [comment]
Hey @phamvinhdat ,
I tried our audit log example and everything is working as expected. https://refine.dev/docs/api-reference/core/providers/audit-log-provider/#example

**Comment by phamvinhdat** [comment]
thank you for your support. I'm trying to reproduce it on codesandbox. I will give you when it is ready

**Comment by BatuhanW** [comment]
Hello @phamvinhdat, closin the issue due to inactivity, please feel free to re-open it if your problem persists.
