### ISSUE TITLE
[BUG] useUpdate's optimistic updates of lists queries is broken

### ISSUE THREAD

**Issue by fuunnx** [refinedev/refine#3652]
### Describe the bug

Hi, I'm using optimistic updates on a list with the `useUpdate` hook. But the updated value on the list is incomplete : only the changed values exist, everything else becomes undefined during the mutation.

This is an easy fix, a merge request can be made quickly :

https://github.com/refinedev/refine/commit/9bf2969cd6797e459590393f8d341cd81705d5b9

### Steps To Reproduce

1. Use `useList` on a resource
2. Update an item of this list with useUpdate in optimistic mode

```ts
function Component() {
  const { data: listResponse } = useList({ resource: 'resource' })

  const { mutate } = useUpdate()

  return (
    <>
      {listResponse.data?.map(item => {
        if(item.name === undefined) { throw Error('item.name is undefined') }
        return (
          <button 
            onClick={() => {
              mutate({
                resource: 'resource',
                id: item.id,
                values: { count: item.count + 1 },
                mutationMode: 'optimistic',
              })
            }}>
            {item.name} {item.count}
          </button>
        )
      })
    </>
  )
}
```

### Expected behavior

I expect item.name to remain the same, while the count is updated. But during the mutation it becomes undefined

**Comment by BatuhanW** [comment]
Hello @fuunnx thanks for the contribution!

Can you create a PR referencing this issue? We'll review ASAP.

**Comment by omeraplak** [comment]
Hey @fuunnx @BatuhanW ,
The patch looks great. Do we need to apply it to the `useUpdateMany` hook as well?

**Comment by fuunnx** [comment]
Hi, `useUpdateMany` seem good, it does not need to be changed
