### ISSUE TITLE
How to query Hasura by using MUI Datagrid

### ISSUE THREAD

**Issue by josuablejeru** [refinedev/refine#3655]
Hello everybody!

I have currently some issues wrapping my head around how to access data from Hasura by using the refine Hasura dataprovider.
There is no Example using the MUI package with the `DataGrid` component in combination with Hasura so I tried to get bits and pieces from multiple sources.

This is the error message which is blocking me currently. It tells me that there is no resource `NPI_sample_data` to be queried.
<img width="1012" alt="image" src="https://user-images.githubusercontent.com/37913833/221125619-2102cde4-04af-4079-84a4-77fafbbfc9c1.png">

My schema in Hasura is simple and not complex. In the beginning, I just wanted to render some Id's. Here you can see `NPI_sample_data` is existent.
<img width="1135" alt="image" src="https://user-images.githubusercontent.com/37913833/221123029-9f5913bd-8ebd-47a5-8fe4-528b47df5690.png">

My next step was to register the Resource using the same name as provided in Hasura.
<img width="648" alt="image" src="https://user-images.githubusercontent.com/37913833/221125870-bc3f6a8f-38be-463e-9eb9-53dfe0a9d8bd.png">

After what I created a `npi_sample_data/list.tsx` component
```tsx
import React from 'react'
import {
    DataGrid,
    GridColumns,
    List,
    useDataGrid,
} from '@pankod/refine-mui'

interface IItem {
    id: number
    npi_id: number
    pag_me_comment: string
}

/**
 * https://refine.dev/docs/api-reference/mui/hooks/useDataGrid/
*/
const ItemsList: React.FC = () => {
    const {
        dataGridProps,
    } = useDataGrid<IItem>({
        resource: 'NPI_sample_data',
        initialPageSize: 20,
        initialSorter: [
            {
                field: 'npi_id',
                order: 'asc'
            }
        ],
        metaData: {
            fields: ["npi_id"]
        }
    })

    const columns = React.useMemo<GridColumns<IItem>>(
        () => [
            {
                field: "npi_id",
                headerName: "ID",
                type: "number",
                width: 75,
            }
        ],
        []
    );

    return (
        <List>
            <DataGrid
                {...dataGridProps}
                columns={columns}
                autoHeight/>
        </List>
    )
}

export default ItemsList
```

For me, this looks totally fine and should work as the over datasource providers and UI Libraries. Your help is really appreciated as I want to use refine also in the future.  
Thank you for your time! 🤗

**Comment by BatuhanW** [comment]
Hello @josuablejeru

I think you can pass your query name in `metadata.operation` field, and name your resource differently. It doesn't need to match with the query name.

```
const {
        dataGridProps,
    } = useDataGrid<IItem>({
        resource: 'NPI_sample_data',
        initialPageSize: 20,
        initialSorter: [
            {
                field: 'npi_id',
                order: 'asc'
            }
        ],
        metaData: {
         >>>operation: "NPI_sample_data",
            fields: ["npi_id"]
        }
    })
```

**Comment by josuablejeru** [comment]
Thank you @BatuhanW for your answer! I implemented the change you suggested and got the same result.

<img width="1040" alt="image" src="https://user-images.githubusercontent.com/37913833/221163506-97e10d70-1862-44dd-babf-4013b3a34ec4.png">

here is the request send by the browser. It might be the Graphql request is not constructed as it should be.
```
{
  "query": "query ($limit: Int, $offset: Int, $order_by: [NPI_sample_data_order_by!], $where: NPI_sample_data_bool_exp) { NPI_sample_data (limit: $limit, offset: $offset, order_by: $order_by, where: $where) { npi_id } NPI_sample_data_aggregate (where: $where) { aggregate { count } } }",
  "variables": {
    "limit": 20,
    "offset": 0,
    "order_by": {
      "npi_id": "asc"
    },
    "where": {
      "_and": []
    }
  }
}
```

**Comment by BatuhanW** [comment]
This error says that `NPI_sample_data` is not found in the query root, but in your screenshot we can see that. Could you double-check your URL to hasura server? Because the generated query looks correct.

**Comment by josuablejeru** [comment]
I checked the URL again and also tried it with Insomnia there I can get my data successfully.

<img width="1213" alt="image" src="https://user-images.githubusercontent.com/37913833/221373347-d9663840-c33e-4888-a233-523b96c78477.png">

This again is the response from the browser requesting the resources.
```json
{
    "errors": [
        {
            "extensions": {
                "code": "validation-failed",
                "path": "$.selectionSet.NPI_sample_data"
            },
            "message": "field 'NPI_sample_data' not found in type: 'query_root'"
        }
    ]
}
```

**Comment by BatuhanW** [comment]
@josuablejeru Can you try your query by removing "MyQuery" part. Basically like:
```
query {
 NPI_sample_date { npi_id }
}
```

Let's see if we'll get the same error.

**Comment by josuablejeru** [comment]
@BatuhanW the query suggested by you is a valid Graphql query. I thing the dataprovider is missforming the query somehow.

**Comment by josuablejeru** [comment]
As it is shown also in the thread before. This is what is send other the wire from refine
```
{
  "query": "query ($limit: Int, $offset: Int, $order_by: [NPI_sample_data_order_by!], $where: NPI_sample_data_bool_exp) { NPI_sample_data (limit: $limit, offset: $offset, order_by: $order_by, where: $where) { npi_id } NPI_sample_data_aggregate (where: $where) { aggregate { count } } }",
  "variables": {
    "limit": 20,
    "offset": 0,
    "order_by": {
      "npi_id": "asc"
    },
    "where": {
      "_and": []
    }
  }
}
```

this is a working curl example without "myQuery"
```
curl --request POST \
  --url http://localhost:8080/v1/graphql \
  --header 'Content-Type: application/json' \
  --data '{"query":"query {\n\tNPI_sample_data{\n\t\tnpi_id\n\t}\n}\n","variables":null}'
```


this is the curl command which is generated by chrome and is the representation of what the data provider is constructing
```
curl 'http://localhost:8080/v1/graphql' \
  -H 'Accept: */*' \
  -H 'Accept-Language: en-GB,en' \
  -H 'Connection: keep-alive' \
  -H 'Origin: http://localhost:3000' \
  -H 'Referer: http://localhost:3000/' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: same-site' \
  -H 'Sec-GPC: 1' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36' \
  -H 'content-type: application/json' \
  -H 'x-hasura-role: public' \
  --data-raw $'{"query":"query ($limit: Int, $offset: Int, $order_by: [NPI_sample_data_order_by\u0021], $where: NPI_sample_data_bool_exp) { NPI_sample_data (limit: $limit, offset: $offset, order_by: $order_by, where: $where) { npi_id } NPI_sample_data_aggregate (where: $where) { aggregate { count } } }","variables":{"limit":20,"offset":0,"order_by":{"npi_id":"asc"},"where":{"_and":[]}}}' \
  --compressed
```

the response:
```
{
    "errors": [
        {
            "extensions": {
                "code": "validation-failed",
                "path": "$.selectionSet.NPI_sample_data"
            },
            "message": "field 'NPI_sample_data' not found in type: 'query_root'"
        }
    ]
}

```


I also found a Hasura Github Issue referencing the same error message but it was closed in fixed in November 2021.
https://github.com/hasura/graphql-engine/issues/7706

**Comment by BatuhanW** [comment]
Hello @josuablejeru, it's hard to judge without having the whole code. Could you provide us a reproducible example with codesandbox? Would be great. We'd like to help you 🙏🏼

**Comment by josuablejeru** [comment]
@BatuhanW thank you for the help you provided me! I found the issue. The dataprovider was misconfigured.

the default config for `x-hasura-role` provided by the template was preventing me to fetch the data
```
const client = new GraphQLClient(settings.HASURA_API_URL, {
  headers: {
    "x-hasura-role": "public",
  },
}); 
```

It must be changed to `"x-hasura-role": "admin"` or left out to work seamless if you work on a clean Hasura install
```
const client = new GraphQLClient(settings.HASURA_API_URL, {
  headers: {
    "x-hasura-role": "admin",
  },
});
```

**Comment by BatuhanW** [comment]
Hello @josuablejeru, I'm happy your issue is resolved! And it will be helpful if someone else have the similar issue. Thanks for the contribution!
