### ISSUE TITLE
[FEAT] Possibility to remove registration from AuthPage component

### ISSUE THREAD

**Issue by Mikilll94** [refinedev/refine#3658]
### Is your feature request related to a problem? Please describe.

In my app there is no user registration so I want to remove this text `Don’t have an account? [Sign up]` from AuthPage component. I want to achieve this without creating `AuthPage` component from scratch.

### Describe alternatives you've considered

Create `AuthPage` component from scratch.

### Describe the thing to improve

Add a prop `disableRegistration` to `AuthPage` component.

**Comment by Kitkatnik** [comment]
I love the idea of a disable prop!!!

To solve this right now though, have you swizzled the AuthPage? If you haven't, swizzling it will create a folder of auth components where should be able to edit the login page to remove the "Don't have an account?" text. It's not technically building it from scratch, but it is pulling it out into your components folder.

[Here's the docs on swizzling](https://refine.dev/docs/packages/documentation/cli/#swizzle)

<img width="1321" alt="_FEAT__Possibility_to_remove_registration_from_AuthPage_component_·_Issue__3658_·_refinedev_refine_and_login_tsx_—_OpenSource__Workspace_" src="https://user-images.githubusercontent.com/5871075/221344481-d8bf13a2-2e4f-4525-8ad4-abb5d1e6c118.png">


Also, if you need more help, their Discord support is AMAZING and super quick to respond there. You can join here - https://discord.gg/refine

**Comment by BatuhanW** [comment]
Hello @Mikilll94, if you pass null to the `registerLink` prop, it will be hidden.

https://refine.dev/docs/api-reference/antd/components/antd-auth-page/#registerlink
