### ISSUE TITLE
[BUG] Errors when launching example `finefoods-mui`

### ISSUE THREAD

**Issue by 0x66656c6978** [refinedev/refine#3669]
### Describe the bug

When you create a new app using the example `finefoods-mui` the UI will error out that the @ts-expect-error directive was found, but there was no error. Seemingly the error has already been fixed but it was forgotten to remove the @ts-expect-error directive.

### Steps To Reproduce

1. Create example app using `npm create refine-app@latest -- --example finefoods-mui`
2. Run example using `rpm run refine dev`

### Expected behavior

When you look at the console output and also the web app, you will immediately see the errors about the directive.

### Desktop

- OS: MacOS 13
- Browser: Chrome, Safari, Firefox, Edge
- Version: latest `next` branch

**Comment by BatuhanW** [comment]
Hello @0x66656c6978, thanks for the contribution!

I saw you closed your PR, should we close the issue as well?

**Comment by 0x66656c6978** [comment]
You could try to reproduce the steps and see if you get the same behaviour. Otherwise close it because I'm not sure whether I made an error 🙏 Thank you for the fast response!

**Comment by BatuhanW** [comment]
@0x66656c6978 I can see the same errors on local, we'll check it.

**Comment by omeraplak** [comment]
Hey @0x66656c6978 ,
Thank you for reporting the issue. I checked again, but it seems that there are still errors on the MUI side. This issue has been expected to be resolved by MUI for a long time. I'm closing it because it doesn't prevent Refine from working.

https://github.com/mui/material-ui/issues/35287
