### ISSUE TITLE
[BUG] Invalidating custom queries using custom querykey raised TypeError: this is undefined

### ISSUE THREAD

**Issue by dipbazz** [refinedev/refine#3671]
### Describe the bug

While trying to invalidate a query using a custom `queryKey` I got an error as `TypeError: this is undefined`.

### Steps To Reproduce

1. First create a custom query with a custom queryKey.
```
const {} = useCustom({
    method: "get",
    url: "https://api.fake-rest.refine.dev/posts",
    queryOptions: {
        queryKey: ["custom-key"],
    },
});
```

2. Then try to invalidate the above custom query.
```
const { invalidateQueries } = useQueryClient();
invalidateQueries(["custom-key"]);
```

This will throw an error as below:
```
TypeError: this is undefined
    invalidateQueries queryClient.ts:331
    batch notifyManager.ts:17
    invalidateQueries queryClient.ts:324
    onMutationSuccess index.tsx:76
    onSuccess useForm.ts:360
    notify mutationObserver.ts:167
    batch notifyManager.ts:17
    notify mutationObserver.ts:155
    onMutationUpdate mutationObserver.ts:93
    dispatch mutation.ts:326
    dispatch mutation.ts:326
    batch notifyManager.ts:17
    dispatch mutation.ts:328
    execute mutation.ts:214
    mutate mutationObserver.ts:127
    mutate useMutation.ts:91
    onFinish useForm.ts:356
    setTimeout handler*onFinish/< useForm.ts:355
    onFinish useForm.ts:355
    onFinish useForm.ts:157
    onSubmit index.tsx:185
    onFinish Form.js:63
    submit useForm.js:756
    promise callback*FormStore/this.submit useForm.js:752
    onClick useDrawerForm.ts:95
    handleClick button.js:104
    callCallback bundle.js:234566
    React 3
    executeDispatch bundle.js:238825
    React 14
mutation.ts:240
TypeError: error.response is undefined
    checkError authProvider.ts:55
    fn mutation.ts:172
    run retryer.ts:138
    createRetryer retryer.ts:182
    executeMutation mutation.ts:167
    execute mutation.ts:209
    mutate mutationObserver.ts:127
    mutate useMutation.ts:91
    onError useUpdate.ts:425
    execute mutation.ts:241
    mutate mutationObserver.ts:127
    mutate useMutation.ts:91
    onFinish useForm.ts:356
    setTimeout handler*onFinish/< useForm.ts:355
    onFinish useForm.ts:355
    onFinish useForm.ts:157
    onSubmit index.tsx:185
    onFinish Form.js:63
    submit useForm.js:756
    promise callback*FormStore/this.submit useForm.js:752
    onClick useDrawerForm.ts:95
    handleClick button.js:104
    callCallback bundle.js:234566
    React 3
    executeDispatch bundle.js:238825
    React 14
mutation.ts:240
undefined query.ts:433
undefined query.ts:433
```

### Expected behavior

When we invalidate a query based on custom key the query should be invalidated and re fetched whenever the query is required. 

### Desktop

- OS: Ubuntu 22.04
- Browser: Firefox
- Version: 110.0
- Used dataProvider: `refine-simple-rest` by overriding to meet custom need.

**Comment by BatuhanW** [comment]
Thanks for the report @dipbazz, we'll get back to you soon.

**Comment by BatuhanW** [comment]
Hey @dipbazz, we have some plans to fix mentioned queryKey override. We'll come up with a PR if needed soon.

By the way, it seems you have 2 errors in the report, could you investigate this part?

```
TypeError: error.response is undefined
    checkError authProvider.ts:55
```

**Comment by dipbazz** [comment]
Hey @BatuhanW, I have investigated the issue and it was cause by the the authProvider `checkError` method. Whenever I get any kind of error during mutation that would trigger a `checkError` method I guess. So when the error is triggered my error doesn't have `response` attribute. I have fixed it by checking if response exist in error as `error?.response?.status`.

**Comment by rdjanuar** [comment]
any update of this bug ?

**Comment by omeraplak** [comment]
Hey @dipbazz @rdjanuar,
We apologize for the delay, we were working intensively on Refine v4. Now you can use it this fix by upgrading your "@refinedev/core" dependency to the latest (@4.1.4) version. 

> If you haven't yet upgraded your project to Refine v4, please follow our migration guide document at https://refine.dev/docs/migration-guide/3x-to-4x/.

```ts
import { useCustom } from "@refinedev/core";
const {} = useCustom({
    method: "get",
    url: "https://api.fake-rest.refine.dev/posts",
    queryOptions: {
        queryKey: ["custom-key"],
    },
});

const queryClient = useQueryClient();
queryClient.invalidateQueries(["custom-key"]);
```

**Comment by rdjanuar** [comment]
Hi @omeraplak thanks for fixing this bug
