### ISSUE TITLE
[FEAT] Add example how to integrate Refine with Firebase Authentication

### ISSUE THREAD

**Issue by Mikilll94** [refinedev/refine#3684]
### Is your feature request related to a problem? Please describe.

It's not easy to figure out how to integrate Firebase Authentication with Refine app.

https://firebase.google.com/docs/auth/web/start?authuser=0

Especially I have no idea how to combine `AuthProvider` form Refine with authentication state observer from Firebase:

https://firebase.google.com/docs/auth/web/start?authuser=0#set_an_authentication_state_observer_and_get_user_data

```js
import { getAuth, onAuthStateChanged } from "firebase/auth";

const auth = getAuth();
onAuthStateChanged(auth, (user) => {
  if (user) {
    // User is signed in, see docs for a list of available properties
    // https://firebase.google.com/docs/reference/js/firebase.User
    const uid = user.uid;
    // ...
  } else {
    // User is signed out
    // ...
  }
});
```

This seems not compatible with `checkAuth` from Refine.

### Describe alternatives you've considered

Not using Refine.

### Describe the thing to improve

Add an example how to integrate Refine with Firebase Authentication.

**Comment by BatuhanW** [comment]
Hello @Mikilll94, we aren't officially supporting firebase, however @resulturan has this great package for integrating firebase:

https://github.com/resulturan/refine-firebase
