### ISSUE TITLE
[FEAT] Add custom error message in CheckError

### ISSUE THREAD

**Issue by mivvan** [refinedev/refine#3695]
### Is your feature request related to a problem? Please describe.

In AuthProvider:login we are able to pass custom error message in Promise.reject() to notify user.
I'd like to pass custom error message in AuthProvider:CheckError also

### Describe the thing to improve

example:
```
Checkerror: (error) => {
    if (error.response.status === 401 || error.response.status === 403) {
       return Promise.reject({redirectPath:false,message:error.response.message,description:error,response.data.detail})
    return Promise.resolve()
```

**Comment by BatuhanW** [comment]
Hello @mivvan

checkError method gets error. From here, you can use notification provider to show it to the user in this method.

https://refine.dev/docs/api-reference/core/providers/notification-provider/#built-in-notification-providers

**Comment by mivvan** [comment]
Yes, it get's error, but message format is predefined in data hooks and always looks like:
`Error (status code: ${err.statusCode})`

**Comment by BatuhanW** [comment]
Hello @mivvan

You can customize error format as seen here: https://refine.dev/docs/api-reference/core/providers/data-provider/#error-format

**Comment by BatuhanW** [comment]
Hello @mivvan closing the issue, feel free to re-open it if your issue persists.
