### ISSUE TITLE
[BUG] Sider - secondary color mixed with primary contrastText

### ISSUE THREAD

**Issue by Mikilll94** [refinedev/refine#3740]
### Describe the bug

When customizing `Sider` in MUI template I noticed that it uses `secondary.main` color. However for texts it uses `primary.contrastText` color.

You can check this in this file:
https://github.com/refinedev/refine/blob/HEAD/packages/mui/src/components/layout/sider/index.tsx

Just search for `secondary.main` and `primary.contrastText`.

IMO this is counter-intuitive. I just want to change sider texts color without affecting, i.e. primary buttons.

### Steps To Reproduce

1. Go to this file
https://github.com/refinedev/refine/blob/HEAD/packages/mui/src/components/layout/sider/index.tsx

2. Search for `secondary.main` and `primary.contrastText`

### Expected behavior

Sider should use `secondary.contrastText` color for texts instead of `primary.contrastText`.

**Comment by BatuhanW** [comment]
Hello @Mikilll94, thanks for the report!

We'll check this issue. In the meantime, feel free to create a PR.

**Comment by BatuhanW** [comment]
Hello @Mikilll94, we have a PR for this one, but since it's a breaking change, we'll release this change with v4.
