### ISSUE TITLE
[BUG] Access control - mistake in the docs

### ISSUE THREAD

**Issue by Mikilll94** [refinedev/refine#3742]
### Describe the bug

![Screenshot 2023-03-07 at 15 20 32](https://user-images.githubusercontent.com/17653648/223449391-41f616b7-9e2a-4ad0-853e-42062874d303.png)

As you can see there is a mistake in this banner because `@pankod/refine-antd` is displayed twice.

Link to the relevant docs page -> https://refine.dev/docs/advanced-tutorials/access-control/

### Steps To Reproduce

1. Just go to this page https://refine.dev/docs/advanced-tutorials/access-control/ and find the banner.

### Expected behavior

Mistake in the docs should be fixed.

**Comment by BatuhanW** [comment]
Hello @Mikilll94, I don't think this is an issue.

**Comment by Mikilll94** [comment]
@BatuhanW Could you read the content of this yellow? There is a clear typo.
