### ISSUE TITLE
[DOC] Access control - 404 after clicking a link

### ISSUE THREAD

**Issue by Mikilll94** [refinedev/refine#3743]
### Documentation issue

![Screenshot 2023-03-07 at 15 25 32](https://user-images.githubusercontent.com/17653648/223450818-4381b427-86b8-4047-b271-480f934bf222.png)

When clicking on "here" I got 404.

link -> https://refine.dev/docs/advanced-tutorials/access-control/

### Describe the thing to improve

I should not get 404.

**Comment by aliemir** [comment]
Hey @Mikilll94, sorry for the trouble! Do you want to create a PR for this? We'd love to see your contribution to refine! External links sometimes break without us noticing 😅

**Comment by adityakode** [comment]
@aliemir  can I solve this ?
Would love to contribute to the project !

**Comment by Mikilll94** [comment]
@adityakode Yes, feel free to do it. All links on this page are broken.

**Comment by adityakode** [comment]
@Mikilll94 made a PR #3747 
thanks for the encouragement!
