### ISSUE TITLE
[DOC] useDataGrid - mistake in the docs

### ISSUE THREAD

**Issue by Mikilll94** [refinedev/refine#3744]
### Documentation issue

https://refine.dev/docs/api-reference/mui/hooks/useDataGrid/#resource

![Screenshot 2023-03-07 at 15 54 52](https://user-images.githubusercontent.com/17653648/223458946-68747529-f1f3-4462-a1af-6b91ea97cd58.png)

There is a mistake in this place. Should be `useDataGrid` instead of `useTable` because this whole page is about `useDataGrid`.

### Describe the thing to improve

Typo should be fixed.

**Comment by aliemir** [comment]
Sorry for the issue @Mikilll94, that's overlooked 🤦 Do you want to create a PR for this? 🙏

**Comment by aliemir** [comment]
Just opened a PR to fix it. We'll merge it soon 🚀
