### ISSUE TITLE
[DOC] AuthPage - broken example

### ISSUE THREAD

**Issue by Mikilll94** [refinedev/refine#3749]
### Documentation issue

https://refine.dev/docs/api-reference/mui/components/mui-auth-page/#contentprops

This example is not working. As you can title is not changed to "Login".

![Screenshot 2023-03-07 at 16 42 27](https://user-images.githubusercontent.com/17653648/223472511-e6141427-48cc-41ca-a720-7327f24795ff.png)

### Describe the thing to improve

Example should work.

**Comment by aliemir** [comment]
Hey @Mikilll94, sorry for the issue. That's should not be in the example, `title` is only available for the `antd`'s `AuthPage` component. Let's have a look for our options here, It will be good to have the `title` property 😅 Let's update this example first, then we can think about making this work properly.

**Comment by Mikilll94** [comment]
@aliemir Is it going to be fixed? Currently it's a blocker for me because it seems that there is no way to customize swizzle MUI AuthPage component.

**Comment by aliemir** [comment]
@Mikilll94, this has two sides like I said above. Just opened a PR for a fix in documentation. I've updated the example code snippet with the correct props. I've also added the missing ability to change the title of the card to our backlog, we'll resolve this soon 🙏 For now, you can use `swizzle` command to customize the `@pankod/refine-mui`'s `AuthPage` 🚀
