### ISSUE TITLE
[DOC] Broken internal links in layout-wrapper / api reference

### ISSUE THREAD

**Issue by florent-andre** [refinedev/refine#3750]
### Documentation issue

* The links for detailled api-reference goes to 404 : 
* see links at the bottom: https://refine.dev/docs/api-reference/core/components/layout-wrapper/#properties

### Describe the thing to improve

* This links should be updated: https://github.com/refinedev/refine/blob/master/documentation/docs/api-reference/core/components/layout-wrapper.md?plain=1#L78

**Comment by adityakode** [comment]
Can I work on this ?

**Comment by adityakode** [comment]
I have made a PR.
I have put direct website links .
PS see if this approach works or else we can try another.

**Comment by aliemir** [comment]
Hey @florent-andre sorry for the issue and thanks for the explanation. 🙏 

@adityakode thank you for the contribution!! 🚀 We'll do a quick review on the PR 🤝

**Comment by florent-andre** [comment]
:runner: 
Well done !
