### ISSUE TITLE
[DOC] MarkdownField example is not showing any markdown

### ISSUE THREAD

**Issue by Mikilll94** [refinedev/refine#3761]
### Documentation issue

https://refine.dev/docs/api-reference/mui/components/fields/markdown/

![Screenshot 2023-03-08 at 14 36 40](https://user-images.githubusercontent.com/17653648/223727014-f33ac3ec-0768-4064-84a8-f8dce23a8954.png)

The code example for `MarkdownField` is not showing any markdown so it looks like it's not working.

### Describe the thing to improve

The code example for `MarkdownField` should show some markdown.

**Comment by BatuhanW** [comment]
Hello @Mikilll94, thanks for the issue as always 🔥 

This example is getting it's data from a shared data provider, if we change this to markdown, all other examples where we don't have markdown will also try to render MD.

We'll modify our example data provider and will have a different resource specially with markdown and render it here in the future.

**Comment by Mikilll94** [comment]
This issue still exists
