### ISSUE TITLE
[DOC] TextField example shows strange readonly input

### ISSUE THREAD

**Issue by Mikilll94** [refinedev/refine#3762]
### Documentation issue

https://refine.dev/docs/api-reference/mui/components/fields/text/

![Screenshot 2023-03-08 at 14 51 52](https://user-images.githubusercontent.com/17653648/223730413-99eaa38f-09f9-49f1-9a8e-462f06e6ea45.png)

`TextField` example looks like readonly input. When you click on it, it shows the cursor but you cannot enter anything. This looks strange and I don't think this is an intended behavior.

### Describe the thing to improve

`TextField` example should just display text without the readonly input.

**Comment by alicanerdurmaz** [comment]
Hi @Mikilll94, thanks for the issue.

[TextField](https://github.com/refinedev/refine/blob/next/packages/mui/src/components/fields/text/index.tsx) It uses Material UI [<Typography>](https://mui.com/material-ui/react-typography/#main-content) component. It means this behavior comes from MUI and we should not change MUI's intended behavior.

If you don't like it, you can swizzle to customize it or you can open an issue on MUI.

**Comment by Mikilll94** [comment]
@alicanerdurmaz Just click on this input. You will that it is looking strange. I assume that we want just a normal text cell like i.e. here https://refine.dev/docs/api-reference/mui/components/inferencer/#list

**Comment by alicanerdurmaz** [comment]
@Mikilll94 are you talking about weird borders? you're right, it looks ugly. we will look at this. Thank you 🙏 

![image](https://user-images.githubusercontent.com/23058882/223968641-5a80974b-6cb0-474f-9a77-ee93b79a7727.png)

**Comment by alicanerdurmaz** [comment]
> @alicanerdurmaz Just click on this input. You will that it is looking strange. I assume that we want just a normal text cell like i.e. here [refine.dev/docs/api-reference/mui/components/inferencer/#list](https://refine.dev/docs/api-reference/mui/components/inferencer/#list)

@Mikilll94 are you talking about weird borders? you're right, it looks ugly. we will look at this. Thank you 🙏 

![image](https://user-images.githubusercontent.com/23058882/223968641-5a80974b-6cb0-474f-9a77-ee93b79a7727.png)
