### ISSUE TITLE
[DOC] What is the difference between FileField and UrlField?

### ISSUE THREAD

**Issue by Mikilll94** [refinedev/refine#3815]
### Documentation issue

What is the difference between?
- `FileField` https://refine.dev/docs/api-reference/mui/components/fields/file/
- `UrlField` https://refine.dev/docs/api-reference/mui/components/fields/url/

Currently in the examples, it looks like both fields look and behave the exactly same.

Also IMO these example looks very artificial:

![image](https://user-images.githubusercontent.com/17653648/224538755-182cf08b-4c65-43c4-b984-2fbfbec632b5.png)

Who really wants to display the image url? I think it would be better just to display image.

### Describe the thing to improve

`FileField` and `UrlField` should not work and behave the same.

**Comment by omeraplak** [comment]
Hey @Mikilll94 ,
Unlike URLField, FileField takes 'title' parameter. Maybe in the future, we can merge the two components
