### ISSUE TITLE
[FEAT] export RouteProvider from refine-react-router-v6

### ISSUE THREAD

**Issue by Inoir** [refinedev/refine#3817]
### Is your feature request related to a problem? Please describe.

Id like to use only the RouteProvider, not the Router itself.
We have apps in microfronends and one hub. If you call the app from the hub, there is already an router defined. since you cant have 2 router in your project, this fails with refine currently.
Define the routes, without router, would fix this.

### Describe alternatives you've considered

None

### Describe the thing to improve

Export "RouteProvider" from refine-react-router-v6

**Comment by BatuhanW** [comment]
Hello @Inoir, we are releasing v4 very soon and with the new version, router will be way more flexible, please stay in touch!

**Comment by omeraplak** [comment]
Hey @Inoir ,
We've released refine v4. With refine v4, the routing API has completely changed. You can review the Migration Guide for more information https://refine.dev/docs/migration-guide/router-provider/#motivation-behind-the-changes
