### ISSUE TITLE
[BUG] useTable(React Table) is adding an eq condition when I use a gte filter

### ISSUE THREAD

**Issue by thiagotognoli** [refinedev/refine#3824]
### Describe the bug

useTable(React Table) is adding an eq condition when I use a gte filter

The useTable function from the react-table package is adding an eq condition when using a gte filter.

when i call:

```typescript
useTable({
   columns,
   refineCoreProps: {
      permanentFilter: [{
         field: "category.id",
         operator: "gte",
         value: 0,
      },],
   },
})
```

That way I can't use the useTable

Below is my jest to reproduce

### Steps To Reproduce

```typescript
import { renderHook, waitFor } from "@testing-library/react";
import { ColumnDef } from "@tanstack/react-table";

import { TestWrapper } from "../../test";
import { useTable } from "./index";

type Post = {
    id: number;
    title: string;
};

const columns: ColumnDef<Post>[] = [
    {
        id: "id",
        header: "ID",
        accessorKey: "id",
    },
    {
        id: "title",
        header: "Title",
        accessorKey: "title",
        meta: {
            filterOperator: "contains",
        },
    },
];

describe("useTable Hook", () => {
    it("It should work successfully with permanentFilter", async () => {
        const { result } = renderHook(
            () =>
                useTable({
                    columns,
                    refineCoreProps: {
                        permanentFilter: [
                            {
                                field: "category.id",
                                operator: "gte",
                                value: 0,
                            },
                        ],
                    },
                }),
            {
                wrapper: TestWrapper({}),
            },
        );

        await waitFor(() => {
            expect(
                !result.current.refineCore.tableQueryResult.isFetching,
            ).toBeTruthy();
        });

        const {
            refineCore: { filters: filtersCore },
        } = result.current;

        expect(filtersCore).toEqual([
            { field: "category.id", operator: "gte", value: 0 },
        ]);
    });
});
```

### Expected behavior

I would expect as a result the filter 
```typescript
[{ field: "category.id", operator: "gte", value: 0 }, ]
```
 but I am getting 
```typescript
[{ field: "category.id", operator: "gte", value: 0 } , { field: "category.id", operator: "eq", value: 0 }, ]
```

**Comment by BatuhanW** [comment]
Hello @thiagotognoli, thanks a lot for the great detailed issue! We'll check it and get back to you.

**Comment by salihozdemir** [comment]
Hi @thiagotognoli,

I want to let you know that the issue you encountered is not actually a bug. Instead, you can define the operator by using the `filterOperator` in the `meta` property when defining the column.

You can find an example of how to do this in the following link:

https://github.com/refinedev/refine/blob/master/examples/table-react-table-basic/src/pages/posts/list.tsx#L29

Although your PR looks good and works fine in tests, it seems like it's not working in the example app because the `@tanstack/table` filter state only includes `id` and `value`. Therefore, you cannot use `operator` or some other properties in the `@tanstack/table` state. You can refer to the [`ColumnFilter`](https://tanstack.com/table/v8/docs/api/features/filters#state) type in the documentation to learn more.

**Comment by salihozdemir** [comment]
> > Hi @thiagotognoli,
> > I want to let you know that the issue you encountered is not actually a bug. Instead, you can define the operator by using the `filterOperator` in the `meta` property when defining the column.
> > You can find an example of how to do this in the following link:
> > https://github.com/refinedev/refine/blob/master/examples/table-react-table-basic/src/pages/posts/list.tsx#L29
> > Although your PR looks good and works fine in tests, it seems like it's not working in the example app because the `@tanstack/table` filter state only includes `id` and `value`. Therefore, you cannot use `operator` or some other properties in the `@tanstack/table` state. You can refer to the [`ColumnFilter`](https://tanstack.com/table/v8/docs/api/features/filters#state) type in the documentation to learn more.
> 
> Hi @salihozdemir ,
> 
> Thanks for the feedback.
> 
> I understood your point of view, but I believe that the addition of the 'eq' operator is still a bug, if the objective is not to use the operator in the permanetFilter, it should be removed from the parameters. Although I don't see the need because my PR solves the problem and there are cases where only one operator doesn't solve the problem, for example if you want to filter a range with lte and gte.
> 
> The ColumnFilter really doesn't have the operator field, I did it with the intention of solving it, but I recognize that it is not the best practice. But this can be easily solved by creating an extra variable with the operator, if you are willing to accept this solution I can change the PR.
> 
> I await your return,
> 
> Thanks.

Of course you can use `permanentFilter` or `initialFilter` for filtering process. When you define `permanentFilter` or `initialFilter`, the `useTable` hook maps the **refine** filter state to `@tanstack/table` filter state. Conversely, when you define `@tanstack/table` filter state, the `useTable` hook maps the **refine** filter state to `@tanstack/table` filter state.

When the `useTable` hook maps the `@tanstack/table` filter state to the **refine** filter state, the `useTable` hook uses the `filterOperator` defined in the column definition. If you don't define the `filterOperator` in the column definition, the `useTable` hook uses the `eq` operator by default.

In your case a usage like below doesn't work?

```tsx
import { useTable } from "@refinedev/react-table";

import { ColumnDef, flexRender } from "@tanstack/react-table";

...

const columns = React.useMemo<ColumnDef[]>(
    () => [
        {
            id: "id",
            header: "ID",
            accessorKey: "id",
        },
        {
            id: "category.id",
            header: "Category",
            accessorKey: "category.id",
            meta: {
                filterOperator: "gte",
            },
        },
    ],
    [],
);

...

useTable({
    columns,
    refineCoreProps: {
        permanentFilter: [
            {
                field: "category.id",
                operator: "gte",
                value: 0,
            },
        ],
    },
}),


...


```

**Comment by salihozdemir** [comment]
Hey @thiagotognoli,

I reviewed again your changes with a fresh mind and I think it is good to go. When I first reviewed it, I was worried about the `filterColumn` type, but now I think it is fine. 

Just one thing, can you please add a changeset? You can do it by running `npx changeset` on the root of the project. You can read more about it [here](https://refine.dev/docs/contributing/#changeset).

**Comment by omeraplak** [comment]
Hey @thiagotognoli ,
Thank you very much for your contribution! If you reach me on Discord, we would like to give you the 'contributor' title.
