### ISSUE TITLE
[BUG] useList filter not working 

### ISSUE THREAD

**Issue by jkim1998** [refinedev/refine#3828]
### Describe the bug

Hello, 

I am trying to apply filters on useList data query from API but looks like filter is not working. 
I want the list of users with "admin" role. 
```
interface User {
  _id: string;
  name: string;
  role: string;
}

  const { data: Admin } = useList<User>({
    resource: "users",
    config: {
      hasPagination: false,
      filters: [
        {
          field: "role",
          operator: "eq",
          value: "admin",
        },
      ],
    },
  });

  const admin: User[] = Admin?.data ?? [];

console.log("admin:", admin);
```
and the result as the screenshot 

I was thinking that if I messed up somewhere, I shouldn't be getting any query results and since I am always receiving every data in the collection, filtering is not working. 

hasPagination and pagination are working fine but filters and sort are not.

I checked the documentation but still not sure what is wrong with my code. 
I tried creating a new react app and used the example code but it still doesn't work. 
https://refine.dev/docs/api-reference/core/hooks/data/useList/

Thank you in advance. 

### Steps To Reproduce

useList filters

### Expected behavior

not working 

### Screenshot

![filter](https://user-images.githubusercontent.com/101679287/224605492-b068e94e-39d9-4f81-85e7-5bc7d81c05ac.png)

### Desktop

-OS: windows 10
-browser: Chrome

**Comment by omeraplak** [comment]
Hey @jkim1998 👋 ,
It seems to be related to your DataProvider. Have you correctly configured the API configuration for filtering in your DataProvider? Please follow our DataProvider tutorial at https://refine.dev/docs/tutorial/understanding-dataprovider/index/.
