### ISSUE TITLE
[DOC] All code examples on MUI List view are broken

### ISSUE THREAD

**Issue by Mikilll94** [refinedev/refine#3846]
### Documentation issue

All code examples are broken on this page

https://refine.dev/docs/api-reference/mui/components/basic-views/list/

![image](https://user-images.githubusercontent.com/17653648/224833207-9736b9c2-89ea-4ea3-a515-8283f3c68ae1.png)

### Describe the thing to improve

Fix the code examples.

**Comment by yildirayunlu** [comment]
We are aware of this problem, it will be resolved after the release.
