### ISSUE TITLE
django provider

### ISSUE THREAD

**Issue by omeraplak** [refinedev/refine#389]

**Comment by bilicifatih** [comment]
My Refine app trying http://127.0.0.1:8000/api/tur?_end=10&_order=desc&_sort=id&_start=0& request to Dango Rest Api getting status code :301 error. But when i try to request from http://127.0.0.1:8000/api/tur/?_end=10&_order=desc&_sort=id&_start=0& manualy getting status code 200 and working properly in console. How can change to my call http://127.0.0.1:8000/api/tur? to http://127.0.0.1:8000/api/tur/?.

**Comment by omeraplak** [comment]
Hey @izgaradusmani 👋,
You can override getList function like this, https://refine.dev/docs/faq/#how-i-can-override-specific-function-of-data-providers
