### ISSUE TITLE
[BUG] contrastText on lightTheme same as darkTheme

### ISSUE THREAD

**Issue by YechiamTK** [refinedev/refine#3897]
### Describe the bug

I've noticed this when a user with white theme (oh boy) accessed my ReadyPage (swizzled from the default one).
The LightTheme values for `contrastText` are white - when I think they're suppose to be black (or some shade-of).
https://github.com/refinedev/refine/blob/next/packages/mui/src/theme/palette/lightPalette.ts

### Steps To Reproduce

Well you can probably see it in the default ReadyPage with White Theme

### Expected behavior

Should be shade of black.

**Comment by omeraplak** [comment]
Hey @YechiamTK ,
Thank you for contacting us! Would you like to open a PR that fixes this error?

**Comment by YechiamTK** [comment]
@omeraplak hi there :)
I have no problem doing so, but I don't know the exact shade you'd like to be the default one.

**Comment by YechiamTK** [comment]
@omeraplak OK so I'll just do it with #000, pretty standard.
However I actually never worked with github on an actual project (stash ftw 😄).
I would I go about creating a branch that's attached to this issue?

**Comment by omeraplak** [comment]
Hey @YechiamTK ,
Great! You can follow our contribution document at https://refine.dev/docs/contributing/

**Comment by YechiamTK** [comment]
Oh ok @omeraplak so just work on next directly. Np, will upload a PR in a few.

**Comment by YechiamTK** [comment]
@omeraplak opened PR; I couldn't manage to run changeset (seems like an open issue? https://github.com/changesets/changesets/issues/1055); but perhaps it's not needed for this small change?
