### ISSUE TITLE
[BUG]Authenticated component is not working in V3.50 core version

### ISSUE THREAD

**Issue by joanaavelar** [refinedev/refine#3898]
### Describe the bug

When wrapping a page component with Authenticated component, that page is never rendered. It seems that Authenticated component is in loop.

### Steps To Reproduce

1. Unzip **authenticated_sample.zip**
2. Open  **authenticated_sample** folder
3. Run yarn install
4. Run yarn start
5. Login with **admin** user and **dummy** password
6. See that posts page is not rendered

### Expected behavior

Authenticated component should validate if the user is authenticated or not and when it is, posts page should be shown. 

### Additional Context

Please consider the sample attached.

[authenticated_sample.zip](https://github.com/refinedev/refine/files/10992858/authenticated_sample.zip)

**Comment by BatuhanW** [comment]
Hello @joanaavelar, unfortunately, your project doesn't compile. It has issues not related to refine, and also you are using very old version. After fixing the project, please consider upgrading your project to v4. You can run codemod with a single command and it should be done.

https://refine.dev/docs/migration-guide/3x-to-4x/

**Comment by joanaavelar** [comment]
Hello. 
Sorry, the sample had some problems indeed. 
I've corrected them and attached it is a new working version.
I understand that this is an old version, but, for now, it is not possible to migrate to a newer one.
This Authenticated component seems to have issues. Could you take a look and guide me to a possible fix that I could implement in this version?

Thanks in advance,

Joana Avelar
[authentication_sample_v3.50.zip](https://github.com/refinedev/refine/files/10999257/authentication_sample_v3.50.zip)
