### ISSUE TITLE
[FEAT] Text Color In Footer

### ISSUE THREAD

**Issue by himanshu1221** [refinedev/refine#3914]
### Is your feature request related to a problem? Please describe.

Text color of the the footer is very very light it should be a bit darker so that it should be visible 

### Describe alternatives you've considered

It Should be a bit darker 

### Additional context

![Screenshot from 2023-03-17 22-27-56](https://user-images.githubusercontent.com/32031706/225970288-4e73dd97-29a4-4b13-a7ab-a13122095a1c.png)

### Describe the thing to improve

The content of the footer should be darker

**Comment by omeraplak** [comment]
Hey @himanshu1221  ,
Thank you for contacting us! Would you like to open a PR that fixes this issue?

**Comment by himanshu1221** [comment]
> Hey @himanshu1221 , Thank you for contacting us! Would you like to open a PR that fixes this issue?

Ill be happy to!
It would be great if you assign me the issue

**Comment by BatuhanW** [comment]
@himanshu1221, you are assigned! Looking forward to your PR 🙌🏼

**Comment by himanshu1221** [comment]
hey @omeraplak apologies for the delay I have made

I have made a PR for this issue it would be great if you review It

**Comment by omeraplak** [comment]
Thank you @himanshu1221 🎯
