### ISSUE TITLE
[BUG] Incorrect parameter after  light color mode check

### ISSUE THREAD

**Issue by aalvarado** [refinedev/refine#3917]
### Describe the bug

Introduced here:

https://github.com/refinedev/refine/pull/1952/files#diff-934258df31bbe37f67489ca0075d554d92488a0403bcb533a17f9677904c72faR30-R34

This function

```typescript
    const setColorMode = () => {
        if (mode === "light") {
            setMode("dark");
        } else {
            setMode("light");
        }
    };   
```

Seems incorrect

### Steps To Reproduce

- create app
- go to src/contexts/color-mode/index.tsx

### Expected behavior

light when it's light
dark when it's dark

**Comment by aliemir** [comment]
Hey @aalvarado, this is an unfortunate naming but I think what this function does is to toggle the color mode rather than setting it to a provided value. That's why it sets to `light` if the `mode` equals to `dark` and vice versa.

**Comment by aalvarado** [comment]
Oh I see, sorry for the confusion!
