### ISSUE TITLE
[FEAT] Redirect the user instead of showing 404 page

### ISSUE THREAD

**Issue by Mikilll94** [refinedev/refine#3923]
### Is your feature request related to a problem? Please describe.

![Screenshot 2023-03-20 at 09 49 48](https://user-images.githubusercontent.com/17653648/226290013-6d16d6fd-ac89-45ef-ae4a-3fbbe3f8946d.png)

Currently if `accessControlProvider` blocks access to the resource for a user, a 404 page is shown. Instead I would like to redirect the user to the first available resource.

Take a look at this example:

```
{
  name: "orders",
  list: MuiInferencer,
  edit: MuiInferencer,
  show: MuiInferencer,
  create: MuiInferencer,
  canDelete: true,
},
{
  name: "users",
  list: MuiInferencer,
  create: MuiInferencer,
  edit: MuiInferencer,
  canDelete: true,
},

```

```
accessControlProvider={{
    async can({ resource }) {
      const userResponse = await supabaseClient.auth.getUser();
      const user = userResponse.data.role;
      if (user.role === "user-manager") {
        return Promise.resolve({
          can: resource === "users",
        });
      }
    },
  }}
```

If the user has `user-manager` role, then after sign in, he will see a 404 page. Instead I would like him to redirect to `users` resource.

### Describe the thing to improve

Provide a mechanism to redirect a user to the first available resource when access control blocks access.

**Comment by BatuhanW** [comment]
Hello @Mikilll94, I guess that wouldn't be good UX. If a user doesn't have access to certain page, it should render error page, so user who doesn't have access *may* ask for access if they know which page they are on. Redirecting to another resource may look like a bug and user wouldn't know which page they don't have access to.

**Comment by Mikilll94** [comment]
Hello @BatuhanW ,
Current behavior is blocking me because I have a user who has access only to `users` resource so after logging in he should land on the `users` page. Instead he lands on the first defined resource which results in 404. How this can be fixed?

IMO would be nice to have something like this:

```
return Promise.resolve({
          can: resource === "users",
redirectIfAccessDenied: "users"
        });
```

or add a possibility to define dynamic start page

**Comment by BatuhanW** [comment]
Hello @Mikilll94,

I think it can be fixed from auth provider, WDYT? In the login method, you can define `redirectTo` path according the logged in user's permissions.

**Comment by Mikilll94** [comment]
![Screenshot 2023-03-20 at 11 52 41](https://user-images.githubusercontent.com/17653648/226319025-08cdf0e7-5ba6-4216-a4c0-968de257562d.png)

@BatuhanW 
I was trying to do this but unfortunately I have found an issue. Resolving a `Promise` with a url is not redirecting a user anywhere. I am still using Refine v3 and I don't want to migrate now because my app is almost completed.

**Comment by omeraplak** [comment]
Hey @Mikilll94 ,
Thank you for contacting us. Can you provide us with a CodeSandbox or StackBlitz so that we can reproduce the issue?
