### ISSUE TITLE
[BUG] Clicking logout adds invalid redirect url to the query string

### ISSUE THREAD

**Issue by Mikilll94** [refinedev/refine#3928]
### Describe the bug

When clicking `logout` button I noticed that some strange redirect url is added to the query string.

It looks like that:
```
http://localhost:3000/login?to=%2Flogin
```

It causes issues because when using `redirectTo` in `authProvider` `login` method, the `redirectTo` parameter is ignored. Instead it uses `/login` from url.

### Steps To Reproduce

1. Add custom redirection in `login` method of `authProvider`.
```
return {
  success: true,
  redirectTo: "/xxx",
};
```
2. Click "logout"
![Screenshot 2023-03-20 at 12 45 25](https://user-images.githubusercontent.com/17653648/226330106-2b34cd3d-2e37-4c5a-95b1-e7721116b41e.png)
3. Look at the url.
4. Login again.
5. You are NOT redirected to `/xxx`.

### Expected behavior

User should be redirected to `/xxx`.

**Comment by BatuhanW** [comment]
Hello @Mikilll94, if you are using `useLogout` hook, could you try removing `v3LegacyAuthProviderCompatible` if it exists?

**Comment by Mikilll94** [comment]
@BatuhanW I don't have any `v3LegacyAuthProviderCompatible` in my code. I removed them during migration.

**Comment by omeraplak** [comment]
Hey @Mikilll94 ,
Thank you for contacting us. Can you provide us with a CodeSandbox or StackBlitz so that we can reproduce the issue?
