### ISSUE TITLE
[BUG] csb___base.state is undefined

### ISSUE THREAD

**Issue by Mikilll94** [refinedev/refine#3935]
### Describe the bug

This CodeSandbox is not working

https://codesandbox.io/s/sharp-snowflake-yxc8q9?file=/src/App.tsx:916-948

App throws` TypeError: $csb___base.state is undefined`

### Steps To Reproduce

1. Open this CodeSandbox -> https://codesandbox.io/s/sharp-snowflake-yxc8q9?file=/src/App.tsx:916-948
2. You will see an error: ` TypeError: $csb___base.state is undefined`

### Expected behavior

App should work without error

### Desktop

macOS: 11.6.1
Firefox: 111.0
@refinedev/core: 4.3.0

**Comment by omeraplak** [comment]
Hey @Mikilll94 ,
Thank you for contacting us! I don't think this issue is related to refine. I haven't seen any problems in the examples in our documentation. https://refine.dev/docs/examples/real-world-refine-example/

**Comment by Mikilll94** [comment]
@omeraplak But this example from the docs is completely different. What I have in Codesandbox is a tiny refine app which should work or just give some indication what is wrong.

I have spent hours on this and I still cannot find the issue.

**Comment by Mikilll94** [comment]
Looks like this is some issue with Inferencer

**Comment by BatuhanW** [comment]
Hello @Mikilll94, I copy-pasted exact App.tsx and CategoryList.tsx into my local and started the server, it works as expected without any issues. Only difference I can see is that codesandbox has `@refinedev/mui` version 4.1.0 while I used `4.2.0`.
