### ISSUE TITLE
[BUG] Access control provider is not working

### ISSUE THREAD

**Issue by Mikilll94** [refinedev/refine#3937]
### Describe the bug

Access control provider is not working in Refine v4.

I am following the example in the docs -> https://refine.dev/docs/api-reference/core/providers/accessControl-provider/#usage

### Steps To Reproduce

1. Open this CodeSandbox https://codesandbox.io/s/sharp-snowflake-yxc8q9?file=/src/App.tsx
2. This code should block access to `categories` resource but it's not working

```
            accessControlProvider={{
              can: async ({ resource, action, params }) => {
                if (resource === "categories") {
                  return Promise.resolve({
                    can: false,
                    reason: "Unauthorized"
                  });
                }

                return { can: true };
              }
            }}
```

### Expected behavior

Access control provider should work. Categories page should not be accessible.

### Desktop

- macOS 11.6.1
- Chrome 111.0.5563.64
- @refinedev/core 4.3.0
- @refinedev/mui 4.1.0

**Comment by BatuhanW** [comment]
Hello @Mikilll94, nice catch! You are right, we should *always* return object, will update docs in a bit.

**Comment by Mikilll94** [comment]
@BatuhanW But even if I return an object, access control provider is not working

Take a look at updated Code Sanbox

https://codesandbox.io/s/sharp-snowflake-yxc8q9?file=/src/App.tsx

**Comment by BatuhanW** [comment]
Hello @Mikilll94, I'll update the docs to add references to respective documentation, but basically, you need to wrap your routes with <CanAccess> component.

https://refine.dev/docs/packages/documentation/routers/react-router-v6/#usage-with-access-control-providers

**Comment by Mikilll94** [comment]
@BatuhanW Thanks. This raises also a question. How can we use the default access denied page like in Refine v3?

**Comment by BatuhanW** [comment]
Hello @Mikilll94, you can import <ErrorPage> from your UI library and pass it as fallback to CanAccess component

**Comment by BatuhanW** [comment]
Hello @Mikilll94, by the way off-topic, if you reach me out from batuhan@refine.dev, we'd like to send you a gift code from refine store for your contributions. IF you are interested, shoot me an email, so I can give you the code.

**Comment by Mikilll94** [comment]
@BatuhanW There is no `ErrorPage` component in MUI.

**Comment by BatuhanW** [comment]
Hello @Mikilll94, sorry for the confusion, when I said MUI, I meant *our* MUI package.

`import { ErrorComponent } from "@refinedev/mui";`
