### ISSUE TITLE
[FEAT] Access control provider - bad performance

### ISSUE THREAD

**Issue by Mikilll94** [refinedev/refine#3946]
### Is your feature request related to a problem? Please describe.

I have noticed that `can` method from access control provider is executed for every row. This can lead to terrible performance when i.e. you need to make an http call to check permissions and have about 1000 rows. This will result in 1000 http calls.

Steps To Reproduce

1. Open this CodeSandbox.
https://codesandbox.io/s/sharp-snowflake-yxc8q9?file=/src/App.tsx
2. Log in
3. Look at the console. You will see that ACCESS CONTROL PROVIDER is printed 53 times.

### Describe the thing to improve

`can` method from access control provider should be executed only once.
Screenshot

**Comment by Mikilll94** [comment]
@BatuhanW
Sometimes the server does not support server-side pagination. In this case I fetch 1000 records from the server and handle pagination client-side. In this case 1000 http requests are made.

**Comment by BatuhanW** [comment]
@KOCNS1, AFAIK @Mikilll94 makes a single query which returns 1000 records, next 1000 requests are made by refine access control provider for each record.

**Comment by BatuhanW** [comment]
> @BatuhanW Sometimes the server does not support server-side pagination. In this case I fetch 1000 records from the server and handle pagination client-side. In this case 1000 http requests are made.

I see, if you have some solution, API Design in mind, please share with us! We are happy to discuss and implement it.
