### ISSUE TITLE
[DOC] Algolia Search is broken on old 3.x.x.x docs version

### ISSUE THREAD

**Issue by MetaMmodern** [refinedev/refine#3952]
### Documentation issue

When I switch to old version and go to search, the search bar not giving me any results:
<img width="1532" alt="image" src="https://user-images.githubusercontent.com/42899786/226898952-a647994b-73d5-4841-aa6c-a84a0ce78721.png">

### Describe the thing to improve

-

### Describe the solution (optional)

-

**Comment by BatuhanW** [comment]
Hello @MetaMmodern, thanks for the report, we'll check it soon!

**Comment by BatuhanW** [comment]
Hello @MetaMmodern, it should be fixed now.
