### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by vinhhypc** [refinedev/refine#3958]
### Describe the bug

I got : Cannot read properties of undefined (reading 'slice') 

### Steps To Reproduce

i practise with https://api.fake-rest.refine.dev. I create a resources={[
              {
                name: "posts",
                list: PostList,
                show: PostShow,
                create: PostCreate,
                edit: PostEdit,
              }]} with AntdInferencer. It can get data sometimes , but sometime it get error like this when i change pagination.

### Expected behavior

solve  error

### Screenshot

![Uploading error1.png…]()
![Uploading error2.png…]()

**Comment by omeraplak** [comment]
Hey @vinhhypc ,
I tested it but couldn't reproduce the issue. Could you let me know if the problem persists?
