### ISSUE TITLE
useCustom missing 3rd generic type

### ISSUE THREAD

**Issue by rdjanuar** [refinedev/refine#3960]
my use case is to overrides  data from api via select options(queryOptions) but i dont know how to adding custom type in useCustom to overrides existing type. according to tkdodo blog (https://tkdodo.eu/blog/react-query-and-type-script) the way to overrides generic type TQueryFnData is adding new type in 3rd generic type called TData = TQueryFnData in useQuery. how can i do to overrides TData from useCustom ? sorry for my bad english

**Comment by rdjanuar** [comment]
any update ?

**Comment by bombillazo** [comment]
Updates on this issue?

**Comment by BatuhanW** [comment]
Hello @bombillazo, we have an open PR for this one, we'll be releasing it soon! Stay tuned.
