### ISSUE TITLE
[FEAT] Modify a request in Create and Edit views

### ISSUE THREAD

**Issue by Mikilll94** [refinedev/refine#3979]
### Is your feature request related to a problem? Please describe.

https://refine.dev/docs/api-reference/mui/components/basic-views/create

Currently it seems like there is no way to modify a request made by `Create` and `Edit` components. In my case I need to add one additional field to the request json.

### Describe the thing to improve

Add a possibility to modify a request json made by `Create` and `Edit` components.

**Comment by omeraplak** [comment]
Hey @Mikilll94 ,
As stated in the documents, Basic View does not contain any logic but adds extra functionalities like action buttons and giving titles to the page.

**Comment by Mikilll94** [comment]
@omeraplak But when you click "Save" button, it sends a request to the API. How can I customize this request without going to data provider? (I am using Supabase data provider so I cannot modify it).

**Comment by omeraplak** [comment]
The structure that provides this is useForm. Please refer to the FAQ section in the documentation of the form library you are using. For example: [rew](https://refine.dev/docs/api-reference/antd/hooks/form/useForm/#how-can-i-change-the-form-data-before-submitting-it-to-the-api)

**Comment by Mikilll94** [comment]
@omeraplak But this is for AntD. I need to do this for MUI. I don't any documentation for doing this in MUI.

**Comment by omeraplak** [comment]
You're probably using "react-hook-form" with MUI. You can find its documentation here: https://refine.dev/docs/packages/documentation/react-hook-form/useForm/#how-can-i-change-the-form-data-before-submitting-it-to-the-api

```tsx
  const {
    saveButtonProps,
    handleSubmit,
    register,
    control,
    formState: { errors },
    refineCore: { onFinish }
  } = useForm();

  const onFinishHandler = (data: FieldValues) => {
    onFinish({
      ...data,
      test: 1
    });
  };

  return (
    <Create
      saveButtonProps={{
        ...saveButtonProps,
        onClick: (e: any) => {
          handleSubmit(onFinishHandler, () => false)(e);
        }
      }}
    >
```

https://codesandbox.io/s/nice-rgb-ol5uc6?file=/src/pages/posts/create.tsx
