### ISSUE TITLE
Hasura ID options doesn't contain `String`

### ISSUE THREAD

**Issue by mayurdhurpate** [refinedev/refine#3981]
https://github.com/refinedev/refine/blob/1a6c1e8a7754b5b6bb9567f83bc93ac9ef1f7c73/packages/hasura/src/dataProvider/index.ts#L155

We had created a Postgres table with text primary key, and the Qraphql query expects the same in ID type. But, ID customization only offers `Int` and `uuid` as 2 options, leading to query throwing the error. I think we should add all the types possible as an ID field here.

**Comment by BatuhanW** [comment]
Hello @mayurdhurpate, thanks for the report! Do you want to create a PR for this one?

**Comment by mayurdhurpate** [comment]
I'm actually a beginner to GraphQl/Hasura framework, and I might not know all the data types supported for ID Type. Would be better if someone more experienced take it up. Currently, I solved it by silencing linting errors with `any` and passing `idType`as `String`.
