### ISSUE TITLE
[FEAT] Display a notification from authProvider

### ISSUE THREAD

**Issue by Mikilll94** [refinedev/refine#3983]
### Is your feature request related to a problem? Please describe.

Forgot password page which is shown in the docs has bad UX because after the successful submit there is completely no feedback to the user.

https://refine.dev/docs/tutorial/understanding-authprovider/headless/auth-pages/#forgot-password-page

Instead a success toast message should shown to the user. Unfortunately according to the docs notification provider can be only accessed from `useNotification` hook -> https://refine.dev/docs/api-reference/core/providers/notification-provider

In my case I need to trigger a notification from auth provider.

### Describe the thing to improve

Add a possibility to trigger a notification from auth provider.

**Comment by omeraplak** [comment]
Hey @Mikilll94 ,
Can you review this topic (https://discord.com/channels/837692625737613362/1088507646388215979/1088507646388215979)? It's a technical limitation caused by MUI not providing a native notification system. Alternatively, you can choose to use the methods mentioned in the topic.
