### ISSUE TITLE
[FEAT] Customize subtitle in notification

### ISSUE THREAD

**Issue by Mikilll94** [refinedev/refine#3984]
### Is your feature request related to a problem? Please describe.

Currently I am customizing error notification from `authProvider`

```js
const authProvider: AuthBindings = {
  login: async ({ email, password }) => {
    try {
      const { data, error } = await supabaseClient.auth.signInWithPassword({
        email,
        password,
      });

      if (error) {
        return {
          success: false,
          error: new Error("Nieprawidłowy email lub hasło"),
        };
      }
}
```

which results in this

<img width="322" alt="Screenshot 2023-03-27 at 11 39 46" src="https://user-images.githubusercontent.com/17653648/227904243-2815048d-594d-4b3f-baec-13578b5dff56.png">

Unfortunately I don't see a way to change `Error` subtitle in the notification. This "Error" text is also not present in translations. How can I customize it?

### Describe the thing to improve

Customize subtitle text in error notifications triggered from auth provider.

**Comment by MetaMmodern** [comment]
Hi, @Mikilll94 , check this thread https://discord.com/channels/837692625737613362/1088080397314838679

**Comment by Mikilll94** [comment]
@MetaMmodern

<img width="660" alt="Screenshot 2023-03-28 at 16 22 09" src="https://user-images.githubusercontent.com/17653648/228269218-d0cd90e8-3bf3-448d-a4d6-c6169d4c6069.png">

When using `@refinedev/react-hook-form` there are no `successNotification` and `errorNotification` properties.

```
Object literal may only specify known properties, and 'successNotification' does not exist in type 'UseFormProps<BaseRecord, HttpError, FieldValues, {}>'.
```

**Comment by omeraplak** [comment]
It seems that the Error type in useLogin is incorrect. It should be a type with 'name' and 'message' fields. @BatuhanW 

https://github.com/refinedev/refine/blob/next/packages/core/src/hooks/auth/useLogin/index.ts#L210

**Comment by Mikilll94** [comment]
@MetaMmodern
Thx. That's working great.

@omeraplak 
Will this be fixed? Currently it's not possible to change the subtitle or the error snackbar.

**Comment by BatuhanW** [comment]
Hello @Mikilll94, we'll work on this issue soon. I can give you a suggestion in the meantine. If you want to modify subtitle, you can create a new error class extending from Error, or you can just return object with `name` and `message` fields, where `name` will be title and `message` will be subtitle.

```
class MyError < Error
end

new MyError("Message")

```

**Comment by salihozdemir** [comment]
Hey @Mikilll94,

Now you can return the `error` like below. One of prop is notification subtitles depending on your UI framework.

```ts
const authProvider: AuthBindings = {
  login: async ({ email, password }) => {
    try {
      // ...

      if (error) {
        return {
          success: false,
          error: {
              message: "Nieprawidłowy email lub hasło",
              name: "Foo"
          },
        };
      }
}
```
