### ISSUE TITLE
[FEAT] Single place to handle all notifications

### ISSUE THREAD

**Issue by MetaMmodern** [refinedev/refine#4006]
### Is your feature request related to a problem? Please describe.

It might be useful to have a single place to configure all different notification messages for different resources, cause they might be similar(Successfully created resource_a by name name_a, sucessflully edited the same resource, etc.). Duplicating them and even creating reusable functions is not helpful. 

For errors you did a great thing: 2 options, either edit in DataProvider or reject in axios.interceptors. I'd like to see a similar thing for successful notifications as well.

### Describe the thing to improve

Notification controller/center or smth like that.(Not notification provider, it's a diferent thing and it does it's job)

**Comment by omeraplak** [comment]
Hey @MetaMmodern ,
Thank you for contacting us. Isn't NotificationProvider exactly what you are looking for? If not, why?

**Comment by MetaMmodern** [comment]
@omeraplak hi, no, because notifications provider is about what notification engine we use and how the toasts look like
I don't have any issue with that. My issue is with the values, provided into notification provider when notification happens.
Even if I change the provider, the values that are sent by refine core will be the same.

**Comment by facucalle92** [comment]
Hello i have a question related to this.

I want to translate error.message when and error ocurr.

Why?

Because my back-end send me an error message in english and i want to translate this error to multiple languages.

for example: What is the best way to translate the error.message when a request fail?

**Comment by yildirayunlu** [comment]
> Hello i have a question related to this.
> 
> I want to translate error.message when and error ocurr.
> 
> Why?
> 
> Because my back-end send me an error message in english and i want to translate this error to multiple languages.
> 
> for example: What is the best way to translate the error.message when a request fail?

Hey @facucalle92 

The best way to do this is to use [i18n](https://refine.dev/docs/api-reference/core/providers/i18n-provider/). Added translation files have a section like the one below.

```
// public/locales/en/common.json
// ...
"notifications": {
    "success": "Successful",
    "error": "Error (status code: {{statusCode}})",
    "undoable": "You have {{seconds}} seconds to undo",
    "createSuccess": "Successfully created {{resource}}",
    "createError": "There was an error creating {{resource}} (status code: {{statusCode}})",
    "deleteSuccess": "Successfully deleted {{resource}}",
    "deleteError": "Error when deleting {{resource}} (status code: {{statusCode}})",
    "editSuccess": "Successfully edited {{resource}}",
    "editError": "Error when editing {{resource}} (status code: {{statusCode}})",
    "importProgress": "Importing: {{processed}}/{{total}}"
},
// ...
```

**Comment by MetaMmodern** [comment]
not_stale

**Comment by MetaMmodern** [comment]
not stale
