### ISSUE TITLE
Unable to access environment variables set in .env or .env.local files

### ISSUE THREAD

**Issue by ausshadu** [refinedev/refine#4039]
### Describe the bug

I have declared couple of variables in `.env` file as show below

`API_KEY=my_awesome_api_key`

And referring to the same value via `process.env.API_KEY` but the value turns out to be **null**

### Steps To Reproduce

1. Initialize a new project
2. Create a `.env` or `.env.local` file
3. Add some variables. Ex. 
FOO=bar

4. Reference the same via process.env.FOO
5. Value returns null

### Expected behavior

The environment value should return the expected value.

### Desktop

- OS: macOS Monterey 12.6
- Browser: Chrome version 111.0.5563.146
- DataProvider: REST dataProvider

**Comment by rainerregan** [comment]
Have you installed dotenv package?

https://www.npmjs.com/package/dotenv

**Comment by ausshadu** [comment]
> Have you installed dotenv package?
> 
> https://www.npmjs.com/package/dotenv

I had not installed assuming the refine have installed automatically. But, I did install it now explicitly. 
"dotenv": "^16.0.3",

Results are the same.

**Comment by rainerregan** [comment]
Make sure to configure dotenv before everything else
```javascript
import * as dotenv from 'dotenv' // see https://github.com/motdotla/dotenv#how-do-i-use-dotenv-with-import
dotenv.config()
import express from 'express'
```

Source: https://www.npmjs.com/package/dotenv

**Comment by ausshadu** [comment]
> Make sure to configure dotenv before everything else
> 
> ```js
> import * as dotenv from 'dotenv' // see https://github.com/motdotla/dotenv#how-do-i-use-dotenv-with-import
> dotenv.config()
> import express from 'express'
> ```
> 
> Source: https://www.npmjs.com/package/dotenv

It is not a server (express) application. I am running refine's CRA React Client app with REST data provider.

**Comment by omeraplak** [comment]
Hey, this question is not directly related to Refine. Please follow this document of CRA at https://create-react-app.dev/docs/adding-custom-environment-variables/
