### ISSUE TITLE
[FEAT] Create a non-resource page which will be visible in the side panel

### ISSUE THREAD

**Issue by Mikilll94** [refinedev/refine#4051]
### Is your feature request related to a problem? Please describe.

Right now I don't see anything in the docs how to add a non-resource page which will be visible in the side panel.

### Describe the thing to improve

Add a possibility to create a non-resource page which will be visible in the side panel.

**Comment by salihozdemir** [comment]
Hey @mil,

Hey @Mikilll94,

For internal links, easiest way is to create a dummy resource and add it to the `resources` prop of the `<Refine>` component. This will add a navigation link to the sidebar.

```tsx
import { Refine } from "@refinedev/core";
<Refine
    ...
    resources={[
        {
            name: "dummy-resource",
            list: "/internal-link",
            meta: {
                label: "Navigation Link",
                icon: <span>👋</span>,
            },
        },
    ]}
/>;
```

For external links, you can use the `render` prop of the `<Sider>` component. This will allow you to render any custom component.

```tsx
import { Layout, Sider } from "@refinedev/antd";
const CustomSider = () => {
  return (
    <Sider
      render={({ items, logout }) => {
        return (
          <>
            <a href="https://refine.dev/">👋 Navigation Link</a>
            {items}
            {logout}
          </>
        );
      }}
    />
  );
};
const CustomLayout = () => {
  return <Layout Sider={CustomSider}>...</Layout>;
};
```

Additionally, you can use **swizzle** command to copy the default `Sider` component to your project. This will allow you to customize the sidebar as you want.

[Refer to the swizzle documentation for more information.](https://refine.dev/docs/packages/documentation/cli/#swizzle)

**Comment by Kkkassini** [comment]
How to hide items from the sidebar that appear in resources?
