### ISSUE TITLE
[BUG] Installation broken out of the box (headless)

### ISSUE THREAD

**Issue by PerryRylance** [refinedev/refine#4052]
### Describe the bug

Hi folks

Easy solution here, simply get rid of the following in `App.tsx`

I'm trying to bolt Refine onto an existing Laravel project which we have our own UI framework setup for, I'm seeing this after copying the contents of my Refine project into the Laravel project and merging `package.json` and `.gitignore`.

```
import {
  BlogPostList,
  BlogPostCreate,
  BlogPostEdit,
  BlogPostShow,
} from "pages/blog-posts";
import {
  CategoryList,
  CategoryCreate,
  CategoryEdit,
  CategoryShow,
} from "pages/categories";
```

### Steps To Reproduce

- Run setup for headless
- Run `npm run dev`

### Expected behavior

- Builds out of the box

**Comment by yildirayunlu** [comment]
Hey @PerryRylance 

I don't think this is a bug. I could not understand what you mean. Can you elaborate more?

**Comment by PerryRylance** [comment]
Hi @yildirayunlu 

If you install Refine as headless and try to run it, then the following imports will fail

```
import {
  BlogPostList,
  BlogPostCreate,
  BlogPostEdit,
  BlogPostShow,
} from "pages/blog-posts";
import {
  CategoryList,
  CategoryCreate,
  CategoryEdit,
  CategoryShow,
} from "pages/categories";
```

These need to be deleted in order for the headless installation to build.

In other words, the installation is broken, and this has to be repaired in order to build and run it for the first time.

**Comment by yildirayunlu** [comment]
We fixed this problem. Thank you for the feedback 🙏🏼
