### ISSUE TITLE
[FEAT] Inferring from empty resources

### ISSUE THREAD

**Issue by PerryRylance** [refinedev/refine#4053]
### Is your feature request related to a problem? Please describe.

Hi folks

As far as I can tell, the inferencer cannot work without at least one record being present in the tables.

Is there any way at all to indicate to the server that the resource is being probed, eg have the inferencer set a header to let the server know that it's being probed and to send a temporary example resource if none are available at the requested URI?

I'd like to use this library in a project where end users will potentially delete all of a particular resource. I'd like them to still be able to add items when this happens.

Thank you

### Describe the thing to improve

Inferencing without any resources present

**Comment by yildirayunlu** [comment]
Hey @PerryRylance 

First of all, `Inferencer` is not ready to use in production yet.

As you wrote, there must be at least one record for the `Inferencer` to work. This is required for work. Maybe you can show another screen when there is no data.
