### ISSUE TITLE
[FEAT]I want refinedev can support trpc!

### ISSUE THREAD

**Issue by putao520** [refinedev/refine#4054]
### Is your feature request related to a problem? Please describe.

I want refinedev can support trpc!

### Describe the thing to improve

I want refinedev can support trpc!

**Comment by omeraplak** [comment]
Hello, thank you for contacting us. There is already a discussion thread (https://github.com/refinedev/refine/discussions/3470) available for gRPC. Please let's continue the conversation there. Thank you for your understanding.

**Comment by putao520** [comment]
Hello, trpc and grpc are not the same thing, 

this trpc's website https://github.com/trpc/trpc

**Comment by Oelyhasina** [comment]
is this request forthcoming? refine doesn't support trpc or can we customize a dataprovider?
