### ISSUE TITLE
[BUG] Supabase - sort items by id (primary key) if no sorters are specified

### ISSUE THREAD

**Issue by Mikilll94** [refinedev/refine#4055]
### Describe the bug

Currently when using Refine with Supabase examples, items are returned in non-deterministic order because they are not sorted by id (primary key). I know that I can set sorters manually but in MUI I can have only one sorter at the time so if the user removes sorters, items are displayed in non-deterministic order.

### Steps To Reproduce

1. Go to this example
https://codesandbox.io/s/github/refinedev/refine/tree/master/examples/data-provider-supabase?from-embed=&file=/src/App.tsx
2. Remove sorting from all the columns
3. As you can see, items are displayed in non-determnistic order.

### Expected behavior

If no sorters are specified, items should be sorted by id (primary key).

**Comment by yildirayunlu** [comment]
Thank you for the feedback 🙏🏼  We'll check and get back to you.

**Comment by Mikilll94** [comment]
@yildirayunlu 
`sorter.permanent` is not going to work for me because in MUI you can have only one sorter in free version.

So if I set a permanent sorter on one column, user cannot sort by other column.

**Comment by yildirayunlu** [comment]
@Mikilll94 It can handle this situation by overriding the `dataProvider` methods. You can use [`getList`](https://github.com/refinedev/refine/blob/next/packages/supabase/src/index.ts#L133) method from icon source codes. There is a [document](https://refine.dev/docs/faq/#how-i-can-override-specific-function-of-data-providers) about it.
