### ISSUE TITLE
[FEAT] Global MUI translations

### ISSUE THREAD

**Issue by Mikilll94** [refinedev/refine#4057]
### Is your feature request related to a problem? Please describe.

Right now,  I don't see a way how we can change the translation of MUI components according to this page:
https://mui.com/material-ui/guides/localization/#locale-text

Refine internally uses `createTheme` function and does not expose it so we cannot override it.

### Describe the thing to improve

Add a possibility to change translations of MUI components.

**Comment by salihozdemir** [comment]
Hey @Mikilll94,

We will look into it in the next few days. For now, can you try to spread the `LightTheme` or `DarkTheme` objects in `createTheme` function? It should work, but I'm not sure if it will work as expected.

```tsx
import { createTheme } from "@refine-dev/mui";
import { zhCN } from "@mui/material/locale";

const theme = createTheme(
  { ...LightTheme },
  zhCN
);
```

**Comment by salihozdemir** [comment]
> Hey @Mikilll94,
> 
> We will look into it in the next few days. For now, can you try to spread the `LightTheme` or `DarkTheme` objects in `createTheme` function? It should work, but I'm not sure if it will work as expected.
> 
> ```tsx
> import { LightTheme } from "@refine-dev/mui";
> import { zhCN } from "@mui/material/locale";
> 
> const theme = createTheme(
>   { ...LightTheme },
>   zhCN
> );
> ```

I tried it and it works as expected:

<img width="444" alt="image" src="https://user-images.githubusercontent.com/41580619/229817724-b30b1f9d-284b-4b04-abc9-88aaaafb077c.png">
