### ISSUE TITLE
[DOC] Show Code / Give Feedback Component is hard to remove and find

### ISSUE THREAD

**Issue by brandoncamerer** [refinedev/refine#4060]
### Documentation issue

[DOC] Show Code / Give Feedback Component is hard to remove and find....

There are now 2 recent posts on Discord about this, I have searched the documentation, used the bot and asked a user t no avail. 

### Describe the thing to improve

Document how to remove the Show Code and Give Feedback components

**Comment by omeraplak** [comment]
Hey @brandoncamerer 
You cannot hide these buttons because 'Inferencer' is only a development-only feature. Please visit the Inferencer documentation (https://refine.dev/docs/packages/documentation/inferencer/) for more detailed information.
