### ISSUE TITLE
[DOC] Add to the documentation that you cannot remove the "Give Feedback" / "Show Code" Inferencer feature.

### ISSUE THREAD

**Issue by brandoncamerer** [refinedev/refine#4061]
### Documentation issue

[DOC] Add to the documentation that you cannot remove the "Give Feedback" / "Show Code" Inferencer feature. Saving users time having to search through discord to find the answer. 

### Describe the thing to improve

[DOC] Add to the documentation that you cannot remove the "Give Feedback" / "Show Code" Inferencer feature. Saving users time having to search through discord to find the answer.

**Comment by ArslanYM** [comment]
Can i work on this?

**Comment by ArslanYM** [comment]
@omeraplak Can you assist me on how to get started with this? Where exactly should I position the documentation and what contents it should have?

**Comment by brandoncamerer** [comment]
@ArslanYM @omeraplak - I would suggest putting it here! https://refine.dev/docs/

Would save people time who are looking for a fully editable UI!

<img width="792" alt="image" src="https://user-images.githubusercontent.com/50874245/230445327-a1ce715f-cb5f-4331-8f56-8a58983b4a91.png">

**Comment by omeraplak** [comment]
Good news, we will soon add the ability to hide these buttons. Therefore, I am closing the issue. Stay tuned 🪄
