### ISSUE TITLE
[BUG] Yellow theme is not working

### ISSUE THREAD

**Issue by Mikilll94** [refinedev/refine#4066]
### Describe the bug

Yellow theme is not working

I have set `<ThemeProvider theme={RefineThemes.Yellow}>` but there is no yellow color on the page.

![Screenshot 2023-04-03 at 13 47 03](https://user-images.githubusercontent.com/17653648/229500337-f1734397-9b0c-4a2f-8c61-3b38353154a6.png)

### Steps To Reproduce

1. Download and run this repro project:
[dummy-resource.zip](https://github.com/refinedev/refine/files/11137891/dummy-resource.zip)

2. You will see that the theme is not yellow.

### Expected behavior

Theme should be yellow

### Desktop

- macOS 11.6.1
- Chrome 111.0.5563.146

**Comment by DoguhanOzgurAkca** [comment]
I think this is only about hexcodes of the colours, which are :
main: #FFA000", light: "#ffb333", dark: "#b27000",
replacing them with colours like 
main: "#ffd900", light: "#ffc633", dark: "#efac00",
Might solve the issue

**Comment by alicanerdurmaz** [comment]
Hi @Mikilll94, can you update this components please ?

```diff
	import {
-  		Layout,
+		ThemedLayout
	} from "@refinedev/mui";
```

```diff
    <Route
                element={
-                  <Layout>
+				   <ThemedLayout>
                     <Outlet />
-                  </Layout>
+				   </ThemedLayout>
                }
	>
```

**Comment by Mikilll94** [comment]
@omeraplak @alicanerdurmaz 
Thx.`ThemedLayout` is working but still `RefineThemes.Yellow` does not contain any yellow. It is barely distinguishible from from `RefineThemes.Orange`.

![Screenshot 2023-04-03 at 14 37 48](https://user-images.githubusercontent.com/17653648/229511626-f59fa58b-ec11-40b4-900f-6af5d26b4f0f.png)

IMO yellow theme should contain some yellow color.
