### ISSUE TITLE
[DOC] Search is not working on the home page

### ISSUE THREAD

**Issue by Mikilll94** [refinedev/refine#4070]
### Documentation issue

1. Go to this page -> https://refine.dev/
2. Search for i.e. Supabase 
3. No results are founds
4. Now go here -> https://refine.dev/docs/
5. Search again for Supabase
6. Now you can see the results

### Describe the thing to improve

Search should also work on the home page

**Comment by Danish-Belal** [comment]
https://refine.dev/  Search bar is working on this page also.  Kindly review from your side also.

**Comment by Mikilll94** [comment]
Hm... it's working now. Strange.
