### ISSUE TITLE
[BUG] RefineThemes and ThemedLayout not exported for a CRA project with Mantine UI

### ISSUE THREAD

**Issue by ioannisth** [refinedev/refine#4073]
### Describe the bug

Creating a new project, with Create React App and Mantine UI. When the boilerplate is added ThemedLayout and RefineThemes are not able to be imported gtom @refinedev/mantine

### Steps To Reproduce

here are my choices
$ pnpm create refine-app@latest
.../share/pnpm/store/v3/tmp/dlx-660749   | +211 +++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /home/myhomefolder/.local/share/pnpm/store/v3
  Virtual store is at:             ../.local/share/pnpm/store/v3/tmp/dlx-660749/node_modules/.pnpm
.../share/pnpm/store/v3/tmp/dlx-660749   | Progress: resolved 211, reused 211, downloaded 0, added 211, done

✔ Downloaded remote source successfully.
✔ Choose a project template · refine-react
✔ What would you like to name your project?: · my-admin
✔ Choose your backend service to connect: · data-provider-custom-json-rest
✔ Do you want to use a UI Framework?: · mantine
✔ Do you want to add example pages?: · inferencer
✔ Do you need any Authentication logic?: · auth-provider-custom
✔ Do you need i18n (Internationalization) support?: · no
✔ Choose a package manager: · **pnpm**
✔ Would you mind sending us your choices so that we can improve superplate? · no

### Expected behavior

when doing pnpm dev, I should see the sample website, instead I get a message about missing exports

**Comment by alicanerdurmaz** [comment]
@ioannisth Hi,

This is a cache problem. We will release the fix today for `pnpm`.  
Meanwhile, you can use `npm create refine-app@latest` to create a project and after that, you can select `pnpm` and continue to use `pnpm`

**Comment by alicanerdurmaz** [comment]
@ioannisth we released the fix. can you try again?

**Comment by ioannisth** [comment]
@alicanerdurmaz  looks good!
