### ISSUE TITLE
[BUG] syncWithLocation sort not working properly

### ISSUE THREAD

**Issue by DeveloperTheExplorer** [refinedev/refine#4097]
### Describe the bug

The built-in `syncWithLocation` feature does not work correctly with the sort feature as it does not load onto the tables. It gets saved to the URL, but when the URL is loaded, the sort does not affect the table.

### Steps To Reproduce

1. Create a Refine Repo
2. Create a list/table with `useList` or `useDataGrid`
3. Enable `syncWithLocation` in the `<Refine ... options={{ syncWithLocation: true }}  />`
4. Go on a view with a table, and play around with the sort (and perhaps filters & pagination)
5. Notice how they do get saved properly onto the URL search params.
6. Now copy and paste the URL containing a sort parameter onto a new tab
7. Upon loading in new tab, notice how the sort parameter is deleted from the URL and the sort is not used in the table.

### Expected behavior

The expected behaviour is that the sort parameters defined in the URL search params, properly load onto the table/list.

### Before: As you can see the sort is set here and the URL search params reflect that
![before](https://user-images.githubusercontent.com/51036481/230226827-204db228-e95c-4685-8b48-b8c6cb2d04e6.png)

### After: The sort search params are no longer in the URL and the table/list isn't sorted
![after](https://user-images.githubusercontent.com/51036481/230226836-1513fc79-76b0-4c9b-ac95-ef7ad216db21.png)

### Desktop

- Mac OS 13.2.1
- Chrome Version 111.0.5563.146
- @refinedev/core version 4.5.2

### Additional Context

I'm not sure if this is relevant but this might have something to do with the deprecation of `sorter` that changed to `sorters`.

**Comment by yildirayunlu** [comment]
Hey @DeveloperTheExplorer 

I've seen this working in the [`base-mui`](https://github.com/refinedev/refine/tree/next/examples/base-mui) project. Maybe you can check the versions. If the problem persists, we would appreciate it if you could send a reproduced codesanbox.

**Comment by g3vxy** [comment]
```json
{
   "dependencies":{
      "@emotion/react":"^11.8.2",
      "@mantine/core":"^5.10.4",
      "@mantine/form":"^5.10.4",
      "@mantine/hooks":"^5.10.4",
      "@mantine/notifications":"^5.10.4",
      "@refinedev/cli":"^2.1.2",
      "@refinedev/core":"^4.8.2",
      "@refinedev/inferencer":"^3.1.4",
      "@refinedev/kbar":"^1.1.0",
      "@refinedev/mantine":"^2.5.0",
      "@refinedev/react-router-v6":"^4.1.0",
      "@refinedev/react-table":"^5.1.4",
      "@refinedev/simple-rest":"^4.0.0",
      "@tabler/icons":"^1.1.0",
      "i18next":"^20.1.0",
      "i18next-browser-languagedetector":"^6.1.1",
      "i18next-xhr-backend":"^3.2.2",
      "react":"^18.0.0",
      "react-dom":"^18.0.0",
      "react-i18next":"^11.8.11",
      "react-router-dom":"^6.8.1",
      "react-scripts":"^5.0.0"
   }
}
```
We can reproduce this issue with the given dependency versions. @omeraplak 

![Screenshot 2023-04-11 at 22 44 20](https://user-images.githubusercontent.com/43988284/231272054-42de4301-9201-44d3-a970-3f26ac5cec0e.png)
