### ISSUE TITLE
[BUG] AntdInferencer not working even adjusting the new API

### ISSUE THREAD

**Issue by kalib-code** [refinedev/refine#4107]
### Describe the bug

updated to latest version but AntdListInferencer is not working afterward. 

<img width="1178" alt="image" src="https://user-images.githubusercontent.com/17924045/230327630-cbb239ac-3461-41cf-bc62-abb8eec7716d.png">

<img width="1015" alt="image" src="https://user-images.githubusercontent.com/17924045/230327590-d9078df2-b194-46ff-ac74-025750fa131f.png">

result 

<img width="1255" alt="image" src="https://user-images.githubusercontent.com/17924045/230327865-abc6d605-7890-43c5-83b5-ad2f2996169a.png">

### Steps To Reproduce

1. update to latest version 
2. AntdListInferencer on loading state. 

### Expected behavior

expected should see list view with table. 

### Screenshot

<img width="1178" alt="image" src="https://user-images.githubusercontent.com/17924045/230327630-cbb239ac-3461-41cf-bc62-abb8eec7716d.png">

<img width="1015" alt="image" src="https://user-images.githubusercontent.com/17924045/230327590-d9078df2-b194-46ff-ac74-025750fa131f.png">

result 

<img width="1255" alt="image" src="https://user-images.githubusercontent.com/17924045/230327865-abc6d605-7890-43c5-83b5-ad2f2996169a.png">

### Desktop

- OS mac 
- chrome 

### Additional Context

as given in the photo above I have the expected data using a custom data provider and using useList but the AntdListInferencer is in unli loading

**Comment by omeraplak** [comment]
Hey @kalib-code ,
Could you share a CodeSandbox environment where we can reproduce the issue?
