### ISSUE TITLE
[BUG] using useFieldArray from react-hook-form and useStepForm resets the non array data

### ISSUE THREAD

**Issue by julirofrano** [refinedev/refine#4126]
### Describe the bug

I'm having troubles while using useFieldArray from react-hook-form and useStepForm from refine with Material UI 
Maybe i'm doing something wrong here?
https://codesandbox.io/s/pensive-brahmagupta-5phufk?file=/src/pages/posts/edit.tsx

### Steps To Reproduce

Modify the tittle from step 1
Go to step 2
click add
go back to step 1
the tittle is now the original tittle

### Expected behavior

The data from non array fields keeps its state

**Comment by sevkioruc** [comment]
Hi @julirofrano,
I thought while examining your code whatever this definition `const { control, register } = useForm();`  is required or not .
What do you think?

**Comment by alicanerdurmaz** [comment]
@julirofrano Hi, we are investigating the issue

**Comment by alicanerdurmaz** [comment]
After appending a new item to the form, the dirty state of all form fields is set to `false`. This causes the form values to be reset according to the value coming from the API.

Unfortunately, we have not found a solution yet.

**Comment by julirofrano** [comment]
sure no worries! let me know if i can help

**Comment by alicanerdurmaz** [comment]
@julirofrano Hello again, next week we will open an issue in the react-hook-form repository.

**Comment by alicanerdurmaz** [comment]
@julirofrano Hi again,
We opened a discussion in the React Hook Form repository. https://github.com/orgs/react-hook-form/discussions/10290

**Comment by omeraplak** [comment]
Hey @julirofrano ,
We fixed this error with version [@refinedev/react-hook-form@4.2.2](https://github.com/refinedev/refine/releases/tag/%40refinedev%2Freact-hook-form%404.2.2). Can you confirm the fix?
