### ISSUE TITLE
[BUG] IMG uploaded correctly on strapi but file details not stored.

### ISSUE THREAD

**Issue by rubek-joshi** [refinedev/refine#4161]
### Describe the bug

>I'm following the [refine week ft. strapi blog](https://refine.dev/blog/refine-invoice-generator/) and got stuck in the uploading of an img part. I just cloned the example from Github and have the same problem occurring in the example project. The IMG is uploaded correctly in the media library but the file details are not stored at all in the company collection.

### Steps To Reproduce

1. Follow the blog and [reach here](https://refine.dev/blog/refine-react-invoice-generator-3/#company-create-action).
2. Create a company and upload image.
3. Save company.
4. See error in image.

### Expected behavior

The image is tied to the company.

### Screenshot

![image](https://user-images.githubusercontent.com/33681318/231676736-cf992ba5-5703-40b9-871a-d9bdadd140a7.png)

### Desktop

n/a

### Mobile

n/a

### Additional Context

See [this discord help post](https://discord.com/channels/837692625737613362/1095769269058408469)

**Comment by omeraplak** [comment]
Hey @rubek-joshi ,
Thank you! We'll fix it soon 🪄

**Comment by salihozdemir** [comment]
Hey @rubek-joshi and @jsmb768ypl,

I've created a PR. I hope it helps you 🙏🏻
