### ISSUE TITLE
[DOC] Example of using Refine with Hasura LiveProvider in the docs

### ISSUE THREAD

**Issue by purplefish32** [refinedev/refine#4178]
### Is your feature request related to a problem? Please describe.

Missing example of using Refine with Hasura LiveProvider in the docs

### Describe the thing to improve

Would it possible to have an example of using Refine with Hasura LiveProvider in the docs ?

**Comment by BatuhanW** [comment]
Hello @purplefish32, we have the necessary code in the example for live provider but codesandbox blocks ws protocol, it doesn't work. However, you can see the example here and run it locally: https://github.com/refinedev/refine/tree/next/examples/data-provider-hasura
