### ISSUE TITLE
[FEAT] Local filtering (and sorting?)

### ISSUE THREAD

**Issue by snird** [refinedev/refine#4180]
### Is your feature request related to a problem? Please describe.

There are "lists" that are not too long. For example, 20-30 items.

In this size, it makes more sense to serve them all at once to the client and operate on them locally.

This is already possible with the paginations side:
```
    pagination: {
      mode: "client",
    },
```

but filtering still sends a request to the server every time.

### Describe the thing to improve

If we can have a global "client" mode, not just for pagination.
So that filtering and sorting will get done on the local data set.

EDIT:
The reason I want this implemented on refine, rather than simply filter the array myself is integration with everythings else.
Most importantly, the url changing to reflect the filter

**Comment by BatuhanW** [comment]
Hey @snird, could you share a snippet of relevant parts, so we can debug better?
