### ISSUE TITLE
[FEAT] @refinedev/nhost could be based on @refinedev/hasura

### ISSUE THREAD

**Issue by beepsoft** [refinedev/refine#4190]
### Is your feature request related to a problem? Please describe.

As nhost uses Hasura under the hood it may be better to base the implementation of the nhost data provider on the Hasura provider. This way these two could be always in sync and would  not need a separate implementation of the same Hasura API as is the case now.

### Describe the thing to improve

The only difference between the nhost and Hasura provider seems to be the use of the client: NhostClient vs. generic GraphQLClient.

**Comment by omeraplak** [comment]
Hey @beepsoft  👋 , we will be discontinuing native support for nHost data provider soon. If you would like to continue maintaining this package, please let us know. We can make the necessary changes in the documentation 🙂
