### ISSUE TITLE
[BUG] MaterialUI Themed not apply for imports from @mui

### ISSUE THREAD

**Issue by MetaCorp** [refinedev/refine#4203]
### Describe the bug

I'm using refine and I also have imports from @mui. But the theme I set from refine header (dark/light mode) is not apply to the components imported from @mui, only to the components build in refine.

### Steps To Reproduce

1. Install a refine project
2. Import a component from @mui
3. Change the theme

### Expected behavior

The theme is applied to components imported from @mui.

**Comment by aliemir** [comment]
Hey @MetaCorp, can you elaborate a bit more and provide a repro or a guide to repro? 🤔 I've just created a Material UI + CRA app with `create-refine-app` and added a button from `@mui/material`. 

```tsx
<Button variant="contained">Contained Button</Button>
```

When I try to change the theme, button reflect the changes in the theme 🤖

**Comment by aliemir** [comment]
Closing this for now. Do not hesitate to re-open when you can provide a repro 🙏
