### ISSUE TITLE
[BUG] Freshly installed Refine project but can't signup

### ISSUE THREAD

**Issue by MetaCorp** [refinedev/refine#4204]
### Describe the bug

I just installed a Refine project with Supabase and Next.js.

The login works fine with default credentials. But I can't create a new account as I get this error : 
'Cannot destructure property 'success' of 'undefined' as it is undefined.  TypeError'

### Steps To Reproduce

1. Install Refine project
2. Try to register an account

### Expected behavior

The account is registered successfully.

**Comment by munnokd** [comment]
Hey @MetaCorp can you assign this issue to me?
