### ISSUE TITLE
[DOC] Wrong "RUN IN YOUR LOCAL" command for example with-remix-auth

### ISSUE THREAD

**Issue by haveagoodone** [refinedev/refine#4225]
### Documentation issue

The command `npm create refine-app@latest -- --example with-remix-oauth` is wrong. There is no example with the name `with-remix-oauth`. The correct example is `with-remix-auth`.

### Describe the thing to improve

The command is correct `npm create refine-app@latest -- --example with-remix-auth`

**Comment by aliemir** [comment]
Hey @haveagoodone sorry for the issue. 🙏  Do you want to create a PR for a fix? Every contribution is welcome 🚀

**Comment by haveagoodone** [comment]
Hey,
good idea ;-) I'll create a PR.
