### ISSUE TITLE
File structure different from the video

### ISSUE THREAD

**Issue by sankyrajeev** [refinedev/refine#4242]
When i install the latest refine i get a different file structure a the one in your video. Am i doing something wrong? For example. I do not have the Layouts folder at all

**Comment by alicanerdurmaz** [comment]
Hi @sankyrajeev, JavaScript Mastery's video using **refine**@3. **refine**'s latest version is @4 

You can use this command to create **refine@3** app.
```bash 
npm create refine-app@latest -- --branch v3
```

After that, you can read our [migration guide](https://refine.dev/docs/migration-guide/3x-to-4x/).
