### ISSUE TITLE
[BUG] refine-nextjs template can't deploy to vercel

### ISSUE THREAD

**Issue by hongfanmeng** [refinedev/refine#4249]
### Describe the bug

I created a refine application with the following options and deployed it to vercel and I get a 504 GATEWAY_TIMEOUT

✔ Downloaded remote source successfully.
✔ Choose a project template · refine-nextjs
✔ What would you like to name your project?: · refine-with-next
✔ Choose your backend service to connect: · data-provider-custom-json-rest
✔ Do you want to use a UI Framework?: · mui
✔ Do you want to add example pages?: · inferencer
✔ Do you need any Authentication logic?: · auth-provider-custom
✔ Do you need i18n (Internationalization) support?: · no
✔ Choose a package manager: · yarn
✔ Would you mind sending us your choices so that we can improve superplate? · no

### Steps To Reproduce

1. create a refine project with options provided
2. deploy app to vercel
3. get a 504 GATEWAY_TIMEOUT

### Expected behavior

It should display correctly

### Screenshot

![image](https://user-images.githubusercontent.com/51071010/235362673-5acd4405-189f-4a35-8d71-1490d8568e96.png)

**Comment by DoguhanOzgurAkca** [comment]
<img width="1162" alt="Screenshot 2023-04-30 at 19 06 28" src="https://user-images.githubusercontent.com/76914028/235363636-3eb83263-4988-4665-b106-d722818f0914.png">
Trying to recreate it, i got the same problem. Site was running without a problem (except for having only the github banner) but then, boom. 
It also says 
 npm run start

> kind-suns-go@0.1.0 start
> refine start

sh: refine: command not found

whenever i try to run it, but might be a me thing since i never used yarn till now.

**Comment by hongfanmeng** [comment]
I also tested the antd version of refine-next and it works fine.

**Comment by DoguhanOzgurAkca** [comment]
<img width="716" alt="Screenshot 2023-04-30 at 20 24 47" src="https://user-images.githubusercontent.com/76914028/235367206-8d3599f0-80d2-4417-b451-4740454d7155.png">
I think the problem might be caused by this,

**Comment by hongfanmeng** [comment]
> <img alt="Screenshot 2023-04-30 at 20 24 47" width="716" src="https://user-images.githubusercontent.com/76914028/235367206-8d3599f0-80d2-4417-b451-4740454d7155.png">
> 
> I think the problem might be caused by this,

Where did this file come from?

**Comment by DoguhanOzgurAkca** [comment]
I think its created while building the app

**Comment by omeraplak** [comment]
Hey @hongfanmeng ,
I was able to reproduce the same issue. I'm getting a timeout with the 'Hobby' package. There's probably something wrong with Material UI. Thank you for reporting the issue. We will take care of it as soon as possible

**Comment by aliemir** [comment]
Hey @hongfanmeng, we had some updates in our codebase also on create-refine-app templates. Just tested out with a hobby plan and had no issue with timeouts. Turns out It was mostly related to Material UI imports 😅
