### ISSUE TITLE
[FEAT] Trigger getList function in custom data provider manually

### ISSUE THREAD

**Issue by azmicirit** [refinedev/refine#4258]
### Is your feature request related to a problem? Please describe.

Is it possible to trigger `getList` function in custom data provider via `useDataGrid` hook manually? Currently, I had to call the `setFilters` function with unique key for each trigger needs. My problem is we have a toggle button in actions and we'd like to refresh datagrid's data(state) after toggle state is changed in a record.

My solution is: Send a same filter props and one unique key to bypass `React.memo`. There is an `useEffect` hook which listens every custom mutate so we are able to catch the toggle changes.
```  
useEffect(() => {
    if (customMutateData?.data) {
      setFilters([...filters, { field: Date.now().toString(), operator: 'eq', value: '' }]);
    }
  }, [customMutateData]);
```

### Describe alternatives you've considered

As I reviewed source codes, `getList` is called in `useTable` hook after component is initialized.
https://github.com/refinedev/refine/blob/9c4f73e5112f74b77f0ed415f5296ee32fc969dd/packages/core/src/hooks/useTable/index.ts#L511-L530

### Describe the thing to improve

We'd like to trigger useList, useUpdate and other hooks in DataGrid Component via useDataGrid hook, manually whenever we  want without a trick.

**Comment by omeraplak** [comment]
Hey @azmicirit ,
Thank you for getting in touch with us. Does the `refetch` function work for your use case? You can find more information here: https://refine.dev/docs/faq/#how-can-i-refetch-data"

**Comment by azmicirit** [comment]
@omeraplak Sorry, It was my fault. I see now, there is a nested export in useDataGrid hook.
