### ISSUE TITLE
[BUG] Save button does not revert state to not editing for useEditableTable

### ISSUE THREAD

**Issue by aidanlloydtucker** [refinedev/refine#4274]
### Describe the bug

When using an editable table, the save button does not close the editing state of the row

### Steps To Reproduce

1. Go to [this example](https://refine.dev/docs/api-reference/antd/hooks/table/useEditableTable/)
2. Click edit
3. change the text field
4. click save
5. save button does not go away

### Expected behavior

edit state should be reverted to false

**Comment by alicanerdurmaz** [comment]
Hello, we will discuss with the core team the feasibility of automatically performing this task by "useEditableTable".

but meanwhile, you can manually close the row after the mutation is a success
```ts
useEditableTable({
        onMutationSuccess: () => {
            setEditId(undefined);
        },
});
```
full example: https://codesandbox.io/s/sweet-haibt-2y9zbj?file=/src/pages/posts/list.tsx:534-562

**Comment by alicanerdurmaz** [comment]
Hi @aidanlloydtucker, I opened PR for this bug https://github.com/refinedev/refine/pull/4278
Thanks for the issue 👍
