### ISSUE TITLE
[BUG] PreviousData does not get populated in Audit when update event is triggered

### ISSUE THREAD

**Issue by joanaavelar** [refinedev/refine#4275]
### Describe the bug

Using a sample provided on refine website -[https://codesandbox.io/s/github/refinedev/refine/tree/next/examples/audit-log-provider?from-embed](url) or by installing the same sample, **previousData** does not get populated.

### Steps To Reproduce

1. Open [https://codesandbox.io/s/github/refinedev/refine/tree/next/examples/audit-log-provider?from-embed](url) or install the sample  - npm create refine-app@latest -- --example audit-log-provider
2. Open Inspect
3. Click on edit button
4. Update something on the edit page
5. On Network tab look for logs endpoint and under preview tab validate that **previousData** is not defined.

### Expected behavior

When an update event is triggered, **previousData** should contain previous data information.

### Screenshot

![image](https://user-images.githubusercontent.com/11629784/236332376-8dae6c37-0743-4d5b-a4bf-4f94fa56d90d.png)

**Comment by yildirayunlu** [comment]
Hey @joanaavelar Thank you for reporting this issue. I created a PR to solve this. We will release a patch for `@refinedev/core`. Don't forget to update.
