### ISSUE TITLE
[BUG] can't swizzle @refinedev/graphql

### ISSUE THREAD

**Issue by nikun** [refinedev/refine#4282]
### Describe the bug

Running swizzle the prompt doesn't show the data provider: @refinedev/graphql

### Steps To Reproduce

`npm install @refinedev/graphql`
`npm run refine swizzle`

### Expected behavior

The command should show the installed package.

### Screenshot

![Selection_283](https://user-images.githubusercontent.com/1055045/236676455-9f772d30-57d6-42fc-9b63-1493ff2a7830.png)

### Desktop

- Ubuntu 16
- Node 16.19.1

**Comment by alicanerdurmaz** [comment]
Hi @nikun,
I couldn't reproduce the problem. Could you please provide the output of `npm run refine whoami`?
<img width="840" alt="image" src="https://user-images.githubusercontent.com/23058882/236798895-fd24941d-31cc-4182-b22c-b6cc73e22201.png">

**Comment by alicanerdurmaz** [comment]
@nikun Hi again, we found the issue. I will open PR today. thanks for the issue

**Comment by alicanerdurmaz** [comment]
@nikun We released a fix `(version: @refinedev/graphql: 6.4.2)`.

You can update with refine CLI: `npm run refine update`.

I tested and it works as expected. Please let us know if you find any other problems 🚀

**Comment by nikun** [comment]
i just tested the swizzle command and works prefect with the updated package 6.4.2.
Thks!!
