### ISSUE TITLE
[FEAT]Requests can support react-jsonschema-form

### ISSUE THREAD

**Issue by qianxuanyon** [refinedev/refine#4299]
### Is your feature request related to a problem? Please describe.

no

### Describe the thing to improve

Whether you can use json to build a form based on dynamic forms to add, delete, modify and check
Suitable for scenarios where the form is not fixed

https://rjsf-team.github.io/react-jsonschema-form/docs/

**Comment by aliemir** [comment]
Hey @qianxuanyon, refine has no limitations on using external libraries such as `react-jsonschema-form` when creating your components. If you have any issues while using it with refine, you can reach out to us from issues or from our [discord channel](https://discord.gg/refine).

Still, we'd love to add it to our list of examples if you can provide a working example with refine and create a PR for it 🙏
