### ISSUE TITLE
[FEAT]: Provide a way to tweak navigation for resources

### ISSUE THREAD

**Issue by Mr0nline** [refinedev/refine#4310]
### Is your feature request related to a problem? Please describe.

It would be good if we can forcefully render on Resource click. For example, I'm working on a big-scale ERP-like software and I've created some resources like the following.

```javascript
//...some jsx stuff
resources={[
  {
    name: 'dashboard',
    list: '/',
    meta: {
      label: 'Dashboard',
      icon: <Dashboard />
    }
  },
  {
    name: 'weight-calculator',
    list: WEIGHT_CALCULATOR_PATH,
    meta: {
      label: 'Weight Calculator',
      parent: 'Tools',
      icon: <Calculate />
    }
  },
  {
    name: 'weight-calculator-records',
    list: WEIGHT_CALCULATOR_RECORDS_PATH,
    meta: {
      label: 'Calculation Records',
      parent: 'Tools',
      icon: <Feed />
    }
  },
  {
    name: 'roles-list',
    list: ROLES_LIST_PATH,
    meta: {
      label: 'Roles',
      icon: <ManageAccounts />
    }
  }
]}
```

Currently, it seems there is no easier way to achieve the reload on the menu click. What I mean here is that if my current tab is `Weight Calculator` and I click on it again, It just navigates to the path but it doesn't trigger remounting. Because of this, the UI gets reset but the form values stay persistent!

### Describe alternatives you've considered

I can do a nasty workaround using some sort of `useEffect` and state to check if the values have been reset and then upon that, I can reset the form as well so it just seems a bit of a hacky way to do this!

### Additional context

![Screenshot_63](https://github.com/refinedev/refine/assets/57582883/03da4619-59f6-4652-8f92-05b8267262d1)
![Screenshot_64](https://github.com/refinedev/refine/assets/57582883/672f8fe9-e3b8-4663-a817-60d8e1236d11)

### Describe the thing to improve

I have 2 suggestions.
There can be an optional prop that ignores active tab click, So if the route and resource are on the same URL, Clicking on a resource will not trigger route change if this prop has been turned on

Alternatively, we can have a prop similar to `navigationProps` which contains settings related to navigations like `reload: boolean` etc!

**Comment by Mr0nline** [comment]
I'm willing to work on a PR if anyone has a clue about where shall I be starting! :crossed_fingers:

**Comment by Mr0nline** [comment]
Bumping this up for any leads!

**Comment by aliemir** [comment]
Hey @Mr0nline, thank you for the issue! Do you think making the active element unclickable will be enough? I'm closer to this option than to add a `reload` property for sake of simplicity. And if anyone wants to change the behavior of in an uncommon way they can use the `swizzle` command to achieve that? 🤔 

Let's settle the details of the implementation and then we will assign the issue to you. I'll also try to assist you on how to start the development.

**Comment by Mr0nline** [comment]
Hello @aliemir, Yes adding `reload: false` should be fine for my use case and is a simpler approach imo as well. I looked at `swizzle` to do a complete override but I thought to raise a feature request as it seems useful for general usecase and also contain a subtle API changes in default props.

Do let me know about starting points and I'll start working on the contribution :crossed_fingers:

**Comment by Mr0nline** [comment]
@aliemir :wave: 
Bumping this up so that I can start working on it ASAP :+1:

**Comment by Mr0nline** [comment]
> Actually, I meant to support the other option sweat_smile
So, Basically, Refine should disable active routes by default and there will be no props/settings to make it enable right?
Is this what I shall be aiming to implement? :thinking:  Sorry just a bit confused haha.

This one also will work for my use case though

**Comment by aliemir** [comment]
Let's have a way to toggle the disabled status of the active item click by adding a prop to `<Sider>` components.

`<Sider>` components use a shared interface which you can access at `@refinedev/ui-types` (`/packages/ui-types`). We can add a prop like `activeItemDisabled?: boolean`. 

In the `<Sider>` components of the UI packages, we will use this prop to determine the behavior and disable the `onClick` method (or whichever is used in there) of the menu item.

Is this enough for you to start with or do you think there are still blind spots? I'd be happy to help clear things out. If you encounter any issues while working on this, let us know from our [Discord channel](https://discord.gg/refine) 🚀 🚀

**Comment by Mr0nline** [comment]
@aliemir, I've did the required changes (hopefully)! Let me know if any further changes are required :crossed_fingers:
