### ISSUE TITLE
[BUG] Supabase - Inferencer skips reference fields

### ISSUE THREAD

**Issue by Mikilll94** [refinedev/refine#4330]
### Describe the bug

In the `orders` table, I have a reference field `address_id` but this field is skipped in `Inferencer` generated code.

![Przechwytywanie](https://github.com/refinedev/refine/assets/17653648/bd0949eb-3a42-40a5-9848-d943b126759a)

![image](https://github.com/refinedev/refine/assets/17653648/c497d9bf-6f08-4a52-8589-535f7f4fa95f)

As you can see, there is no `Address` field in the UI.

### Steps To Reproduce

1. Download this project: [cyan-views-cover.zip](https://github.com/refinedev/refine/files/11467871/cyan-views-cover.zip)
2. Run
```
npm install
npm run serve
```
3. Look at the `Inferencer` generated code.

### Expected behavior

`Inferencer` should generate the code for reference fields.

### Desktop

- Windows 11
- Brave 1.51.114 Chromium: 113.0.5672.92
- @refinedev/cli: 2.5.3
- @refinedev/core: 4.14.3
- @refinedev/inferencer: 3.3.4
- @refinedev/supabase: 5.5.2

**Comment by BatuhanW** [comment]
Hello @Mikilll94, we debugged the problem and it's because your first record coming from API has null address_id field, thus inferencer won't infer it. We have a task in our backlog to fix this issue, stay in touch 🙌🏼

**Comment by aliemir** [comment]
Updated our inference logic at PR #4382 to prevent this issue from happening, at least for `list` and `create` actions where we infer the fields by the `getList` calls. Now the inferencer will work with all the list records instead of just one.
