### ISSUE TITLE
[BUG] Blog footer darkmode text

### ISSUE THREAD

**Issue by Krut-in** [refinedev/refine#4346]
### Describe the bug

When in dark mode, the footer text is of dark color. That is, the text color is according to light mode even in dark mode. There should be a contrast between the background and the text, which is absent in this case, when in dark mode blog website, footer location

### Steps To Reproduce

1. Got to the Website (https://refine.dev/blog/)
2. Click on the dark mode button and activate it
3. Scroll down to see the footer
4. See an error; you will have difficulty in reading the text as it's not according to the dark mode

### Expected behavior

I expect the text color to be white in color when in dark mode. So the users can easily read it and there should be a contrast between the background and the text color

**Comment by Krut-in** [comment]
Can i solve this bug?!

**Comment by BatuhanW** [comment]
Hello @Krut-in, of course! Feel free to create a PR, we are looking forward to it!

**Comment by BatuhanW** [comment]
Hello @Krut-in, we are working on re-design of our documentation, so this will change soon. Thanks for the report!
