### ISSUE TITLE
[BUG] In ArchLinux, While creating app with refine doesn't initialize the git repository.

### ISSUE THREAD

**Issue by nishu-murmu** [refinedev/refine#4364]
### Describe the bug

> **Note**
Only happening for ArchLinux

I wanted to create a next.js project using refine with app directory.
But I noticed one thing that it doesn't initialize the git repository.
Then I created applicaion with different flags but none of them were initializing git repo.

### Steps To Reproduce

1. Create a project with any example
2. You'll probably see the error

### Expected behavior

Should create the project with git repo initialized.

### Screenshot

![refine](https://github.com/refinedev/refine/assets/71123337/cdfb6aa8-7a09-481c-8f89-92ba4f5c15af)
Doesn't create the repo
But it does in Windows.
If there is something wrong with my side do let me know

### Desktop

- OS: ArchLinux
- Browser: Google Chrome
- Version: 113.0.5672.126 (Official Build) (64-bit)

**Comment by aliemir** [comment]
Hey @nishu-murmu, can you share your `git` version installed on your setup? 🙏 Let's investigate this issue and hopefully we'll deploy a fix soon.

**Comment by nishu-murmu** [comment]
> Hey @nishu-murmu, can you share your `git` version installed on your setup? pray Let's investigate this issue and hopefully we'll deploy a fix soon.

Sure, happy to help
`git` version 2.40.1

**Comment by aliemir** [comment]
Sorry to ask you much @nishu-murmu but I don't have an ArchLinux environment ready for testing. Can you help me understand the issue? 🙏 

After you create the example without a git repo initialized, can you try to navigate to the directory and run:

```bash
git init
git checkout -b main
git add -A
git commit --message="Initial commit from Create Refine App"
```

Let's see if the error is happening due to the commands we're trying to run or due to the way we're running them 😅

**Comment by aliemir** [comment]
Just had a chance to test it out with a fresh setup, had the same error. Tried to follow the above steps, found out I was having an error at `git commit` due to lack of user config on my `git` setup. Added a username and an email, tried again and had no issues. 🤔

**Comment by nishu-murmu** [comment]
> Just had a chance to test it out with a fresh setup, had the same error. Tried to follow the above steps, found out I was having an error at `git commit` due to lack of user config on my `git` setup. Added a username and an email, tried again and had no issues. thinking Of course this is due to my missing configuration and your case might be different, I'll be waiting for your response for the above comment pray Anyways, I'll try to add some logic to show info about the failing steps.

Yeah setting up the git config was the issue, My bad.
