### ISSUE TITLE
[BUG] Right clicking on the Refine logo opens up Figma design file for Refine logo

### ISSUE THREAD

**Issue by amanShouts** [refinedev/refine#4368]
### Describe the bug

When I right-click on the Refine logo on the homepage, a Figma design file for the logo opens up in a new tab. 
Link of Figma design file - https://www.figma.com/file/y8lhTyumAN0zYI5nKKLoLN/refine.dev-brand-assets?type=design&t=4Y56MTBK1eIlf1Oq-0on

### Steps To Reproduce

1. Go to Logo on Homepage ( this behavior persists on other pages as well )
2. Right-Click on the logo

### Expected behavior

Not sure, but
1 For starters stop opening the Figma design altogether (-  if this wasn't intentional to begin with)
2. Right-click should show normal browser options like - Save link, Open in a new tab or window, copy link, etc. 

### Desktop

- OS Windows 11
- Browser - Edge Version 113.0.1774.50

**Comment by yildirayunlu** [comment]
Hey @amanShouts we added this as an [easter egg](https://en.wikipedia.org/wiki/Easter_egg_(media)).
