### ISSUE TITLE
[BUG] Inferencer assumes `id` is number

### ISSUE THREAD

**Issue by bombillazo** [refinedev/refine#4390]
### Describe the bug

At least for the AntD Inferencers, the `id` is interpolated directly into the id property, seemingly assuming that it is a number:
```tsx
export const ${COMPONENT_NAME}: React.FC<IResourceComponentsProps> = () => {
        const { queryResult } = useShow(${
            isCustomPage
                ? `{ 
                    resource: "${resource.name}", 
                    id: ${id}, // <----- HERE
                    ${getMetaProps(
                        resource?.identifier ?? resource?.name,
                        meta,
                        "getOne",
                    )}
                }`
```

If one is using UUIDs or any other string-based ids, the Inferencer fails as the string is not properly assigned:

<img width="467" alt="image" src="https://github.com/refinedev/refine/assets/44002321/d4caa952-8765-42ca-bbb6-5655f28edf26">

### Steps To Reproduce

1. Setup a test page with an inferencer.
2. Pass a string as an `id` with either `show` or `edit` actions.
3. Navigate to page and see error.

### Expected behavior

Component is able to fetch the data and render the component fully.

### Screenshot

<img width="946" alt="image" src="https://github.com/refinedev/refine/assets/44002321/520f9390-613b-4d19-9e9d-1cab07245c77">

**Comment by yildirayunlu** [comment]
Hey @bombillazo Thank you for reporting this issue 🙏🏼 
There is such a problem with `isCustomPage`. We've added it to the Todo list, and we'll fix it soon 🚀
