### ISSUE TITLE
[BUG] the 'queryOptions.enabled' option of useSelect does not work as intende

### ISSUE THREAD

**Issue by coder-layne** [refinedev/refine#4408]
### Describe the bug

According to the [document](https://refine.dev/docs/api-reference/core/hooks/useSelect/#defaultvaluequeryoptions), queryOptions will be used when defaultValueQueryOptions is not passed in, but everything does not execute as expected when there is a defaultValue

### Steps To Reproduce

```javascript
useSelect({
  resource: "todos",
  defaultValue: 1,
  queryOptions: {
    enabled: false,
  },
});
```

### Expected behavior

Due to the 'enabled' being set to false, as expected, no requests should be made until it becomes true.

**Comment by bombillazo** [comment]
I think the docs are not updated or reflecting the proper functionality. `defaultValue` uses the `useMany` hook and, yes, it uses the `queryOptions` if `defaultValueQueryOptions` is not passed, **_except_** for the enabled property:

```tsx
    const defaultValueQueryOptions =
        defaultValueQueryOptionsFromProps ?? (queryOptions as any);

    const defaultValueQueryResult = useMany<TQueryFnData, TError, TData>({
        resource,
        ids: defaultValues,
        queryOptions: {
            ...defaultValueQueryOptions,
            enabled:
                defaultValues.length > 0 &&
                (defaultValueQueryOptionsFromProps?.enabled ?? true), // <----- looking at the props `enabled` directly from defaultValueQueryOptions 
            onSuccess: (data) => {
                defaultValueQueryOnSuccess(data);
                defaultValueQueryOptions?.onSuccess?.(data);
            },
        },
        meta: combinedMeta,
        metaData: combinedMeta,
        liveMode: "off",
        dataProviderName,
    });
```

For enabled, it still looks for the property from `defaultValueQueryOptions`, I am not sure why though.
