### ISSUE TITLE
[BUG] Create refine-app crashing with SAOError 

### ISSUE THREAD

**Issue by kevnoutsawo** [refinedev/refine#4414]
### Describe the bug

I am trying to create a refine project with the following command:
`npm create refine-app@latest client`

However, it systematically crashes at the moment of Installing packages with npm with this error:
```
superplate-cli has encountered an error.

If you think this is caused by a bug. Please check out:
https://github.com/pankod/superplate/issues

ERROR SAOError: Failed to install packages in /home/kevin/Projects/refine_dashboard/client
    at ChildProcess.<anonymous> (/home/kevin/.npm/_npx/98c66fac912b1cba/node_modules/sao/dist/chunk.T-GsVNZ1.js:6885:16)
    at ChildProcess.emit (node:events:526:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5) {
  sao: true
}
```

### Steps To Reproduce

1) Open terminal
2) Run create refine-app with following command: 
`npm create refine-app@latest client`
3) Select following options:
```
✔ Choose a project template · refine-react
✔ What would you like to name your project?: · client
✔ Choose your backend service to connect: · data-provider-custom-json-rest
✔ Do you want to use a UI Framework?: · mui
✔ Do you want to add example pages?: · inferencer
✔ Do you need any Authentication logic?: · auth-provider-google
✔ Do you need i18n (Internationalization) support?: · no
✔ Choose a package manager: · npm
✔ Would you mind sending us your choices so that we can improve superplate? · yes
```
4) Validate choices to proceed with installation

### Expected behavior

It should properly create the project without errors

### Screenshot

```
✔ Downloaded remote source successfully.
✔ Choose a project template · refine-react
✔ What would you like to name your project?: · client
✔ Choose your backend service to connect: · data-provider-custom-json-rest
✔ Do you want to use a UI Framework?: · mui
✔ Do you want to add example pages?: · inferencer
✔ Do you need any Authentication logic?: · auth-provider-google
✔ Do you need i18n (Internationalization) support?: · no
✔ Choose a package manager: · npm
✔ Would you mind sending us your choices so that we can improve superplate? · yes
superplate-cli has encountered an error.

If you think this is caused by a bug. Please check out:
https://github.com/pankod/superplate/issues

ERROR SAOError: Failed to install packages in /home/kevin/Projects/refine_dashboard/client
    at ChildProcess.<anonymous> (/home/kevin/.npm/_npx/98c66fac912b1cba/node_modules/sao/dist/chunk.T-GsVNZ1.js:6885:16)
    at ChildProcess.emit (node:events:526:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5) {
  sao: true
}
```

### Desktop

- OS: Ubuntu 22.04
- Browser: Google Chrome

**Comment by BatuhanW** [comment]
Hello @kevnoutsawo we'll check the issue and get back to you.

**Comment by BatuhanW** [comment]
Hello again, @kevnoutsawo, unfortunately, couldn't reproduce the issue. It could be a connectivity problem, could you try it again or retry with pnpm? Alternatively, you can also try `DEBUG=true npm create refine-app@latest client`, it should log some errors about babel, ( starts with `Error: Could not find source file..` you can ignore them, but if you still have error, you can send us latest error log, so we can help.

![Screenshot 2023-05-30 at 11 43 36](https://github.com/refinedev/refine/assets/16444991/c46eefd4-e686-4be9-bcb4-f1e96f0f7c54)

**Comment by kevnoutsawo** [comment]
Hi @BatuhanW ,
I installed pnpm and ran the installation with it and it works. I am currently using a mobile connexion and it probably is part of the issue. pnpm seems more resilient than npm in this regard. I am marking this as solved.
Thanks a lot.
