### ISSUE TITLE
[BUG] Next 13 app dir router breaks Create and List components navigation

### ISSUE THREAD

**Issue by Nmaxime** [refinedev/refine#4420]
### Describe the bug

In a Next 13 with app directory, we can't go back from a Create page using the Create component to a List page using the List component.

### Steps To Reproduce

1. Create a refine context in a client component, imports the next app router from `@refinedev/nextjs-router/app`, then provide the client component in the root layout.

2. Create a list and create pages

```ts
'use client'

import { List } from '@refinedev/chakra-ui'

export default async function Page() {
    return (
        <List canCreate resource="test">
            test 1
        </List>
    )
}
```
```ts
'use client'

import { List } from '@refinedev/chakra-ui'

export default async function Page() {
    return (
        <Create resource="test">
            test 2
        </Create>
    )
}
```

3. Go to the list page and click on the Create button
4. On the Create page, click on the return button
5. The URL will change but not the page content. The page will be stuck.

### Expected behavior

Going  back from a Create page to a List page should not crash the app.

### Desktop

OS: Ubuntu 22.04

```
"next": "13.4.4"
"@refinedev/chakra-ui": "2.14.2"
"@refinedev/core": "4.16.2"
"@refinedev/nextjs-router": "5.3.0"
```

**Comment by BatuhanW** [comment]
Hello @Nmaxime, could you retry after changing the name of the component? Let us know if you still have the issue.

**Comment by Nmaxime** [comment]
Hello @BatuhanW , thanks for the advise. I still have the same issue. Can you reproduce the bug?

**Comment by BatuhanW** [comment]
Hello @Nmaxime could you provide a minimal reproducible example? Would be great

**Comment by Nmaxime** [comment]
Hello @BatuhanW , here is the reproducible example.

https://github.com/Nmaxime/refine-bug-4420

**Comment by BatuhanW** [comment]
Hey @Nmaxime, thanks! We are on it.

**Comment by BatuhanW** [comment]
Hello @Nmaxime, we don't have a solution yet but, problem is when function defined as async, temporarily as a workaround, you can convert pages to sync functions for now.

```
'use client'

import { Create } from '@refinedev/chakra-ui'

export default  function CreatePage() {
    return <Create>test</Create>
}
```

**Comment by Nmaxime** [comment]
Hello @BatuhanW, it works perfectly, thanks!
