### ISSUE TITLE
[BUG] queryOptions on useModalForm doesn't seem to work properly

### ISSUE THREAD

**Issue by vinclou** [refinedev/refine#4422]
## System Info

- [ ] All required packages are up to date.
- [ ] Core and AntD libraries are being used.

### Last week, I migrated from version 3 to version 4.

I encountered a bug related to how ids are handled in your library. Due to the way ids are handled, I had to refactor my usage of the `useModalForm` hook.

Here's the original code:
```tsx
/*
* @description In the following example, only:
* https://localhost:5507/api/directory/Internal/v1/Organizations/180b5f6b-0411-46f1-a217-bf4e93bdb99e
* will be fetched, and https://localhost:5507/api/directory/Internal/v1/Organizations won't ever be called 
*/
const {
    queryResult: orgQueryResult,
    modalProps: updateOrgModalProps,
    formProps: updateOrgFormProps,
    show: showUpdateOrgModal,
    close: closeUpdateOrgModal
} = useModalForm<Organization, HttpError, IOrganizationFormValues>({
    action: 'edit',
    // Notice that 'id' is missing, but it's a part of the resource (query fetched exactly once)
    resource: `directory/Internal/v1/Organizations/${record?.organizationId as string}`,
    redirect: false,
    queryOptions: {
        enabled: Boolean(record?.organizationId)
    },
    onMutationSuccess: () => {
        closeUpdateOrgModal()
    }
})
```

Here's what I'm being forced to refactor with the new version:

```tsx
/*
* @description In the following example, both:
* https://localhost:5507/api/directory/Internal/v1/Organizations/180b5f6b-0411-46f1-a217-bf4e93bdb99e
* will be fetched, and https://localhost:5507/api/directory/Internal/v1/Organizations will also be called.
* The latter could potentially be a query with thousands of records (resulting in a significant performance hit).
*/
const orgId = record?.organizationId || undefined;
const {
    queryResult: orgQueryResult,
    modalProps: updateOrgModalProps,
    formProps: updateOrgFormProps,
    show: showUpdateOrgModal,
    close: closeUpdateOrgModal
} = useModalForm<Organization, HttpError, IOrganizationFormValues>({
    action: 'edit',
    id: orgId, // Notice that now I pass the 'id' as a prop
    resource: `directory/Internal/v1/Organizations`,
    redirect: false,
    syncWithLocation: false,
    queryOptions: {
        enabled: Boolean(orgId)
    },
    onMutationSuccess: () => {
        closeUpdateOrgModal()
    }
})
console.log('orgId:', orgId);
console.log('orgId enabled:', Boolean(orgId));
console.log('orgId orgQueryResult:', orgQueryResult?.data?.data);
```

### Why does this happen?

I am quite certain that this issue occurs because you set the id to an empty string. When the id is empty, the underlying hook used for fetching assumes that it is acceptable to fetch the resource and sends a query to the wrong path. However, once the id is received, the hook realizes it needs to re-render and re-fetch the correct data. In the end, the data turns out to be correct, and the form works as expected.

Unfortunately, there is no way to disable the initial query that is made for an endpoint with a similar name but is not the desired query. Here's an example of what should and should not be triggered:

Desired Query:
- `api/directory/Internal/v1/Organizations/{someId}`

Undesired Query (should not be triggered if id is undefined):
- `api/directory/Internal/v1/Organizations`

### Steps To Reproduce

- [ ] create a useModalForm that depends on an id from other query
- [ ] make sure there are routes for `/posts` and `/posts/{id}`(must be same)
- [ ] observe both /posts and /posts/{id} is called when id is undefined 

### Expected behavior

 - [ ] The query is not enabled when Id is missing

### Screenshot

`Just logs to make sure the enabled can be false:`
![Screenshot 2023-05-30 at 12 07 10 PM](https://github.com/refinedev/refine/assets/54914693/25fc4c16-478c-4c09-8923-306e3cfa3569)

`Screenshots that the query is "duplicated" - wrong query is made if id is undefined`

![Screenshot 2023-05-30 at 12 15 57 PM](https://github.com/refinedev/refine/assets/54914693/b1c919b6-00be-4053-9baf-43f6
![Screenshot 2023-05-30 at 12 16 16 PM](https://github.com/refinedev/refine/assets/54914693/fb21f318-6b63-41db-b70d-e1d301939559)
2c1db800)
![Screenshot 2023-05-30 at 12 16 27 PM](https://github.com/refinedev/refine/assets/54914693/59b94294-f457-48d6-b314-f7f609e84c96)

**Comment by vinclou** [comment]
#### Update

 - After removing queryOptions from the hook definition the extra fetch request is not happening...
 - 💁🏼‍♂️ 
 
```tsx
	const orgId = record?.organizationId || undefined
	const {
		queryResult: orgQueryResult,
		modalProps: updateOrgModalProps,
		formProps: updateOrgFormProps,
		show: showUpdateOrgModal,
		close: closeUpdateOrgModal
	} = useModalForm<Organization, HttpError, IOrganizationFormValues>({
		action: 'edit',
		resource: `directory/Internal/v1/Organizations`,
		id: orgId,
		redirect: false,
		syncWithLocation: false,
		onMutationSuccess: () => {
			closeUpdateOrgModal()
		}
	})
```

**Comment by BatuhanW** [comment]
Hello @vinclou, thanks for the greatly detailed issue! We'll check and get back to you.

**Comment by vinclou** [comment]
> Hello @vinclou, thanks for the greatly detailed issue! We'll check and get back to you.

@BatuhanW Thank you, might be something on my end, after all, had no time to make repro with mocked API
in a sandbox, it was definitely weird that it started working once I removed the explicit query options and made
it implicit handled by the framework

**Comment by BatuhanW** [comment]
Hello @vinclou, we'll groom this issue and add it into the next sprint, stay tuned 👊🏼

**Comment by BatuhanW** [comment]
Hello @vinclou , can you let us know if the previous message helps with your issue? Please let us know if you still have this problem, so we can proceed.

**Comment by vinclou** [comment]
@BatuhanW Np will let u know when I'll be back on the refactor branch (haven't been doing much frontendish work past 2 month) 

I'll close this one out myself if everything is okay 🙏

**Comment by BatuhanW** [comment]
> @BatuhanW Np will let u know when I'll be back on the refactor branch (haven't been doing much frontendish work past 2 month) 
> 
> 
> 
> I'll close this one out myself if everything is okay 🙏

Hey @vinclou feel free to close it and/or re-open as you see fit!
