### ISSUE TITLE
[BUG] goBack prop with SHOW Component is not working as expected. Back button is not coming.

### ISSUE THREAD

**Issue by ammar-yasir** [refinedev/refine#4464]
### Describe the bug

```
<Show
      isLoading={isLoading}
      title={'Dummy Title'}
      goBack={<BackButton />}
      headerButtons={() => <BackButton />}
>
    
```

As you can see in the above code that I have given prop **goBack** but it is not working as expected. It is not showing me the back /previous icon with link. It just shows title and no button prior to it which should not be like this.

**Note:** The URL for this page is **"/crfqs/comparison-analysis/97d0aab2"**. It is not having **show** keyword, I even tried with changed URL as well.
But when I use it on this URL "/crfqs/show/97d0aab2", it shows back button.

Kindly look into this issue and get it fixed as soon as possible.

### Steps To Reproduce

No steps.

### Expected behavior

It should show BACK button with **goBack** prop.

### Screenshot

<img width="1339" alt="Screen Shot 2023-06-06 at 1 56 25 PM" src="https://github.com/refinedev/refine/assets/32488967/9b20ed4c-51d6-4801-982c-644a9a10956a">
<img width="1338" alt="Screen Shot 2023-06-06 at 1 56 37 PM" src="https://github.com/refinedev/refine/assets/32488967/74068a78-cc45-4594-aeb2-9d04354f2299">

### Desktop

OS: Mac
Browser: Chrome

### Mobile

No mobile preview.

**Comment by BatuhanW** [comment]
Hello @ammar-yasir could you provide us a minimal reproducible example?

**Comment by salihozdemir** [comment]
Hey @ammar-yasir,

Internally `<Show>` compoennt uses the `<PageHeader>` component from `@ant-design/pro-layout`. `<PageHeader>` component has a `onBack` property which is a function that is called when the back button is clicked. By default, if your route has no `:action` parameter, the back button will not be shown. You can override this behavior by passing a `headerProps` property to the `<Show>` component like this:

```tsx
import { useBack } from "@refinedev/core";
import { Show } from "@refinedev/antd";

const back = useBack();

<Show headerProps={{ onBack: back }} />;
```

**Comment by BatuhanW** [comment]
Hello @ammar-yasir we've merged a PR making the clarification. Feel free to re-open the issue if your problem still persists.

**Comment by ammar-yasir** [comment]
Thank you so much. It worked like a charm.
