### ISSUE TITLE
[BUG] LiveProvider generates wrong graphql subscription query

### ISSUE THREAD

**Issue by hbtecRJE** [refinedev/refine#4524]
### Describe the bug

When I use the LiveProvider for a graphql subscription from @refinedev/graphql, a query is created starting with "query" instead of "subscription".

Find documentation about subscription here: https://refine.dev/docs/api-reference/core/providers/live-provider/#creating-a-live-provider-with-graphql-subscriptions

The generateUseListSubscription function uses `gql.query` instead of `gql.subscription`.
https://github.com/refinedev/refine/blob/6fdf9c002c55359a7c6fcd7e03b3ca0698a44996/packages/graphql/src/utils/generateUseListSubscription.ts#L42

### Steps To Reproduce

1. create liveProvider of @refinedev/graphql
2. check ws query

### Expected behavior

![image](https://github.com/refinedev/refine/assets/122349054/adb82b93-a558-497a-bcba-5af74612ef93)

**Comment by yildirayunlu** [comment]
Hey @hbtecRJE, We are sorry for this issue. If you want to support us, can you open a PR for this issue? 🙏🏼

**Comment by haszankauna** [comment]
Hello @yildirayunlu Can I please work on this?

**Comment by hbtecRJE** [comment]
@yildirayunlu done, please review.

**Comment by yildirayunlu** [comment]
Hey @hbtecRJE Thank you for your support 🥳 We will review and release it shortly 🚀
