### ISSUE TITLE
[FEAT]In previous versions, if the Table of Contents was empty on an article page, it would be centered.

### ISSUE THREAD

**Issue by linkdao** [refinedev/refine#4532]
### Is your feature request related to a problem? Please describe.

In previous versions, if the Table of Contents was empty on an article page, it would be centered.

### Describe alternatives you've considered

I think that it would be visually more pleasing and comfortable if article pages were centered when the table of contents is disabled or not present.

### Additional context

I'm glad you like the layout of the article page, and I can definitely help you with centering it automatically. There are several ways to achieve this, depending on the structure of your webpage and the CSS styles that you're using.

One easy way is to set the `margin` property of the container element to `auto`. This will center the element horizontally within its parent container. Here's an example CSS rule that you could add to your stylesheet:

```css
.article-container {
  margin: auto;
}
```

In this example, `.article-container` is the class name of the container element that wraps around your article content. You can replace this with the actual class or ID name of your container element.

If you need further assistance with implementing this change, please let me know!

### Describe the thing to improve

i hope can do it's

**Comment by BatuhanW** [comment]
Hello could you elaborate more on what do you mean by `In previous versions` ?
