### ISSUE TITLE
[FEAT] Add an Option To show Which type of crud operation app user want to build?

### ISSUE THREAD

**Issue by Thedineshk24** [refinedev/refine#4542]
### Is your feature request related to a problem? Please describe.

current I've created a one app to try a refine before starting hackathon, it had given me a boiler plate code for admin dashboard. but the project I'm going to build is more user centric so now i've to delete lots of boiler plate code in-order to achieve that.

### Describe the thing to improve

add a template which focuses on user side as well. if you want i can raise a PR which will shows an template of more user side focused web app.

**Comment by Thedineshk24** [comment]
> Hello @Thedineshk24 thanks for the issue, could you elaborate more on this one?

yes @BatuhanW can you please add a template which focuses on user side of project, current template focuses on admin templates.

**Comment by aliemir** [comment]
Hey 👋  @Thedineshk24, thank you for your suggestion 🙏   The current templates are focused on demonstrating the features and the usage of refine. We find that the best way to do is to construct a admin panel like layouts without diving into much of the design and opinionated implementations. Current layout may look focused on admin panels but with the refine's headless approach, you can tweak and customize it however you like. 

In the future, we'll definitely consider providing more starter templates and layouts but for now, we don't have the enough work force to create and maintain them. 🧯 

If you're willing to create starter projects, we'll be more than happy to mention and promote your work in our website if you end up publishing them in GitHub or any other platform available. 🚀 🚀
