### ISSUE TITLE
[BUG] Choose pnpm but still use npm to install dependencies

### ISSUE THREAD

**Issue by TinsFox** [refinedev/refine#4566]
### Describe the bug

I was getting started with the tutorial, and when I got to the part of creating a project, I chose pnpm to execute the command, but I still used npm installation when installing dependencies

### Steps To Reproduce

Just execute the following command

```bash
pnpm create refine-app@latest -- -o refine-chakra-ui tutorial
```

### Expected behavior

Dependencies should be installed using pnpm, not npm

### Screenshot

<img width="1076" alt="image" src="https://github.com/refinedev/refine/assets/33956589/b963b512-97b1-47ce-b6eb-6b214e4f94c0">

<img width="933" alt="image" src="https://github.com/refinedev/refine/assets/33956589/b3a0a7c1-994d-45da-a048-15fe55098e14">

<img width="390" alt="image" src="https://github.com/refinedev/refine/assets/33956589/9b96ac45-47ff-4dd0-89ab-588ccce203a4">

**Comment by BatuhanW** [comment]
Hello @TinsFox from the screenshot, selected option looks like `npm`, not `pnpm`. Are you sure you correctly picked pnpm?

**Comment by TinsFox** [comment]
> Hello @TinsFox from the screenshot, selected option looks like `npm`, not `pnpm`. Are you sure you correctly picked pnpm?

Please see the command executed in the first picture

**Comment by BatuhanW** [comment]
Running the command with pnpm doesn't mean it will use pnpm as package manager. Package manager is the last question, you should pick pnpm there.


![Screenshot 2023-06-21 at 16 15 58](https://github.com/refinedev/refine/assets/16444991/793d991f-10bd-46ac-829e-27512fa9d76b)

**Comment by TinsFox** [comment]
But I think it would be better and less confusing for users.  Otherwise, it doesn't make sense to use any package manager without options.

The command I executed had no options.

This is an area that can be improved, right?  Although it's not that important.

**Comment by TinsFox** [comment]
It's just this performance that confuses me, and I think it can be done better!

**Comment by BatuhanW** [comment]
Hello @TinsFox thanks for the suggestion, we could accept `--package-manager pnpm` param to the CLI, that would be an improvement.

pnpm, npm, yarn, these are all *clients* and it's hard for us to know which client triggered the command and pre pick the command's client. But I'll check if it's possible.

Also feel free to create a PR if you want to work on passing package manager parameter. You should first create a PR against https://github.com/pankod/superplate

refine cli just like a proxy, passing parameters to superplate cli under the hood.
