### ISSUE TITLE
[BUG] List retrieval fails when using Hasura Provider with naming-convention: graphql-default

### ISSUE THREAD

**Issue by IkumaTadokoro** [refinedev/refine#4574]
### Describe the bug

Hasura and Hasura Provider can use either "hasura-default" or "graphql-default" as the naming convention for GraphQL fields.
When using the latter, attempting to retrieve a list will result in a "TypeError: Cannot read properties of undefined (reading 'aggregate')" and data retrieval will fail.

In getList, the total number of data is obtained by `result[aggregateOperation].aggregate.count`, but when using graphql-default, a camelized aggregateOperation is returned in the query when graphql-default is used.
In fact, when I modified the corresponding part of the Hasura Provider through swizzle to `camelizedAggregateOperation`, the data collection worked fine.

### Steps To Reproduce

1. Create a project with the following configuration values.

```bash
❯ npm create refine-app@latest
✔ Downloaded remote source successfully.
✔ Choose a project template · refine-vite
✔ What would you like to name your project?: · metal-goats-flash
✔ Choose your backend service to connect: · data-provider-hasura
✔ Do you want to use a UI Framework?: · mui
✔ Do you want to add example pages?: · no
✔ Do you need any Authentication logic?: · none
✔ Do you need i18n (Internationalization) support?: · no
✔ Choose a package manager: · npm
```

2. Add namingConvention settings to Hasura Provider(src/App.tsx).

```diff
  <Refine
-    dataProvider={dataProvider(client)}
+    dataProvider={dataProvider(client, { namingConvention: "graphql-default" })} 
```

3. Create a Hasura project for testing and set naming-convention to graphql-default according to the [documentation](https://hasura.io/docs/latest/schema/postgres/naming-convention/).
4. Add an appropriate resource for the list and generate the list display page with inferencer.
5. The above-mentioned bug occurs during data acquisition.

### Expected behavior

Correct list acquisition even if naming-convention is graphql-default.

### Desktop

- version: 
  - "@refinedev/cli": "^2.5.1"
  - "@refinedev/core": "^4.5.8"
  - "@refinedev/hasura": "^6.0.0"
  - "@refinedev/inferencer": "^4.0.0"
- Used dataProvider: Hasura

### Additional Context

Looking at the source, it seems to me that the same cause also occurs with other APIs (getOne, createMany, update.... ...etc.), I think it also happens with other APIs (getOne, createMany, update...etc.).

**Comment by BatuhanW** [comment]
Hello @IkumaTadokoro thanks for the report! Would you like to create a PR and make a contribution?

**Comment by IkumaTadokoro** [comment]
@BatuhanW 
Thanks for reply! Could you please review the PR I created?
https://github.com/refinedev/refine/pull/4584
