### ISSUE TITLE
[BUG] Inferencer not working as expected

### ISSUE THREAD

**Issue by merabtenei** [refinedev/refine#4575]
### Describe the bug

The inferencer with a custom rest-api produces an exception

### Steps To Reproduce

Using the tutorial code with a different rest-api having these two endpoints:
```
// /api/users
[
		{
			"date_joined": "2023-06-15T15:48:25",
			"email": "aaaa@aaaa.com",
			"first_name": "aaaaa",
			"groups": [
				{
					"id": 1,
					"name": "Group 2",
					"permissions": [],
					"resource_uri": "/api/v1/groups/1"
				},
				{
					"id": 4,
					"name": "Group 9",
					"permissions": [],
					"resource_uri": "/api/v1/groups/4"
				}
			],
			"id": 1,
			"is_active": true,
			"is_staff": true,
			"is_superuser": true,
			"last_login": null,
			"last_name": "bbbb",
			"resource_uri": "/api/v1/users/1",
			"user_permissions": [],
			"username": "admin"
		}
	]
```
```
// /api/groups
[
		{
			"id": 3,
			"name": "Group 8",
			"permissions": [],
			"resource_uri": "/api/v1/groups/3"
		},
		{
			"id": 5,
			"name": "Group 12345",
			"permissions": [],
			"resource_uri": "/api/v1/groups/5"
		},
		{
			"id": 2,
			"name": "Changed from Refine",
			"permissions": [],
			"resource_uri": "/api/v1/groups/2"
		},
		{
			"id": 1,
			"name": "Group 2",
			"permissions": [],
			"resource_uri": "/api/v1/groups/1"
		},
		{
			"id": 4,
			"name": "Group 9",
			"permissions": [],
			"resource_uri": "/api/v1/groups/4"
		}
]
```
**Listing groups works fine but Listing users produces this Exception: **
```
Unhandled Runtime Error
ReferenceError: groupsIsLoading is not defined
```
After checking the Chrome devtools I notice the app tries to perform some unexpected fetch requests like :

- /api/first_names/aaaaa (why would refine try to get this as it's not a relation)
- /api/last_names/bbbb (same here)
- api/groups?id=Group%202 (This should use the value of "id" field not the "name" field !)
- ...

### Expected behavior

In this case List Inferencer should display the list of users.

### Screenshot

![ssrefine](https://github.com/refinedev/refine/assets/95150308/4e84dfac-aadd-4665-94e8-11e07976720d)

### Additional Context

Generated code with inferencer :
```typescript
import React from "react";
import {
    IResourceComponentsProps,
    BaseRecord,
    useTranslate,
} from "@refinedev/core";
import {
    useTable,
    List,
    EditButton,
    ShowButton,
    DeleteButton,
    DateField,
    TagField,
    EmailField,
    BooleanField,
} from "@refinedev/antd";
import { Table, Space } from "antd";

export const UserList: React.FC<IResourceComponentsProps> = () => {
    const translate = useTranslate();
    const { tableProps } = useTable({
        syncWithLocation: true,
    });

    return (
        <List>
            <Table {...tableProps} rowKey="id">
                <Table.Column
                    dataIndex={["date_joined"]}
                    title={translate("users.fields.date_joined")}
                    render={(value: any) => <DateField value={value} />}
                />
                <Table.Column
                    dataIndex={["email"]}
                    title={translate("users.fields.email")}
                    render={(value: any) => <EmailField value={value} />}
                />
                <Table.Column
                    dataIndex="first_name"
                    title={translate("users.fields.first_name")}
                />
                <Table.Column
                    dataIndex="groups"
                    title={translate("users.fields.groups")}
                    render={(value: any[]) =>
                        groupsIsLoading ? (
                            <>Loading...</>
                        ) : (
                            <>
                                {value?.map((item, index) => (
                                    <TagField key={index} value={item} />
                                ))}
                            </>
                        )
                    }
                />
                <Table.Column
                    dataIndex="id"
                    title={translate("users.fields.id")}
                />
                <Table.Column
                    dataIndex={["is_active"]}
                    title={translate("users.fields.is_active")}
                    render={(value: any) => <BooleanField value={value} />}
                />
                <Table.Column
                    dataIndex={["is_staff"]}
                    title={translate("users.fields.is_staff")}
                    render={(value: any) => <BooleanField value={value} />}
                />
                <Table.Column
                    dataIndex={["is_superuser"]}
                    title={translate("users.fields.is_superuser")}
                    render={(value: any) => <BooleanField value={value} />}
                />
                <Table.Column
                    dataIndex="last_name"
                    title={translate("users.fields.last_name")}
                />
                <Table.Column
                    dataIndex="resource_uri"
                    title={translate("users.fields.resource_uri")}
                />

                <Table.Column
                    dataIndex="username"
                    title={translate("users.fields.username")}
                />
                <Table.Column
                    title={translate("table.actions")}
                    dataIndex="actions"
                    render={(_, record: BaseRecord) => (
                        <Space>
                            <EditButton
                                hideText
                                size="small"
                                recordItemId={record.id}
                            />
                            <ShowButton
                                hideText
                                size="small"
                                recordItemId={record.id}
                            />
                            <DeleteButton
                                hideText
                                size="small"
                                recordItemId={record.id}
                            />
                        </Space>
                    )}
                />
            </Table>
        </List>
    );
};
```

**Comment by divyansh7924** [comment]
I am still facing the issue, is this fix rolled out yet?
`{
  "name": "oreo-admin",
  "version": "0.1.0",
  "private": true,
  "type": "module",
  "dependencies": {
    "@emotion/react": "^11.8.2",
    "@emotion/styled": "^11.8.1",
    "@mui/icons-material": "^5.8.3",
    "@mui/lab": "^5.0.0-alpha.85",
    "@mui/material": "^5.8.6",
    "@mui/x-data-grid": "^6.6.0",
    "@refinedev/cli": "^2.7.2",
    "@refinedev/core": "^4.26.2",
    "@refinedev/inferencer": "^4.3.0",
    "@refinedev/kbar": "^1.1.0",
    "@refinedev/mui": "^5.7.0",
    "@refinedev/nestjsx-crud": "^4.3.4",
    "@refinedev/react-hook-form": "^4.1.2",
    "@refinedev/react-router-v6": "^4.1.0",
    "axios": "^0.26.1",
    "i18next": "^20.1.0",
    "i18next-browser-languagedetector": "^6.1.1",
    "i18next-xhr-backend": "^3.2.2",
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "react-hook-form": "^7.30.0",
    "react-i18next": "^11.8.11",
    "react-router-dom": "^6.8.1"
  },
  "devDependencies": {
    "@types/node": "^18.16.2",
    "@types/react": "^18.0.0",
    "@types/react-dom": "^18.0.0",
    "@typescript-eslint/eslint-plugin": "^5.57.1",
    "@typescript-eslint/parser": "^5.57.1",
    "@vitejs/plugin-react": "^4.0.0",
    "eslint": "^8.38.0",
    "eslint-plugin-react-hooks": "^4.6.0",
    "eslint-plugin-react-refresh": "^0.3.4",
    "typescript": "^4.7.4",
    "vite": "^4.3.1"
  },
  "scripts": {
    "dev": "refine dev",
    "build": "tsc && refine build",
    "preview": "refine start",
    "refine": "refine"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
`
<img width="1439" alt="Screenshot 2023-07-05 at 2 38 27 PM" src="https://github.com/refinedev/refine/assets/36097299/1d307e5d-b69a-474b-bf27-0a12e570ccc0">


inference generated code
`import {
    useShow,
    IResourceComponentsProps,
    useTranslate,
} from "@refinedev/core";
import {
    Show,
    TextFieldComponent as TextField,
    MarkdownField,
    DateField,
} from "@refinedev/mui";
import { Typography, Stack } from "@mui/material";

export const BlogPostShow: React.FC<IResourceComponentsProps> = () => {
    const translate = useTranslate();
    const { queryResult } = useShow();
    const { data, isLoading } = queryResult;

    const record = data?.data;

    return (
        <Show isLoading={isLoading}>
            <Stack gap={1}>
                <Typography variant="body1" fontWeight="bold">
                    {translate("blog_posts.fields.id")}
                </Typography>
                <TextField value={record?.id} />
                <Typography variant="body1" fontWeight="bold">
                    {translate("blog_posts.fields.title")}
                </Typography>
                <TextField value={record?.title} />
                <Typography variant="body1" fontWeight="bold">
                    {translate("blog_posts.fields.content")}
                </Typography>
                <MarkdownField value={record?.content} />
                <Typography variant="body1" fontWeight="bold">
                    {translate("blog_posts.fields.status")}
                </Typography>
                <TextField value={record?.status} />
                <Typography variant="body1" fontWeight="bold">
                    {translate("blog_posts.fields.createdAt")}
                </Typography>
                <DateField value={record?.createdAt} />
                <Typography variant="body1" fontWeight="bold">
                    {translate("blog_posts.fields.updatedAt")}
                </Typography>
                <DateField value={record?.updatedAt} />
                <Typography variant="body1" fontWeight="bold">
                    {translate("blog_posts.fields.category")}
                </Typography>

                {categoryIsLoading ? (
                    <>Loading...</>
                ) : (
                    <>{categoryData?.data?.id}</>
                )}
            </Stack>
        </Show>
    );
};
`

**Comment by divyansh7924** [comment]
Can be replicated here as well
https://refine.new/preview/4c23df03-c08d-45d6-b07d-e69cc85c4297

**Comment by PranavRangate** [comment]
Hi, I’m Pranav Rangate. I’d like to work on this issue—please assign it to me. Thanks!
