### ISSUE TITLE
[BUG] Duplicated requests

### ISSUE THREAD

**Issue by Mikilll94** [refinedev/refine#4603]
### Describe the bug

I have noticed that Refine makes many unnecessary requests which affects performance.

![image](https://github.com/refinedev/refine/assets/17653648/150b6d1a-4c97-4182-8ab7-52efc9648b2d)

You can see on the screenshot above that `blog_posts` was requested twice and `categories` were requested 3 times.

### Steps To Reproduce

1. Create a new project using `create-refine-app`.
2. Select Supabase as a data provider.
3. Answer "Y" for "Add example pages".
4. Open devtools.
5. Log in.
6. You can see duplicated requests in the dev tools.
7. Clear the devtools and reload the page.
8. You can see duplicated requests again.

### Expected behavior

There should be no unnecessary requests.

### Desktop

- Windows 10
- @refinedev/core 4.5.8

**Comment by BatuhanW** [comment]
Hello @Mikilll94, welcome back!

Does that happens on production environment? On development environment, it's expected, please see the related FAQ here: https://refine.dev/docs/faq/#why-are-api-calls-triggering-twice

**Comment by BatuhanW** [comment]
Closing the issue for now, feel free to re-open it if your problem persists.
