### ISSUE TITLE
[BUG] RefreshButton does not refresh content

### ISSUE THREAD

**Issue by code-282** [refinedev/refine#4618]
### Describe the bug

When using the default RefreshButton provider by <Show> component, the API is called and the new content is fetched. However, the content on UI remains the same and does not refresh.

### Steps To Reproduce

1. Created custom CRUD Rest API
2. Created basic refine project and use custom API as data provider
3. Click on "show" for any record
4. Change data in database or on API level
5. Click on "Refresh Button"
6. Check network or react-query logs, the new data is fetched but UI content is not updated

### Expected behavior

The UI data should be refreshed based on the latest data fetched from API

**Comment by aliemir** [comment]
Hey @code-282, sorry for the issue! We'll be checking it soon.
