### ISSUE TITLE
[BUG] How to send headers in api request?

### ISSUE THREAD

**Issue by SnpGroup1** [refinedev/refine#4622]
### Describe the bug

I am using Vite & Material UI package for my admin panel.

I have to send token in headers in API request. 

I tried using useOne & useCustom but did not work.

Please guide me, as my development got stuck due to this.

### Steps To Reproduce

1. use useOne in App.tsx
2. use useCustom in App.tsx

### Expected behavior

with useOne application stops working

  useOne({
    meta: {
      headers: { token: localStorage.getItem('token') }
    }
  });

useCustom is giving syntax error

  useCustom({
    config: {
      headers: {
        token: localStorage.getItem('token')
      },
    },
  });

### Desktop

- Device: Laptop
- OS: Windows
- Browser: Chrome
- Version: Latest

**Comment by dipbazz** [comment]
Hey @SnpGroup1, which data provider are you using? If you are using [simple rest](https://refine.dev/docs/packages/documentation/data-providers/simple-rest/) then you can have a reference of [setting Authorization Credentials](https://refine.dev/docs/tutorial/understanding-authprovider/create-authprovider/#setting-authorization-credentials) when the user login to your app. 

Are you trying to send this token on every request or just for some specific request?

**Comment by SnpGroup1** [comment]
yes, I am using simple rest.

yes, I have to send token on every request.

Are you talking about creating axiosInstance and link it with dataProvider?

**For example:**
import axios from "axios";
const axiosInstance = axios.create();

// This sets the authorization headers on Axios instance
axiosInstance.defaults.headers.common = {
    Authorization: `Bearer ${user.token}`,
};

dataProvider={dataProvider(API_URL, axiosInstance)}

**Comment by dipbazz** [comment]
Hey @SnpGroup1, yes I am suggesting you to use axios and create an axios instance and pass the authorization token when user login, Same as in this example [setting authorization credentials](https://refine.dev/docs/tutorial/understanding-authprovider/create-authprovider/#setting-authorization-credentials)

**Comment by aliemir** [comment]
Hey @SnpGroup1, check out the docs @dipbazz has shared for solution 🙏 You can either set default values for the axios instance or if your case has some dynamic needs; using interceptors might do the trick.

**Comment by ghbishal** [comment]
hello @dipbazz  i am getting the same issue i am using 
https://github.com/MahirMahdi/refine-jsonapi
as my data provider and i need to pass bearer token in every request how can i do it?

**Comment by BatuhanW** [comment]
Hello @ghbishal, this library has optional 2nd argument, which is axiosInstance. You can create your own axiosInstance with authorization header set, and pass it to this data provider.
