### ISSUE TITLE
[DOC] MUI change default font family example not working

### ISSUE THREAD

**Issue by pentolbakso** [refinedev/refine#4631]
### Documentation issue

MUI Theme overriding for typography is not working. fontFamily is not changing

https://refine.dev/docs/api-reference/mui/theming/#overriding-variables

### Describe the thing to improve

For typography override, we need to recreate the theme using `createTheme`

```typescript
const typographyOptions: TypographyVariantsOptions = {
  fontFamily: [
    "Montserrat",
    "-apple-system",
    "BlinkMacSystemFont",
    '"Segoe UI"',
    "Roboto",
    '"Helvetica Neue"',
    "Arial",
    "sans-serif",
    '"Apple Color Emoji"',
    '"Segoe UI Emoji"',
    '"Segoe UI Symbol"',
  ].join(","),
};

const overridedLightTheme = createTheme({
  palette: RefineThemes.Blue.palette,
  typography: {
    ...typographyOptions,
  },
});
```

**Comment by aliemir** [comment]
Hey @pentolbakso, thank you for reporting this and for providing the correct way! Do you want to send a PR for the changes? We'll be happy to see your contribution 🙏 🚀

**Comment by alicanerdurmaz** [comment]
@pentolbakso Thank you for helping us 🚀 We updated our documentation  🙌
