### ISSUE TITLE
[BUG] Can't resolve antd dependencies

### ISSUE THREAD

**Issue by bombillazo** [refinedev/refine#4638]
### Describe the bug

I am getting the following errors when using refine with antd:

```sh
- wait compiling /[...catchAll] (client and server)...
- error ./node_modules/@refinedev/antd/dist/esm/index.js:1:17980
Module not found: Can't resolve 'antd/es/ConfigProvider'
```

### Steps To Reproduce

Run Refine app and import an AntD package in any page.

### Expected behavior

App builds without issues.

### Screenshot

![image](https://github.com/refinedev/refine/assets/44002321/0121d998-fee9-4d43-a8ac-acb033a70374)

### Desktop

"@refinedev/antd": "^5.28.0",
"@refinedev/cli": "^2.7.2",
"@refinedev/core": "^4.26.4",

**Comment by bombillazo** [comment]
Seems this is the possible cause: https://github.com/ant-design/ant-design/issues/43362

**Comment by aliemir** [comment]
We'll be watching the progress on this issue on both ant design and next.js side. For now, the issue is not related with refine and we'll re-open if the solutions have any side effects on our codebase. 🙏
