### ISSUE TITLE
[BUG] Antd table filtering with pagination.mode=client and filters.mode=off doesn't rebuild pagination

### ISSUE THREAD

**Issue by wxkk** [refinedev/refine#4646]
### Describe the bug

Starting with the [table-antd-table-filter](https://codesandbox.io/p/sandbox/github/refinedev/refine/tree/next/examples/table-antd-table-filter?embed=1&file=%2Fsrc%2Fpages%2Fposts%2Flist.tsx%3A45%2C9-45%2C17) example, I removed the `onSearch` and `<Filter />` part, added `pagination.mode="client"` and `filters.mode="off"` to `useTable`. Also added `filters={...}` and `onFilter{...}` to the status `<Table.Column />`. The filter works, you can select for example "Draft" and it will show only the draft posts, but the pages doesn't contain the X/page rows, the amount of rows is  the draft posts that were originally on each page.

### Steps To Reproduce

1. Go to [codesanbox example](https://codesandbox.io/p/sandbox/gifted-rui-8hygc6?embed=1&file=%2Fsrc%2Fpages%2Fposts%2Flist.tsx%3A70%2C13-70%2C26)
2. Click the filter icon on the Status column
3. Click one checkbox and click ok
4. Notice how the amount of rows on each page decreases to just the amount of matches the filter has

### Expected behavior

Pagination should be rebuilt/recalculated when filtering on client side.

**Comment by BatuhanW** [comment]
Hey @wxkk thanks for the report, we'll check it soon.

**Comment by alicanerdurmaz** [comment]
Hello @wxkk, I updated [your example ](https://codesandbox.io/p/sandbox/dazzling-thompson-zjy8v8?embed=1&file=/src/pages/posts/list.tsx:67,30)

This will completely cancel the refine's pagination logic and leave it to ant design, giving you full control over the pagination and filter.

changes:
```tsx
pagination: {
      mode: "off",
}

<Table {...tableProps} pagination={undefined} rowKey="id">
```
