### ISSUE TITLE
[BUG] Fresh project -- app-icon component cause build error, antd causes runtime error (remix, antd, rest, google)

### ISSUE THREAD

**Issue by ansley257** [refinedev/refine#4651]
### Describe the bug

1. Using either refine.new or the create-refine-app, without modifying any code, the new project created has the following runtime error in the browser, with a few additional errors in the browser console, which are attached:

`TypeError: Cannot read properties of null (reading 'firstChild')
    at injectCSS (http://localhost:3000/build/_shared/chunk-DOI7WL5K.js:14967:30)
    at syncRealContainer (http://localhost:3000/build/_shared/chunk-DOI7WL5K.js:15002:28)
    at updateCSS (http://localhost:3000/build/_shared/chunk-DOI7WL5K.js:15011:3)
    at http://localhost:3000/build/_shared/chunk-DOI7WL5K.js:15919:22
    at http://localhost:3000/build/_shared/chunk-DOI7WL5K.js:15217:67
    at http://localhost:3000/build/_shared/chunk-DOI7WL5K.js:15160:5
    at commitHookEffectListMount (http://localhost:3000/build/_shared/chunk-GY5AQWTY.js:16904:34)
    at commitMutationEffectsOnFiber (http://localhost:3000/build/_shared/chunk-GY5AQWTY.js:17700:19)
    at recursivelyTraverseMutationEffects (http://localhost:3000/build/_shared/chunk-GY5AQWTY.js:17681:15)
    at commitMutationEffectsOnFiber (http://localhost:3000/build/_shared/chunk-GY5AQWTY.js:17695:15)`

2. Using refine.new or adding example pages to create-refine-app, creates the 'app-icon' component, which uses 'fill-rule' and 'clip-rule', instead of the React versions of these properties 'fillRule' and 'clipRule'. Upon modifying these, however, the project builds properly (but still has the above runtime error).

### Steps To Reproduce

1. create a refine project with create-refine-app or refine.new (both have the same problem), with the following settings
`~/refine % npm create refine-app@latest
Need to install the following packages:
  create-refine-app@1.11.0
Ok to proceed? (y) y
✔ Downloaded remote source successfully.
✔ Choose a project template · refine-remix
✔ What would you like to name your project?: · refine-template
✔ Choose your backend service to connect: · data-provider-custom-json-rest
✔ Do you want to use a UI Framework?: · antd
✔ Do you want to add example pages?: · no
✔ Do you need any Authentication logic?: · auth-provider-google
✔ Choose a package manager: · yarn`
Note, at this point, I'm already getting warnings about deprecations and peer dependency issues (below), but no outright errors. 
`warning @refinedev/cli > jscodeshift > micromatch > snapdragon > source-map-reso
lve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
warning @refinedev/cli > jscodeshift > micromatch > snapdragon > source-map-reso
warning @refinedev/cli > jscodeshift > micromatch > snapdragon > source-map-reso
lve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
warning @refinedev/cli > jscodeshift > micromatch > snapdragon > source-map-reso
lve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
warning @refinedev/cli > jscodeshift > micromatch > snapdragon > source-map-reso
lve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning @refinedev/cli > jscodeshift > micromatch > snapdragon > source-map-reso
lve > source-map-url@0.4.1: See https://github.com/lydell/source-map-url#depreca
ted
warning @remix-run/dev > cacache > @npmcli/move-file@1.1.2: This functionality h
as been moved to @npmcli/fs
warning "@refinedev/cli > jscodeshift@0.13.1" has unmet peer dependency "@babel/
preset-env@^7.1.6".
warning "@refinedev/cli > ink-markdown > marked-terminal@4.2.0" has incorrect pe
er dependency "marked@^1.0.0 || ^2.0.0".
warning "@refinedev/cli > ink > react-reconciler@0.26.2" has incorrect peer depe
`
2. cd refine-template
3. yarn dev
4. Open either localhost or the assigned IP at port 3000. It may start to render the page, but almost immediately throws a type error on whatever is calling 'firstChild'.

### Expected behavior

The app should run the out of the box program without any errors. 

### Screenshot

<img width="682" alt="image" src="https://github.com/refinedev/refine/assets/54201747/3943e75f-8b58-475e-af82-7faa900a64d8">

<img width="677" alt="image" src="https://github.com/refinedev/refine/assets/54201747/d1c301ad-87ba-4b00-94e3-f925c8d7db6a">

### Desktop

- OS: macOS Ventura 13.4
- Browser: chrome
- Version: 114.0.5735.133 (Official Build) (arm64)
- Used data provider: Rest API

### Additional Context

I did a bit of digging and the problem looks like it starts in rc-util/es/DOM/dynamicCSS.js (antd dependency) in the getContainer(options) function, where there may be a race condition. If you log out options and document, both are defined, but document.body and document.querySelector('head') are both undefined. 

`function getContainer(option) {
  console.log('getContainer option', option)
  if (option.attachTo) {
    return option.attachTo;
  }
  var head = document.querySelector('head');
  console.log('getContainer head', head)
  console.log('getContainer document.body', document.body)
  console.log('document', document)
  return head || document.body;
}`

double returns:  
<img width="675" alt="image" src="https://github.com/refinedev/refine/assets/54201747/9c1e7683-b2a5-4b63-b512-8481f28b6c38">

I can also bring this up to antd's issue board, if this is better suited there, but I'm hoping this is a matter of getting something to load inside a useEffect. 

P.S.
There looks like there's a known issue with rc-util and antd ([see here](https://github.com/react-component/util/pull/114)) that had been resolved with a versions of rc-util from 2020. It's very similar issue, but dealt with a getContainer function that was returning null somewhere else. I did a quick double check, and everything is running on latest right now (antd@5.6.4 and rc-util@5.34.1). There was also an [antd issue](https://github.com/ant-design/ant-design/issues/169) on it like 8 years ago, but the solution didn't seem to help.

**Comment by BatuhanW** [comment]
Hello @ansley257 thanks for the report! We'll check it and get back to you soon.

**Comment by yildirayunlu** [comment]
Hey @ansley257 

When these choices were made, I could not reproduce the same problem. The problem is caused by dependencies and may be resolved. 

Please let us know if the problem persists 🚀
