### ISSUE TITLE
[BUG] When using custom resources in useTable (antd), Table does not update even though item deleted.

### ISSUE THREAD

**Issue by vnStrawHat** [refinedev/refine#4655]
### Describe the bug

our backend API follow this design:
List posts: GET categories/1/posts
Create posts: POST categories/1/posts
Edit posts: PUT posts/id
delete posts: DELETE posts/id

After chang resource in useTable to categories/1/posts, Edit, Create, Show work normal but Delete don't work as expected.
The deleted item is still displayed in the table.

### Steps To Reproduce

Example: https://codesandbox.io/p/sandbox/charming-frog-qjnlq8

1. Change resource of useTable in Posts/list.tsx. from "posts" to "categories/1/posts"
2. Add Delete button: <DeleteButton hideText size="small" recordItemId={record.id} />
3. delete item in table
4. we will see success notification, but table do not update. The deleted item still display in the table
5. item was actually deleted

### Expected behavior

Deleted item must be remove from the table

**Comment by BatuhanW** [comment]
Hello @vnStrawHat can you provide us a minimal reproducible example?

**Comment by vnStrawHat** [comment]
this is example: https://codesandbox.io/p/sandbox/charming-frog-qjnlq8

Try to use delete button, you will see successful notification but the record still in the table

**Comment by yildirayunlu** [comment]
Hey @vnStrawHat 

The deletion is successful, but `invalid` does not work correctly because the `resources` are different.

Invalidate Resource: `posts`
Correct Resource: `categories/1/posts`

```
import { useInvalidate } from "@refinedev/core";

const invalidate = useInvalidate();

// ...

<DeleteButton
  // invalidate resource
  onSuccess={() => {
    invalidate({
      resource: "categories/1/posts",
      invalidates: ["list"],
    });
  }}
  hideText
  size="small"
  recordItemId={record.id}
/>
```

**Comment by vnStrawHat** [comment]
Hi @yildirayunlu
with small custom in the data provider, now I can use resource eq "posts" in useTable.
your suggestion can also solve this issue.

Thank you @yildirayunlu,
