### ISSUE TITLE
[FEAT] Adding option to make sidebar fixed

### ISSUE THREAD

**Issue by Jrgsto** [refinedev/refine#4667]
### Is your feature request related to a problem? Please describe.

Currently I can only "swizzle" the sidebar to fully customize it. I would like to have an option to pass down a property that lets me define if the menu items in the sidebar should be fixed or not.

I have a workaround that only allows me to have the desired functionallity on non collapsed menu:
<img width="920" alt="image" src="https://github.com/refinedev/refine/assets/53819309/b6941b12-f929-47fe-b37a-5948ec5a7681">

### Describe alternatives you've considered

It would be great if you allow to pass down a prop "fixed" to the Sidebar that can then influences the behaviour of the renderMenu function within the Side component from "@refinedev/antd";

### Describe the thing to improve

I can not add a fixed property to the menu items so that they will be fixed on the left hand side. I would like to be able to pass either a property down "fixed" to the sider with the following options and consequences:
fixed={true}
--> Menu items are fixed on the left hand side
--> I have a flow scroll on the left hand side, in case menu items are in number higher than the screen can fit in

In case you wont be able to do it due to time constraint, happy to contribute.

**Comment by omeraplak** [comment]
Hey @Jrgsto ,
The `ThemedSiderV2` component already has a `fixed` property. You can find more details here https://refine.dev/docs/api-reference/antd/components/antd-themed-layout/#sider-props

**Comment by Pedroalexandrelopes** [comment]
@omeraplak that prop doesn't seem to be available on `ThemedSiderV2 ` from `@refinedev/mui`. Is there any option to use?
