### ISSUE TITLE
[BUG] View Inferencer not rendering details

### ISSUE THREAD

**Issue by divyansh7924** [refinedev/refine#4679]
### Describe the bug

View Item Inferencer throws the error categoryIsLoading isn't defined on a preview app created using refine.new.
Settings:
1. Material UI, also on Chakra UI
2. NestJSX Cruds
3. Vite JS

### Steps To Reproduce

1. Go to https://refine.new/preview/4c23df03-c08d-45d6-b07d-e69cc85c4297
2. Click on the view icon on any row in `Blog Posts`

Error
An error occured while rendering the generated component.You can check the generated code from the below "Show Code" button and fix the error manually.

If you think this is a bug, please report the issue at https://github.com/refinedev/refine/issues

Exception:

ReferenceError: categoryIsLoading is not defined

### Expected behavior

Details should render by View inferencer

### Screenshot

![Screenshot 2023-07-18 at 9 40 30 AM](https://github.com/refinedev/refine/assets/36097299/2ecb4ab1-7a43-4997-9b32-d17189b42a26)

### Additional Context

I have tried the setup on local as well, after upgrading to the latest version of refine it still appears.

**Comment by divyansh7924** [comment]
Reported here as well before
https://github.com/refinedev/refine/issues/4575#issuecomment-1621345887

**Comment by yildirayunlu** [comment]
Hey @divyansh7924 

Thank you for reporting this issue. We will fix this in the next release.
