### ISSUE TITLE
[BUG] Can't resolve '@ant-design/icons/lib/icons/createFromIconfontCN' - Pro Layout

### ISSUE THREAD

**Issue by Avatarchik** [refinedev/refine#4690]
### Describe the bug

create project https://refine.new/
project https://refine.new/api/.refine/d/mqPo7c22Bxv2LfZ
React Platform
Next.js

UI Framework
Ant Design

Backend
Strapi

Authentication
Strapi

./node_modules/@ant-design/pro-layout/es/components/SiderMenu/BaseMenu.js:7:0
Module not found: Can't resolve '@ant-design/icons/lib/icons/createFromIconfontCN'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./node_modules/@ant-design/pro-layout/es/components/TopNavHeader/index.js
./node_modules/@ant-design/pro-layout/es/index.js
./node_modules/@refinedev/antd/dist/esm/index.js
./pages/_app.tsx

and not work dark theme

### Steps To Reproduce

create project https://refine.new/

React Platform
Next.js

UI Framework
Ant Design

Backend
Strapi

Authentication
Strapi

### Expected behavior

work project

**Comment by omeraplak** [comment]
Hey @Avatarchik,
Yes, we're confirming this issue. I believe it's related to the @ant-design/pro-layout dependency.

**Comment by denisprado** [comment]
I got the same error when I upgraded the Next from version 13.4.6 to 13.4.12.

**Comment by alicanerdurmaz** [comment]
@denisprado @Avatarchik Thanks for the issue. 

We found the problem and we release the fix. 
When you remove `transpilePackages` from `next.config.js` the problem will be solved.

```diff
const { i18n } = require("./next-i18next.config");

module.exports = {
  i18n,
  experimental: {
    newNextLinkBehavior: true,
  },
-  transpilePackages: [
-    "@refinedev/antd",
-    "@refinedev/inferencer",
-    "antd",
-    "@ant-design/pro-components",
-    "@ant-design/pro-layout",
-    "@ant-design/pro-utils",
-    "@ant-design/pro-provider",
-    "rc-pagination",
-    "rc-picker",
-  ],
};
```
