### ISSUE TITLE
[FEAT] Support Yarn 2 (specifically Plug n Play)

### ISSUE THREAD

**Issue by s1anden** [refinedev/refine#4698]
### Is your feature request related to a problem? Please describe.

I see in the documentation that currently only Yarn 1 is supported by Refine:

![Screenshot 2023-07-21 at 12 56 03 PM](https://github.com/refinedev/refine/assets/3629052/8edfc254-7674-4a22-b2db-f2a57d441d4e)

I tested this a bit myself, and was in fact able to get a Refine project to run using Yarn Modern, but where it breaks down is in attempting to use the Plug 'n' Play. Specifically the first issue is [here](https://github.com/refinedev/refine/blob/next/packages/cli/src/commands/runner/projectScripts.ts), where various `.bin/` scripts that aren't listed as dependencies of the project are imported.

Are there any plans on the roadmap to add support for PNP?

### Describe the thing to improve

I'd like to be able to use Refine in a project that's using yarn Plug n Play!

**Comment by BatuhanW** [comment]
Hello @s1anden unfortunately, I don't have enough context atm, but would like to do some research and get back to you in couple of days. In the meantime, if you would like to contribute, feel free to do it! We are more than happy to assist you in the process.

**Comment by aliemir** [comment]
@achalagarwal, what's the error you're facing here? Can you give a bit more context about the problems you're having? I'm not sure if this related with the plug-n-play feature of yarn v2 or not 🤔

**Comment by achalagarwal** [comment]
Seems to be an issue with resolving the `.bin` dependency. Maybe I have to `yarn dlx patch:add pathToRefineBin`. Don't know. Will continue using npm for now

Error: @refinedev/cli tried to access .bin, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: .bin (via ".bin/vite")

---

Traces:

/home/B/A/.pnp.cjs:28668
      Error.captureStackTrace(firstError);
            ^

Error: @refinedev/cli tried to access .bin, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: .bin (via ".bin/vite")
Required by: @refinedev/cli@npm:2.16.16 (via /home/B/A/.yarn/cache/@refinedev-cli-npm-2.16.16-6fa370b561-afaaa2ab71.zip/node_modules/@refinedev/cli/dist/)

Require stack:
- /home/B/A/.yarn/cache/@refinedev-cli-npm-2.16.16-6fa370b561-afaaa2ab71.zip/node_modules/@refinedev/cli/dist/cli.js
    at require$$0.Module._resolveFilename (/home/B/A/.pnp.cjs:28668:13)
    at Function.resolve (node:internal/modules/cjs/helpers:127:19)
    at Object.getBin (/home/B/A/.yarn/cache/@refinedev-cli-npm-2.16.16-6fa370b561-afaaa2ab71.zip/node_modules/@refinedev/cli/dist/cli.js:4:953)
    at Command.mo (/home/B/A/.yarn/cache/@refinedev-cli-npm-2.16.16-6fa370b561-afaaa2ab71.zip/node_modules/@refinedev/cli/dist/cli.js:17:1347)
    at Command.listener [as _actionHandler] (/home/B/A/.yarn/cache/commander-npm-9.4.1-9deffb2749-bfb18e325a.zip/node_modules/commander/lib/command.js:482:17)
    at /home/B/A/.yarn/cache/commander-npm-9.4.1-9deffb2749-bfb18e325a.zip/node_modules/commander/lib/command.js:1264:65
    at /home/B/A/.yarn/cache/commander-npm-9.4.1-9deffb2749-bfb18e325a.zip/node_modules/commander/lib/command.js:1155:33
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by BatuhanW** [comment]
Hello @achalagarwal thanks for the inspection! Would you like to work on this issue with your findings?

**Comment by achalagarwal** [comment]
Had I known the solution, I would have pushed a fix 😔
