### ISSUE TITLE
[DOC] Wrong symbol used in the date picker doc

### ISSUE THREAD

**Issue by Manice18** [refinedev/refine#4702]
### Documentation issue

![image](https://github.com/refinedev/refine/assets/91601706/ca9105a9-3817-471f-aa67-43172a86da91)

this is not the correct symbol used here and copying this throws error in the code editor.

### Describe the thing to improve

Instead proper single quote must be used.

### Describe the solution (optional)

![image](https://github.com/refinedev/refine/assets/91601706/6ced1bd5-170c-43a2-a00d-8ae1dc84d9eb)
I have already made the change by forking the repo as you can see in the image

Can I create a PR ?

**Comment by BatuhanW** [comment]
Hello @Manice18 we'd be more than happy if you create a PR! Looking forward to it!

**Comment by Manice18** [comment]
@BatuhanW  can you check ?

**Comment by omeraplak** [comment]
Thank you! @Manice18 ⚡️
