### ISSUE TITLE
[FEAT] Support multi path for same resource

### ISSUE THREAD

**Issue by wenerme** [refinedev/refine#4729]
### Is your feature request related to a problem? Please describe.

I'm new to refine, I want to point multi path to same resource

e.g.

```tsx
export function createCustomerRoutes({prefix}:{prefix:string}): RouteObject[] {
  return [
    {
      element: (
        <Refine
          dataProvider={dataProvider(`${location.origin}/api`)}
          routerProvider={routerProvider}
          resources={[
            {
              name: 'account',
              list: `${prefix}/account`,
              show: `${prefix}/account/:id`,
            },
            {
              name: 'contact',
              list: `${prefix}/contact`,
            },
          ]}
        >
          <Outlet />
        </Refine>
      ),
      children: [
        {
          path: 'account',
          element: <AccountListPage/>,
        },
        {
          path: 'contact',
          element: <div>contact list</div>,
        },
      ],
    },
  ];
}
```

bu this function may called by multi context, Refine should put into top level, but I want to multi path point to same resource

- /svr1/account -> account
- /svr2/account -> account

for different role, they use difference entrypoint.

### Describe the thing to improve

Support multi path for same resource

**Comment by alicanerdurmaz** [comment]
> Seems I should use `identifier`.

Yes `identifier` exactly for this use case 🚀 
https://refine.dev/docs/api-reference/core/components/refine-config/#identifier
