### ISSUE TITLE
[BUG] chakraui/themedLayoutV2 - unable to make header sticky

### ISSUE THREAD

**Issue by krsnaa** [refinedev/refine#4730]
### Describe the bug

In refine/packages/chakra-ui/src/components/themedLayoutV2/index.tsx, themedLayoutV2 renders the containing wrapper with overflow="auto", and so its children (Header, Body, Footer) cannot be sticky.

### Steps To Reproduce

https://refine.dev/docs/examples/tutorial/chakra-ui-tutorial/

compare it with the sticky header in https://refine.dev/docs/examples/tutorial/mui-tutorial/

### Expected behavior

A sticky header in the ChakraUI template

**Comment by yildirayunlu** [comment]
Hey @krsnaa 

Thank you for reporting this. Sorry for the problem. We have defined `overflow:auto` for the problem [here](4644).

We would be happy if you could support us in solving this problem 🥳
