### ISSUE TITLE
Add support for caching with Redis

### ISSUE THREAD

**Issue by siddiquiaffan** [refinedev/refine#4751]
### Is your feature request related to a problem? Please describe.

Fetching data on each request increases the load on server as well as database. Using caching can help in reducing load.

### Describe the thing to improve

Add caching with Redis to reduce load on database and reduce final cost.

**Comment by alicanerdurmaz** [comment]
Hi @siddiquiaffan, just to clarify, **refine** is a frontend framework, and caching on Redis is not something managed directly on the frontend. The responsibility for caching, including Redis caching, typically lies with the backend/API.

Moreover, it's worth mentioning that **refine** already has built-in caching capabilities on the client side using [TanStack Query](https://tanstack.com/query/latest).
