### ISSUE TITLE
[BUG] syncWithLocation not propagating to antd table UI

### ISSUE THREAD

**Issue by aidanlloydtucker** [refinedev/refine#4755]
### Describe the bug

syncWithLocation sorts/filters provided in the URL modify the table content but do not show on the UI.

### Steps To Reproduce

1. Sort or filter a table with `syncWithLocation` enabled
2. Note how the UI will show a small arrow for sorting or a label of what is being filtered
3. Reload page
4. Note how the data stays sorted/filtered but the UI does not reflect the sorted/filtered data in the table column header anymore.

### Expected behavior

The UI should reflect the `syncWithLocation` URL sorters/filters.

### Screenshot

Before reloading:
<img width="238" alt="Screenshot 2023-07-28 at 12 40 50 PM" src="https://github.com/refinedev/refine/assets/9687761/89866078-cb19-4324-a31d-58de186ca0ab">

After reloading:
<img width="230" alt="Screenshot 2023-07-28 at 12 40 57 PM" src="https://github.com/refinedev/refine/assets/9687761/15636f13-a2bb-4785-8c2d-6ad4844d0557">

(note the data in the table didn't change, still filtered by active.

### Desktop

- OS: MacOS
- Browser: Chrome
```
    "@refinedev/antd": "^5.30.0",
    "@refinedev/cli": "^2.7.4",
    "@refinedev/core": "^4.30.0",
    "@refinedev/inferencer": "^4.3.4",
    "@refinedev/react-router-v6": "^4.3.2",
    "@refinedev/simple-rest": "latest",
```

**Comment by BatuhanW** [comment]
Hello @aidanlloydtucker, thanks for the report! We'lll check the issue and get back to you.

**Comment by alicanerdurmaz** [comment]
Hi @aidanlloydtucker,

I revisited the issue you mentioned but couldn't reproduce it.

You can check out [our example](https://codesandbox.io/p/sandbox/relaxed-bohr-yf6rq4?embed=1&file=%2Fsrc%2Fpages%2Fposts%2Flist.tsx%3A124%2C1-125%2C1) to see that it is functioning as expected.

To help us understand and debug the problem better, could yo provide us with a reproducible example?

**Comment by aidanlloydtucker** [comment]
Hi,

Apologies for not being more clear. This only happens when the column is gated by the `useCan` hook. Eg: [in this example](https://codesandbox.io/p/sandbox/busy-johnson-32ttdj?embed=1&file=%2Fsrc%2Fpages%2Fposts%2Flist.tsx%3A23%2C65), the category column.

**Comment by alicanerdurmaz** [comment]
Hello again @aidanlloydtucker, thank you for raising the issue.
I made a change by replacing `defaultFilteredValue` with `filteredValue`, and it worked as expected. You can see the updated [example](https://codesandbox.io/p/sandbox/peaceful-sutherland-n2wtf8?embed=1&file=%2Fsrc%2Fpages%2Fposts%2Flist.tsx%3A66%2C1-67%2C1).

The reason `defaultFilteredValue` wasn't working is that it only renders on the initial render.

If you come across any other problems, please let us know.

**Comment by aidanlloydtucker** [comment]
Thank you!
