### ISSUE TITLE
[FEAT] add inferencer to swizzle

### ISSUE THREAD

**Issue by YechiamTK** [refinedev/refine#4758]
### Is your feature request related to a problem? Please describe.

Hi there 👋🏼 

I don't know if you guys remember my weird use case, but I heavily modify the inferencer.
The way I do it isn't quite convenient (copying the files I want to modify into my project), and swizzling the package will make my life a whole lot easier.

I know it'll probably not be prioritized anytime soon, but I'd like to have it somewhere in the roadmap so I decided to open an issue :)

### Describe alternatives you've considered

Manually copying the files into the project

### Describe the thing to improve

Add @refinedev/inferencer package to swizzle

**Comment by aliemir** [comment]
Hey @YechiamTK, thank you for the request 🙏 We're planning to do some updates in the inferencer package and make it more easily customizable for the users (not necessarily tied to the `swizzle` command). After the changes we're planning to make, we can make the inferencer components exportable through `swizzle`. 

Until this changes are made, we don't think making the inferencer components swizzle-able is very helpful. The current state of the inferencer codebase is not very customization friendly. I remember your case and you've done some great work with it but as you can understand, the current codebase is not very easy to customize 😅 

We're adding this to our backlog and hopefully work on this with the planned inferencer changes 🚀

**Comment by YechiamTK** [comment]
@aliemir yep, I agree the codebase isn't the most dev-friendly :D
If needed, I might be able to help (I'd like to help push this as much as possible, I've gotten my company excited and I suddenly need to make bunch of changes which would be easier with a more friendly code :)).

Please let me know if you need any helping hand.
