### ISSUE TITLE
[DOC] missing closing tag on line 660

### ISSUE THREAD

**Issue by alexcode4ever** [refinedev/refine#4768]
### Documentation issue

https://refine.dev/docs/api-reference/antd/components/antd-auth-page/#rememberme

The section of loginLink did not display correctly

### Describe the thing to improve

Missing closing tag ::: on line 660 of the markdown, which causes the loginLink did not display properly. 

### Describe the solution (optional)

Should be a quick fix by adding the ::: closing tag to line 660 
https://github.com/refinedev/refine/blob/next/documentation/docs/api-reference/antd/components/auth-page.md?plain=1

**Comment by omeraplak** [comment]
Hey,
Thank you for reporting the issue. Would you like to create PR?

**Comment by omeraplak** [comment]
Thank you @alexcode4ever ⚡️
