### ISSUE TITLE
[BUG] Meta title reverts to 'refine' when page isn't loaded.

### ISSUE THREAD

**Issue by marqpdx** [refinedev/refine#4793]
### Describe the bug

My pages use a layout's custom headers such as:
```
  <Head>
    <title>My page title</title>
    <meta property="og:title" content="My page title" key="title" />
  </Head>
```
When i load one of these pages the Title of the page (as shown by metatag) shows as 'refine' (hover over the browser tab to see) then it flash-changes to 'My page title' (which is what i want). If i navigate away from this page and navigate back the Title now only shows as 'refine' and not 'My page title'.

1. how to avoid the default 'refine' page title showing up? (the flash of titles is annoying on my end)
2. how to have my page titles never revert to 'refine' as the default (and my metatag are ignored)?

Am using Next 13+ and Chakra UI.

Thanks!

### Steps To Reproduce

1. add <Head> element to a Next page
2. load page, see title not be as desired.

### Expected behavior

There should be a simple way to overwrite the 'refine' title so that it never shows at all.

### Screenshot

![auVRO3CG](https://github.com/refinedev/refine/assets/1056353/2ccc597e-04f0-4bb5-845b-2eb9af078caa)

**Comment by aliemir** [comment]
Hey @marqpdx, refine doesn't change the title unless `<DocumentTitleHandler />` is used inside the `<Refine>` component. Can you check if it is included in your project?

**Comment by marqpdx** [comment]
@aliemir thank you for your timely response.
Yes, that was it. i have removed that line and now all is good :) 
I knew it was likely to be something simple i overlooked. 

Much appreciated,
m
