### ISSUE TITLE
[BUG] `disableTelemetry` prop in `<Refine>` component

### ISSUE THREAD

**Issue by zhou0219** [refinedev/refine#4796]
### Describe the bug

AuthBindings; DataProvider: Required<IDataContextProvider>; NotificationProvider: ()=>Required<...>; RouterProvider: RouterBindings; DisableTelemetry: boolean; Resources: ({...;} | {...;}) []; Options: {...;};} " Assign to type 'IntrinsicAttributes&RefineProps'.
The attribute 'disableTelemetry' does not exist on type 'IntrinsicAttributes&RefineProps'. Ts (2322)
(property) disableTelemetry: boolean

### Steps To Reproduce

`<Refine
              authProvider={authProvider}
              dataProvider={DataProvider(API_URL + `/api`, axiosInstance)}
              notificationProvider={notificationProvider}
              routerProvider={routerBindings}
              disableTelemetry={true}
>
</Refine>
`

### Expected behavior

Telemetry can be turned off.

**Comment by BatuhanW** [comment]
Hello @zhou0219 sorry for the confusion. You need to pass `disableTelemetry` to `options` prop, not in the root. You can disable telemetry as seen below:

```
<Refine options={{ disableTelemetry: true }}>
  ...
</Refine>
```

It seems it's overlooked in our docs, we'll update it soon.
