### ISSUE TITLE
[FEAT] CrudOperators nnull not working with Nestjsx Crud provider

### ISSUE THREAD

**Issue by quangbkl** [refinedev/refine#4805]
### Describe the bug

I use Nestjsx Crud provider and I try to add filter "{field: 'title', operator:'nnull', value: ''}" but it automatically converts "nnull" operator to "eq" operator.

### Steps To Reproduce

1. Add filter "{field: 'title', operator:'nnull', value: ''}"
2. Check the request using Chrome debug

### Expected behavior

Don't auto-convert to "eq" operator

**Comment by alicanerdurmaz** [comment]
Hello @quangbkl, thanks for the issue 🚀 

As you can see [here](https://github.com/refinedev/refine/blob/next/packages/nestjsx-crud/src/utils/mapOperator.ts), we haven't mapped the `nnul` operator. If it's supported by nextjs-crud, it should be straightforward for us to implement on our end.

Would you like to contribute to **refine** with this feature? If so, we'd be more than happy to help you through the process. 🙌

**Comment by yildirayunlu** [comment]
[nestjsx-crud](https://github.com/nestjsx/crud/wiki/Requests#filter-conditions) supports this filter with `CondOperator.NOT_NULL`.

**Comment by alicanerdurmaz** [comment]
@quangbkl  I changed the issue label to "FEAT". I hope it's okay for you too 🙌

**Comment by MahirMahdi** [comment]
If no one's working on it, I'd like to give it a try.

**Comment by Ponnada96** [comment]
Hi @alicanerdurmaz  , Can you please assign this issue to me?
