### ISSUE TITLE
[BUG] React Table global filter

### ISSUE THREAD

**Issue by Almalerik** [refinedev/refine#4808]
### Describe the bug

I tried to implement a global filter using refine with react table but filter value is not applied.

### Steps To Reproduce

I tried two way:
1. i followed the example from [tanstack filters example](https://tanstack.com/table/v8/docs/examples/react/filters): 
[here ](https://codesandbox.io/p/sandbox/trusting-christian-7qn873?embed=1&file=%2Fsrc%2Fpages%2Fposts%2Flist.tsx%3A9%2C46) a sandbox forked from [Refine advance react table](https://refine.dev/docs/examples/table/react-table/advanced-react-table/)
`180: + const [globalFilter, setGlobalFilter] = React.useState("");`
`202: +    state: {`
`203: +      globalFilter,`
`204: +    },`
`205: +    onGlobalFilterChange: setGlobalFilter,`
`326: +    <label htmlFor="globalFilter">Global filter: </label>`
`327: +     <input`
`328: +           id="globalFilter"`
`329: +           type="text"`
`330: +           value={(globalFilter as string) ?? ""}`
`331: +           onChange={(event) => setGlobalFilter(event.target.value)}`

2. i used setGlobalFilter from useTable:  
[here ](https://codesandbox.io/p/sandbox/optimistic-stallman-3v5z44?embed=1&file=%2Fsrc%2Fpages%2Fposts%2Flist.tsx%3A1%2C1-496%2C1) a sandbox forked from [Refine advance react table](https://refine.dev/docs/examples/table/react-table/advanced-react-table/)
`208: + setGlobalFilter`
`326: +    <label htmlFor="globalFilter">Global filter: </label>`
`327: +     <input`
`328: +           id="globalFilter"`
`329: +           type="text"`
`330: +           value={(getState()?.globalFilter as string) ?? ""}`
`331: +           onChange={(event) => setGlobalFilter(event.target.value)}`

### Expected behavior

I would expect that filter is applied and table updated but nothing happens.

**Comment by alicanerdurmaz** [comment]
Hello @Almalerik,

Consider [`useTable @refinedev/react-table`](https://refine.dev/docs/api-reference/core/hooks/useTable/#basic-usage) as a link between `dataProvider` and TanStack Table. It automatically manages API requests when the state changes.

However, at the moment, we don't support `setGlobalFilters`. This means that `useTable` doesn't monitor changes to `globalFilter` and won't send requests to the API accordingly.

If you wish to utilize `globalFilters`, you can disable the **refine**'s filtering feature and directly use the plain TanStack Table. In doing so, you'll need to handle API requests manually.

```ts
useTable<IPost>({
    enableGlobalFilter: true,
    refineCoreProps: {
      filters: {
        mode: "off",
      },
    },
});
```

For further details on `filters`, you can refer to the documentation [here](https://refine.dev/docs/api-reference/core/hooks/useTable/#filtering).

**Comment by Almalerik** [comment]
Thanks @alicanerdurmaz, I'll do it that way.
