### ISSUE TITLE
[BUG] @refine/mui list header buttons do not align

### ISSUE THREAD

**Issue by rikas** [refinedev/refine#4816]
### Describe the bug

When using the `<List>` component with header buttons (like the create button) the buttons horizontal align is inconsistent with the rest of the layout.

The code used is pretty standard:
```jsx
<List>
  <DataGrid
    {...dataGridProps}
    columns={columns}
    disableColumnMenu
    autoHeight
  />
</List>
```

See screenshot attached for the result.

### Steps To Reproduce

I prepared a codesandbox with a very basic example, just navigate to this URL:

https://codesandbox.io/s/refinedev-with-mui-hw2z4d?file=/src/PostList.tsx:540-685

It's a very minimal setup with @refinedev/mui and it's clear that the *Create* button is not aligned in the `PostList` component.

### Expected behavior

The header buttons should have some margin right. If I add that margin manually then everything's ok:

```jsx
<List headerButtons={({ defaultButtons }) => (
  <Stack direction="row" gap={2} mr={1}>
    {defaultButtons}
  </Stack>
)}>...</List>
```

### Screenshot

<img width="725" alt="image" src="https://github.com/refinedev/refine/assets/14589/76fcb935-9d40-41c5-83bb-98b825de2216">

**Comment by rikas** [comment]
Diving a little bit into the issue I found that @refinedev/mui is using a card for the <List> layout.

In a simple form it is coded as follows:

```jsx
  <Card>
    <CardHeader
      sx={{ display: "flex", flexWrap: "wrap" }}
      title={<Typography variant="h5">Title of card</Typography>}
      action={
        <Box display="flex" gap="16px">
          <Button variant="contained" color="primary">
            Create
          </Button>
        </Box>
      }
    />
    <CardContent>
      <Paper variant="outlined" square>
        This will be the table
      </Paper>
    </CardContent>
  </Card>
````

The Box component in the action will not be correctly aligned with the table with this minimal setup:

<img width="464" alt="image" src="https://github.com/refinedev/refine/assets/14589/088b653a-21df-4b0e-8d85-9bf0e42b7671">

Here's this card example in a codesandbox:

https://codesandbox.io/s/mui-card-with-action-l6vk3q?file=/src/App.tsx

**Comment by alicanerdurmaz** [comment]
Hi @rikas, I'm back with an update. I've identified the problem and have already opened a [pull request (PR)](https://github.com/refinedev/refine/pull/4823) to address it. If you have any additional suggestions or insights, please feel free to share. Thanks once again for your support! 🙌

**Comment by rikas** [comment]
@alicanerdurmaz thanks, this has bugging me for a while, where I need to use custom header code every time. Your finding on the mui negative margin is even better! Thanks!

**Comment by alicanerdurmaz** [comment]
@rikas I'm glad to hear that. 
In the meantime, you can use this while waiting for the fix to be released.

```ts
    <List
      wrapperProps={{
        sx: {
          ".MuiCardHeader-action": {
            margin: 0,
          },
        },
      }}
    >
      <DataGrid {...dataGridProps} columns={columns} autoHeight />
    </List>
```

live example: https://codesandbox.io/p/sandbox/damp-wave-jfkh3j?embed=1&file=/src/pages/posts/list.tsx:71,1-72,1
