### ISSUE TITLE
[FEAT] Dataprovider trpc for refine

### ISSUE THREAD

**Issue by Oelyhasina** [refinedev/refine#4819]
### Is your feature request related to a problem? Please describe.

No dataprovider for trpc

### Describe the thing to improve

hello, api based on trpc nextjs is starting to take up space now: adding a dataprovider for trpc in refine would be a good feature in addition to refine.

**Comment by BatuhanW** [comment]
Hello @Oelyhasina thanks for the suggestion, we'll check it and get back to you!

**Comment by fourscience** [comment]
Bump, it would be awesome at least to see types going trough :)

**Comment by alechaye** [comment]
Nice to have an official data provider
