### ISSUE TITLE
[FEAT] Image gallery

### ISSUE THREAD

**Issue by denisprado** [refinedev/refine#4827]
### Is your feature request related to a problem? Please describe.

I need to create an image gallery.

### Describe alternatives you've considered

I considered create an resource for image and other to album table and, after create gallery, upload images one per one choosing the gallery which it will be included.

### Describe the thing to improve

Probably may have an better way to do this, creating an album register with fields for it images ands descriptions in just one form.

**Comment by BatuhanW** [comment]
Hello @denisprado thanks for the suggestion. Could you elaborate more on your issue? We welcome any contributions if you want to add this feature.
