### ISSUE TITLE
[FEAT] `useVerify` hook

### ISSUE THREAD

**Issue by MahirMahdi** [refinedev/refine#4834]
### Is your feature request related to a problem? Please describe.

Just a suggestion, how about adding a `useVerify` hook into the Core API's Authentication?

### Describe the thing to improve

It would be great to have a `useVerify` hook for email verification purposes just like there are hooks like `useLogin` for logging in and `useUpdatePassword` for updating passwords.

**Comment by MahirMahdi** [comment]
Hello @alicanerdurmaz, hope you're doing great.

Yes sure. So, refine has almost every kind of hook we need for authentication except the `useVerify` hook. 

Let's take Appwrite as a use case here. Suppose I want the users to verify their email addresses, so I would have to use the verify method of the `account` instance.

First we need to send a verification link to the user's email address:

```bash
import { Client, Account } from "appwrite";

const client = new Client();

const account = new Account(client);

client
    .setEndpoint('YOUR_CLOUDWRITE_API_ENDPOINT')
    .setProject('YOUR_CLOUDWRITE_PROJECT_ID');

await account.createVerification('https://example.com');

```

Then the provided link should redirect the user back to the app and allow them to complete the verification process by verifying both the userId and secret params: 

```bash
import { Client, Account } from "appwrite";

const client = new Client();

const account = new Account(client);

client
    .setEndpoint('YOUR_CLOUDWRITE_API_ENDPOINT')
    .setProject('YOUR_CLOUDWRITE_PROJECT_ID');

await account.updateVerification('[USER_ID]', '[SECRET]');

```

Instead, we can make the verification process easier with the `useVerify` hook. Just to make the hook clearer it would be something like this: 

```bash
export const authProvider: AuthBindings = {
  createVerification: async ({ verification_link, redirect_url })  => {
    try {
      await account.createVerification(verification_link,);
      return {
        success: true,
        redirectTo: {redirect_url},
      };
    } catch (error) {
      const { type, message, code } = error as AppwriteException;
      return {
        success: false,
        error: {
          message,
          name: `${code} - ${type}`,
        },
      };
    }
  },
  updateVerification: async ({ user_id, secret, redirect_url })  => {
    try {
     await account.updateVerification(user_id, secret);
      return {
        success: true,
        redirectTo: {redirect_url},
      };
    } catch (error) {
      const { type, message, code } = error as AppwriteException;
      return {
        success: false,
        error: {
          message,
          name: `${code} - ${type}`,
        },
      };
    }
   },
 }
```

**Comment by aliemir** [comment]
Hey @MahirMahdi, at first glance this looks more like a backend work than frontend. I understand your use case but not sure if this is very useful for the majority of the users. We'll consider adding this to our roadmap for the future but currently we'll probably won't have any progress for now until the specs are clear and until its decided to be useful.

**Comment by MahirMahdi** [comment]
Hey @aliemir thanks for looking into it. I appreciate it.😀

**Comment by BatuhanW** [comment]
Hey @akhil888binoy, no on yet. Do you want me to assign it to you?

**Comment by akhil888binoy** [comment]
yeah sure , 
happy to work on it
