### ISSUE TITLE
[BUG] I face an error with infrancer 

### ISSUE THREAD

**Issue by Mahmoudgalalz** [refinedev/refine#4841]
### Describe the bug

This what I face when I try to load the data

I use the REST api way, and the data is persisted but the error appears after that

The API isn't complete yet and does not have the pagination yet

I removed the pagination and all sorter and stuff but still get the error and the url change to have the searchParams

### Steps To Reproduce

just I go to the page

and also the auto direct to the page isn't working too

it returns empty page 

### Expected behavior

the error should not persiste

### Screenshot

![image](https://github.com/refinedev/refine/assets/42272376/593b5486-c122-492e-aa4f-b45314d7a086)

**Comment by BatuhanW** [comment]
Hello @Mahmoudgalalz, could you provide us a reproducible example connected with your API? We can't understand the problem judging from the screenshot. We need more details.
