### ISSUE TITLE
[DOC] Typo Error

### ISSUE THREAD

**Issue by vtonu** [refinedev/refine#4855]
### Documentation issue

Typo Error

![image](https://github.com/refinedev/refine/assets/56773210/1360f6db-294f-4664-ae2f-7b26df2db66a)

### Describe the thing to improve

*to*

**Comment by omeraplak** [comment]
Hey,
Thank you for reporting the issue! Would you like to open a PR to fix this?

**Comment by vtonu** [comment]
> Hey, Thank you for reporting the issue! Would you like to open a PR to fix this?


This was my first time doing this, I forked, then I fixed the typo, then merged on my own, then created a pull request. Hope it's right.

**Comment by omeraplak** [comment]
Thank you! @vtonu !
