### ISSUE TITLE
Problem submitting form

### ISSUE THREAD

**Issue by van-vince** [refinedev/refine#4881]
Hi @BatuhanW  thanks for the replying the previous issue but solution is not working for me
![Screenshot 2023-08-30 at 9 27 03 AM](https://github.com/refinedev/refine/assets/67305320/6a7a04dc-2e13-42d7-8715-0d4255c7feff)
![Screenshot 2023-08-30 at 9 26 25 AM](https://github.com/refinedev/refine/assets/67305320/36c96691-a7e9-4ab6-8935-85cda741bb10)
![Screenshot 2023-08-30 at 9 37 00 AM](https://github.com/refinedev/refine/assets/67305320/dcd52798-35a9-4e22-91f7-ef08bac98d75)
I later change the server url for create user to http://localhost:8000/api/v2/user and it was successful. so is there any other way to make the request point to http://localhost:8000/api/v2/user/create-user.

**Comment by van-vince** [comment]
@BatuhanW W
here is the help forum please?

**Comment by BatuhanW** [comment]
You can use our discord and documentation https://refine.dev/docs
