### ISSUE TITLE
[FEAT] JSON:API Support for Dataprovider in Refine

### ISSUE THREAD

**Issue by PitBult** [refinedev/refine#4907]
### Is your feature request related to a problem? Please describe.

The problem we're facing is the absence of a dataprovider with JSON:API support in Refine. This absence forces us to manually create such dataproviders by modifying code from other sources, which is cumbersome and time-consuming.
A SPECIFICATION FOR BUILDING APIS IN JSON
[JSON:API](https://jsonapi.org/format/)

### Describe the thing to improve

It would be great to add a dataprovider with JSON:API support for Refine. It's sorely missed in our workflow, and currently, we have to create it manually by rewriting and modifying code from other dataproviders.

**Comment by BatuhanW** [comment]
Hello @PitBult,

As you mentioned, we don't have JSON:API data provider, but if you created it already, we are open to contributions and would like to share it as a package.

Also, you might be interested this part of the documentation.

https://refine.dev/docs/tutorial/understanding-dataprovider/swizzle

**Comment by PitBult** [comment]
Hello!
I used swizzle to create my DataProvider. 
Unfortunately, I'm a beginner React frontend developer and I may not be able to create a new DataProvider for JSON:API correctly. I've managed to create only basic requests for working with the API, which is built on the Laravel JSONAPI backend - https://laraveljsonapi.io/

It's also crucial to implement error handling according to the standard, which I haven't quite managed to do.

**Comment by omeraplak** [comment]
Hey @PitBult ,
Hey, if you choose to create a PR, we can help you until it gets merged, and this could be your first open-source contribution! :)

**Comment by JoelJaison394** [comment]
Hi,  Just checking in to see if anyone is currently working on this issue...

**Comment by BatuhanW** [comment]
Hello @JoelJaison394, AFAIK, no one is working on this issue, feel free to work on it if you want to!

**Comment by MahirMahdi** [comment]
If no one's working on it then I would like to.

**Comment by BatuhanW** [comment]
Hey @MahirMahdi, great to hear! Just assigned this issue to you.

**Comment by MahirMahdi** [comment]
Thanks @BatuhanW! On it.

**Comment by MahirMahdi** [comment]
Hey @BatuhanW, done with `dataProvider` with `JSON:API` specifications.

Should I update the documentation as well? Or update it in another PR?

**Comment by BatuhanW** [comment]
Hello @MahirMahdi thanks for the contribution! You can create a repository, publish it on NPM. Then you can create a PR in this repository to add your dataprovider to our community data providers list.

**Comment by MahirMahdi** [comment]
Hey @BatuhanW anytime! 😃  Sure, on it.
