### ISSUE TITLE
[DOC] Adding Instructions for using Keycloak JWT with DataProvider/Axios in Refine

### ISSUE THREAD

**Issue by PitBult** [refinedev/refine#4908]
### Documentation issue

No, this is not related to an existing part of the documentation.

### Describe the thing to improve

A clear and concise description of problems and what you would like to see.
I would like to suggest adding a section to the documentation or examples that demonstrates how to use Keycloak JWT with the DataProvider and Axios in Refine. Specifically, I'd like to see guidance on how to pass headers to the AxiosInstance, such as 
```JS
request.headers["Authorization"] = Bearer ${token}`; 
```
in the context of authentication with Keycloak.

Example:
```JS
axiosInstance.interceptors.request.use((request) => {

  // const { key, init } = useKeycloak();
  const token = localStorage.getItem(TOKEN_KEY);
  if (token) {
    if (request.headers) {
      request.headers["Authorization"] = `Bearer ${token}`;
      request.headers["Accept"] = `application/vnd.api+json`;
      request.headers["Content-Type"] = `application/vnd.api+json`;
    }
  }
  return request;
});
```

### Describe the solution (optional)

To improve the experience for beginners and readers, I propose adding a dedicated section or example in the documentation that showcases the integration of Keycloak JWT with Refine's DataProvider and Axios. This section should provide step-by-step instructions, code samples, and explanations on how to set up authentication using Keycloak and pass authentication headers in Axios requests.

**Comment by BatuhanW** [comment]
Hello @PitBult, we have some sections that mentions it already. If you see any improvement, we are open to contributions.

https://refine.dev/docs/tutorial/understanding-authprovider/create-authprovider/#setting-authorization-credentials

https://refine.dev/docs/api-reference/core/providers/data-provider/#error-format

https://refine.dev/docs/packages/documentation/data-providers/simple-rest/#usage
