### ISSUE TITLE
Request to Update Twitter Icon to X

### ISSUE THREAD

**Issue by lalitkumawat1m** [refinedev/refine#4918]
### Describe the bug

Twitter logo is updated recently and hasnt been updated on the site. I didnt find any issue related to this.

### Steps To Reproduce

Scroll to footer section and see twitter old logo

### Expected behavior

Twitter logo should be changed to X

### Screenshot

<img width="946" alt="Screenshot 2023-09-07 181827" src="https://github.com/refinedev/refine/assets/91591901/488584f6-515d-4e9b-b72b-a92cdb79d971">

### Additional Context

Won't change anything in the code as such would replace the twitter-logo with a new file. No code will be touched.

@BatuhanW 
I am just starting with open source contribution. I would love to take this issue as my first ever contribution could you please assign this to me?

**Comment by aliemir** [comment]
Hey @lalitkumawat1m, assigning this issue on you. We'll be waiting for your PR 🚀 Happy hacking! 🎉

**Comment by lalitkumawat1m** [comment]
Thanks @aliemir will raise a pr soon

**Comment by omeraplak** [comment]
Hey @lalitkumawat1m -- Thank you for your contribution! 💥
