### ISSUE TITLE
[BUG] Some MUI Data Grid filter is not working with Hasura Provider

### ISSUE THREAD

**Issue by IkumaTadokoro** [refinedev/refine#4970]
### Describe the bug

When using MUI's DataGrid and Hasura Provider and selecting 'starts with', 'ends with' or 'is any of' in the DataGrid default filter, I get the 'Operator <SELECTED_OPERATOR_NAME> is not supported' error.

---

Here is my guess for the situation.

The error seems to occur because the Hasura Provider throws an exception when an unsupported filter is specified in the Hasura Provider.
However, the Hasura Provider defines 'starts with' and 'ends with' as filters. 

Therefore, I suspect that this is not a bug specific to Hasura Provider, but a bug in useDataGrid, which provides props to the Data Grid. useDataGrid has a process for converting MUI operators to refine CRUDOperators. However, the conversion target for the three filters above is not implemented here. 

refs: https://github.com/refinedev/refine/blob/next/packages/mui/src/definitions/dataGrid/index.ts#L35-L69

The 'equals', 'isEmpty' and 'isNotEmpty' definitions, which are defined here, and 'contains', which can be referenced directly in the Hasura Provider, work correctly.

The title of this issue assumes that the MUI and Hasura Providers are used, but in reality other DataProviders may not be able to retrieve data correctly, just because they do not generate errors.

### Steps To Reproduce

1. Create MUI × Hasura playground with [refine.dev](https://refine.dev/#playground). (I chose Vite + MUI + Hasura + No Auth)
1. Filter record by one of the operators "starts with", "ends with", "is any of".
1. After a while, an error "Operator <SELECTED_OPERATOR_NAME> is not supported" is  occurs.

### Expected behavior

- "starts with" behaves as a starts with filter for each Provider.
- "ends with" behaves as an ends with filter for each Provider.
- "is any of" shall behave as an in filter for each Provider.

### Screenshot

https://github.com/refinedev/refine/assets/61409641/93bbe52d-f164-40ac-82ce-c75d8b390096

### Additional Context

There is also a bug that the "is not empty" filter does not work correctly if "namingConvention: "graphql-default" is specified in the Hasura provider.
However this is a bug on the Hasura provider side, so it has been fixed in another issue. I would like to submit it as a separate issue (This is because `_is_null` cannot be converted correctly as camelCase and the correct query cannot be issued).

**Comment by alicanerdurmaz** [comment]
Hello @IkumaTadokoro, Thanks for the detailed issue.

We've added this issue to our backlog, and we'll address it as soon as possible.

If you'd like to solve it and open a pull request, we'd be very happy. 🙌

**Comment by IkumaTadokoro** [comment]
@alicanerdurmaz 
Thanks for reply! I need to look at the current useDataGrid specification more closely, but it can probably be solved, so I will create a PullRequest!

**Comment by IkumaTadokoro** [comment]
I have created a PullRequest and would like to review it! #4974

**Comment by BatuhanW** [comment]
Hello @IkumaTadokoro thanks for the PR, we'll review it soon!

**Comment by omeraplak** [comment]
Hey @IkumaTadokoro ,
Thanks for your hard work! We'll release it soon.
