### ISSUE TITLE
[FEAT] Nhost dataProvider requires aggregateOperation name paramater in meta

### ISSUE THREAD

**Issue by nicholashu** [refinedev/refine#4988]
### Is your feature request related to a problem? Please describe.

I would like to display Nhost users in an Antd table. Nhost predefines and uses camelCase i.e.,`usersAggregate` for the Select Aggregate on the users table. This is not compatible with the snake_case operation names found throughout Hasura and the dataProvider useList function
```
const aggregateOperation = defaultNamingConvention
                ? `${operation}_aggregate`
                : camelCase(`${operation}_aggregate`);
```

changing the select aggregate in Hasura directly breaks the Nhost console auth section as it relies on the name to be `usersAggregate`

### Describe alternatives you've considered

the operation name can be customised with 
```const operation = defaultNamingConvention
                ? meta?.operation ?? resource
                : camelCase(meta?.operation ?? resource);
```
so, something like this maybe? 
```
const aggregateOperation = defaultNamingConvention
                ? meta?.aggregateOperation ?? `${operation}_aggregate`
                : camelCase(`${operation}_aggregate`);
```

### Additional context

Currently using a customised dataProvider that returns  
```
{
    ...dataProvider(client),
     getList: the modified function that allows meta?.aggregateOperation
}
```

### Describe the thing to improve

I would like to be able to query the user list with a custom aggregate operation name

**Comment by BatuhanW** [comment]
Hello @nicholashu I think you can pass 2nd parameter to convert to camel case.

```
const dataProvider = dataProvider(client, { namingConvention: "graphql-default" })
```

Let me know if that helps with your issue 🙌🏼

**Comment by nicholashu** [comment]
> Hello @nicholashu I think you can pass 2nd parameter to convert to camel case.
> 
> ```
> const dataProvider = dataProvider(client, { namingConvention: "graphql-default" })
> ```
> 
> Let me know if that helps with your issue 🙌🏼

it doesn't work in the nhost version of the dataProvider
```
const dataProvider = (
    client: NhostClient,
    options?: NHostDataProviderOptions,
): Required<DataProvider> => {
    const { idType } = options ?? {};

```

**Comment by BatuhanW** [comment]
Hello @nicholashu we have an option to convert to camelCase for hasura but not for nhost package, which is mostly similar. Feel free to create a PR to update `nhost` data provider and add camelCase option like in hasura.

**Comment by Ponnada96** [comment]
Hello @BatuhanW ,
I would like to work on this issue. Can you please assign it to me?.

**Comment by BatuhanW** [comment]
We are dropping `nhost` data provider support. People who are interested in the community can fork and maintain it.
