### ISSUE TITLE
[BUG] Typing issues with TypeScript 5 and tsconfig.json "moduleResolution": "Bundler"

### ISSUE THREAD

**Issue by dzcpy** [refinedev/refine#4999]
### Describe the bug

If you are using TypeScript 5, there is a new moduleResolution option which is "Bundler".
With this setup, when building refine.dev projects using vite, there will be an error message like this:
```
src/App.tsx:6:56 - error TS7016: Could not find a declaration file for module '@refinedev/react-router-v6'. '/node_modules/.pnpm/@refinedev+react-router-v6@4
.5.0_@refinedev+core@4.42.0_@types+react-dom@18.2.7_@types+react@_fwg4v2jhs3hybc3iotfsqx6icq/node_modules/@refinedev/react-router-v6/dist/esm/index.js' implicitly has an 'any' type.
  There are types at '/apps/admin/node_modules/@refinedev/react-router-v6/dist/index.d.ts', but this result could not be resolved when respecting package.json "exports". The '@refinedev/react-router-v6' library may need to update its package.json or typings.
```

### Steps To Reproduce

1. Create a new Refine.dev project with vite and TypeScript v5
2. Set tsconfig.json, change moduleResolution to "Bundler" and module to "ESNext"
3. Import @refinedev/react-router-v6 from any file `import routerProvider from '@refinedev/react-router-v6'`
4. Run npm run build

### Expected behavior

Correctly pick up typings for TypeScript 5

**Comment by aliemir** [comment]
Hey @dzcpy, sorry for the issue and thanks for the quick PR! Did you ran into the same issue for other refine packages or just for the `@refinedev/react-router-v6`? We'll also review the PR and check if we need to apply any changes to other packages as well 🚀
