### ISSUE TITLE
[BUG] Received `false` for a non-boolean attribute `loading`

### ISSUE THREAD

**Issue by adjsky** [refinedev/refine#5002]
### Describe the bug

When rendering `RefreshButton` from the `refine/chakra-ui` package warnings appear in the console.

### Steps To Reproduce

Render `RefreshButton` component from the `refine/chakra-ui` package.

### Expected behavior

No warnings in the console.

### Screenshot

![image](https://github.com/refinedev/refine/assets/49305219/a20c4524-1ecd-42e5-bdce-0fe75a492d25)

**Comment by BatuhanW** [comment]
Hey @adjsky thanks for the contributon! We'll release it once the patch changeset is added!
