### ISSUE TITLE
[DOC] Absolutely unclear how inferencer generates the code

### ISSUE THREAD

**Issue by al-muammar** [refinedev/refine#5004]
### Documentation issue

I'm not a React pro at all and I'm going through your tutorial. And the section 2.4 about inferencer is not clear at all: https://refine.dev/docs/tutorial/getting-started/antd/generate-crud-pages/

It is said that somehow when you add `AntdInferencer` to your `App.tsx` it should generate something. But nothing was actually generated (and who is responsible for that actually?)

Another problem is that the code in `npm create refine-app@latest -- -o refine-antd tutorial` is slightly different from what is in the tutorial. So it adds another layer of confusion

### Describe the thing to improve

Describe in more details which part should generate the code, what should be generated, how one could access and preview this code in their local repository, not in the online doc

**Comment by aliemir** [comment]
Hey @al-muammar, sorry for the confusion. When you use an inferencer component, they try to infer the data structure of the given resource by sending API requests when mounted and then generate a code for that resource's data schema. You should be able to see the preview and the generated code when you open the route you've added the Inferencer component. Let us know if you have issues viewing the preview or the generated code by the inferencer component. 

Check out the inferencer docs for more info about how it works and how it infers the fields, https://refine.dev/docs/packages/documentation/inferencer

We're also checking the differences between the tutorial and the generated project, sorry for that. We'll update our tutorial to match the generated project by the `refine-create-app` 🙏
