### ISSUE TITLE
[BUG] Doesn't show English Language text even though selected English Language

### ISSUE THREAD

**Issue by Neon-20** [refinedev/refine#5028]
### Describe the bug

The English Language is not showing even after selecting english.

### Steps To Reproduce

Create project in nextjs
Choose backend as rest api
choose google auth
launch project

### Expected behavior

It should show english language instead of german or random language

### Screenshot

<img width="1280" alt="Screenshot 2023-09-28 at 16 42 59" src="https://github.com/refinedev/refine/assets/55043383/3f9c3b24-c9a8-4c92-b41f-15c7bbc881ed">

### Additional Context

I can fix this if allowed to.

**Comment by BatuhanW** [comment]
Hey @Neon-20, in the screenshot, as you can see, table header columns, buttons are already english. Obviously, content texts are randomly generated lorem ipsum. Content doesn't change based on language preference.

**Comment by Neon-20** [comment]
Ok sure sure, my bad thanks for rectifying.
