### ISSUE TITLE
[DOCS] refine logos in readme files are not readable

### ISSUE THREAD

**Issue by manzil-infinity180** [refinedev/refine#5032]
### Is your feature request related to a problem? Please describe.

<img width="1609" alt="Screenshot 2023-09-29 at 12 42 41 AM" src="https://github.com/refinedev/refine/assets/119070053/51323270-e9be-4696-b0a0-c612cdc61cdc">

// logo image is not cleared

### Describe the thing to improve

replace the image with another image

**Comment by necatiozmen** [comment]
Hey @manzil-infinity180 thanks for informing us. We have updated all refine logos in the repository.
https://github.com/refinedev/refine/pull/5048
https://github.com/refinedev/refine/pull/5062
