### ISSUE TITLE
[FEAT] `useCustomMutation` should be able to modify headers for each individual call.

### ISSUE THREAD

**Issue by alicanerdurmaz** [refinedev/refine#5039]
### Is your feature request related to a problem? Please describe.

The following Providers are currently setting default headers, which results in the same headers being included in all subsequent API calls. Data providers should have the capability to modify headers for each individual call.

- [altogic](https://github.com/refinedev/refine/blob/next/packages/altogic/src/index.ts#L276)
- [medusa](https://github.com/refinedev/refine/blob/next/packages/medusa/src/dataProvider/index.ts#L159)
- [nestjsx-crud](https://github.com/refinedev/refine/blob/next/packages/nestjsx-crud/src/provider.ts#L197)
- [strapi](https://github.com/refinedev/refine/blob/next/packages/medusa/src/dataProvider/index.ts#L159)
- [strapi-v4](https://github.com/refinedev/refine/blob/next/packages/medusa/src/dataProvider/index.ts#L159)

We can implement this feature like this:
https://github.com/refinedev/refine/pull/5036

**Comment by MahirMahdi** [comment]
If no one's working on it, I would like to. 😃

**Comment by omeraplak** [comment]
> If no one's working on it, I would like to. 😃

Cool, happy hacking!
