### ISSUE TITLE
[DOC] filtering icon not showing in chakra ui tutorial on point 5

### ISSUE THREAD

**Issue by qhoirulanwar** [refinedev/refine#5083]
### Documentation issue

filtering icon not showing in chakra ui tutorial on point 5
https://refine.dev/docs/tutorial/adding-crud-pages/chakra-ui/adding-sort-and-filters/#adding-sorting

### Describe the thing to improve

add icon componen in property icon on IconButton component

### Describe the solution (optional)

`
        <IconButton
            aria-label="Sort"
            size="xs"
            icon={sorted === "asc" ? <IconChevronDown size={18} /> : sorted === "desc" ? <IconChevronUp size={18} /> : <IconSelector size={18} />}
            onClick={column.getToggleSortingHandler()}
        >
        </IconButton>`

**Comment by BatuhanW** [comment]
Hello @qhoirulanwar thanks for the issue and PR! We'll review it soon.
