### ISSUE TITLE
[BUG] Pagination in AntD not working 

### ISSUE THREAD

**Issue by Kkkassini** [refinedev/refine#5085]
### Describe the bug

![image](https://github.com/refinedev/refine/assets/31933415/44455206-421c-43d2-bbbe-7da8d623abec)
Already set pagination to server mode: 
`pagination: {
          mode: "server",
        },`
and added total count parameter in API header:
` content-length: 87804 
 content-type: application/json 
 date: Mon,09 Oct 2023 15:44:29 GMT 
 server: uvicorn 
 x-total-count: 1322 `
But the pagination still doesnt work. The API returns from _start to _end, and the table has always 1 page only.

### Steps To Reproduce

.

### Expected behavior

Multiple pages available to click

**Comment by alicanerdurmaz** [comment]
Hello @Kkkassini,

There don't seem to be any issues with our examples. We would be happy to debug if you provided a reproducible example via CodeSandbox or another platform.

But I can recommend looking into this concept. This might be the issue.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Headers

**Comment by BatuhanW** [comment]
Hello @Kkkassini closing the issue now, if you still have this problem, feel free to re-open it with more details and reproducible example.
