### ISSUE TITLE
[BUG]: Chakra UI Table's `<ColumnSorter />` icon not shown

### ISSUE THREAD

**Issue by alicanerdurmaz** [refinedev/refine#5097]
### Describe the bug

In our Chakra UI examples, Chakra UI Table's `<ColumnSorter />` icon is not shown.
We can solve this problem like [in this PR](https://github.com/refinedev/refine/pull/5084/files).

> You can find `<ColumnSorter />` component [here](https://github.com/refinedev/refine/blob/next/examples/base-chakra-ui/src/components/table/columnSorter.tsx#L25). All Chakra UI examples uses similar file structure.

### Steps To Reproduce

1. clone refine repo
2. run any chakra-ui example. [see contributing guide](https://refine.dev/docs/contributing/#running-in-development-mode)
3. look at the table's column
   

### Expected behavior

`<ColumnSorter />` icon is should shown

### Screenshot

<img width="947" alt="image" src="https://github.com/refinedev/refine/assets/23058882/0607cdee-3c45-4c94-b232-4c6d689ac871">

**Comment by nitinryali** [comment]
Assign this to me

**Comment by nitinryali** [comment]
Where can i find exactly the table in the website?

**Comment by sjcode99** [comment]
Hey @alicanerdurmaz, is this issue still open?

**Comment by nitinryali** [comment]
Yeah you can do it @sjcode99

**Comment by sjcode99** [comment]
Hey @alicanerdurmaz @nitinryali, fixed the bug for the ColumnSorter icon in the Chakra UI table. Please check it and let me know if anything else is required.
