### ISSUE TITLE
[FEAT]Add app directory option for nextjs

### ISSUE THREAD

**Issue by An0nymous0** [refinedev/refine#5103]
### Is your feature request related to a problem? Please describe.

<img width="943" alt="image" src="https://github.com/refinedev/refine/assets/6836030/a9244212-1df9-4779-ba93-174048d02eae">
Currently, creating nextjs is in the page directory, have you considered adding an app directory option?

### Describe the thing to improve

Add app directory option for nextjs

**Comment by An0nymous0** [comment]
Looking forward to😆

**Comment by BatuhanW** [comment]
Now we are using AppDir by default for NextJS projects.
