### ISSUE TITLE
[FEAT] Pass dynamic initialization data to create form (via `CreateButton`)

### ISSUE THREAD

**Issue by protyposis** [refinedev/refine#5113]
### Is your feature request related to a problem? Please describe.

In a relational data model, e.g., `countries` and `cities`, where a country can have multiple cities, I'd like to be able to use the `CreateButton` to create a city for a specific preselected country, i.e., pass the `countryId` to the city `Create` form so that the country can be preselected. Currently, I can only link to a blank form and need to manually select the country, even when it's known from the context.

### Describe alternatives you've considered

I tried to create a separate resource, e.g.,

```js
resources={[
  {
    name: 'countries',
    create: '/countries/create',
    show: '/countries/show/:id',
  },
  {
    name: 'cities',
    create: '/cities/create',
    show: '/cities/show/:id',
  },
  {
    name: 'cities',
    identifier: 'citiesWithCountry',
    create: '/countries/:countryId/create',
  },
```
in conjunction with the `meta` property of `CreateButton` and `useParsed()` in the create form, but that seems very hacky because I need to create an additional resource, duplicate the city create form, and it's not scalable to multiple values.

I also tried using query parameters for the resource, e.g.,
```js
  {
    name: 'cities',
    create: '/cities/create?countryId=:countryId',
    show: '/cities/show/:id',
  },
```
but that doesn't seem to be supported at all, and also seems hacky. 

### Describe the thing to improve

It would be great to have a way of passing data with the `CreateButton` (and maybe other button types too), e.g., as query parameters, or documentation on the suggested way of handling this case in Refine (if it exists already).

**Comment by BatuhanW** [comment]
Hello @protyposis, thanks for the issue. I see the problem here, we could make some tweaks and make buttons more flexible, so you can append any arbitrary query parameters, which you can parse in the create form and pre-fill fields.

For now, as a workaround you can swizzle the button and utilize `useGo` hook there. useGo hook supports `query` parameters. 

https://refine.dev/docs/api-reference/core/hooks/navigation/useGo/

**Comment by protyposis** [comment]
Thanks, that works nicely 👍
