### ISSUE TITLE
[BUG] MUI DataGrid filters are not all working

### ISSUE THREAD

**Issue by levipro** [refinedev/refine#5115]
### Describe the bug

In the MUI DataGrid there are a number of filters that do not work, the bug is occurring in my project and on the documentation site https://refine.dev/docs/api-reference/mui/hooks/useDataGrid/#basic-usage

The following are some that seem to be broken:
- starts with
- ends with
- is empty
- is not empty
- is any of
- `>`
- `<`

### Steps To Reproduce

Go to https://refine.dev/docs/api-reference/mui/hooks/useDataGrid/#basic-usage and try to use the data grid filtering

### Expected behavior

All the filters should work

### Desktop

chrome

**Comment by BatuhanW** [comment]
Hello @levipro, which data provider are you using? It's possible that your data provider might be missing mappings from filters to API. We have a similar issue here: https://github.com/refinedev/refine/issues/4970

If you are using a custom data provider, you'll need to do these mappings yourself, if you are using one of our dataproviders, let us know so we can check.

**Comment by BatuhanW** [comment]
Hello @levipro, thanks for the follow-up! Found the issue, will raise a PR in a bit.

**Comment by BatuhanW** [comment]
Hello @levipro, we've merged the fix and it will be released soon. Once it's released, can you check if that fixes your issue and let us know?

**Comment by omeraplak** [comment]
Hey @levipro,
We have just released @refinedev/mui@5.13.17. Could you please review and approve this update?

**Comment by levipro** [comment]
Looks good. Thanks for the quick fix!
