### ISSUE TITLE
[DOC] Add License link in readme file

### ISSUE THREAD

**Issue by adityadeshpande09** [refinedev/refine#5155]
### Documentation issue

There is no link for the license in the readme file.

### Describe the thing to improve

Link to the MIT license of the repository needs to be added.

### Describe the solution (optional)

Add a link which takes the user to the MIT license file.

**Comment by adityadeshpande09** [comment]
Can I start working on this ?

**Comment by omeraplak** [comment]
Hey @adityadeshpande09 , since the MIT license is one of the most commonly used licenses, I don't think we need to add a link. Thank you.
