### ISSUE TITLE
[BUG] Mantine useSelect hook return value as type number instead of type string

### ISSUE THREAD

**Issue by an-tran511** [refinedev/refine#5157]
### Describe the bug

For mantine Select, it only accepts value as string but the current useSelect hook return value type of number instead. It's kinda inconvenient to convert data type once again.

Current code of core useSelect doesn't actually convert the type of value:
<img width="331" alt="Screen Shot 2023-10-24 at 12 47 38" src="https://github.com/refinedev/refine/assets/146188526/32826842-d189-49de-acec-332b03fb2923">

Fix proposal:
a.toString() or String(a)

### Steps To Reproduce

 I reproduced the code: 
<img width="332" alt="Screen Shot 2023-10-24 at 12 45 28" src="https://github.com/refinedev/refine/assets/146188526/68b318cf-fb39-42f3-aa54-41eb4475960e">
<img width="173" alt="Screen Shot 2023-10-24 at 12 46 53" src="https://github.com/refinedev/refine/assets/146188526/3227473d-d345-4c5b-a096-7237c3c5f377">

### Expected behavior

Each option should have `value` of type string

**Comment by alicanerdurmaz** [comment]
@an-tran511 Thanks for the issue.

Do you want to open a PR to fix it?  🙌

**Comment by BatuhanW** [comment]
Hello @an-tran511 

As a hint, we need to change this line to fix this issue: https://github.com/refinedev/refine/blob/ceadcd29fc9e42c875a4b0a78622e9fc14b4ce42/packages/core/src/hooks/useSelect/index.ts#L252

Then you can create a patch changeset open the PR.
https://refine.dev/docs/contributing/#changeset
