### ISSUE TITLE
[BUG] onSearchProps values'

### ISSUE THREAD

**Issue by j2yau** [refinedev/refine#5164]
### Describe the bug

https://refine.dev/docs/api-reference/antd/hooks/table/useTable/#searchformprops

I followed the codes from this example and it's causing at an error of 'values' is of type 'unknown'

`const PostList: React.FC = () => {
    const { searchFormProps, tableProps } = useTable<IPost, HttpError, ISearch>(
        {
            onSearch: (values) => {
                return [
                    {
                        field: "title",
                        operator: "contains",
                        value: values.title,
                    },
                ];
            },
        },
    );
`

### Steps To Reproduce

1. https://refine.dev/docs/api-reference/antd/hooks/table/useTable/#searchformprops
2. Use the codes provided

### Expected behavior

To pass a value for search results

### Screenshot

![error-refine](https://github.com/refinedev/refine/assets/140708598/43120cb4-916e-4bd4-b7bc-83b2ae7e1d67)

### Desktop

Windows 11
Visual Studio Code
NPM 9.8.1
refinedev/antd@5.36.14
antd 5.10.2
typescript 4.9.5

**Comment by BatuhanW** [comment]
Hello @j2yau,

We couldn't reproduce the bug locally. We also have an example here, and it works. Can you also check? 

https://codesandbox.io/p/sandbox/gracious-margulis-yh7h8s?embed=1&file=%2Fsrc%2Fpages%2Fposts%2Flist.tsx%3A27%2C1-28%2C1
