### ISSUE TITLE
Inferencer + Supabase + foreign key: Objects are not valid as a React child 

### ISSUE THREAD

**Issue by d9k** [refinedev/refine#5184]
### Describe the bug

When I open my local refine project http://localhost:5173/members I get error

```
Error: Objects are not valid as a React child (found: object with keys {id, team_name}). If you meant to render a collection of children, use an array instead.
```

#### Details

Inferencer sends request:

`GET https://*****.supabase.co/rest/v1/teams?select=*&id=in.%281%29`

Result:

```
[{"id":1,"team_name":"Village of the Hidden Mist"}]
```

### Steps To Reproduce

Project: https://github.com/d9k/d9k-examples/tree/main/ts/supabase-refine

Supabase PostgreSql dump:
https://github.com/d9k/d9k-examples/blob/main/ts/supabase-demo/demo.sql

#### `<MembersList>` source:

https://github.com/d9k/d9k-examples/blob/main/ts/supabase-refine/src/pages/members/list.tsx

### Expected behavior

No error, visible datagrid.

### Screenshot

![Screenshot from 2023-10-27 18-55-35](https://github.com/refinedev/refine/assets/7331988/50b373f0-8474-4bb6-ae57-671532ec143d)

**Comment by d9k** [comment]
Related parts of supabase DB dump:

```
create table sportmans (
  "id" serial primary key,
  "name" text
);

INSERT INTO sportmans ("name") VALUES
	 ('Zabuza');

create table teams (
  "id" serial primary key,
  "team_name" text
);

INSERT INTO teams (team_name) VALUES
	 ('Village of the Hidden Mist');

create table members (
  "sportman_id" int references sportmans,
  "team_id" int references teams,
  primary key (sportman_id, team_id)
);

INSERT INTO members (sportman_id,team_id) VALUES
	 (1,1);
```

**Comment by AnuMessi10** [comment]
Hi @d9k I am new to this and would like to have a look at it, let me know if you can assign this to me. Cheers!

**Comment by aliemir** [comment]
Hey @d9k sorry for the issue! Looks like Mantine's Inferencer fails to generate the proper code for fields. We'll check the example you've provided for the investigation and get back to you with a fix soon! 🙏

**Comment by d9k** [comment]
@aliemir, tried with `HeadlessInferencer`, same error.

**Comment by aliemir** [comment]
Hey @d9k, I just opened up a PR https://github.com/refinedev/refine/pull/5373 which resolves the errors in fields with unknown properties (sometimes inferencer fails to understand which key to use when rendering an object field or a relation). Now inferencer will provide messages for such fields but continue rendering without an error. 

Also updated the logic of determining the key of the object so it will find keys more accurately. For example, now for your case it will use the `team_name` field when rendering the `team` relation. 

We'll add this PR to our release queue and we'll also update this issue when its released 🚀 Thank you for your patience 🙏
