### ISSUE TITLE
[DOC] Links in documentation stop working after a few seconds

### ISSUE THREAD

**Issue by axertion** [refinedev/refine#5186]
### Documentation issue

Links within the documentation pages stop working after a few seconds.

**Example page where this is happening:**
https://refine.dev/docs/tutorial/getting-started/antd/generate-crud-pages/

**Here's a loom video of the issue:**
https://www.loom.com/share/3499962ba7ae4ecd92fe8d2525145e41?sid=38d036ba-4dee-4f13-bbdd-e922d626b8fc

### Describe the thing to improve

Fix the bug where links become unclickable in the documentation

**Comment by aliemir** [comment]
Hey @axertion, sorry for the issue! I've just sent a fix for the issue, turns out there's an overlay that captures the pointer events 🤦 It will be deployed in short time.

**Comment by axertion** [comment]
thank you @aliemir!
