### ISSUE TITLE
[BUG] after upgrade to 4.44.9 optionLabel in useSelect not working

### ISSUE THREAD

**Issue by buildizer** [refinedev/refine#5192]
### Describe the bug

After upgrade to 4.44.9 the optionLabel in useSelect always return the default value which is title and after change it to another value it refused and it always return title and when title is not available is return the value which is the ID 

 

### Steps To Reproduce

Upgrade the refine core to 4.44.9 
using userSelect 
add option optionLabel 
```
const { selectProps: accomodationSelectProps } = useSelect({
    resource: "accomodation",
    optionLabel: "name",
  });
```

### Expected behavior

Returrn optionLabel: "name", as per the endpoint

**Comment by buildizer** [comment]
I'm using the useSelect to get some data from a resource using the below const to load the accommodation name from accommodation resource in version 4.44.7 this was working fine without any issue after upgrade to 4.44.9 this const doesn't work and it always return ID. 

```
const { selectProps: accomodationSelectProps } = useSelect({
    resource: "accomodation",
    optionLabel: "name",
  });
```
I have attached the resource response to be able to check it. 
![Uploading Screenshot 2023-10-30 at 9.47.00 PM.png…]()


 When I checked the release note I found that you changed the optionLabel attribute default value from name to title and the when I try to set it back to name it don't work

**Comment by BatuhanW** [comment]
Thanks for the details @buildizer, we'll fix it soon.
