### ISSUE TITLE
[FEAT] Vite support on  Remix experimental 

### ISSUE THREAD

**Issue by kalib-code** [refinedev/refine#5202]
### Describe the bug

Trying to use remix in vite support experimental [link](https://remix.run/docs/en/main/future/vite)  and refine giving issue on  `[vite] Error when evaluating SSR module /app/root.tsx: failed to import "@refinedev/remix-router"`

### Steps To Reproduce

create remix on vite using it docs and manually add refine base on the instruction docs based

### Expected behavior

refine should be working and no issue 

### Additional Context

I  know its remix support is experimental but it no hurt if we could support it in early stage thanks

**Comment by omeraplak** [comment]
Hey, Thank you very much for your interest. We don't think that the core team needs to put effort into this phase. However, if the community wants to work on it, we would be happy to support it.

**Comment by omeraplak** [comment]
> @omeraplak the Remix Vite plugin is now stable, shipped in Remix `v2.8`. Is now a better time to look at this?
> 
> I'm trying to merge Express and Remix projects into one but since Refine controls the build scripts making changes would require patching the packages

Hey, thanks for the update. I'll discuss the Remix Vite support with the `core` team.

But for now, to help you, by 'refine controls the build script', do you mean these commands? https://refine.dev/docs/packages/cli/#dev-start-build If so, you can alternatively use the command 'npm run refine run {CUSTOM_BIN} start' (https://refine.dev/docs/packages/cli/#run)

**Comment by cbnsndwch** [comment]
Thanks! I'll give that a try!

**Comment by pcfreak30** [comment]
see https://github.com/refinedev/refine/issues/5734

These issues have been dug into, and hopefully, all problems have been solved, including the remix-router package.
