### ISSUE TITLE
[FEAT] there should be commands to configure refine devtools? 

### ISSUE THREAD

**Issue by L-Ryland** [refinedev/refine#5211]
### Is your feature request related to a problem? Please describe.

When devtools is installed with command `refine devtools init`, there's no way to stop the devtools server from starting, even if I remove Panel and Provider from `App.tsx`. The available scripts `refine devtools` give are barely `init` and `start`. 

I have to remove `devtools` folder totally from the `node_modules` folder in order to get rid of it. 

### Describe the thing to improve

There should be options to flag whether devtools server should be started, and option to remove in from the project

**Comment by omeraplak** [comment]
Hey, thank you for reaching out to us. You can prevent the devtools-server from running by using the parameter npm run refine dev -- --devtools=false.

If you don't mind me asking, why do you want to disable the devtools server?

**Comment by omeraplak** [comment]
Thank you for reporting the issue. You can temporarily remove devtools from your project by deleting the `@refinedev/devtools` dependency. We will inform you once we have implemented a permanent solution
