### ISSUE TITLE
[DOC] Some properties are not available in useHook (Headless mode)

### ISSUE THREAD

**Issue by jamesthesken** [refinedev/refine#5216]
### Documentation issue

While using headless mode, I ran into a rate limiting issue performing filters and pagination. I would like to handle this client side however the [documentation](https://refine.dev/docs/api-reference/core/hooks/useTable/#resource) for properties seems out of date. Or I am not understanding its usage correctly. Please let me know!

### Describe the thing to improve

For example, to enable [client side filtering](https://refine.dev/docs/api-reference/core/hooks/useTable/#filtersmode) the docs say the following:
```
useTable({
    filters: {
        mode: "off",
    },
});
```

When it should be:

```
useTable({
    refineCoreProps: {
      filters: {
        mode: "off",
      },
    },
  });

```

**Comment by BatuhanW** [comment]
Hello @jamesthesken, actually the documentation link you sent is for `@refinedev/core`, so it's actually correct.

We are open to contributions, who wants to add `import { useTable } from "@refinedev/core"` to these examples, to prevent confusion.

**Comment by jamesthesken** [comment]
> Hello @jamesthesken, actually the documentation link you sent is for `@refinedev/core`, so it's actually correct.
> 
> We are open to contributions, who wants to add `import { useTable } from "@refinedev/core"` to these examples, to prevent confusion.

I would love to, I will start on that today

**Comment by jamesthesken** [comment]
Hey @BatuhanW would you mind taking a look at the PR I just submitted? This is my first time contributing to open source so please let me know if anything needs to change.

Thank you!
