### ISSUE TITLE
[BUG] Search form reset does not invalidate a table

### ISSUE THREAD

**Issue by elsiniestra** [refinedev/refine#5220]
### Describe the bug

I want to add a `Reset` button for my filter form. But, in return, only the visuals of the form are getting cleared. If you try to trigger the refetch/submit manually, you will see that the request is sent with the previous values.

### Steps To Reproduce

1. Get the example: https://refine.dev/docs/examples/table/antd/tableFilter/
2. Add the `<Button htmlType="reset" type="default" danger>Reset</Button>` button
3. See that on click only form is cleared, the result is not refetched

### Expected behavior

Clicking the reset button for the form filter triggers request invalidation as it is with the form filter submit button

**Comment by BatuhanW** [comment]
Hello @elsiniestra, could you provide us a minimal reproducible example?

**Comment by elsiniestra** [comment]
@BatuhanW Hi, as I've mentioned in the description, you can take the code example provided in [the docs](https://refine.dev/docs/examples/table/antd/tableFilter/) and just add the reset button `<Button htmlType="reset" type="default" danger>Reset</Button>` into the filter to get that behaviour

**Comment by alicanerdurmaz** [comment]
Hello @elsiniestra, yes `htmlType="reset"` resets form but `useTable` still doesn't know. you need to reset filter state by `setFilters`

```tsx
const { tableProps, searchFormProps, setFilters } = useTable()

const resetFilters = () => {
    setFilters([], "replace");
};
```
