### ISSUE TITLE
[BUG] The filter type of the useTable is strange

### ISSUE THREAD

**Issue by KoYoungWock** [refinedev/refine#5230]
### Describe the bug

The filter type of the useTable is strange

Currently, I'm
You are using filters, the useTable return value of '@refinedev/core'. However, when the actual filter is selected, there is a field attribute in the filter object in the array, but the type does not seem to be.

### Steps To Reproduce

1. Get 'useTable' from '@refinedev/core'.
2. Use the useTable as shown below.
3. Set the filter and check the object type in the array of filters.
4. At this time, there is no field.

### Expected behavior

The type of 'filters' returned from the useTable should be 'LogicalFilter[]'.

### Screenshot

![스크린샷 2023-11-08 오전 10 42 35](https://github.com/refinedev/refine/assets/134250452/864bde03-c0cf-48ae-b2ee-418f2ff2bc81)

**Comment by alicanerdurmaz** [comment]
Hello @KoYoungWock, filters are union to support `OR` and `AND` values.
```ts
export type LogicalFilter = {
    field: string;
    operator: Exclude<CrudOperators, "or" | "and">;
    value: any;
};

export type ConditionalFilter = {
    key?: string;
    operator: Extract<CrudOperators, "or" | "and">;
    value: (LogicalFilter | ConditionalFilter)[];
};

export type CrudFilter = LogicalFilter | ConditionalFilter;
export type CrudFilters = CrudFilter[];
```

The type of `filters` correct but you need to check is `LogicalFilter` or `ConditionalFilter`.
If you are sure about filters you can use `as`:
```ts
const tableFilters = filters as LogicalFilter[]
```

or you can use field key check:
```ts
if("field" in filters) {
// in this scope typeof filters will be LogicalFilter[]
}
```
