### ISSUE TITLE
[BUG] useStepsForm shows field value from same-index field in previous step

### ISSUE THREAD

**Issue by manosbatsis** [refinedev/refine#5231]
### Describe the bug

It seems the useStepsForm applies field values from same-index fields in previous steps. 

When the second step and field is rendered, it already the value entered in the field of the previous step as shown in the screenshots bellow. You can find  the modified form-material-ui-use-steps-form example in [my fork](https://github.com/refinedev/refine/compare/master...manosbatsis:refine:master).

### Steps To Reproduce

Suppose you have a step form with `amount` and `amount2` fields in separate steps: 

```
const renderFormByStep = (step: number) => {
    switch (step) {
        case 0:
            return (
                <>
                    // ...
                    <TextField
                        id="amount"
                        type="number"
                        {...register("amount", {
                            required: "This field is required",
                        })}
                        error={!!errors.amount}
                        helperText={errors.amount?.message}
                        margin="normal"
                        fullWidth
                        label="amount"
                        name="amount"
                        autoFocus
                    />
                    // ...
                </>
            );
        case 1:
            return (
                <>
                    // ...
                    <TextField
                        id="amount2"
                        type="number"
                        {...register("amount2", {
                            required: "This field is required",
                        })}
                        error={!!errors.amount2}
                        helperText={errors.amount2?.message}
                        margin="normal"
                        fullWidth
                        label="amount2"
                        name="amount2"
                        autoFocus
                    />
                    // ...
                </>
            );
        //...
    }
};
```

### Expected behavior

The "amount2" should be empty when step 2 is rendered.

### Screenshot

Step 1, enter an "amount" value:

![step1](https://github.com/refinedev/refine/assets/3016927/d42dc233-7530-4ccf-b1d2-5f2173e87068)

Step 2, the value is shown to "amount2":

![step2](https://github.com/refinedev/refine/assets/3016927/a5f5ff11-9c98-47a3-b3d7-55b60ec22ef0)

### Desktop

- Linux tower 6.5.6-76060506-generic #202310061235~1697396945~22.04~9283e32 SMP PREEMPT_DYNAMIC Sun O x86_64 x86_64 x86_64 GNU/Linux
- Firefox 118.0.2 (64-bit)

**Comment by BatuhanW** [comment]
Hello @manosbatsis thanks for the detailed report! We are open to contributions for this issue, I'm adding relevant tags now.

Also, could you fork this example and reproduce it here? It's easier for contributors to see bug, without setting up the application locally. https://refine.dev/docs/examples/form/mui/useStepsForm/

**Comment by manosbatsis** [comment]
A fork is available [here](https://github.com/refinedev/refine/compare/master...manosbatsis:refine:master) and a [codesandbox here](https://codesandbox.io/p/sandbox/thirsty-visvesvaraya-77g238?embed=1&file=%2Fsrc%2Fpages%2Fposts%2Fcreate.tsx&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522closhkc5z0008206atc8sca6q%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522closhkc5z0003206atjmnqo77%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522closhkc5z0005206a41fzlsr3%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522closhkc5z0007206aq3y8ilns%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522closhkc5z0003206atjmnqo77%2522%253A%257B%2522id%2522%253A%2522closhkc5z0003206atjmnqo77%2522%252C%2522activeTabId%2522%253A%2522closhn91400da206aumwncv76%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522closhkc5y0002206a8971xe4t%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Finterfaces%252Findex.d.ts%2522%252C%2522id%2522%253A%2522closhmahp007g206amj8f6x21%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fpages%252Fposts%252Fcreate.tsx%2522%252C%2522id%2522%253A%2522closhn91400da206aumwncv76%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522closhkc5z0007206aq3y8ilns%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522closhkc5z0006206a4avh2q9p%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252Fposts%252Fcreate%2522%257D%255D%252C%2522id%2522%253A%2522closhkc5z0007206aq3y8ilns%2522%252C%2522activeTabId%2522%253A%2522closhkc5z0006206a4avh2q9p%2522%257D%252C%2522closhkc5z0005206a41fzlsr3%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522closhkc5z0004206agw66drua%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%257D%255D%252C%2522id%2522%253A%2522closhkc5z0005206a41fzlsr3%2522%252C%2522activeTabId%2522%253A%2522closhkc5z0004206agw66drua%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by aliemir** [comment]
This looks more like an issue between Material UI and React Hook Form 🤔 As expected, `<TextField type="number" ... />` is not re-mounting on step changes. Same thing will also happen if other indexes of the cases has matching components. 

I'm guessing due to some internal state of the inputs, the change of props coming from the registered input doesn't trigger a change in the internal states of the Material UI inputs. This can be avoided by simply adding `key` prop to the matching components.

I just tried adding `key="amount"` and `key="amount2"` to the respective elements in the sandbox and get it working with no issues.
