### ISSUE TITLE
[BUG] Not reset filter when side bar click

### ISSUE THREAD

**Issue by KoYoungWock** [refinedev/refine#5235]
### Describe the bug

Hi

I encountered an issue while running the Mantine Advance Filter Example Project provided in Refine. When I click on a filter, the filter values are applied to the URL parameters as expected. However, when I click on the Sidebar, the URL parameters disappear, but the actual filter values are not reset. 

### Steps To Reproduce

Encountered an issue in the Mantine Advance Filter Example Project in Refine.
When I click on a filter, the filter values are correctly applied to the URL parameters.
However, when I click on the Sidebar, the URL parameters disappear, but the actual filter values are not reset.
I plan to create a GitHub issue to address this problem.

### Expected behavior

The expected behavior, in fact, is that when you apply filter values in the List and then click on the Sidebar, the filter values should reset.

### Screenshot

https://github.com/refinedev/refine/assets/134250452/277445eb-0b9c-42ca-bf4d-9d291e020fad

### Desktop

- OS Ventura 13.3(22E252)
```
"@refinedev/mantine": "^2.28.2",
"@refinedev/core": "^4.36.0",
"@refinedev/cli": "^2.9.0",
"@refinedev/react-router-v6": "^4.5.0",
"@refinedev/simple-rest": "^4.5.0",
"@refinedev/react-table": "^5.6.0",
"@tanstack/react-table": "^8.2.6",
```

**Comment by BatuhanW** [comment]
Hello @KoYoungWock thanks for the detailed report. We are open to contributions for this issue. 

Note for future contributors: You can find reproducible example here: https://refine.dev/docs/examples/table/mantine/basic/

**Comment by KoYoungWock** [comment]
@BatuhanW Thank you for your answer! I'll try the method you taught me!

**Comment by Ponnada96** [comment]
Hi @BatuhanW , Can you please assign this issue to me?

**Comment by aniruddhha** [comment]
In my opinion need make changes in routeProvider bindings i.e. https://github.com/refinedev/refine/blob/master/packages/react-router-v6/src/bindings.tsx

**Comment by aniruddhha** [comment]
@BatuhanW @omeraplak can you please assign this issue to me also ?

**Comment by BatuhanW** [comment]
Hello @aniruddhha, assigned 🚀 Looking forward to your contribution. 🙌🏼

**Comment by shivam-raj03** [comment]
@BatuhanW Can you plz assign this issue to me also?
