### ISSUE TITLE
[BUG] Select component numbers are sent as string when posting to dataProvider

### ISSUE THREAD

**Issue by silentnyte** [refinedev/refine#5273]
### Describe the bug

When using the Select component to select a value from a related table the related item id value is a number. When saving the change on either the Edit or Create page it is passed to the dataProvider through `variables` as a string.

### Steps To Reproduce

- Go to edit page for a resource that has a related resource
- Use select to select option
- Click `Save`
- Monitor `variables` in dataProvider

### Expected behavior

Numbers to be passed to dataProvider as numbers with out quotations ie 42 NOT '42'

### Screenshot

https://i.imgur.com/cE1Bd91.png
https://i.imgur.com/EiXo2Yp.png

### Desktop

- Windows 11
- Chrome
- "@refinedev/core": "^4.28.2",
- "@refinedev/chakra-ui": "^2.5.4",
- Custom dataProvider

**Comment by silentnyte** [comment]
Additional details, when first loading the edit page if save is pressed the related ids are all numbers. If a new option is selected using the select component then the number becomes a string.

**Comment by silentnyte** [comment]
I confirmed that using the Ant framework does not exhibit the same behavior. In Ant the id is send to the customData provider as a number not a string.

**Comment by alicanerdurmaz** [comment]
Hello @silentnyte,
Probably chakra-ui using native HTML select element and HTML select element works with string.

You [can change form data before submitting](https://refine.dev/docs/faq/#how-can-i-change-the-form-data-before-submitting-it-to-the-api).

**Comment by silentnyte** [comment]
This is a pretty typical database design pattern, related table linked by numeric id. Is this something that the Inferencer could detect and add automatically?
