### ISSUE TITLE
[BUG] ChakraUIInferencer code gen adding unneeded 'id'

### ISSUE THREAD

**Issue by silentnyte** [refinedev/refine#5274]
### Describe the bug

Inferencer adding unneeded `.id` to useSelect defaultValue

### Steps To Reproduce

Use inferencer to generate Edit page

### Expected behavior

Default value to show in select component

### Screenshot

https://i.imgur.com/HFndV5j.png

With id
https://i.imgur.com/yMxh2pE.png

Without id
https://i.imgur.com/l2byTwd.png

### Desktop

Windows 11
Chrome
"@refinedev/core": "^4.28.2",
"@refinedev/chakra-ui": "^2.5.4",
Custom dataProvider

**Comment by BatuhanW** [comment]
Hello @silentnyte, for us to debug it, can you provide us an example API response?

Thanks 🙏🏼

**Comment by silentnyte** [comment]
What exactly are you looking for? Do you want the entire Inferencer response file?

**Comment by aliemir** [comment]
Hey @silentnyte, sorry for the issue! Investigated the source code, found the responsible lines. There's a misuse of property accessing helpers, I'll open up a PR to fix it. I'll provide an update here when its ready and released 🙏

**Comment by silentnyte** [comment]
Thanks!
