### ISSUE TITLE
[FEAT] Create/Edit buttons: pass field value and redirect parameters

### ISSUE THREAD

**Issue by manosbatsis** [refinedev/refine#5286]
### Is your feature request related to a problem? Please describe.

Consider a link to [set filters](https://github.com/refinedev/refine/discussions/3007) for my list view as follows:

```
<Link to={`/posts?filters[0][field]=category.id&filters[0][operator]=eq&filters[0][value]=${row.id}`}>
    {filteredPosts?.length}
</Link>
```

This works for my list view by simply adding:

```
const { dataGridProps } = useDataGrid<IPost>({
    syncWithLocation: true,
})
```
Now I would like to use the `CreateButton/EditButton` in the same list view to:

1. Set the value for a form field using the filter (for create)
2. Redirect to the list view after save, using the same filters

### Describe alternatives you've considered

Alternatives for this functionality are unclear.

### Describe the thing to improve

Perhaps:

1. The button's meta (e.g. for [create](https://refine.dev/docs/api-reference/mui/components/buttons/create-button/#meta)) could allow setting initial values to the create/edit forms 
2. The [useForm.redirect](https://refine.dev/docs/packages/documentation/react-hook-form/useForm/#redirect) could allow applying the previous filters, taken from either the button's meta or history

**Comment by BatuhanW** [comment]
Hello @manosbatsis thanks for the feat request!

For now, you can achieve a similar behavior by utilizing [useParsed](https://refine.dev/docs/api-reference/core/hooks/navigation/useParsed/#paramscurrent) and [useGo](https://refine.dev/docs/api-reference/core/hooks/navigation/useGo/) hooks.

**Comment by Ishpreet01** [comment]
@manosbatsis is this issue still open?

**Comment by manosbatsis** [comment]
Yeah, guess so. Never managed to do this; even if a workaround/alternative way is possible as suggested by @BatuhanW, users like me would need a relevant howto to get it working.

**Comment by manosbatsis** [comment]
Hi @Abhishek-5854 thanks for stepping up. Don't have the rights to assign you the ticket, but I'm pretty sure project admins would happily review a PR for it.
