### ISSUE TITLE
[FEAT] For AuthPage, add a provider only option or customizability of fields

### ISSUE THREAD

**Issue by jackprogramsjp** [refinedev/refine#5302]
### Is your feature request related to a problem? Please describe.

You cannot directly remove the Email/Password fields of the AuthPage. Some people would like an OAuth provider only option, and no email/login password (some companies/websites actually only do OAuth providers, though I wouldn't say it's heavily common in the most popular apps). This makes it so we can use the providers in the AuthPage element, without actually making our own buttons.

### Describe alternatives you've considered

You'll either have to go into the source code itself and change it, or just make an entirely new couple of HTML elements.

### Describe the thing to improve

I would like to see an attribute `providerOnly={true}`, or just something where we can directly access an attribute of an AuthPage element to remove the box/fields of Email/Password, or maybe at least customize it a bit, just like what we can do with the `loginLink` and `registerLink` and etc.
e.g.
```js
    <AuthPage
      type="register"
      loginLink={
        <Box mb="3" bg="gray.200">
          <Link to="/login">Login</Link>
        </Box>
      }
    />
```

### Additional notes

I would like to send a PR of this, if this feature is accepted as requested.

**Comment by BatuhanW** [comment]
Hello @jackprogramsjp thanks for the issue, I think we can add `hideForm` prop to hide form components. Assigning this one to you. 🚀
