### ISSUE TITLE
[FEAT] Provide resource information inside of the data-provider for composite primary keys

### ISSUE THREAD

**Issue by bastianwegge** [refinedev/refine#5306]
### Is your feature request related to a problem? Please describe.

We're currently creating a workaround inside of our custom-data-provider to provide multi-key resource functionality. Say a URL not just has `:id` as a parameter, but you want to request a more specific resource for a `:locale_id` and `country_id`. In refine a resource for this would look like the following example:

```
...
{
  name: 'myi18nresource',
  identifier: 'myi18nresource',
  list: '/myi18n/',
  show: '/myi18n/show/:id/:locale_id/:country_id',
  edit: '/myi18n/edit/:id/:locale_id/:country_id',
},
...
```

Despite the fact that Refine does not provide composite-primary-key support we could come up with something like this inside our custom data-provider. 

```tsx
const isTranslationTable = resource.toLowerCase().includes('i18n');
if (isTranslationTable && metaHasLocale && metaHasCountry) {
  return `${url}/${id}/${meta.locale_id}/${meta.country_id}`;
}
```

I have three of this kind and I'm about to implement the fourth, whereas I'm just trying to see: 
"Is there a meta field with the same name in the route of my resource?"
"Yes? OK then set the param in the url to the meta-fields value!"

Right now we cannot access route-information from the actual resource inside of data-provider.getOne, which doesn't make sense to me.

### Describe alternatives you've considered

If we had access to the actual resource definition inside of i.e. `getOne`, we could do something like this:

```
const metaHasEditUrl = 'url' in meta;
if (metaHasEditUrl) {
  console.log({ meta });
  const metaUrl = meta.url as string;
  const urlPartsWithColons = metaUrl.split('/').filter((part) => part.includes(':'));

  const keysWithValues = urlPartsWithColons
    .map((part) => {
      const actualKey = part.replace(':', '');
      if (actualKey === 'id') return id;
      if (actualKey in meta) return meta[actualKey];
    })
    .filter(Boolean)
    .join('/');

  return `${url}/${keysWithValues}`;
}
```

As you can see I'm using `meta.url` which I added to the resource like this as a work-around:
```tsx
...
{
  name: 'myi18nresource',
  identifier: 'myi18nresource',
  list: '/myi18n/',
  show: '/myi18n/show/:id/:locale_id/:country_id',
  edit: '/myi18n/edit/:id/:locale_id/:country_id',
  meta: {
    url: '/myi18n/edit/:id/:locale_id/:country_id',
  },
},
...
```

### Describe the thing to improve

In my opinion it would make sense to provide the resource information inside of the data-provider. Since we already pass `meta` information, this seems like a missing piece to me to avoid duplication of the original-url or pattern.

**Comment by BatuhanW** [comment]
Hello @bastianwegge thanks for the issue! As you mentioned, it can be handled through meta and we think it would be overkill to pass entire resource definitions to data providers. Closing the issue as it's not planned.
