### ISSUE TITLE
[BUG] npm create refine-app@latest missing dependencies

### ISSUE THREAD

**Issue by silentnyte** [refinedev/refine#5336]
### Describe the bug

Dependency missing after initial install
@refinedev/react-table
@refinedev/react-hook-form

### Steps To Reproduce

npm create refine-app@latest
- Next.JS
- REST API
- Headless
- No examples
- Google auth
- i18n
- pnpm
pnpm run build

### Expected behavior

All dependencies installed

### Desktop

Windows 11
Chrome
"@refinedev/core": "^4.28.2",

**Comment by BatuhanW** [comment]
Hello @silentnyte these dependencies are not installed, because they aren't used anywhere, since you choose "No examples".

**Comment by silentnyte** [comment]
As soon as you create a resource they will be needed. Is there a use case where refine is used without any resources?
