### ISSUE TITLE
[BUG] @refinedev/remix-router doesn't work with Remix v2

### ISSUE THREAD

**Issue by rodbs** [refinedev/refine#5347]
### Describe the bug

After installing  "@refinedev/remix-router": "^2.3.0", I get this error
 ```
✘ [ERROR] No matching export in "node_modules/@remix-run/react/dist/esm/index.js" for import "unstable_useBlocker"

    node_modules/@refinedev/remix-router/dist/esm/index.js:158:9:
      158 │ import { unstable_useBlocker as useBlocker } from "@remix-run/rea...
          ╵          ~~~~~~~~~~~~~~~~~~~
```

### Steps To Reproduce

1. Remix 2.3.1
2. Install "@refinedev/remix-router": "^2.3.0"
3. npm run dev

### Expected behavior

Run it without errros

### Desktop

- Mac 13.6
- Chrome  119

### Additional Context

I think this error is due to the fact that `unstable_useBlocker` is deprecated in Remix 2.
In general it'd be appreciate it if you could update all Remix examples to Remix v2

**Comment by BatuhanW** [comment]
Hello @rodbs we are open to contributions for this one, however, in order to not have a breaking change, perhaps we could create a new router integration for remix v2, like `@refinedev/remix-router-v2`. cc @aliemir

**Comment by aliemir** [comment]
Hey @rodbs thank you for reporting this issue!

@BatuhanW, migration from v1 to v2 is painless for Remix and I think we can just introduce a major version that is compatible with Remix v2. As far as I can see, we only have this `useBlocker` change and the rest should already be compatible.

**Comment by rodbs** [comment]
@aliemir You're right. When I delete manually `unstable_useBlocker` from the installed version in `node_modules` it works in remix v2
@BatuhanW  Let me know if I can help ...

**Comment by BatuhanW** [comment]
@rodbs would you like to create a PR for this issue?

**Comment by rodbs** [comment]
@BatuhanW  Ok, I'll give a try
