### ISSUE TITLE
[BUG] RefineDev/Supabase not returning file ID after upload 

### ISSUE THREAD

**Issue by simonsayssa** [refinedev/refine#5350]
### Describe the bug

refinedev/supabase package is not returning the ID of the uploaded file. After checking the storage API's latest update, the ID is being returned after calling the "upload" API. However, in the refinedev/supabase npm package, storage.upload() function, only the path (string) and the fullPath (string) are returned. Kindly add the file id to the response since some users will link the file id to their database tables.

After going through the code in refindev/supabase npm package, I noticed that the ID is being returned by the storage API but the structure of the returned object was {"path": string, "fullPath": string}. Kindly fix it to { id: string; path: string; fullPath: string }
note that the change should be done in StorageFileAPI.ts file line 201

Fixed it by manually changing the @supabase/supabase-js version to 2.39.0 in 'node_modules/@refinedev/supabase/package.json'

### Steps To Reproduce

const { data: uploadFileData, error: uploadFileError } = await supabaseClient
.storage
.from(bucketName)
.upload(path, file, {
{},
cacheControl: "3600",
upsert: true
});
the id was not returned.

### Expected behavior

the response data object should contain id.

**Comment by BatuhanW** [comment]
Hello @simonsayssa, you can swizzle the supabase package and modify to fit your needs. https://refine.dev/docs/packages/data-providers/simple-rest/#customizing-the-data-provider

We are open to community contributions to this issue.

**Comment by ananta** [comment]
@BatuhanW I can work on this one 😄.  Should I add add the missing id of the uploaded artifact?

**Comment by simonsayssa** [comment]
> Hello @simonsayssa, you can swizzle the supabase package and modify to fit your needs. https://refine.dev/docs/packages/data-providers/simple-rest/#customizing-the-data-provider
> 
> We are open to community contributions to this issue.

This worked. Thanks for your support
