### ISSUE TITLE
[BUG] @refinedev/antd doesn't work with NextJS 14.0.3

### ISSUE THREAD

**Issue by w20k** [refinedev/refine#5353]
### Describe the bug

Refine doesn't support latest Next.js (tested version: 14.0.3).

### Steps To Reproduce

1. Generate project with `npm create refine-app@latest`
2. Upgrade nextjs and next-i18next (if installed) to the latest ("next-i18next": "^15.0.0", "next": "^14.0.3")
3. Add missing dependencies: "react-i18next": "13.3.1", "i18next": "23.7.7" 
4. Run with `yarn dev` or `npm run dev`

### Expected behavior

Dev build should start without errors.

### Screenshot

<img width="862" alt="Screenshot_2023-12-06_at_00_02_05-2" src="https://github.com/refinedev/refine/assets/1053320/a406de21-b330-42a2-9577-fd77a6fc92a8">

### Desktop

- Not browser specific

### Mobile

- Not mobile specific

### Additional Context

Seems like it's related to the bug within the next.js: https://github.com/vercel/next.js/issues/58817

This particular [answer](https://github.com/vercel/next.js/issues/58817#issuecomment-1836539459) doesn't work, removing or adding those doesn't solve a thing.

Tried with and without (added all as from comment above):
```
  transpilePackages: [
    '@refinedev/antd',
    '@refinedev/inferencer',
    '@refinedev/ui-types',
    'antd',
    '@ant-design/icons',
    '@ant-design/pro-components',
    '@ant-design/pro-layout',
    '@ant-design/pro-utils',
    '@ant-design/pro-provider',
    '@rc-component',
    'rc-cascader',
    'rc-checkbox',
    'rc-collapse',
    'rc-dialog',
    'rc-drawer',
    'rc-dropdown',
    'rc-field-form',
    'rc-image',
    'rc-input',
    'rc-input-number',
    'rc-mentions',
    'rc-menu',
    'rc-motion',
    'rc-notification',
    'rc-pagination',
    'rc-picker',
    'rc-progress',
    'rc-rate',
    'rc-resize-observer',
    'rc-segmented',
    'rc-select',
    'rc-slider',
    'rc-steps',
    'rc-switch',
    'rc-table',
    'rc-tabs',
    'rc-textarea',
    'rc-tooltip',
    'rc-tree',
    'rc-tree-select',
    'rc-upload',
    'rc-util',
  ],
```

**Comment by BatuhanW** [comment]
Hello @w20k, as you also pointed, this issue isn't related to refine, so we can't do anything about it.
