### ISSUE TITLE
[FEAT] Supabase LiveProvider improvements

### ISSUE THREAD

**Issue by jimsmart** [refinedev/refine#5357]
### Is your feature request related to a problem? Please describe.

Using Supabase client's liveProvider, with `liveMode: "auto"`...

1) On a page featuring a List, where the primary resource has related/child resources, liveProvider subscriptions that are automatically added to watch for changes on child/related resources overwrite other subscriptions on the page, so the only one that actually is left working is the last one to get set up. Naturally, this means the main resource (plus any other related/child resources on the page before this one), do not receive change notification messages. This is actually a bug, caused by every call to `subscribe` using the same channel name of `"any"`.

2) Calls to Supabase's liveProvider's `subscribe` method do not currently handle multiple event types — only the first in the passed `types` param gets used. This is mentioned in the 'Caution' section of https://refine.dev/docs/packages/data-providers/supabase/#supabase-real-time-support, where it says "Multiple subscriptions needs to be made in a single call, which is not supported by the current version of the `@refinedev/supabase` data provider."

### Describe alternatives you've considered

n/a

### Additional context

n/a

### Describe the thing to improve

I have fixed both of the above-mentioned issues.

My changes consist of: 

- Building a proper channel name to send to Supabase, using the (a) `channel` passed in to the call to `subscribe` (which includes the resource name), plus (b) the passed event `types` (sorted, for stability), and additionally (c) a string based upon `params.filters`. This fixes (1) above. Therefore a channel name passed internally to Supabase with the new code might look like `"resources/blog_posts:*:` (assuming no filters here) — as opposed to all subscriptions on the page using `"any"` as their channel name.
- Calling `client.[...].on` for every event in `types` before calling `subscribe` — as opposed to the current code which only called `client.[...].on` once, using `events[0]`.

I've currently done all of this in a swizzled copy of the Supabase data provider, but I will put together a proper pull request, and reference this issue.

**Comment by BatuhanW** [comment]
Hello @jimsmart thanks for the issue and the PR! We'll check it soon.
