### ISSUE TITLE
[DOC] I want to remove ?& when calling API in useTable

### ISSUE THREAD

**Issue by SeungChans** [refinedev/refine#5359]
### Documentation issue

I want to remove ?& when calling API in useTable

### Describe the thing to improve

I want to remove the ?& when calling the api in useTable and use the custom query I created.

**Comment by BatuhanW** [comment]
Hello @SeungChans can you provide more details? Minimal reproducible example would be great, but you can also let us know which data provider you are using, your example code and generated query.

**Comment by BatuhanW** [comment]
Request is generated by data provider, so we can't know the reason if you don't let us know which data provider you are using.

**Comment by BatuhanW** [comment]
Thanks for the information @SeungChans.

Issue arise from this line: https://github.com/refinedev/refine/blob/fba8f7370057fa8d4c27de6b9432fec4ccada268/packages/simple-rest/src/provider.ts#L50

We are adding `?` and `&`, without checking the existence of queries and filters. We need to manually add `?` and/or `&` depending on the existence of queries and filters.

We are open to contributions for this issue, should be easy to fix! 🚀 

@SeungChans if you need a quick solution, you can swizzle the data provider and fix it locally.  https://refine.dev/docs/tutorial/understanding-dataprovider/swizzle/#how-do-you-use-swizzle-to-create-an-data-provider

**Comment by amanzrx4** [comment]
Hey @BatuhanW I tried to resolve this with a util function [here](https://github.com/refinedev/refine/pull/5378). Please let me know if that's the correct approach and i'll proceed with updating the code everywhere and in docs too. Thanks
