### ISSUE TITLE
[FEAT] Allow objects to be translated in i18nProvider

### ISSUE THREAD

**Issue by jaulz** [refinedev/refine#5364]
### Is your feature request related to a problem? Please describe.

In certain cases it makes sense to store translations as JSON objects (with locales as keys) in the database. It would be great if the types of the `i18nProvider` could be extended to allow objects as well as the first parameter of the `translate` function so we can easily translate them as well.

### Describe alternatives you've considered

An alternative is of course a function in user land.

### Describe the thing to improve

I would like to see the following type in `@refinedev/core/src/contexts/translation/ITranslationContext.ts`:
````typescript
export type Translate = (
    key: string | Record<string, string>, // here is the change
    options?: any,
    defaultMessage?: string,
) => string;
````

**Comment by BatuhanW** [comment]
Hello @jaulz thanks for the suggestion. I'm not quite clear about the request tho. Would you mind elaborating more? Perhaps adding some pseudo example code?

**Comment by jaulz** [comment]
@BatuhanW sure, let me try. So sometimes I have fields in the database which are JSON objects and represent translations:
```typescript
country.title = {
  en: 'Switzerland',
  de: 'Schweiz',
}
```

Now, it would be great if I could simply pass this object to the existing `translate` function to avoid having another hook:
```typescript
const translate = useTranslate()

const translation = translate(country.title)
```

The change itself would only be in the types and it's up to the developer to implement it or not.

**Comment by BatuhanW** [comment]
Oh, I see. Great idea! I think currently, the only limitation is the TypeScript type. As a quick solution, you can mark is as any, and it should work.

Some pseudo-code example to give you an idea:

```typescript
let locale = "en";

const i18nProvider = {
    getLocale: () => locale,
    changeLocale: async (newLocale: any) => {
        locale = newLocale;
        return locale;
    },
    translate: (key: any) => {
        return key[locale];
    },
};


export const App = () => {
  return <Refine ... i18nProvider={i18nProvider}>...</Refine>
}
```

Then you can use `useTranslate` hook:

```typescript
const translate = useTranslate();
const title = {
  en: 'Switzerland',
  de: 'Schweiz',
}
  
console.log(
  "Translate",
  translate(title as any),
);

// Switzerland || Schweiz
```

I quickly tried this locally, and it works!

**Comment by BatuhanW** [comment]
We are open to contributions for this one, should be relatively simple task.

**Comment by aliemir** [comment]
Hey @jaulz and @BatuhanW, I think there's no need for a change in the API. The proposed change is going to be a breaking one for all of the existing i18n provider implementations.

@jaulz the feature you're requesting can simply be done via using `options` (2nd argument of the `useTranslate`'s `translate` function)

Here's an example:

```tsx
import { useTranslate } from "@refinedev/core";

const Component = () => {
  const t = useTranslate();

  t("a.dummy.key", { obj });
}
```

`useTranslate`'s return function has two overloads:

```ts
function translate(key: string, options?: any, defaultMessage?: string): string;
function translate(key: string, defaultMessage?: string): string;
```

If you pass an object in the second argument it will be treated as `options` and sent to the `i18nProvider`'s `translate` method. Then you can use it as you like.

**Comment by jaulz** [comment]
Okay, thanks for the feedback!
