### ISSUE TITLE
[BUG] Missing `loginLink` attribute in AuthPageProps for AuthPage type="register".

### ISSUE THREAD

**Issue by aberhamm** [refinedev/refine#5380]
### Describe the bug

`Type '{ type: "register"; loginLink: Element; }' is not assignable to type 'IntrinsicAttributes & AuthProps'.
  Property 'loginLink' does not exist on type 'IntrinsicAttributes & { type: "register"; providers?: OAuthProvider[] | undefined; hideForm?: boolean | undefined; } & { children?: ReactNode; } & { ...; } & { ...; }'.ts(2322)`
  
packages:
├── @ant-design/icons@5.2.6
├── @refinedev/antd@5.37.0
├── @refinedev/cli@2.16.20
├── @refinedev/core@4.46.0
├── @refinedev/devtools@1.1.28
├── @refinedev/inferencer@4.5.15
├── @refinedev/kbar@1.3.4
├── @refinedev/nextjs-router@5.5.4
├── @refinedev/supabase@5.7.3
├── @types/node@18.19.3
├── @types/react-dom@18.2.18
├── @types/react@18.2.45
├── @typescript-eslint/parser@5.48.0
├── antd@5.12.2
├── cross-env@7.0.3
├── next-i18next@8.10.0
├── next@13.5.6
├── nookies@2.5.2
├── react-dom@18.2.0
├── react@18.2.0
└── typescript@4.9.5

### Steps To Reproduce

1. `npm create refine-app@latest`
2. Selected Supabase for db and auth, Ant design for ui
3. Navigate to `/pages/register/index.tsx`
4. Attempt to add custom loginLink

### Expected behavior

Should not get typescript errors.

### Screenshot

<img width="883" alt="Screenshot 2023-12-16 at 10 38 26 AM" src="https://github.com/refinedev/refine/assets/5833422/2d067dc2-2f72-4ddd-9b0d-80367776bb0e">

### Additional Context

Adding the following code to the Registration props seemed to resolve the issue:

`packages/core/src/interfaces/auth.tsx`
```
/**
     * @description Render a redirect to login page button node. If set to false, login button will not be rendered.
     * @default `"/login"`
     * @optional
     */
    loginLink?: React.ReactNode;
```

**Comment by aberhamm** [comment]
Here's the commit on my forked repo: https://github.com/refinedev/refine/pull/5381/commits/704db99a44a2b3ef0ff65478915f4780a65a1460

**Comment by BatuhanW** [comment]
Hey @aberhamm thanks for the issue, we'll check it and get back to you!

**Comment by BatuhanW** [comment]
Thanks for the PR @aberhamm. I'm assigning it to the January release.
