### ISSUE TITLE
No browser caching of JS and CSS files when deploying new project versions in PROD env

### ISSUE THREAD

**Issue by joanaavelar** [refinedev/refine#5383]
Hello,

I've looked into your documentation and I didn't find out if there are any configuration OOTB in refine that prevents the  browser caching of JS and CSS files when new deploys occur.

Thanks in advance,

Joana Avelar

**Comment by aliemir** [comment]
Hey @joanaavelar,

This topic falls outside of Refine's concerns. Refine doesn't require any additional steps for the build process of the application and doesn't interfere with the build step of the platforms. Preventing the caching of assets is related with the production builds and how this steps generates assets.

With Refine, we have 3 platforms that is promoted in the documentation Vite, Next.js and Remix; All three of them provides a simple solution of adding hashes to the filenames of the assets for production builds. To learn more about how they handle this case, please check out their respective documentations. 

Let us know if you have any further questions 🙏
