### ISSUE TITLE
[bug] : Add link tag props and change subtitle props

### ISSUE THREAD

**Issue by SeungChans** [refinedev/refine#5418]
### Is your feature request related to a problem? Please describe.

Add link tag props and change subtitle props

### Describe the thing to improve

https://github.com/refinedev/refine/blob/096c289aa41408c75e1739ddb61fa6eb0dde7e9b/packages/antd/src/components/pages/auth/components/register/index.tsx#L265

Here to="login" to={loginLink || "/login"} How about changing it like this?

https://github.com/refinedev/refine/blob/096c289aa41408c75e1739ddb61fa6eb0dde7e9b/packages/antd/src/components/pages/auth/components/login/index.tsx#L271

Here to="register" to={registerLink || "/register"} How about changing it like this?

https://github.com/refinedev/refine/blob/8ac42ef1b8975bb51ea94ceb0c3f621bf173fe89/packages/antd/src/components/pageHeader/index.tsx#L34

props title too const subtitle = typeof props.subTitle === "string"

How about suggesting a change like this?

**Comment by BatuhanW** [comment]
Hello @SeungChans from what I understand, you want to modify text of the link components.

We already have `{translate("pages.login.title", "Sign in to your account")}`, so if you want to modify this text, you can add translations.

We may consider accepting optional props to be used as a fallback. WDYT? cc @aliemir @alicanerdurmaz

**Comment by SeungChans** [comment]
Thank you for answer! What do you think about passing it on as an option rather than a translation? If it's better to pass it on optionally, I'm thinking of posting a PR and revising it.

**Comment by BatuhanW** [comment]
Hello @SeungChans, feel free to create a PR!
