### ISSUE TITLE
[BUG]: `react-markdown`'s `remark` plugins throws type error

### ISSUE THREAD

**Issue by alicanerdurmaz** [refinedev/refine#5463]
### Describe the bug

When `import ReactMarkdown from "react-markdown"` used with `remark-gfm` plugin, it throws the following error

```md
assignable to type 'Pluggable<any[], Settings>'.
  Type 'Gfm' is not assignable to type 'Plugin<any[], Settings>'.
    The 'this' types of each signature are incompatible.
      Property 'attachers' is missing in type 'Processor<Settings>' but required in type 'Processor<void, Node<Data>, void, void>'.
```

To fix this we can use `@ts-expect-error`

Other related issues: https://github.com/orgs/rehypejs/discussions/63

### Steps To Reproduce

build packages using `react-markdown`

Build packages 
```bash
npm run bootstrap -- --scope @refinedev/chakra-ui --scope @refinedev/antd  --scope @refinedev/mui --scope @refinedev/mantine
```

### Expected behavior

Should not give type error

**Comment by BatuhanW** [comment]
Related https://github.com/remarkjs/react-markdown/issues/627
