### ISSUE TITLE
[FEAT] Ability to configure `useCan`'s queryOptions globally and through `CanAccess` component.

### ISSUE THREAD

**Issue by BatuhanW** [refinedev/refine#5472]
### Is your feature request related to a problem? Please describe.

Currently, `useCan` hook already accepts `queryOptions` parameter. This is useful when users wants to modify `cacheTime` or `staleTime` options to improve performance.

However, currently it's not possible to modify queryOptions for `CanAccess` component, or UI components using `CanAccess` under the hood, such as `EditButton` of `@refinedev`'s `antd`, `mui`, `mantine`, `chakra-ui` packages.

### Describe alternatives you've considered

It's possible to swizzle these components and update their `useCan` calls, but that's irreversible and overkill, just to cache AC queries.

### Describe the thing to improve

1-) Global Configuration

Update `AccessControlProvider` interface to accept optional `queryOptions`.

```tsx
<Refine ....
  accessControlProvider={{
    can: ....
    options: {
      queryOptions: {  staleTime: 5000 //  UseQueryOptions<CanReturnType> }
    }  
  }}
```

2-) Component prop

Add `queryOptions` prop to `CanAccess` component.

```tsx
<CanAccess queryOptions={{ cacheTime: 25000 }} />
```

Checklist:
- Refactor `useCan` hook to respect `queryOptions` in the following prioritization order if provided: `hook parameter -> component prop -> global config`
- Add new specs.
- Update relevant documentation sections.

**Comment by akkyyypatel** [comment]
The understanding of global configuration is good

**Comment by Conqxeror** [comment]
Is someone working on this issue or should I take it? @BatuhanW @alicanerdurmaz @aliemir

**Comment by BatuhanW** [comment]
Hey @Conqxeror, assigned to you. Looking forward to your PR!

**Comment by Conqxeror** [comment]
If my code is right as it was described in issue (I might have misunderstood the issue, even got confused while solving) then I can go further with docs? @BatuhanW

**Comment by BatuhanW** [comment]
> If my code is right as it was described in issue (I might have misunderstood the issue, even got confused while solving) then I can go further with docs? @BatuhanW

Your code looks good, added some minor comments for adding specs.

For documentation, you can update the following docs:
- https://github.com/refinedev/refine/blob/master/documentation/docs/authorization/access-control-provider/index.md
- https://github.com/refinedev/refine/blob/master/documentation/docs/authorization/components/can-access/index.md
