### ISSUE TITLE
[FEAT] Add `successNotification` field to AuthProvider methods' return type.

### ISSUE THREAD

**Issue by BatuhanW** [refinedev/refine#5473]
### Is your feature request related to a problem? Please describe.

Currently, if any of the Auth Provider methods returns `success: false` and `error` fields, we are showing error notification.

But it's not possible to do the same easily for success notifications.

### Additional context

https://github.com/refinedev/refine/discussions/5170#discussioncomment-7619752

### Describe the thing to improve

1- Add `successNotification` field to [`AuthActionResponse` type](https://github.com/refinedev/refine/blob/master/packages/core/src/interfaces/bindings/auth.ts).

```ts
type SuccessNotificationResponse {
  message: string;
  description?: string;
}

export type AuthActionResponse = {
    success: boolean;
    redirectTo?: string;
    error?: RefineError | Error;
    [key: string]: unknown;
    successNotification?: SuccessNotificationResponse
};
```

2-) Update relevant hooks to show success notification when `successNotification` object is provided and **add specs**.

- `useForgotPassword`
- `useLogin`
- `useLogout`
- `useRegister`
- `useUpdatePassword`

3-) Update relevant documentation pages.

**Comment by Conqxeror** [comment]
Fixed the issue, needed review. @BatuhanW
