### ISSUE TITLE
[FEAT] Update `@ant-design/charts` package to v2 for examples

### ISSUE THREAD

**Issue by BatuhanW** [refinedev/refine#5474]
### Is your feature request related to a problem? Please describe.

Due to dependency issues with `@ant-design/charts@1`, we are having installation issues. We have `.npmrc` file to workaround this issue, but it's not ideal.

### Describe the thing to improve

1) Update `@ant-design/charts` package to `v2` in the following examples and remove `.npmrc`:
- [`finefoods-antd`](https://github.com/refinedev/refine/blob/master/examples/finefoods-antd/package.json)
- [`blog-issue-tracker`](https://github.com/refinedev/refine/blob/master/examples/blog-issue-tracker/package.json)

2) Test these applications by running locally and make sure they work as expected.

3) Check if their blog posts needs to be updated:

https://github.com/refinedev/refine/blob/master/documentation/blog/2021-11-12-issue-tracker-refine.md

https://github.com/refinedev/refine/blob/master/documentation/blog/2023-04-06-finefood-admin-dashboard.md

**Comment by devhik0** [comment]
Hello, if i am allowed to take this task, i would like to assign it to myself to do it. Thanks for your understanding

**Comment by BatuhanW** [comment]
Hello @devhik0 assigned this issue to you. Looking forward to your PR!

**Comment by devhik0** [comment]
I wanted to start it but that error occured i mentioned in my issue

**Comment by devhik0** [comment]
Hey @BatuhanW, i solved that ENV problem via installing `cross-env` to package.json at root. But now same command still failing due to type error, i ll show it below, hope it helps to understand problem better. This logs coming from nx at terminal also.

```
[Package: @refinedev/antd, build: fail]
```
```
> cli run build --include-dependencies --scope @refinedev/core --scope @refinedev/antd --scope base-antd --includeDependencies
```
```
CLI Target: node14
ESM Build start
CJS Build start
IIFE Build start
ESM dist\esm\index.js     81.86 KB
ESM dist\esm\index.js.map 385.65 KB
ESM ⚡️ Build success in 4467ms
CJS dist\index.js     85.31 KB
CJS dist\index.js.map 373.55 KB
CJS ⚡️ Build success in 4518ms
IIFE dist\iife\index.js     215.42 KB
IIFE dist\iife\index.js.map 1.13 MB
IIFE ⚡️ Build success in 4644ms
src/components/table/components/filterDropdown/index.tsx(86,17): error TS2769: No overload matches this call.
  The last overload gave the following error.
    Argument of type '{ onChange: (e: any) => void; value: any; }' is not assignable to parameter of type 'Partial<unknown> & Attributes'.
      Object literal may only specify known properties, and 'onChange' does not exist in type 'Partial<unknown> & Attributes'.
src/hooks/table/useTable/useTable.ts(251,13): error TS2322: Type '(paginationState: TablePaginationConfig, tableFilters: Record<string, (string | number | boolean) | (string | number | boolean)[] | null>, sorter: SorterResult<any> | SorterResult<any>[]) => void' is not assignable to type '(pagination: TablePaginationConfig, filters: Record<string, FilterValue | null>, sorter: SorterResult<TData> | SorterResult<...>[], extra: TableCurrentDataSource<...>) => void'.
  Types of parameters 'tableFilters' and 'filters' are incompatible.
    Type 'Record<string, FilterValue | null>' is not assignable to type 'Record<string, string | number | boolean | (string | number | boolean)[] | null>'.
      'string' index signatures are incompatible.
        Type 'FilterValue | null' is not assignable to type 'string | number | boolean | (string | number | boolean)[] | null'.
 ELIFECYCLE  Command failed with exit code 2
```
In same file there is a TS error shows that:

```
No overload matches this call.
  The last overload gave the following error.
    Object literal may only specify known properties, and 'onChange' does not exist in type 'Partial<unknown> & Attributes'.ts(2769)
```

```tsx
86 | const childrenWithProps = React.Children.map(children, (child) => {
        if (React.isValidElement(child)) {
            return React.cloneElement(child, {
                onChange, <---
                value: mappedValue(value),
            });
        }
        return child;
    });
```
Hope it helps.

**Comment by BatuhanW** [comment]
> Hey @BatuhanW, i solved that ENV problem via installing `cross-env` to package.json at root. But now same command still failing due to type error, i ll show it below, hope it helps to understand problem better. This logs coming from nx at terminal also.
> 
> ```
> [Package: @refinedev/antd, build: fail]
> ```
> 
> ```
> > cli run build --include-dependencies --scope @refinedev/core --scope @refinedev/antd --scope base-antd --includeDependencies
> ```
> 
> ```
> CLI Target: node14
> ESM Build start
> CJS Build start
> IIFE Build start
> ESM dist\esm\index.js     81.86 KB
> ESM dist\esm\index.js.map 385.65 KB
> ESM ⚡️ Build success in 4467ms
> CJS dist\index.js     85.31 KB
> CJS dist\index.js.map 373.55 KB
> CJS ⚡️ Build success in 4518ms
> IIFE dist\iife\index.js     215.42 KB
> IIFE dist\iife\index.js.map 1.13 MB
> IIFE ⚡️ Build success in 4644ms
> src/components/table/components/filterDropdown/index.tsx(86,17): error TS2769: No overload matches this call.
>   The last overload gave the following error.
>     Argument of type '{ onChange: (e: any) => void; value: any; }' is not assignable to parameter of type 'Partial<unknown> & Attributes'.
>       Object literal may only specify known properties, and 'onChange' does not exist in type 'Partial<unknown> & Attributes'.
> src/hooks/table/useTable/useTable.ts(251,13): error TS2322: Type '(paginationState: TablePaginationConfig, tableFilters: Record<string, (string | number | boolean) | (string | number | boolean)[] | null>, sorter: SorterResult<any> | SorterResult<any>[]) => void' is not assignable to type '(pagination: TablePaginationConfig, filters: Record<string, FilterValue | null>, sorter: SorterResult<TData> | SorterResult<...>[], extra: TableCurrentDataSource<...>) => void'.
>   Types of parameters 'tableFilters' and 'filters' are incompatible.
>     Type 'Record<string, FilterValue | null>' is not assignable to type 'Record<string, string | number | boolean | (string | number | boolean)[] | null>'.
>       'string' index signatures are incompatible.
>         Type 'FilterValue | null' is not assignable to type 'string | number | boolean | (string | number | boolean)[] | null'.
>  ELIFECYCLE  Command failed with exit code 2
> ```
> 
> In same file there is a TS error shows that:
> 
> ```
> No overload matches this call.
>   The last overload gave the following error.
>     Object literal may only specify known properties, and 'onChange' does not exist in type 'Partial<unknown> & Attributes'.ts(2769)
> ```
> 
> ```tsx
> 86 | const childrenWithProps = React.Children.map(children, (child) => {
>         if (React.isValidElement(child)) {
>             return React.cloneElement(child, {
>                 onChange, <---
>                 value: mappedValue(value),
>             });
>         }
>         return child;
>     });
> ```
> 
> Hope it helps.

For support, you can use our discord channel or discussions section. Let's not add off-topic comments to the issues. Make sure you run `npm ci` and `npm run coffee` after installation. If you are using pnpm, it could be an issue with that. Can't tell for sure.

**Comment by devhik0** [comment]
So, i added `"@ant-design/charts": "^2.0.3"` to `finefoods-antd` example's package.json and ran locally to see everything as expected or not. I am getting this issue and its same with other errors i had so far. I am sharing full terminal log to see it in detail, thanks.

```
refine>npm run build -- --scope @refinedev/antd --scope finefoods-antd --includeDepende
ncies

> refinejs-repo@0.0.0 build
> lerna run build --include-dependencies --scope @refinedev/core --scope @refinedev/antd --scope finefoods-antd --includeDependencies

lerna notice cli v6.6.2
lerna notice filter including ["@refinedev/core","@refinedev/antd","finefoods-antd"]
lerna notice filter excluding "{monorepo-*,with-nx}"
lerna notice filter including dependencies
lerna info filter [
lerna info filter   '@refinedev/core',
lerna info filter   '@refinedev/antd',
lerna info filter   'finefoods-antd',
lerna info filter   '!{monorepo-*,with-nx}'
lerna info filter ]
lerna info run Using the "include-dependencies" option when Nx targets are configured will include both task dependencies detected by Nx and project dependencies detected by Lerna. See https://lerna.js.org/docs/lerna6-obsolete-options#--include-dependencies for details.
lerna info run Using the "ignore" option when Nx targets are configured will exclude only tasks that are not determined to be required by Nx. See https://lerna.js.org/docs/lerna6-obsolete-options#--ignore for details.

    √  @refinedev/devtools-shared:build (7s)
    √  @refinedev/devtools-internal:build (12s)
    √  @refinedev/devtools-ui:build (37s)
    √  @refinedev/core:build (48s)
    √  @refinedev/ui-types:build (28s)
    √  @refinedev/kbar:build (31s)
    √  @refinedev/react-router-v6:build (31s)
    √  @refinedev/devtools-server:build (1m)
    √  @refinedev/ui-tests:build (28s)

    ×  @refinedev/cli:build
       > @refinedev/cli@2.16.22 build
> tsup --format esm,cjs,iife --minify --legacy-output

CLI Building entry: src/index.ts, src/cli.ts
CLI Using tsconfig: tsconfig.json
CLI tsup v6.7.0
CLI Using tsup config: .\refine\packages\cli\tsup.config.ts
CLI Target: node14
ESM Build start
CJS Build start
IIFE Build start
ESM dist\esm\index.js     1.48 KB
ESM dist\esm\cli.js       38.89 KB
ESM dist\esm\index.js.map 13.75 KB
ESM dist\esm\cli.js.map   173.80 KB
ESM ⚡️ Build success in 4535ms
CJS dist\index.js     2.05 KB
CJS dist\cli.js       40.19 KB
CJS dist\index.js.map 14.37 KB
CJS dist\cli.js.map   173.79 KB
CJS ⚡️ Build success in 4722ms
IIFE dist\iife\index.js     1.58 KB
IIFE dist\iife\cli.js       70.19 KB
IIFE dist\iife\index.js.map 13.74 KB
IIFE dist\iife\cli.js.map   257.59 KB
IIFE ⚡️ Build success in 5246ms
src/commands/swizzle/install-required-packages/index.ts(43,23): error TS7053: Element implicitly has an 'any' type because expression of type '"npm" | "pnpm" | "yarn" | "bun"' can't be used to index type '{ npm: { install: string[]; installDev: string[]; outdatedJson: string[]; }; yarn: { install: string[]; installDev: string[]; outdatedJson: string[]; }; pnpm: { install: string[]; installDev: string[]; outdatedJson: string[]; }; }'.
         Property 'bun' does not exist on type '{ npm: { install: string[]; installDev: string[]; outdatedJson: string[]; }; yarn: { install: string[]; installDev: string[]; outdatedJson: string[]; }; pnpm: { install: string[]; installDev: string[]; outdatedJson: string[]; }; }'.
       src/commands/update/index.ts(93,28): error TS7053: Element implicitly has an 'any' type because expression of type '"npm" | "pnpm" | "yarn" | "bun"' can't be used to index type '{ npm: { install: string[]; installDev: string[]; outdatedJson: string[]; }; yarn: { install: string[]; installDev: string[]; outdatedJson: string[]; }; pnpm: { install: string[]; installDev: string[]; outdatedJson: string[]; }; }'.
         Property 'bun' does not exist on type '{ npm: { install: string[]; installDev: string[]; outdatedJson: string[]; }; yarn: { install: string[]; installDev: string[]; outdatedJson: string[]; }; pnpm: { install: string[]; installDev: string[]; outdatedJson: string[]; }; }'.
       src/utils/package/index.ts(164,32): error TS7053: Element implicitly has an 'any' type because expression of type '"npm" | "pnpm" | "yarn" | "bun"' can't be used to index type '{ npm: { install: string[]; installDev: string[]; outdatedJson: string[]; }; yarn: { install: string[]; installDev: string[]; outdatedJson: string[]; }; pnpm: { install: string[]; installDev: string[]; outdatedJson: string[]; }; }'.
         Property 'bun' does not exist on type '{ npm: { install: string[]; installDev: string[]; outdatedJson: string[]; }; yarn: { install: string[]; installDev: string[]; outdatedJson: string[]; }; pnpm: { install: string[]; installDev: string[]; outdatedJson: string[]; }; }'.
       src/utils/package/index.ts(195,32): error TS7053: Element implicitly has an 'any' type because expression of type '"npm" | "pnpm" | "yarn" | "bun"' can't be used to index type '{ npm: { install: string[]; installDev: string[]; outdatedJson: string[]; }; yarn: { install: string[]; installDev: string[]; outdatedJson: string[]; }; pnpm: { install: string[]; installDev: string[]; outdatedJson: string[]; }; }'.
         Property 'bun' does not exist on type '{ npm: { install: string[]; installDev: string[]; outdatedJson: string[]; }; yarn: { install: string[]; installDev: string[]; outdatedJson: string[]; }; pnpm: { install: string[]; installDev: string[]; outdatedJson: string[]; }; }'.
       src/utils/swizzle/prettierFormat.ts(1,39): error TS7016: Could not find a declaration file for module 'prettier'. 'C:/Users/aydin/web/contrib/refine/node_modules/prettier/index.js' implicitly has an 'any' type.
         Try `npm i --save-dev @types/prettier` if it exists or add a new declaration (.d.ts) file containing `declare module 'prettier';`

                                                                                                                  
 ———————————————————————————————————————————————————————————————————————————————————————————————————————————————— 

 >  Lerna (powered by Nx)   Ran target build for 13 projects (2m)

    √    9/10 succeeded [0 read from cache]

    ×    1/10 targets failed, including the following:
         - @refinedev/cli:build
```
I think its TS error at `packages\cli\src\commands\swizzle\install-required-packages\index.ts` at ln 50

```ts
export const displayManualInstallationCommand = async (
    requiredPackages: string[],
) => {
    const pm = await getPreferedPM();
    const pmCommand = pmCommands[pm.name].install.join(" "); <-----
    ...
};
```
