### ISSUE TITLE
[BUG] Chakra UI Sider overflows when collapsed 

### ISSUE THREAD

**Issue by alicanerdurmaz** [refinedev/refine#5475]
### Describe the bug

![Screenshot_2023-12-06_133655](https://github.com/refinedev/refine/assets/23058882/b4a4edcb-6bed-4bfd-923b-88828214084b)

### Steps To Reproduce

1. create a Chakra UI project with `npm create refine-app@latest`
2. create a nested resource with an icon
```ts
resources={[
    {
        name: "parent",
    },
    {
        name: "posts",
        list: "posts",
        meta: {
            parent: "parent",
            icon: "✅",
        },
    },
    {
        name: "another posts",
        list: "posts",
        meta: {
            parent: "parent",
            icon: "✅",
        },
    },
]}
```  
4. collapse the sider

### Expected behavior

Sider should not have `overflow-x`

### Additional Context

[here is the source code that renders the sider items](https://github.com/refinedev/refine/blob/master/packages/chakra-ui/src/components/themedLayoutV2/sider/index.tsx#L76)

**Comment by ShivamDureja** [comment]
Hi @alicanerdurmaz I tried to fix this issue by adding value as "hidden" to property name "OverflowX". Please review the changes and approve accordingly.
Thanks

**Comment by ShivamDureja** [comment]
Hi all, sorry I just raised PR directly without claiming the issue as I am new to open source so didn't know the procedure.

**Comment by Avon11** [comment]
@alicanerdurmaz Can I pick this up?

**Comment by alicanerdurmaz** [comment]
Hello @Avon11 thank you but @ShivamDureja already opened a PR. 🙂

**Comment by Avon11** [comment]
> Hello @Avon11. Thank you, but @ShivamDureja has already opened a PR. 🙂

Np 👍
