### ISSUE TITLE
[BUG]Errors occuring while following contributing steps

### ISSUE THREAD

**Issue by devhik0** [refinedev/refine#5492]
### Describe the bug

While i following contributing steps at docs, i stuck at build step because of errors below:

```sh
refine>npm run build -- --scope @refinedev/antd --scope base-antd --includeDependencies

> @refinedev/devtools-server@1.1.22 build ~\refine\packages\devtools-server
> npm run build:client && tsup --format esm,cjs,iife --minify --legacy-output

> @refinedev/devtools-server@1.1.22 build:client
> NODE_ENV=production tsc && vite build --config src/client/vite.config.ts

'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.
 ELIFECYCLE  Command failed with exit code 1.
```

I completed previous steps successfully

### Steps To Reproduce

1. Go to docs/contributing
2. Follow steps as described
3. Run build command after bootstrapping packages and see error

### Expected behavior

Build should finish without errors

### Screenshot

![error](https://github.com/refinedev/refine/assets/151969082/51c609e3-4c71-4fd6-a89a-3321f176e2c5)

### Desktop

OS: Windows, Refine version: latest

### Mobile

- Not related

### Additional Context

I think its related wih node:env but dont know why its causing that error

**Comment by BatuhanW** [comment]
Hello @devhik0, couldn't reproduce the issue locally. Could you run `npm run coffee` and let me know if that fixes the issue?

**Comment by devhik0** [comment]
No, i ran that command but it stuck at same step with same errors, i think its related with OS compatibility as I get from my research.

**Comment by BatuhanW** [comment]
It seems this issue isn't related to Refine, but with Windows.

There is an accepted answer here: https://stackoverflow.com/questions/11928013/node-env-is-not-recognized-as-an-internal-or-external-command-operable-comman
