### ISSUE TITLE
[FEAT] Add Support for Astro framework

### ISSUE THREAD

**Issue by RayyanNafees** [refinedev/refine#5493]
### Is your feature request related to a problem? Please describe.

Yes
Since astro is the favourite framework as per the latest [rising star](https://risingstars.js.org/2023/en?ref=dailydev#section-all) directory

Refine supports Remix which has only 26k stars while Astro has 38k stars

So please add the support for Astro since it's way more popular

### Describe the thing to improve

Nothing to improve
Just add Astro support

**Comment by BatuhanW** [comment]
Hello @RayyanNafees could you elaborate more on this Astro integration?
