### ISSUE TITLE
[DOC] Document using Refine with existing projects

### ISSUE THREAD

**Issue by BatuhanW** [refinedev/refine#5496]
### Documentation issue

For some users, it's not clear if Refine can be used with existing applications. Although it should be straight forward, we aren't clearly explaining concepts and clarifying that it's possible.

### Describe the thing to improve

We need to document using Refine with existing projects.

It may or may not be required to explain it separately for Vite, NextJS or Remix, if we can explain the concept.

### Describe the solution (optional)

- Add a documentation page about Adding Refine to existing projects
- Add examples for Vite, NextJS, Remix. Where refine is mounted only in the `/refine` route.

### References

We have some discussions in the past, which can be used as a reference: https://github.com/refinedev/refine/discussions/3343#discussioncomment-4592073 At the time of this answer, Refine was on v3, but the same concept can be applied to Refine v4 regardless.

https://discord.com/channels/837692625737613362/1186730677694124072

**Comment by Conqxeror** [comment]
Assign me the task, I will do it as mentioned in the comment #3343 by @aliemir . I will try my best to make that page for the documentation.

**Comment by BatuhanW** [comment]
Hello @Conqxeror we'll handle this internally, we discussed and there are some important points needs to be handled.

**Comment by Conqxeror** [comment]
> Hello @Conqxeror we'll handle this internally, we discussed and there are some important points needs to be handled.

Ok @BatuhanW 👍🏻 If y'all need any help on this task then do tell me. I would love to work on this task and to grow and learn with you all.
