### ISSUE TITLE
[DOC] Query in code tutorial not reflects api url example

### ISSUE THREAD

**Issue by iaurg** [refinedev/refine#5509]
### Documentation issue

I'm following the tutorial documentation, and I noticed that some code does not align with the provided examples. This discrepancy may confuse users going through the tutorial.

For instance, in the getList example found here: https://refine.dev/docs/tutorial/understanding-dataprovider/create-dataprovider/#getlist, the API params example is given as follows:

[GET] https://api.fake-rest.refine.dev/posts?_limit=10&_page=2

However, in the code below this example, a variable is created as follows:
```js
...
const { current = 1, pageSize = 10 } = pagination ?? {};

const query: {
    _start?: number;
    _end?: number;
} = {
    _start: (current - 1) * pageSize,
    _end: current * pageSize,
};
...
```
I've tested both sets of parameters in the API URL, and they both work but return different results.

Could we use the same parameters in each example, or is there any issue with this approach?

### Describe the thing to improve

Params examples and code

**Comment by BatuhanW** [comment]
Hello @iaurg thanks for the report! Would you like to create a PR for this issue? As you mentioned, example request should have `_start` and `_end` parameters.

**Comment by Conqxeror** [comment]
> Hello @iaurg thanks for the report! Would you like to create a PR for this issue? As you mentioned, example request should have `_start` and `_end` parameters.

For consistency, you should align the code with the example URL. In this case, you can modify the code to use` _limit` and `_page` instead of `_start` and ` _end`:

```
const { current = 1, pageSize = 10 } = pagination ?? {};

const query: {
    _limit?: number;
    _page?: number;
} = {
    _limit: pageSize,
    _page: current,
};

```

**Comment by BatuhanW** [comment]
> > Hello @iaurg thanks for the report! Would you like to create a PR for this issue? As you mentioned, example request should have `_start` and `_end` parameters.
> 
> For consistency, you should align the code with the example URL. In this case, you can modify the code to use` _limit` and `_page` instead of `_start` and ` _end`:
> 
> ```js
> const { current = 1, pageSize = 10 } = pagination ?? {};
> 
> const query: {
>     _limit?: number;
>     _page?: number;
> } = {
>     _limit: pageSize,
>     _page: current,
> };
> ```

This doc is referencing to `simple-rest` data provider, and we are using `_start`, `_end` parameters in this package, [see here](https://github.com/refinedev/refine/blob/master/packages/simple-rest/src/provider.ts).

So it's better to be consistent with the code in the data provider.

**Comment by Conqxeror** [comment]
> > > Hello @iaurg thanks for the report! Would you like to create a PR for this issue? As you mentioned, example request should have `_start` and `_end` parameters.
> > 
> > 
> > For consistency, you should align the code with the example URL. In this case, you can modify the code to use` _limit` and `_page` instead of `_start` and ` _end`:
> > ```js
> > const { current = 1, pageSize = 10 } = pagination ?? {};
> > 
> > const query: {
> >     _limit?: number;
> >     _page?: number;
> > } = {
> >     _limit: pageSize,
> >     _page: current,
> > };
> > ```
> 
> This doc is referencing to `simple-rest` data provider, and we are using `_start`, `_end` parameters in this package, [see here](https://github.com/refinedev/refine/blob/master/packages/simple-rest/src/provider.ts).
> 
> So it's better to be consistent with the code in the data provider.

Ohhkk👍 I just did the change and I was just going to push the commit. So there's no need to make any changes in it?
