### ISSUE TITLE
[BUG] Running localhost, cannot make request when no internet connection

### ISSUE THREAD

**Issue by ilomon10** [refinedev/refine#5510]
### Describe the bug

I running a refine app on localhost, it should run normal even there's no internet connection

But i cant use the app without internet, i see there is telemetry req error while no connection theni turn off the telemetry through (`Refine` -> `options` -> `disableTelemery: true`). but still not solving the problem, when i see in network console, the requset not start until i connect to internet

### Steps To Reproduce

1. Install refine
2. Setup data and auth provider
3. Login `Success!`
5. Logout
6. Turn off internet connection
7. Retry Login
8. Just loading `Not Working!`
9. Check the network console, no request whatsoever is initiated
10. Retry login
11. Turn on internet connection
12. Check the nework console, request is started
13. Login `Success`

### Expected behavior

It should run normal even in no connection

### Desktop

OS: Linux Ubuntu
Browser: Chrome Latest

**Comment by BatuhanW** [comment]
Hello @ilomon10 how do you expect to login without an internet connection? Can't really see the problem here, as it's expected you can't login or see any data without internet.

**Comment by ilomon10** [comment]
Hello @BatuhanW 
I'm running the project only in local, so all the database and server on local, so why i cant see my own data without internet?

My server is installed on Localhost, my database in localhost, everything in local only there is no effected with outside world

**Comment by BatuhanW** [comment]
Hey @ilomon10 sorry for the misunderstanding, re-opening the issue, we'll investigate it.

**Comment by aliemir** [comment]
Hey @ilomon10, looks like this is an issue with the `@tanstack/query`'s network mode. You can set it to `always` or `offlineFirst` to make it send the requests regardless of the network state.

- Check out the Network Mode docs from the `@tanstack/query` [here](https://tanstack.com/query/v4/docs/react/guides/network-mode)
- Check out the `<Refine />` component config to update it globally [here](https://refine.dev/docs/core/refine-component/#reactquery)

**Comment by ilomon10** [comment]
Thankyou @BatuhanW for reopen the issue 🙇🏻‍♂️ 

Thankyou @aliemir now by setting by this, the request now is started without connection. 🎉 
```javascript
<Refine
  // ...
  options: {
    // ...
    reactQuery: {
      clientConfig: {
        defaultOptions: {
          mutations: {
            networkMode: "offlineFirst" // or replace with "always" to make the request run normally, without connection.
          },
        },
      },
    },
  }
/>
```

**Comment by BatuhanW** [comment]
Hello @ilomon10 would you like to make a contribution by adding this question/answer to our FAQ documentation?

https://github.com/refinedev/refine/blob/master/documentation/docs/guides-concepts/faq/index.md
