### ISSUE TITLE
[FEAT] Add Mantine v7 (latest version)

### ISSUE THREAD

**Issue by NB071** [refinedev/refine#5533]
### Is your feature request related to a problem? Please describe.

Not really. However, the version 5 that is set by default is way too old and missing some of great features of Mantine. Please consider updating the packages related to it, perhaps with `@refinedev/mantine`. 

### Describe alternatives you've considered

The only alternative would be to postpone my project with refine until it is updated since working with old packages are:
1- Deprivation of latest features
2- Potential security risks
3- Huge changes and not being comfortable, esp. if worked with higher versions  
4- Potential dead-ends with some issues because of the patches in new versions. 
and etc.

### Describe the thing to improve

##The upgrade of Mantine library to newest version.##

**Comment by alicanerdurmaz** [comment]
Hello @NB071, thanks for the issue but I will be closing this issue in favor of https://github.com/refinedev/refine/issues/5178
