### ISSUE TITLE
Supabase Inferencer Foreign Key "Cannot Render" [BUG]

### ISSUE THREAD

**Issue by InsightfulFuture** [refinedev/refine#5543]
### Describe the bug

When you have a foreign key in supabase while using the inferencer, it displays `Cannot Render` instead of the actual value. Is there a way around this?

### Steps To Reproduce

Use supabase and inferencer and set up a foreign key

### Expected behavior

Either Have a link to the referenced row or display the actual value

**Comment by BatuhanW** [comment]
Hello @InsightfulFuture please provide a minimal reproducible example with more details.

**Comment by aliemir** [comment]
Hey @InsightfulFuture, "Cannot Render" is displayed when Inferencer fails to understand how to represent the field or cannot find the appropriate resource for the field. You can hover over it to see the reason why it failed to render. 

You can easily fix it by copy-pasting the generated code from the Inferencer and update it according to your needs. Inferencer components are for generating starter codes for your components to give you a faster development process and not recommended for production.
