### ISSUE TITLE
[DOC] The Pixels live demo URL is wrong

### ISSUE THREAD

**Issue by HichamELBSI** [refinedev/refine#5557]
### Documentation issue

The Pixels template live demo URL redirects to the Store template.
https://refine.dev/templates/supabase-crud-app/

### Describe the thing to improve

Update the link url

**Comment by BatuhanW** [comment]
Hello @HichamELBSI thanks for the report! Would you like to create a PR to fix this? Correct URL is: pixels.refine.dev

**Comment by HichamELBSI** [comment]
Sure, I will 😊
