### ISSUE TITLE
[DOC] Data Fetching page link to DataProvider interface is broken

### ISSUE THREAD

**Issue by BenMusch** [refinedev/refine#5588]
### Documentation issue

On this page: https://refine.dev/docs/guides-concepts/data-fetching/

The docs say:
 > To manage data, Refine needs a data provider, which is a function that implements the [DataProvider](https://refine.dev/docs/core/interface-references/#dataprovider) interface.

However, the link (`https://refine.dev/docs/core/interface-references/#dataprovider`) is broken. While the interface-references page exists, there is no `#dataprovider` element and no documentation on the `DataProvider` interface

### Describe the thing to improve

The link should go somewhere useful or not exist

### Describe the solution (optional)

Either the `DataProvider` interface should be documented and linked, or this sentence should be re-written. I am new to this project so I'm not sure if the issue is that this interface does exist and is undocumented or if it doesn't exist at all

**Comment by BatuhanW** [comment]
Hey @BenMusch thanks for the report! We'll check it and get back to you.

**Comment by BatuhanW** [comment]
We are accepting pull requests for this one. The task is as simple as adding `DataProvider` interface definition to [`interface-references`](https://github.com/refinedev/refine/blob/master/documentation/docs/core/interface-references/index.md) page in our documentation.

**Comment by ziqing26** [comment]
Hi @BatuhanW can I work on this? Thanks!
