### ISSUE TITLE
[FEAT]: implement `getApiUrl` in `@refinedev/nestjs-query`

### ISSUE THREAD

**Issue by alicanerdurmaz** [refinedev/refine#5606]
### Is your feature request related to a problem? Please describe.

[`getApiUrl` method](https://github.com/refinedev/refine/blob/master/packages/nestjs-query/src/dataProvider/index.ts#L445C9-L445C18) is not implemented.

### Describe the thing to improve

`getApiUrl` method should return GraphQLClient's URL.

**Comment by 609harsh** [comment]
Hi @alicanerdurmaz please assign this issue to me.

**Comment by userAdityaa** [comment]
Hello, I would like to contribute in it. Is it still under action ?

**Comment by alicanerdurmaz** [comment]
Hello @609harsh, I assigned it to you. Thanks.

@userAdityaa @Sarthakagg31 Thanks, I assigned to @609harsh because @609harsh wrote before. if @609harsh is not available, we will communicate again

**Comment by aliemir** [comment]
Due to inactivity in PR #5844, we're looking for new  contributors to implement this feature 🙏
