### ISSUE TITLE
[DOC] Material UI notifications code sample uses antd

### ISSUE THREAD

**Issue by BenMusch** [refinedev/refine#5620]
### Documentation issue

https://refine.dev/docs/ui-integrations/material-ui/introduction/#notifications

The code sample here does not actually use the material notifications provider

### Describe the thing to improve

The code sample uses the wrong UI package

### Describe the solution (optional)

The code sample should use material ui

**Comment by Mohamed-khattab** [comment]
Hi BenMusch,

I've submitted PR #5621 to address the documentation issue regarding the incorrect usage of the notifications provider in the Material UI integration. This PR updates the code sample to utilize the Material UI notifications provider as recommended.

Please review the changes and provide any feedback or suggestions you may have.

Thanks,
