### ISSUE TITLE
[FEAT] support next js versions like 14

### ISSUE THREAD

**Issue by AbanoubEMhanna** [refinedev/refine#5632]
### Is your feature request related to a problem? Please describe.

i think it will be good if you add options of select versions like next 14 or latest version 

### Describe the thing to improve

i think it will be good if you add options of select versions like next 14 or latest version

**Comment by alicanerdurmaz** [comment]
Hello @AbanoubEMhanna, We have updated [our examples](https://github.com/refinedev/refine/tree/master/examples/with-nextjs) to Next.js 14 and they are using app router.

In 1 or 2 weeks we will update `npm create refine-app` and the app will create projects with router 🚀
