### ISSUE TITLE
[BUG] cannot run nextjs project created with npm create refine-app

### ISSUE THREAD

**Issue by gianpaj** [refinedev/refine#5648]
### Describe the bug

```
npm run start
$ refine start
...
   ▲ Next.js 14.1.0
   - Local:        http://localhost:3000

[Error: ENOENT: no such file or directory, open '/Users/gianpaj/admin-panel-refine/.next/BUILD_ID'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/gianpaj/admin-panel-refine/.next/BUILD_ID'
}
/Users/gianpaj/admin-panel-refine/node_modules/execa/lib/error.js:60
		error = new Error(message);
			^

Error: Command failed with exit code 1: /Users/gianpaj/admin-panel-refine/node_modules/next/dist/bin/next start
```

### Steps To Reproduce

1. `npm create refine-app@latest`
2. select Nextjs
3. use node 20
4. npm run start

### Expected behavior

works out of the box

### Packages

  "dependencies": {
    "@refinedev/cli": "^2.16.21",
    "@refinedev/core": "^4.47.1",
    "@refinedev/devtools": "^1.1.32",
    "@refinedev/nextjs-router": "^6.0.0",
    "@refinedev/kbar": "^1.3.6",
    "next": "14.1.0",
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "@refinedev/simple-rest": "^5.0.1",
    "@refinedev/antd": "^5.37.4",
    "@ant-design/icons": "^5.0.1",
    "antd": "^5.0.5",
    "js-cookie": "^3.0.5",
    "@ant-design/nextjs-registry": "^1.0.0",
    "next-auth": "^4.24.5"
  },

**Comment by alicanerdurmaz** [comment]
Hello @gianpaj, 

`npm run start` is running production build, you need to build your project before starting.

Please use `npm run dev` for development or build your project with `npm run dev` before starting.
