### ISSUE TITLE
[BUG] app-crm: cannot delete contact note

### ISSUE THREAD

**Issue by diegonc** [refinedev/refine#5651]
Trying to delete a contact note results in the following error:

---
![image](https://github.com/refinedev/refine/assets/261458/a4c028d9-70e7-4826-81b1-a58e32a44576)

---

It seems it tries to delete a contact insted of a note.

Changing the line:

https://github.com/refinedev/refine/blob/af05511094963c3c614f486b453f0838b60216a8/examples/app-crm/src/routes/contacts/components/comment/comment-list.tsx#L137

to

```resource="contactNotes"```

fixes the delete operation. But I'm not sure it is the correct fix as I don't know what the meta entry was supposed to do.

**Comment by alicanerdurmaz** [comment]
@diegonc Thanks for the detailed explanation.

Do you want to work on this? all contributions are welcome 🙌

You can find more detailed explanation about operation name here: https://graphql.org/learn/queries/#operation-name

**Comment by diegonc** [comment]
Yeah, I think I knew what operation name is in the context of GraphQL.

What I don't see is:

- Where is `contactNote` operation defined?
- How is it supposed to delete a note?
- Why let the `DeleteButton` use the route provided resource (in this case contact) instead of explicitly setting it to `contactNotes`?

If I would work on it, I'll be proposing the following change.

```diff
diff --git a/examples/app-crm/src/routes/contacts/components/comment/comment-list.tsx b/examples/app-crm/src/routes/contacts/components/comment/comment-list.tsx
index 0299a882bab..1af39675f34 100644
--- a/examples/app-crm/src/routes/contacts/components/comment/comment-list.tsx
+++ b/examples/app-crm/src/routes/contacts/components/comment/comment-list.tsx
@@ -134,7 +134,7 @@ const ContactCommentListItem = ({ item }: { item: ContactNote }) => {
                         </Typography.Link>
                         <DeleteButton
                             recordItemId={item.id}
-                            meta={{ operation: "contactNote" }}
+                            resource="contactNotes"
                             size="small"
                             type="link"
                             successNotification={() => ({
```

For the above patch, I managed to make a clone of the repository at a work computer with fast network but I only have shell access.

Setting up a dev environment at home to make a proper PR will take some time as my network is slow and the repository quite big.

**Comment by alicanerdurmaz** [comment]
> Yeah, I think I knew what operation name is in the context of GraphQL.
> 
> What I don't see is:
> 
> * Where is `contactNote` operation defined?
> * How is it supposed to delete a note?
> * Why let the `DeleteButton` use the route provided resource (in this case `contact`) instead of explicitly setting it to `contactNotes`?
> 
> If I would work on it, I'll be proposing the following change.
> 
> ```diff
> diff --git a/examples/app-crm/src/routes/contacts/components/comment/comment-list.tsx b/examples/app-crm/src/routes/contacts/components/comment/comment-list.tsx
> index 0299a882bab..1af39675f34 100644
> --- a/examples/app-crm/src/routes/contacts/components/comment/comment-list.tsx
> +++ b/examples/app-crm/src/routes/contacts/components/comment/comment-list.tsx
> @@ -134,7 +134,7 @@ const ContactCommentListItem = ({ item }: { item: ContactNote }) => {
>                          </Typography.Link>
>                          <DeleteButton
>                              recordItemId={item.id}
> -                            meta={{ operation: "contactNote" }}
> +                            resource="contactNotes"
>                              size="small"
>                              type="link"
>                              successNotification={() => ({
> ```
> 
> For the above patch, I managed to make a clone of the repository at a work computer with fast network but I only have shell access.
> 
> Setting up a dev environment at home to make a proper PR will take some time as my network is slow (5Mbit/s, in good days) and the repository quite big (2.35 GiB).

You are absolutely right. Thank you for the solution. We would be very happy if you would like to open a PR 🙌

**Comment by diegonc** [comment]
Sure. I'll make the PR. Is there anything else to tackle? Or only the patch above is ok?

**Comment by alicanerdurmaz** [comment]
> Sure. I'll make the PR. Is there anything else to tackle? Or just the patch above is ok?

I believe It's ok. Thank you 🙌
