### ISSUE TITLE
[BUG] Supabase useImport onSucces failure

### ISSUE THREAD

**Issue by derekfinlinson** [refinedev/refine#5655]
### Describe the bug

I'm using useImport and it imports the records correctly but is throwing an error: "Cannot read properties of null (reading 'filter')". I tracked it down to the createMany API call. I'm using supabase and it returns an empty body. But the useCreateMany hook is expecting a body and so is trying to filter a null value. 

### Steps To Reproduce

1. Add useImport hook
2. Import records
3. Add onFinish handler to catch errors

### Expected behavior

Success response returned since records are imported correctly

### Packages

@refinedev/core - 4.47.1

**Comment by alicanerdurmaz** [comment]
@derekfinlinson Thanks for the issue, we will debug it and return you.

**Comment by derekfinlinson** [comment]
I created a new refine project and only added the import button to the blog posts and got the same error. It does create the records and I get the 201 response as well but I also get this in the second image in the console about an error reading filter which is coming from the createMany call trying to read from the response body when there isn't one.

![image](https://github.com/refinedev/refine/assets/1828325/94fc3c71-77f5-4ad4-a208-106cfaf03318)

![image](https://github.com/refinedev/refine/assets/1828325/df9155ad-41a3-4dad-b3d2-004b82d4829f)

**Comment by alicanerdurmaz** [comment]
Hey @derekfinlinson, I believe this will solve the problem. Supabase requires to specify fields

```ts
const importProps = useImport({
        meta: {
            select: "*",
        },
});
```

**Comment by endrit-mesh** [comment]
> ```ts
> select: "*",
> ```

I encountered the same issue with useCreateMany, but managed to resolve it by specifying the fields. However, it would be beneficial to have this documented for others facing similar issues. Thank you

**Comment by alicanerdurmaz** [comment]
@endrit-mesh Yes you are right, thank you 🙌
