### ISSUE TITLE
[FEAT] Editable MUI Data Grid

### ISSUE THREAD

**Issue by beg1c** [refinedev/refine#5656]
### Is your feature request related to a problem? Please describe.

There is currently no quick way to implement editable MUI Data Grid. 

### Describe alternatives you've considered

There is alternative of using useEditableTable in Ant Design System. 

### Describe the thing to improve

It would be very helpful if editable Data Grid could be set up quickly, like Editable Table in Ant.

**Comment by alicanerdurmaz** [comment]
@beg1c Yes, it would be great. Thanks for the issue. 

We are open to contributions 🙌

**Comment by issa012** [comment]
Hello! I would be happy to work on this issue

**Comment by BatuhanW** [comment]
Hey @issa012, assigned this issue to you. Please make sure to follow our [contributing guide](https://refine.dev/docs/guides-concepts/contributing).

**Comment by beg1c** [comment]
@issa012 If you change your mind please let me know. I already looked at ways to implement this, but had no free time to do it. I'll be happy to take over.

**Comment by lnikitadobrenkol** [comment]
Hello! I see this feature is already assigned and have a PR. But I also see that the last update was a while ago, and PR is closed. I'd like to work on this feature. How would you guys recommend proceeding

**Comment by lnikitadobrenkol** [comment]
@BatuhanW, @beg1c, @alicanerdurmaz - I am starting the work on the PR. Please let me know if any objections and concerns about it will arise.

**Comment by BatuhanW** [comment]
Hey @lnikitadobrenkol assigned issue to you. Looking forward to your PR.

**Comment by lnikitadobrenkol** [comment]
Sure, thank you, I am working on it.
