### ISSUE TITLE
[BUG] `onFinish` promise is never rejected

### ISSUE THREAD

**Issue by jaulz** [refinedev/refine#5667]
### Describe the bug

If there is a mutation error, the `onFinish` promise is supposed to be rejected but right now the Promise never finishes because the `reject` function is not called:
https://github.com/refinedev/refine/blob/ae34559a5e44a878e85514d4cc137539e060aeae/packages/core/src/hooks/form/useForm.ts#L461-L464

(same applies for the error handler of update)

I think either the reject function should be passed to the `onMutationError` handler or the reject function should be called in every case.

### Steps To Reproduce

1. Submit a form that throws a mutation error
2. Check if the `onFinish` handler rejects 

### Expected behavior

The `onFinish` handler should not only resolve but also reject in case of any errors.

### Packages

@refinedev/core@latest

**Comment by prabhanshjn** [comment]
Hi @jaulz ,
I would be happy to contribute to this bug. I would want to know more details on how we can test this and call this Promise function.

Can you assign this to me?

**Comment by jaulz** [comment]
@prabhanshjn I just raised a PR at https://github.com/refinedev/refine/pull/5697 but feel free to contribute.

**Comment by prabhanshjn** [comment]
Thanks @jaulz ,
I think what has to be done is,
we remove the return statement from onMutationError, as that is why reject() will never be called.

What we can do is instead is add return in reject statement and that will solve the problem.

**Comment by BatuhanW** [comment]
Closing in favor of https://github.com/refinedev/refine/issues/5702, we'll be handling this and similar other cases with this issue.
