### ISSUE TITLE
[BUG] <Show isLoading={true}> with Material UI doesn't show loading spinner

### ISSUE THREAD

**Issue by rners01** [refinedev/refine#5668]
### Describe the bug

`<Show isLoading={true}>` with Material UI doesn't show loading spinner

### Steps To Reproduce

1. Create <Show> view with isLoading prop set to true
2. Observe no spinner shown

### Expected behavior

Spinner on `isLoading=true`

### Packages

"@refinedev/cli": "2.16.24",
"@refinedev/core": "4.47.1",
"@refinedev/kbar": "1.3.6",
"@refinedev/mui": "5.14.4",
"@refinedev/react-hook-form": "4.8.14",
"@refinedev/react-router-v6": "4.5.5",
"@refinedev/simple-rest": "5.0.2",

**Comment by issa012** [comment]
Hello, I tried to recreate this bug. It is working as you said, there is no loading spinner. However, I think that is the expected behavior. When loading, the component doesn't show a loading spinner, but disables the refresh button. I found that here in the documentation:
https://refine.dev/docs/ui-integrations/material-ui/components/basic-views/show/#isloading

**Comment by BatuhanW** [comment]
Thanks for the explanation, @issa012. As mentioned you can use this prop to disable refresh button.

**Comment by rners01** [comment]
@BatuhanW @issa012 
It's not looking pretty with default values displaying first and then jumping to the API data.
Also Mantine and Ant UI integrations have loading spinner for such scenarios, that's why I though it could be the bug.
So there's no plan to add spinner?

**Comment by issa012** [comment]
I can try, if you assign this to me.

**Comment by BatuhanW** [comment]
Sure, assigned to you. 🚀

**Comment by rners01** [comment]
@BatuhanW Was the feature merged?

**Comment by 0xJaskeerat** [comment]
Hey @rners01 @BatuhanW 
I would love to try on this issue , can you please assign me ?

**Comment by BatuhanW** [comment]
@0xJaskeerat assiged issue to you.

**Comment by paoloLigsay** [comment]
I noticed this issue has been stale for a while. I can work on this, could you please assign it to me, @BatuhanW? Thanks!

**Comment by aliemir** [comment]
I'll leave a comment here to help anyone interested to work on this issue about what we want from the implementation. 🙏 

This fix needs to be implemented for `<Create />`, `<Edit />` and `<Show />` components. `isLoading` prop should be used to display a spinner overlaying the content. 

To avoid any layout shifts, we're recommending using some `absolute` positioned box inside the `<Card />` and positioning the `<Card />` as `relative`.

We can pass `sx.position = "relative"` but also allow overriding this value like:

```ts
    <Card
      {...(wrapperProps ?? {})}
      sx={{
        position: "relative",
        ...wrapperProps?.sx,
      }}
    >
```

Then we can place a `<CircularProgress />` wrapped with `<Box />` inside the `<Card />` like below:

```ts
      {isLoading && (
        <Box
          sx={{
            position: "absolute",
            inset: 0,
            display: "flex",
            justifyContent: "center",
            alignItems: "center",
            zIndex: (theme) => theme.zIndex.drawer + 1,
            // this is needed to support custom themes, dark mode etc.
            bgcolor: (theme) => alpha(theme.palette.background.paper, 0.4),
          }}
        >
          <CircularProgress />
        </Box>
      )}
```

I'm not sure if this covers all the necessary cases but I guess it will be a good starting point for the implementation.

We'll be happy to help if anyone is interested working on this issue. 🚀

**Comment by Anonymous961** [comment]
@aliemir is this issue fixed?
![image](https://github.com/user-attachments/assets/02b88a2e-a486-45e6-a846-df4c210629dd)

**Comment by aliemir** [comment]
Hey @Anonymous961, your screenshot is from Ant Design. This issue is related with our Material UI CRUD components and its still looking for contributors 🙏

**Comment by UjjwalBaranwal** [comment]
Hello
Is this issue still open 
I want to contribute to this
