### ISSUE TITLE
[FEAT] Unified Form View in refine.dev (create, show, edit)

### ISSUE THREAD

**Issue by patbengr** [refinedev/refine#5675]
### Is your feature request related to a problem? Please describe.

Currently, refine.dev provides separate views for showing, editing, and creating records. While this modular approach is useful in many cases, it can sometimes result in duplicated code when the same fields and layout are required for both creating and editing records. To address this concern and promote a more streamlined development process, I suggest the introduction of a new view type, which I would like to call the "Form View" or "Record View."

### Describe the thing to improve

The Form View or Record View would serve as a unified view that combines the functionalities of creating, editing, and showing records. Developers could use this single view for all operations related to a particular record, reducing the need for duplicate code and ensuring a more maintainable codebase.

I have begun working on the implementation of this feature. As part of this process, I encountered the need to refactor prop types, such as creating RefineCrudFormProps like RefineCrudEditProps. I also had to create FormProps like EditProps for libraries like Ant Design. While progressing, I've faced some challenges in finding the optimal approach to tackle this.

The useForm() hook in refine.dev already supports action, allowing developers to pass information on whether it's an edit or create operation. For instance, one can specify "edit" if a record ID exists and "create" if it doesn't. This provides a flexible mechanism to handle different scenarios within the unified Form View.

The show functionality can be integrated into the edit form, with a state toggle to enable or disable editing.

Feel free to suggest alternative approaches, highlight potential challenges, or discuss additional features that could enhance the proposed Form View.

**Comment by BatuhanW** [comment]
Hey @patbengr we don't have a such feature in our roadmap. However, feel free to create an open-source package with your desired features. We may add your package to our documentation's community packages section if we see fit.
