### ISSUE TITLE
[DOC] - Supabase exemple error

### ISSUE THREAD

**Issue by jibize** [refinedev/refine#5678]
### Documentation issue

in the Supabase codesandbox [example](https://refine.dev/docs/data/packages/supabase/#example), we can't create a new blog post. The following error is thrown:
`null value in column "status" of relation "blog_posts" violates not-null constraint
There was an error creating blog_post (status code: 23502)`

### Describe the thing to improve

.

**Comment by alicanerdurmaz** [comment]
@jbeaudlet Thanks for the issue.

The Example needs `status` field on forms [like this](https://github.com/refinedev/refine/blob/master/examples/base-antd/src/pages/posts/edit.tsx#L60) 

Do you want to work on this? All PR's are welcome 🙌

**Comment by jbeaudlet** [comment]
Thank you @MahmoudMousaHamad, that was (too) quick. ;-)

**Comment by MahmoudMousaHamad** [comment]
No problem :)
