### ISSUE TITLE
[BUG] - Using Supabase data provider, the onMutationSuccess callback from useForm doesn't return data

### ISSUE THREAD

**Issue by jibize** [refinedev/refine#5679]
### Describe the bug

Using the Supabase data provider, in useForm() the onMutationSuccess callback doesn't return any data.

### Steps To Reproduce

1. go to this [condesandbox](https://codesandbox.io/p/devbox/dreamy-hopper-ykwdf7?workspaceId=25cf0d17-786f-4d91-b420-7d73415655ab&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clst9m7pa00073p6fb69bjwja%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clst9m7pa00023p6fjtxphfc5%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clst9m7pa00043p6frcb4scix%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clst9m7pa00063p6foedto03v%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B60%252C40%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clst9m7pa00023p6fjtxphfc5%2522%253A%257B%2522id%2522%253A%2522clst9m7pa00023p6fjtxphfc5%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clst9m7pa00063p6foedto03v%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clst9m7pa00053p6fb83skgj4%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252Fblog-posts%253FpageSize%253D10%2526current%253D1%2526sorters%255B0%255D%255Bfield%255D%253Did%2526sorters%255B0%255D%255Border%255D%253Dasc%2522%257D%255D%252C%2522id%2522%253A%2522clst9m7pa00063p6foedto03v%2522%252C%2522activeTabId%2522%253A%2522clst9m7pa00053p6fb83skgj4%2522%257D%252C%2522clst9m7pa00043p6frcb4scix%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clst9m7pa00033p6f5fty4mur%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522clst9m7pa00043p6frcb4scix%2522%252C%2522activeTabId%2522%253A%2522clst9m7pa00033p6f5fty4mur%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) taken from the Supabase codesandbox [example](https://refine.dev/docs/data/packages/supabase/#example)
2. edit a blog post and save, look at the console log that prints the variables from the onMutationSuccess callback. data is undefined

### Expected behavior

According to the [doc](https://refine.dev/docs/data/hooks/use-form/#onmutationsuccess), data should hold the result of the mutation.

### Packages

- @refine/supabase

### Additional Context

The problem seems to be present when creating new record as well. The codesandbox doesn't show this because at the moment we can't create a new record from the Supabase example, see #5678.

**Comment by zelbazk** [comment]
Having the same experience. 

`"use client";

import { Create, useForm } from "@refinedev/antd";
import { Form, Input } from "antd";

import { useCreate } from "@refinedev/core";
import { ITemplate } from "@utility/interfaces";

export default function BlogPostCreate() {
  const { mutate } = useCreate();
  const { formProps, saveButtonProps } = useForm({
    onMutationSuccess: (data, variables, context, isAutoSave) => {
      console.log({ data, variables, context, isAutoSave });
    },
  });

  return (
    <Create saveButtonProps={saveButtonProps}>
      <Form {...formProps} layout="vertical">
        <Form.Item
          label={"Title"}
          name={["title"]}
          rules={[
            {
              required: true,
            },
          ]}
        >
          <Input />
        </Form.Item>
      </Form>
    </Create>
  );
}`

**Comment by alicanerdurmaz** [comment]
Hello @jbeaudlet @zelbazk,

What is the response in your tests? In my tests, response is empty so because of that onMutationSuccess data is undefined

Request URL:
https://iwdfzvfqbtokqetmbmbp.supabase.co/rest/v1/blog_posts?id=eq.000e3b65-43f5-4b0d-891b-ad73df4033e8
Request Method:
PATCH
Status Code:
204 No Content

<img width="300" alt="image" src="https://github.com/refinedev/refine/assets/23058882/53d4942e-6cc4-4000-b9be-ac14d1cfa8c5">

**Comment by zelbazk** [comment]
Hi @alicanerdurmaz Thanks for pointing this out. it's the same for me. Do you know why the response is empty and not returning anything? I am using the refine/supabase data provider, is there a setting I am missing?

**Comment by alicanerdurmaz** [comment]
Hello again @jibize @zelbazk,

for supabase to return data, we need to specify the fields we want. you can use like this

```ts
    const { formProps, saveButtonProps } = useForm({
        meta: {
            select: "*",
        },
    });
```

**Comment by jibize** [comment]
Hi @alicanerdurmaz,

  Thank you for the tip. Is this the intended behaviour? There is no mention in the [doc](https://refine.dev/docs/data/hooks/use-form/#onmutationsuccess). Also it looks like when using another data provider we don't need to set the meta select option. Also in Supabase doc, when the data is needed back, select() needs to be set at the end of the query. See my pull request.

**Comment by alicanerdurmaz** [comment]
@jibize I believe select("*") should be the default, thanks for the PR 🙌

**Comment by issa012** [comment]
Hi @alicanerdurmaz @BatuhanW I think I know how to fix this issue. First of all, in order to update and return the data, select() should be appended at the end of the query, as per the Supabase [docs](https://supabase.com/docs/reference/javascript/update?example=update-a-record-and-return-it). However, 1 test, which should return error PGRST106 is failing. I think it it is failing because it doesn't expect the "select" parameter to be in the query, that is why it is throwing ERR_NOCK_NO_MATCH. I added the select parameter, and the test is working correctly. Please, assign this to me so I can submit a PR.
