### ISSUE TITLE
[FEAT] support _not operator query for hasura data provider

### ISSUE THREAD

**Issue by nbourdin** [refinedev/refine#5689]
### Is your feature request related to a problem? Please describe.

I tried to make the following query with filters and hasura data provider

```
query query {
  event(where: {_not: {group_event: {event__id: {_is_null: false}}}}, limit: 10) {
    id
    group_event {
      event__id
    }
  }
}
```

But the "not" operator doesn't seem to be supported in filter management (https://refine.dev/docs/advanced-tutorials/data-provider/handling-filters/#crudfilters). 

### Describe alternatives you've considered

I used the graphql query in the meta field
https://refine.dev/docs/data/packages/hasura/#developer-experience

### Describe the thing to improve

Implements the not operator ?

**Comment by BatuhanW** [comment]
Hey @nbourdin thanks for the issue! We are open to contributions from the community. I guess the changes needs to be done here: https://github.com/refinedev/refine/blob/master/packages/hasura/src/utils/generateFilters.ts

**Comment by rilrom** [comment]
I'm happy to take a look at this one @BatuhanW.

**Comment by BatuhanW** [comment]
Hey @rilrom assigned to you. Please take a good look at our [contributing guide](https://refine.dev/docs/guides-concepts/contributing/) and **do not create pull requests** until you complete all the requirements in the PR description.
