### ISSUE TITLE
[FEAT] new integrate @tanstack/router

### ISSUE THREAD

**Issue by okxiaoliang4** [refinedev/refine#5708]
### Is your feature request related to a problem? Please describe.

I am doing integrate `@tanstack/router` to my refine project, `@tanstack/router` has nice DX. I want to add a new package in to `refine` packages.

### Describe the thing to improve

- [ ] add a new package @refine/tanstack-router
- [ ] docs update

**Comment by Sarthakagg31** [comment]
I would be happy to help with this one

**Comment by BatuhanW** [comment]
Hey @okxiaoliang4, thanks for the issue! Right now, we are not considering adding support for `@tanstack/router`.

However, you can create an npm package yourself and publish it. We can add your package to our documentation's community packages section.
