### ISSUE TITLE
[BUG] devtools login not work in Safari

### ISSUE THREAD

**Issue by linkscope** [refinedev/refine#5753]
### Describe the bug

Hello, when I use devtools in Safari, the error Invalid-session-token will be reported when logging in. This problem will occur regardless of whether I use Github or Google to log in.

### Steps To Reproduce

1. Open the project in Safari
2. Login when using devtools
3. The pop-up page reports an error Invalid-session-token 

### Expected behavior

Log in successfully in Safari

### Packages

- @refinedev/devtools

### Additional Context

My MacOS version is Sonoma 14.3.1, Safari version is 17.3.1.

**Comment by BatuhanW** [comment]
Hey @linkscope thanks for the report, we'll check it soon.

**Comment by aliemir** [comment]
Hey @linkscope sorry for the issue 🙏 I've just opened up a PR to address this issue. Authentication flow was broken due to cookie issues in Safari. I added a small tweak to the proxy tested it in Chrome and Safari, both are working fine 🚀

**Comment by linkscope** [comment]
> Hey @linkscope sorry for the issue 🙏 I've just opened up a PR to address this issue. Authentication flow was broken due to cookie issues in Safari. I added a small tweak to the proxy tested it in Chrome and Safari, both are working fine 🚀

Thanks a lot for solving this problem and thanks to the team, your efficient work will motivate more people to use Refine.

**Comment by lekhok** [comment]
Facing Same Issue currently, "Invalid Session Token" when signing in with Github

Google Signin doesn't show any error toast notification but redirects to the same login page again.

    "@refinedev/cli": "^2.16.21",
    "@refinedev/core": "^4.47.1",
    "@refinedev/devtools": "^1.1.32",
    "@refinedev/kbar": "^1.3.6",
    
    Safari Version 17.5 
    
    As on date : June 13 2024

<img width="1440" alt="Screenshot 2024-06-13 at 19 32 58" src="https://github.com/refinedev/refine/assets/129063617/4ea62b13-5af3-4e49-83e6-49251eeb9170">

**Comment by Ezers06** [comment]
Also facing same issue but "Invalid Session Token" only show when signing in with Google but my problem is on both Safari and Chrome

Github doesn't show any toast message but keep redirect to login page
    
    "@refinedev/cli": "^2.16.21",
    "@refinedev/core": "^4.47.1",
    "@refinedev/devtools": "^1.1.32",
    "@refinedev/nextjs-router": "^6.0.0",
    "@refinedev/kbar": "^1.3.6",
    
    Date : June 13 2024

**Comment by lekhok** [comment]
> Also facing same issue but "Invalid Session Token" only show when signing in with Google but my problem is on both Safari and Chrome
> 
> Github doesn't show any toast message but keep redirect to login page
> 
> ```
> "@refinedev/cli": "^2.16.21",
> "@refinedev/core": "^4.47.1",
> "@refinedev/devtools": "^1.1.32",
> "@refinedev/nextjs-router": "^6.0.0",
> "@refinedev/kbar": "^1.3.6",
> 
> Date : June 13 2024
> ```

I opened a new issue #6047
