### ISSUE TITLE
[FEAT] Adding <RefreshButton> to a List component

### ISSUE THREAD

**Issue by kyundos** [refinedev/refine#5763]
### Is your feature request related to a problem? Please describe.

Hello, I'm struggling to add a <RefreshButton> component to my user's List page. Here's the approach i've tryed so far:

import {
  List,
  useTable,
  RefreshButton,
  EditButton,
  ShowButton,
  DeleteButton,
} from "@refinedev/antd";

export const UserList: React.FC<IResourceComponentsProps> = () => {
  const { tableProps } = useTable<IUser>({
    initialSorter: [{ field: "last_name", order: "asc" }],
    syncWithLocation: true,
  });

return (
    <List
      headerButtons={({ defaultButtons, refreshButtonProps }) => (
        <>
          {defaultButtons}
          <RefreshButton {...refreshButtonProps} resource="users" />
        </>
      )}
    >
      <Table
        {...tableProps}
        rowKey="id"
        pagination={{
          pageSizeOptions: ["10", "20", "50", "100", "200"],
          showSizeChanger: true,
          total: tableProps.pagination.total,
          current: tableProps.pagination.current,
          pageSize: tableProps.pagination.pageSize,
        }}
      >
    ...
  );
}

Button is actually where it should have to be but, if clicked, there's no way to trigger an update of the user's list. Works flawlessly if used in Show page btw. What am I doing wrong?

### Describe the thing to improve

Is there a way to make it works?
Thanks in advance

**Comment by BatuhanW** [comment]
This is not a place to ask questions. You can refer to our documentation and AI ChatBot if you need help. https://refine.dev/docs/
