### ISSUE TITLE
BUG: NextRouter was not mounted. invariant expected app router to be mounted

### ISSUE THREAD

**Issue by jahansoft** [refinedev/refine#5768]
### Describe the bug

we have updated the next version and this issue raised while build time. we have tried refine update but this never goes. locally it's working fine and view is clear with no error. Issue only appears once we create a build or while deploy time.
![image](https://github.com/refinedev/refine/assets/77854527/f559c96f-ce04-4c53-a542-ffd8659d53d0)

### Steps To Reproduce

Update the next version
use typescript
create build
issue is there

### Expected behavior

![image](https://github.com/refinedev/refine/assets/77854527/35a8fce0-5c94-47e7-b9b8-6b82b657fcc7)

### Packages

"@refinedev/cli": "2.16.27",
"@refinedev/core": "4.48.0",
"@refinedev/devtools": "1.1.35",
"@refinedev/inferencer": "4.5.21",
"@refinedev/kbar": "1.3.7",
"@refinedev/mui": "5.14.5",
"@refinedev/nextjs-router": "^6.0.1",
"@refinedev/react-hook-form": "4.8.15",
"@refinedev/simple-rest": "5.0.3",

**Comment by BatuhanW** [comment]
Hello @jahansoft could you provide a minimal reproducible example? 

You can also check our [documentation page](https://refine.dev/docs/routing/integrations/next-js/) and [nextjs example](https://github.com/refinedev/refine/blob/master/examples/with-nextjs)
