### ISSUE TITLE
[BUG] Missing metadata passed from useNavigation methods.

### ISSUE THREAD

**Issue by soonoo** [refinedev/refine#5785]
### Describe the bug

`show` method from `useNavigation` hook accepts metadata as a fourth parameter. Where can I access that metatdata?  
Neither data provider's `getOne` nor the `useShow` hook can access that data.

### Steps To Reproduce

```javascript
const { show } = useNavigation();

return (
  <Button onClick={() => show("resource-name", id, undefined, { a: 123, b: 456 })} />
);
```

### Expected behavior

metadata is accessible from somewhere. (url, useShow, getOne ..)

### Packages

"@refinedev/core": "^4.48.0"

**Comment by BatuhanW** [comment]
Hey @soonoo you can access it from query params.

https://refine.dev/docs/routing/hooks/use-navigation/#return-values
