### ISSUE TITLE
[DOC] Documenting that `@refinedev/react-router-v6` is working with `<RouterProvider>` also

### ISSUE THREAD

**Issue by sharky98** [refinedev/refine#5797]
### Documentation issue

In their v6.4, `react-router-dom` added an alternative to the Router Components (like the know [`<BrowserRouter>`](https://reactrouter.com/en/main/router-components/browser-router) by using a [`<RouterProvider>`](https://reactrouter.com/en/main/routers/router-provider) with [data API routers](https://reactrouter.com/en/main/routers/picking-a-router).

All documentation of its [integration](https://refine.dev/docs/routing/integrations/react-router/) (there are also example code shown [here](https://refine.dev/docs/guides-concepts/routing/#react-router) and [there](https://refine.dev/docs/guides-concepts/routing/#router-integrations)) in Refine uses the `<BrowserRouter>` method.

### Describe the thing to improve

The doc should be improved to document the fact that using `<RouterProvider>`, with a [`createBrowserRouter()`](https://reactrouter.com/en/main/routers/create-browser-router) is supported and works out of the box (at least, according to #4715 and my limited usage for now[^1]).

Also, it is not clear how all these data apis interact with the integration, including the [loaders](https://reactrouter.com/en/main/route/loader), [fetchers](https://reactrouter.com/en/main/hooks/use-fetcher) and [actions](https://reactrouter.com/en/main/route/action). They seems to provide features that overlap somewhat with Refine.

[^1]: I don't know if there is some smoke tests for `@refinedev/react-router-v6`, but maybe adding some more using the `<RouterProvider>` could be useful?

### Describe the solution (optional)

I think a quick win would be to show the [Basic Usage](https://refine.dev/docs/routing/integrations/react-router/#basic-usage) example with tabs, one with the current code and one using the `<RouterProvider>`. Here what it could look like, using the [migration guide they provide](https://reactrouter.com/en/main/upgrading/v6-data). I did not test the code, simply applied the migration guide.

```typescript
import { Refine } from "@refinedev/core";
import dataProvider from "@refinedev/simple-rest";
import routerProvider from "@refinedev/react-router-v6";
import { createBrowserRouter, RouterProvider, Outlet } from "react-router-dom";

import { PostList, PostCreate } from "pages/posts";
import { CategoryList, CategoryShow } from "pages/categories";

const router = createBrowserRouter([
  {
    Component: RefineProvider,
    children: [
      {
        path: "posts",
        children: [
          { index: true, Component: PostList },
          { path: "create", Component: PostCreate },
        ],
      },
      {
        path: "categories",
        children: [
          { index: true, Component: CategoryList },
          { path: "show/:id", Component: CategoryShow },
        ],
      },
    ],
  },
]);

const App = () => {
  return <RouterProvider router={router} />;
}

const RefineProvider = () => {
  return (
    <Refine
      dataProvider={dataProvider}
      routerProvider={routerProvider}
      resources={[
        {
          name: "posts",
          list: "/posts",
          create: "/posts/create",
        },
        {
          name: "categories",
          list: "/categories",
          show: "/categories/show/:id",
        },
      ]}
    >
      <Outlet />
    </Refine>
  );
}
```

**Comment by BatuhanW** [comment]
Hey @sharky98 nice catch! Would you like to submit a PR ?
