### ISSUE TITLE
[DOC] Broken tutorial on UI libraries section

### ISSUE THREAD

**Issue by sinedie** [refinedev/refine#5802]
### Documentation issue

Tutorial on UI-libraries section is broken. Don't load and all next sections are unreachable.

Browser: Firefox 123.0

### Describe the thing to improve

Go to https://refine.dev/tutorial/ui-libraries/layout/ant-design/react-router/

![2024-03-29T09:37:42,614852875-05:00](https://github.com/refinedev/refine/assets/43920544/f583fb6a-696f-4715-84f1-ede10ad5b2fb)

**Comment by BatuhanW** [comment]
Hey @sinedie thanks for the issue, it's caused by https://github.com/emotion-js/emotion/issues/2413. Will look into it.

**Comment by Om-GG** [comment]
I'm having the same issue with MUI. Thanks for looking into this!
