### ISSUE TITLE
[BUG] env utility breaks Vite dotenv conventions

### ISSUE THREAD

**Issue by seniorquico** [refinedev/refine#5803]
### Describe the bug

Vite uses dotenv (and a plugin or two) to load values from files with the following conventions:

```
.env                # loaded in all cases
.env.local          # loaded in all cases, ignored by git
.env.[mode]         # only loaded in specified mode
.env.[mode].local   # only loaded in specified mode, ignored by git
```

Additionally, it behaves according to the following description:

> An env file for a specific mode (e.g. .env.production) will take higher priority than a generic one (e.g. .env).
> 
> In addition, environment variables that already exist when Vite is executed have the highest priority and will not be overwritten by .env files.

([reference](https://vitejs.dev/guide/env-and-mode))

The Refine CLI automatically loads values in the `.env` file which appear to persist in the environment when executing the Vite commands (i.e. `vite dev`).

https://github.com/refinedev/refine/blob/16eefc493da3e66a095a11d9dcbeff0ec64dca57/packages/cli/src/utils/env/index.ts#L3

These take precedence and effectively break the `.env.local`, `.env.development`, etc. conventions of Vite.

CRA has slightly different but similar conventions. I assume the Refine CLI would be affecting it similarly?

### Steps To Reproduce

1. Create a Refine/Vite project.
2. Create a `.env` file with the content `VITE_TITLE=production`.
3. Create a `.env.development` file with the content `VITE_TITLE=development`.
4. Run `npm run refine dev`.
5. Observe the value of `import.meta.env.VITE_TITLE` is "production", not "development".

### Expected behavior

The Refine CLI shouldn't break Vite's dotenv conventions. In the trivial example provided, the value of `import.meta.env.VITE_TITLE` should be "development" from the `.env.development` file.

### Packages

- "@refinedev/cli": "2.16.27"
- "@refinedev/core": "4.48.0"
- "@refinedev/kbar": "1.3.7"
- "@refinedev/mui": "5.14.5"
- "@refinedev/react-hook-form": "4.8.15"
- "@refinedev/react-router-v6": "4.5.6"
- "vite": "5.2.7"
- package manager: Yarn 4.1.1 w/ node_modules linker

### Additional Context

I explicitly renamed my `.env` file to `.env.production` to "workaround" the issue. That file appears to not be loaded by the Refine CLI, and then my app builds as expected. It's an unfortunate workaround, effectively forcing us to not use the `.env` file and "layering" of settings.

**Comment by BatuhanW** [comment]
Hey @seniorquico we've discussed with the team and thinking that parsing dotenv files in CLI may not be needed at all. I think we could get rid of it and let the underlying framework (Vite, NextJs) take care of it.

**Comment by BatuhanW** [comment]
We are open to contributions for this one.

**Comment by thienandangthanh** [comment]
I have similar problem with Next.js.
Next.js use the same dotenv convention as Vite.
Here's the documentation of it about [Environment Variable Load Order](https://nextjs.org/docs/pages/building-your-application/configuring/environment-variables#environment-variable-load-order)

**Comment by PriyeshPandey2000** [comment]
Hello @BatuhanW would love to work on this issue . Can you provide me little more context on what is needed to be done ?

**Comment by aliemir** [comment]
Let me try to clarify what can be done here to avoid conflicts. For now, we can keep using `.env` file only and don't take other files into account. By default `dotenv.config()` will store values in `process.env` and those will persist in processes spawned by the CLI. We can pass `processEnv` prop to `config()` and prevent it from populating `process.env`. Example below:

```ts
const refineEnv = {};
dotenv.config({ processEnv: refineEnv });

export const ENV = {
  REFINE_NO_TELEMETRY: process.env.REFINE_NO_TELEMETRY || refineEnv.REFINE_NO_TELEMETRY || "false",
  // ....
```

This way we'll still be prioritizing inlined vars and keep `process.env` clean for the next process 🙌 

PRs are welcome for anyone who wants to work on this! Let us know if any help is needed 🙏
