### ISSUE TITLE
[BUG] Register AuthPage using wrong i18n key

### ISSUE THREAD

**Issue by BlackBearFTW** [refinedev/refine#5816]
### Describe the bug

When using the register authpage in combination with i18n, the default auth page is using the wrong key for the "Already have an account" text. It uses `pages.login.buttons.haveAccount` even tho in the i18n translation file offered by the refine documentation has that key in the `pages.register.buttons.haveAccount`. This should be changed so it matches `pages.login.buttons.noAccount`

### Steps To Reproduce

1. Create a refine project (for example vite)
2. Setup i18n using the refine documentation
3. Switch languages to a non-english language
4. See the register page

### Expected behavior

It should use the correct key and translate the value

### Packages

@refinedev/core
@refinedev/antd

**Comment by BatuhanW** [comment]
Hey @BlackBearFTW thanks for the issue. We are open to contributions for this one.

**Comment by Ac-Srikanth** [comment]
Hey @BatuhanW since the PR linking to this issue is closed. Can i take this up ?. will keep the PR template and provide the necessary info this time.

**Comment by BlackBearFTW** [comment]
I can still do it, will take it up in a bit. Will use the PR template this time

**Comment by BlackBearFTW** [comment]
I do not know how to make this changelist without cloning the entire repository to local, so if someone else wants to pick this up go ahead.

**Comment by FatimaSaleem21** [comment]
Hi @BatuhanW, can I work on this?

**Comment by aliemir** [comment]
We're open to contributions on this one! @FatimaSaleem21, If you're still interested I can assign the issue to you and we'll be happy to see your PR! 🚀
