### ISSUE TITLE
This Suspense boundary received an update before it finished hydrating.

### ISSUE THREAD

**Issue by AlexAndrei98** [refinedev/refine#5818]
### Describe the bug

I started working again on a project I left for 3 days and all of a sudden I am getting the error below 
```
Unhandled Runtime Error
Error: This Suspense boundary received an update before it finished hydrating. This caused the boundary to switch to client rendering. The usual way to fix this is to wrap the original update in startTransition.
```

<img width="995" alt="Screenshot 2024-04-03 at 7 13 50 PM" src="https://github.com/refinedev/refine/assets/5164910/516d2fc9-b499-437e-9bde-be27080315cc">

Any pointers would be great!

### Steps To Reproduce

1. 

### Expected behavior

Not sure how to repro as it started popping up right after I do `npm run dev`

### Packages

{
  "name": "electra",
  "version": "0.1.0",
  "private": true,
  "engines": {
    "node": ">=18.0.0"
  },
  "scripts": {
    "dev": "cross-env NODE_OPTIONS=--max_old_space_size=4096 refine dev",
    "build": "refine build",
    "start": "refine start",
    "lint": "eslint '**/*.{js,jsx,ts,tsx}'",
    "refine": "refine"
  },
  "dependencies": {
    "@emotion/react": "^11.8.2",
    "@emotion/styled": "^11.8.1",
    "@mui/icons-material": "^5.8.3",
    "@mui/lab": "^5.0.0-alpha.85",
    "@mui/material": "^5.8.6",
    "@mui/x-charts": "^6.19.4",
    "@mui/x-data-grid": "^6.6.0",
    "@react-pdf/renderer": "^3.3.8",
    "@refinedev/cli": "^2.16.21",
    "@refinedev/core": "^4.46.1",
    "@refinedev/devtools": "^1.1.29",
    "@refinedev/inferencer": "^4.5.16",
    "@refinedev/kbar": "^1.3.5",
    "@refinedev/mui": "^5.14.1",
    "@refinedev/nextjs-router": "^5.5.5",
    "@refinedev/react-hook-form": "^4.8.13",
    "@refinedev/simple-rest": "^5.0.1",
    "@vercel/speed-insights": "^1.0.10",
    "d3": "^7.8.5",
    "next": "^13.0.6",
    "nookies": "^2.5.2",
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "react-pdf": "^7.7.0"
  },
  "devDependencies": {
    "@types/d3": "^7.4.3",
    "@types/node": "^18.0.0",
    "@types/react": "^18.0.0",
    "@types/react-dom": "^18.0.0",
    "@typescript-eslint/parser": "5.48.0",
    "cross-env": "^7.0.3",
    "typescript": "^4.7.4"
  },
  "refine": {
    "projectId": "LqCkSN-iTxp2d-OT9ZPY"
  }
}

**Comment by BatuhanW** [comment]
Hey @AlexAndrei98 I guess this issue is arising from NextJS. Closing the issue, feel free to re-open it if you investigate it and see something related to Refine.
