### ISSUE TITLE
[DOC] error props name in antd useSelect doc page

### ISSUE THREAD

**Issue by j7-dev** [refinedev/refine#5819]
### Documentation issue

go to
https://refine.dev/docs/ui-integrations/mantine/hooks/use-select/#filters

### Describe the thing to improve

![image](https://github.com/refinedev/refine/assets/9213776/ebfcbbfe-9971-4cce-9865-44f1ea8797ce)

### Describe the solution (optional)

add 's' to filter

**Comment by BatuhanW** [comment]
Hey @j7-dev thanks for the detailed report. We are open to contributions.

**Comment by AudreyFW** [comment]
Hi, may I work on this one ?

**Comment by j7-dev** [comment]
@AudreyFW sure, go ahead.

**Comment by AudreyFW** [comment]
It has already been done.
