### ISSUE TITLE
[DOC] Improve DevTools documentation (manual configuration, login, etc.)

### ISSUE THREAD

**Issue by sharky98** [refinedev/refine#5840]
### Documentation issue

I am using a Nx monorepo workspace. I wanted to use `@refinedev/devtools` while keeping my workflow. The documentation make it looks that it is possible (such as [tutorial](https://refine.dev/tutorial/next-steps/devtools/) manual installation section, or the [development guide](https://refine.dev/docs/guides-concepts/development/#using-devtools) also).

However, I was greeted with a `Could not connect to the devtools server`. I was perplexed since I don't remember seeing in the docs that a server is needed, neither other devtools I used before required a separated server. Anyhow, after some deep dive the in source code and trying to search around the docs, I learned that the devtools do need a standalone server that is started by the [`@refinedev/cli` `dev` command](https://refine.dev/docs/guides-concepts/development/#usage).

Since I am not using the CLI, I looked deeper in the source code to figure out how `@refinedev/cli` start the devtools. I was able to find out that to start manually the devtools, I need to install the internal package `@refinedev/devtools-server`, which provides a `refine-devtools` binary that can start the devtools server.

So, I ran `pnpm exec refine-devtools` to launch it. Refresh my frontend, open the devtools panel to be greated by a Login page!?! Nowhere in the documentation mention the needs for a login to Google or Github to be able to use the devtools. This point to me that the devtools might include some [telemetry that is not documented](https://refine.dev/docs/further-readings/telemetry/)? Or the devtools uses some kind of cloud-based storage/process to provide its features?

While searching for more information, I saw the following call made in the network of the developper tools in Chrome:
- `ws://localhost:5002/` : The devtools server is running on port 5001. Why port 5002 is needed?
- `cloud2.refine.dev`: This one was not in the network tab, I had to use a network sniffer...

I was already irrated that using the devtools is so complicated to use (even if its a beta), but seeing that a Google or Github login is required for a local devtools is making me reconsider my choice of using Refine.

----

Also, while searching around, I found those links that bring to dead end.
- https://github.com/refinedev/refine/blob/b4ed3be74f13837ebeb1faa3b616c4c1e4744120/packages/devtools-server/README.md?plain=1#L31
- https://github.com/refinedev/refine/blob/b4ed3be74f13837ebeb1faa3b616c4c1e4744120/packages/devtools/README.md?plain=1#L33

### A) Basic Usage

For the basic usage of the devtools, document that when doing the manual installation, the devtools requires a standalone server that is usually started by using the commands offered in `@refinedev/cli` package.

### B) Usage without `@refinedev/cli`

For usage without `@refinedev/cli`, document that the standalone server can be started manually by installing the `@refinedev/devtools-server` package and then running `pnpm exec refine-devtools` (or the equivalent with npm or yarn).

### C) Login with Google/Github

Explain clearly why the login is required and what information is collected, which non-local backend is used, for what an external backend is used, etc.

### D) Telemetry

If required, update the telemetry page to document which data the devtools server is capturing.

**Comment by TomCaserta** [comment]
I'm also using Devtools in a nx monorepo. Just to note, you can just run `refine devtools` with the CLI instead of installing `@refinedev/devtools-server` directly.

**Comment by aliemir** [comment]
Hey @sharky98, thank you for your effort to create this issue! About the usage section and how to run it separately will be added to the docs with both alternatives from you and @TomCaserta mentioned (thank you 🙏). We'll also include a section about how devtools work and why it requires a server to operate (mentioning required ports and protocols) 

About the telemetry, in Refine Devtools we **do not** track any telemetry data. We care a lot about privacy and we have a section about our docs on what we collect and how we collect in Refine.

The request to our backend is made for our raffle to gift Refine swag kits to our devtools users and nothing is collected with that request. Still, we apologize for leaving this part out of our docs and we'll update it accordingly and address your concerns.

I'll update here when we have any progress on the docs update 🚀

**Comment by mkendall07** [comment]
Hi. It doesn't appear this was ever addressed and is not documneted anywhere as far as I can tell
> The request to our backend is made for our raffle to gift Refine swag kits to our devtools users and nothing is collected with that request. Still, we apologize for leaving this part out of our docs and we'll update it accordingly and address your concerns.

As this is product is targeted to the enterprise applications, requiring a 3rd party login to use dev tools is concerning. Is there an option to turn this off?

**Comment by BatuhanW** [comment]
It's not 3rd party login, you are logging into Refine cloud API.
