### ISSUE TITLE
[BUG] useNotificationsProvider mui anchor position hard coded

### ISSUE THREAD

**Issue by JoeGaffney** [refinedev/refine#5847]
### Describe the bug

Anchor position hard coded in mui useNotificationsProvider

        enqueueSnackbar(
          <Box>
            <Typography variant="subtitle2" component="h6">
              {description}
            </Typography>
            <Typography variant="caption" component="p">
              {message}
            </Typography>
          </Box>,
          {
            key,
            variant: type,
            anchorOrigin: {
              vertical: "top",
              horizontal: "right",
            },
            disableWindowBlurListener: true,
          },
        );
![image](https://github.com/refinedev/refine/assets/11944251/1eb1a807-1c2f-4835-ba72-1058d83d0d86)

Ideally should not be hardcode and take from the provider global settings.

### Steps To Reproduce

1. set snackbar Provider anchorOrigin
          <RefineSnackbarProvider
            maxSnack={5}
            anchorOrigin={{ horizontal: "center", vertical: "bottom" }}
            preventDuplicate={true}
          >

### Expected behavior

Respect the provider props don't hard code later on the call

### Packages

@refinedev/mui

**Comment by aliemir** [comment]
Hey @JoeGaffney, thanks for reporting! I think the step to take here is to move these `anchorOrigin`, `preventDuplicate` and `disableWindowBlurListener` values to `RefineSnackbarProvider` as default values. This way we can allow customization of those. (`autoHideDuration` is related with `undoableTimeout` therefore needs to be there 😅)

Do you want to work on this? We'll be happy to see a PR from you! 🚀

**Comment by joe-noumena** [comment]
Hey @aliemir I'm not sure exactly when I can submit a PR as have a lot of current commitments. If it's still open in a month or so I could do a PR?

Atm I have just made my own notification provider and removed them, so its not a blocker type thing and can be worked around.

**Comment by JoeGaffney** [comment]
Hey @aliemir I'm not sure exactly when I can submit a PR as have a lot of current commitments. If it's still open in a month or so I could do a PR?

Atm I have just made my own notification provider and removed them, so its not a blocker type thing and can be worked around

**Comment by aliemir** [comment]
No problem @JoeGaffney! Let's keep this one open without any assignees in case anyone wants to work on it! 🚀

**Comment by Yash-271120** [comment]
@aliemir Hi!
I would like to take up the issue. I am new to refine open source community. This is something I can start with

**Comment by aliemir** [comment]
Hey @Yash-271120, assigning the issue to you! We'll be looking forward for your PR. Don't forget to read our [Contributing Guide](https://refine.dev/docs/guides-concepts/contributing/) before you get started 🚀

**Comment by Yash-271120** [comment]
@aliemir Hey, Good evening!
I have made a PR with respect to this bug and also have made necessary changes to the tests.
