### ISSUE TITLE
[FEAT] Antd | Allow translation for required field messages

### ISSUE THREAD

**Issue by oscarviq** [refinedev/refine#5855]
### Is your feature request related to a problem? Please describe.

Looks like the rules for form validation in the auth page component's do not allow for setting translated messages to the auth components. This is also true for the register, forgot password, etc. pages.

```
<Form.Item
            name="email"
            label={translate("pages.login.fields.email", "Email")}
            rules={[
              { required: true },
              {
                type: "email",
                message: translate(
                  "pages.login.errors.validEmail",
                  "Invalid email address",
                ),
              },
            ]}
          >
```

![Screenshot 2024-04-15 at 5 27 32 PM](https://github.com/refinedev/refine/assets/61564494/54647fe6-0c82-48ae-b531-406b593e39c6)

### Describe the thing to improve

From the looks of Antd's documentation, you can also pass a message property to the "required" rule:

https://ant.design/components/form#components-form-demo-normal-login

**Comment by alicanerdurmaz** [comment]
Hello @oscarviq, thanks for the issue. As you said, we need to give the `message` prop to the `required` prop.

I will write what needs to be done step by step. please let me know if I missed anything.

### Implementation details
- `message` prop should be added to `required` rule of form items of all [`<AuthPage />`](https://github.com/refinedev/refine/tree/edb4553cdedced5fc3494b71b064afdb0f859678/packages/antd/src/components/pages/auth/components) _(login, register, etc.)_. [login page code is here](https://github.com/refinedev/refine/blob/edb4553cdedced5fc3494b71b064afdb0f859678/packages/antd/src/components/pages/auth/components/login/index.tsx#L166)

_code example:_
```tsx
{
  required: true,
  message: translate(
    "pages.login.errors.requiredEmail",
    "Email is required",
  ),
},
```

- translation keys added to form items of all `<AuthPage />` should also be added to documentation
    - [guides and concepts page](https://refine.dev/docs/guides-concepts/i18n/#translation-file)
    - [i18n-provider page](https://refine.dev/docs/i18n/i18n-provider/#translation-file)

**Comment by 0xJaskeerat** [comment]
Hey @oscarviq I wish to contribute to this 
Please assign the issue to me
