### ISSUE TITLE
[FEAT] Passing arbitrary graphql variables to hasura dataProvider

### ISSUE THREAD

**Issue by tomoemon** [refinedev/refine#5864]
### Is your feature request related to a problem? Please describe.

I am very pleased that gqlQuery allows us to perform arbitrary GraphQL Queries against hasura.
https://github.com/refinedev/refine/issues/5489

However, it is not possible to use hasura's powerful filters because only CrudFilter[] can be passed to filters in the useTable. It is also not possible to use variables type information generated by graphql codegen.

In my case.
Given a type with the relation User has many Books, I can write a query in hasura to get a list of Users who have 3 or more Books, which is not possible in the current CrudFilter.

### Describe alternatives you've considered

added to the following line in hasura dataProvider.
```typescript
        variables = {
          ...hasuraPagination,
          ...(hasuraSorting &&
            (namingConvention === "graphql-default"
              ? {
                orderBy: hasuraSorting,
              }
              : {
                order_by: hasuraSorting,
              })),
          ...(hasuraFilters && {
            where: hasuraFilters,
          }),
          ...(meta?.gqlVariables && meta?.gqlVariables), // added
        };
```
https://github.com/refinedev/refine/blob/master/packages/hasura/src/dataProvider/index.ts#L181

This allows the addition of any where condition supported by hasura, using type information hints, as follows.
```typescript
  const { tableProps } = useTable<GetFieldsFromList<BlogPostsQuery>>({
    syncWithLocation: true,
    meta: {
      gqlQuery: BlogPostsDocument,
      gqlVariables: {
        where: {
          _and: [
            {
              title: {
                _ilike: "%test%",
              },
            }
          ],
        },
      } as BlogPostsQueryVariables, // generated type from graphql query
    },
  });
```

### Describe the thing to improve

- add `gqlVariables?: any` to `GraphQLQueryOptions`
  - Ideally, I would like to pass the type information generated from the graphql query by type parameter instead of any, but I can't think of a way to achieve that right now.
- use `meta.gqlVariables` in `getList`, `getMany` of hasura dataProvider

**Comment by alicanerdurmaz** [comment]
Hello @tomoemon, thanks for the issue. 

It seems like a good idea, but can you give me the GQL Query you want to generate so I can better understand the problem? Maybe we can make CrudFilter[] to support this.

**Comment by tomoemon** [comment]
@alicanerdurmaz Thank you for your response!

For example, I want to execute the following query

Trying to get a list of categories that have at least one Posts with the string "test" in the title.
If the Posts is related to another type, I want to add more nested filters.
```graphql
query Categories {
    categories(
        where: {
            posts_aggregate: {
                count: {
                    predicate: { _gte: 1 },
                    filter: {
                        content: { _ilike: "%test%" }
                    }
                }
            }
        }
    ) {
        id
        title
    }
}
```

schema
```graphql
type Posts {
    id: ID!
    title: String!
    content: String!
    categories: Categories!
}

type Categories {
    id: ID!
    title: String!
    posts: [Posts!]!
    posts_aggregate: posts_aggregate!
}
```

In my opinion, such a condition would be too complex to add to the CrudFilter. Writing complex filter conditions without type completion may also cause bugs.

**Comment by alicanerdurmaz** [comment]
@tomoemon Thanks for the detailed explanation, we'll see what we can do.

**Comment by BatuhanW** [comment]
Hey @tomoemon I think you should use `meta.gqlQuery` and `meta.gqlMutation` fields. There you can pass your GraphQL queries created with `graphql-tag`.

https://refine.dev/docs/data/packages/hasura/#usage-with-graphql-tag

**Comment by tomoemon** [comment]
@BatuhanW 
I don't understand why it was closed.

Do you mean that I should put a specific filter condition directly on the where argument in the gql tagged query?
If so, I can use any filter in hasura, but then how do I give it a dynamic value?

![image](https://github.com/refinedev/refine/assets/1381362/e4b40480-ff9f-4272-bc73-6a100ae7ce78)

**Comment by BatuhanW** [comment]
Hey @tomoemon, you are right. I think we can accept extra `variables` field in the data provider and pass it to the query variables.

**Comment by BatuhanW** [comment]
We are open to contributions for this. This feature can be applied to following packages:

- `@refinedev/hasura`
- `@refinedev/graphql`
- `@refinedev/nestjs-query`

**Comment by yujhenchen** [comment]
Hi @BatuhanW
I'd love to work on this feature, could you assign it to me? Thanks!

**Comment by Sergio16T** [comment]
Hi @aliemir can you please assign this ticket to me? I've begun working on adding support for this enhancement! 🚀

**Comment by aliemir** [comment]
Hey @Sergio16T assigned! Let us know if you have any issues 🙏

**Comment by Sergio16T** [comment]
Hello @aliemir, @BatuhanW, @alicanerdurmaz I've opened an initial draft PR!  The PR description contains notes on pending work that was out of scope for initial changes as well as some questions to consider about desired functionality for `meta.gqlVariables` and how these should affect table column filters(initial, clear). 

Currently the changes apply the meta.gqlVariables to each query with the assumption that these filters are used to reduce the data set returned by the graphQL query and any table column filters will apply to the dataset returned. 

The scope of this PR includes packages/hasura and core package GraphQLQueryOptions type. Once discussion is resolved I can continue dev work on nestjs and graphql packages.As well as any potential changes to useTable Hook. 

 Let me know what your team thinks after reviewing the PR description. 

I look forward to hearing from you.
