### ISSUE TITLE
[DOC] Browser view crashes in Tutorial

### ISSUE THREAD

**Issue by Yash-271120** [refinedev/refine#5871]
### Documentation issue

The browser view crashes on `crud components` and `notifications`

[bug.webm](https://github.com/refinedev/refine/assets/65940625/48ed81fc-6c97-4934-a118-fba0cb7c16a4)

### Describe the thing to improve

Browser view should not crash

### Describe the solution (optional)

Handle null errors. I will put up a PR fixing this

**Comment by aliemir** [comment]
Hey @Yash-271120 thank you for reporting this! Can you create a separate PR for this rather than including it in #5870?

**Comment by aliemir** [comment]
Assigning this on to you, looking forward to see your contribution 🙏 @Yash-271120

**Comment by Yash-271120** [comment]
@aliemir my bad didn't checked the base branch while commiting. I have made necessary changes.
