### ISSUE TITLE
[BUG] `useFieldArray` options dissapear after routing away and back to edit page

### ISSUE THREAD

**Issue by doender** [refinedev/refine#5894]
### Describe the bug

I'm running into issues using `useFieldArray`. This example here https://github.com/refinedev/refine/tree/master/examples/blog-react-hook-dynamic-form has the same bug: when you go from the list to the edit page of a record you can see the skills in the form, but when you then route to the list page and back to the record edit page the skills have disappeared

### Steps To Reproduce

1. Checkout the example: https://github.com/refinedev/refine/tree/master/examples/blog-react-hook-dynamic-form
2. Click on the first record edit button: skills are shown
3. Go back to the list page
4. Click on the first record edit button again: skills are gone

### Expected behavior

The fields are shown

### Packages

See the example

**Comment by aliemir** [comment]
Hey @doender, just opened up a PR #5903 to fix this issue in our `blog-react-hook-dynamic-form`. 

We're using `setValue` from `useForm` of `react-hook-form` internally in our `useForm` of `@refinedev/react-hook-form` to set values per registered field of a record. This does not trigger a re-render and results in outdated display of the array field. Check out the related issue from `react-hook-form` here https://github.com/react-hook-form/react-hook-form/issues/1564

The advised workaround was to use `useWatch` or `watch` to properly rendering the field. In #5903 I did the same, you can check it out to help you resolve issue on your project! 🚀

**Comment by doender** [comment]
Yes, this workaround works, thanks!

**Comment by crazybolillo** [comment]
This fixed my issue for dev builds but it comes back again when I do a production build. Any ideas as to what may be going? Any field declared with `useFieldArray` is empty if I click on a record, go back and click again.
