### ISSUE TITLE
[BUG] Exmaple project cannot view

### ISSUE THREAD

**Issue by linkscope** [refinedev/refine#5896]
### Describe the bug

Hey, I'm trying to take a look at [app-crm-minimal](https://example.minimal-crm.refine.dev/) in the example project and found that I can't log in.

Could it fix or this exmaple project is outdate?

Thanks, team

### Steps To Reproduce

1. Go to /example/app-crm-minimal
2. Click Live Demo
3. Cannot Login in

### Expected behavior

none

### Packages

none

**Comment by eryet** [comment]
it seems every strapi api refine example using return 500 Internal Server Error, i dint test all example only had test refine-week-invoice-generator

**Comment by BatuhanW** [comment]
> ### Describe the bug
> Hey, I'm trying to take a look at [app-crm-minimal](https://example.minimal-crm.refine.dev/) in the example project and found that I can't log in.
> 
> Could it fix or this exmaple project is outdate?
> 
> Thanks, team
> 
> ### Steps To Reproduce
> 1. Go to /example/app-crm-minimal
> 2. Click Live Demo
> 3. Cannot Login in
> 
> ### Expected behavior
> none
> 
> ### Packages
> none
> 
> ### Additional Context
> _No response_

Can't reproduce. CRM Backend restarts itself ever hour to reset database. It could be you were trying to login during this time.

**Comment by BatuhanW** [comment]
> it seems every strapi api refine example using return 500 Internal Server Error, i dint test all example only had test refine-week-invoice-generator

v4 and multi-tenancy should be working. We'll fix invoice generator today.
