### ISSUE TITLE
[BUG] Module '"@refinedev/antd"' has no exported member 'Create' ('List' and so on).

### ISSUE THREAD

**Issue by lcandy2** [refinedev/refine#5926]
### Describe the bug

Follow the Get Start on the official website and use `npm create refine-app@latest` to create a new project based on `Next.js`, `Ant Design`, `REST API`, `Custom Auth`.
Then, when I tried to `npm run build`, the error appeared. (npm, yarn and pnpm were all tried)

```bash
$ npm run build

> the-project@0.1.0 build
> refine build

   ▲ Next.js 14.1.0

   Creating an optimized production build ...
 ✓ Compiled successfully
   Linting and checking validity of types ...
Failed to compile.

./src/app/blog-posts/create/page.tsx:3:10
Type error: Module '"@refinedev/antd"' has no exported member 'Create'.

  1 | "use client";
  2 |
> 3 | import { Create, useForm, useSelect } from "@refinedev/antd";
    |          ^
  4 | import { Form, Input, Select } from "antd";
  5 |
  6 | export default function BlogPostCreate() {
```

### Steps To Reproduce

1. Run `npm create refine-app@latest` in the terminal.
2. Choose `Next.js`, `Ant Design`, `REST API`, `Custom Auth`.
3. Run `npm run build`, error occurs.
4. Update(Reinstall) all dependences to the last version based on instructions ([refine.dev/docs/guides-concepts/faq/#how-to-solve-module-x-has-no-exported-member-y-error](https://refine.dev/docs/guides-concepts/faq/#how-to-solve-module-x-has-no-exported-member-y-error))
5. Run `npm run build` **again**, error **still** occurs.

### Expected behavior

```bash
Type error: Module '"@refinedev/antd"' has no exported member 'Create'.
```
Complete logs below
```bash
npm run build

> avian-sphere@0.1.0 build
> refine build

   ▲ Next.js 14.1.0

   Creating an optimized production build ...
 ✓ Compiled successfully
   Linting and checking validity of types ...
Failed to compile.

./src/app/blog-posts/create/page.tsx:3:10
Type error: Module '"@refinedev/antd"' has no exported member 'Create'.

  1 | "use client";
  2 |
> 3 | import { Create, useForm, useSelect } from "@refinedev/antd";
    |          ^
  4 | import { Form, Input, Select } from "antd";
  5 |
  6 | export default function BlogPostCreate() {
```

### Packages

```json
{
    "@ant-design/icons": "^5.3.7",
    "@ant-design/nextjs-registry": "^1.0.0",
    "@refinedev/antd": "^5.38.0",
    "@refinedev/cli": "^2.16.30",
    "@refinedev/core": "^4.49.1",
    "@refinedev/devtools": "^1.2.0",
    "@refinedev/kbar": "^1.3.9",
    "@refinedev/nextjs-router": "^6.0.3",
    "@refinedev/simple-rest": "^5.0.5",
    "antd": "^5.17.0",
    "js-cookie": "^3.0.5",
    "next": "^14.2.3", // version 14.1.0 behaves the same way!
    "react": "^18.3.1",
    "react-dom": "^18.3.1"
  }
```

**Comment by aliemir** [comment]
Hey @lcandy2 , sorry for the issue. Due to the changes in type declarations with the latest release, now users with Typescript version <5 have this issue. We've prepared a new PR to address this issue #5928. Until this is fixed, you can try upgrading your `"typescript"` dependency to version 5 and the issue will be resolved.
