### ISSUE TITLE
[BUG] Default GraphQL DataProvider GetListResponse from 'count' property not possible.

### ISSUE THREAD

**Issue by jamesdh** [refinedev/refine#5942]
### Describe the bug

The default GraphQL providers `getList` function return the following `GetListResponse` shaped object: 

https://github.com/refinedev/refine/blob/3046f9610f647bb049dbd388cd8cd5c267b481fa/packages/graphql/src/dataProvider/index.ts#L39-L42

As [mentioned by another user on Discord](https://discord-questions.refine.dev/m/1205328662510047242) (possibly @Karabur?), this does not make sense. In order for `getList` to function correctly with various integration points within Refine (like the MUI `useDataGrid` hook), `response[operation]` must return an array of objects. An array cannot have additional properties on it such as `count`.  I'm not sure I understand how anybody could be using this default data provider out of the box with working pagination. 

### Steps To Reproduce

N/A. Per the graphQL spec, a list cannot have additional properties. 

### Expected behavior

I do not see how any GraphQL API could provide a response that would provide working pagination for the default GraphQL provider. Even the [docs for useList indicate something considerably different](https://refine.dev/docs/data/hooks/use-list/#retrieving-the-total-row-count), more akin to a [Relay response](https://relay.dev/graphql/connections.htm).

### Packages

- @refinedev/graphql: 6.5.0

**Comment by BatuhanW** [comment]
Hey @jamesdh you are right, it's a bit illogical to expect a field in an array. GraphQL data provider, due to nature of GraphQL can't fit into every API so it's more like a blueprint to start building your own data provider. I just checked and it seems we are missing asserting count field in the tests. Nevertheless, this can be fixed to avoid confusion.

**Comment by jamesdh** [comment]
> GraphQL data provider, due to nature of GraphQL can't fit into every API

True, but there are conventions for this frequently found in the wild that are based on the Relay spec. Specifically, Relay has the concept of [Connection types](https://relay.dev/graphql/connections.htm#sec-Connection-Types). Connections must contain a [PageInfo](https://relay.dev/graphql/connections.htm#sec-Connection-Types.Fields.PageInfo) field. What you commonly see "in the wild" is that either the Connection object itself or the PageInfo object contain a "totalCount" property. I believe it's usually found on the Connection object, since it should not change between paginations (and hence it makes less sense for it to be on the PageInfo object). 

In any case, the "path" in the object graph where this count property can be found should be something that is definable in the meta object along with the query itself. The same is true for where the intended data can be found, and thus #5943 could be fixed.

**Comment by swethamanur** [comment]
@aliemir , if this issue is still open, could you re-assign this to me please?

**Comment by aliemir** [comment]
I don't have much info about this issue. Maybe @jamesdh or @BatuhanW can help on what to do here or what should we be aware of.

**Comment by jamesdh** [comment]
@aliemir sorry for going radio silent on this! I reinstalled macOS and forgot to install my usual app for getting GitHub notifications so missed everything that wasn't directly work related!

**Comment by BatuhanW** [comment]
No worries, we've released a major version on GraphQL, also covering the changes you were asking for. Graphql data provider should be more usable now, feel free to create new issues if you have more suggestions.
