### ISSUE TITLE
[FEAT] Ant Design's  `<ThemedSiderV2>` change button position under mobile

### ISSUE THREAD

**Issue by linkscope** [refinedev/refine#5958]
### Is your feature request related to a problem? Please describe.

Hey, under mobile `<ThemedSiderV2>` is a button popup, but I've found that it can somewhat obscure the content of the page, in this case it's a problem on all pages, and a bit worse on the `create` and `edit` pages due to the presence of the breadcrumbs, I've taken a screenshot of an example from the docs:

<img width="897" alt="截屏2024-05-17 17 42 01" src="https://github.com/refinedev/refine/assets/56714843/d705caa5-e2d6-4f30-ba90-e5a659d83914">

I was wondering if it would be possible to move the menu button up into the `Header`? That would be much better.

Thanks, team. 

### Describe the thing to improve

It would be possible to move the menu button up into the `Header`.

**Comment by BatuhanW** [comment]
Hey @linkscope you can swizzle the layout and modify it according to your needs.

https://refine.dev/docs/ui-integrations/ant-design/components/themed-layout/#customizing-with-swizzle
