### ISSUE TITLE
Login is showing email not found for 'michael.scott@dundermifflin.com' being used in javascript mastery project

### ISSUE THREAD

**Issue by Pranjaliyadav** [refinedev/refine#5959]
![image](https://github.com/refinedev/refine/assets/51490690/ac769647-4c6c-4b5c-bd1b-45527012da20)

**Comment by BatuhanW** [comment]
Hey @Pranjaliyadav CRM backend was re-deploying every 4 hours to reset delete it's data and seed again. This happens during the deployment. Now we've changed it and DB will refresh it's data without deployments, so we should have now downtime.
