### ISSUE TITLE
[FEAT] Keep filters when refresh the page with useTable

### ISSUE THREAD

**Issue by dfang** [refinedev/refine#6001]
### Is your feature request related to a problem? Please describe.

this is a list of customers filtered with idle status,

https://example.admin.refine.dev/customers?pageSize=10&current=9&sorters[0][field]=isActive&sorters[0][order]=asc&filters[0][field]=fullName&filters[0][operator]=contains

when I refresh the page, the list is not filtered with idle status.

### Additional context

when you filter then click pagination number, it's ok. but refresh and click pagination number, it's not filtered

### Describe the thing to improve

keep the filter after refreshing the page (restore filters from url)

**Comment by alicanerdurmaz** [comment]
Hello @dfang, thanks for the issue!

we need to add `defaultFilteredValue={getDefaultFilter("isActive", filters, "eq")}` to `<Table.Column />` to populate column's default value.

more information is here: https://refine.dev/docs/ui-integrations/ant-design/hooks/use-table/#initial-filter-and-sorter

**Comment by dzcpy** [comment]
Also experinced this problem. Hopefully it can be added soon!

**Comment by alicanerdurmaz** [comment]
Hello @dzcpy, 

Is this not working?

```jsx
import { getDefaultFilter } from "@refinedev/core";

const { filters } = useTable();

// ...
defaultFilteredValue={getDefaultFilter("inspector][id", filters, "eq")}
// ...

```

**Comment by dzcpy** [comment]
> Hello @dzcpy,
> 
> Is this not working?
> 
> ```js
> import { getDefaultFilter } from "@refinedev/core";
> 
> const { filters } = useTable();
> 
> // ...
> defaultFilteredValue={getDefaultFilter("inspector][id", filters, "eq")}
> // ...
> ```

It is working, if you mean `inspector][id` I'm using Strapi integration I looks weird but works.
However it's pretty tedious to change each Table.Column mannually. I've got hundreds of tables. It's better to do it automatically with Refine

**Comment by alicanerdurmaz** [comment]
@dzcpy Thanks for the detailed explanation, you are right there is room for improvement. We'll think about it.

**Comment by ahmedmelfay** [comment]
This doesnt work if you have different filters component, e.g [here](https://codesandbox.io/p/devbox/busy-jang-94dzpq?embed=1), would appreciate if someone has a solution for this
