### ISSUE TITLE
[FEAT] Support Cloudflare Pages on Free Plan, using NextJS on Refine

### ISSUE THREAD

**Issue by jackprogramsjp** [refinedev/refine#6006]
### Is your feature request related to a problem? Please describe.

Basically, when you create a refine app, and try to publish it on Cloudflare Pages on Free Plan, you'll get this: `Error: Failed to publish your Function. Got error: Your Functions script is over the 1 MiB size limit (workers.api.error.script_too_large)`

My CRUD app that uses NextJS and Appwrite does not go over the 1 MiB size limit, so I am not sure if this is more of a Refine app thing?

### Describe the thing to improve

It seems that the Refine app has a size over 1 MiB after compression, is there a way to minimize this? Especially for a barebones refine project...?

**Comment by BatuhanW** [comment]
Hey @jackprogramsjp can you analyze your app with bundle analyzer and let us know the results?
