### ISSUE TITLE
[BUG] Some filter operators are not implemented in the Nestjs-Query Data Provider

### ISSUE THREAD

**Issue by yamadayutaka** [refinedev/refine#6008]
### Describe the bug

The following filter operators are not implemented in the Nestjs-Query Data Provider.

- `containss`
- `ncontainss`
- `startswiths`
- `nstartswiths`
- `endswiths`
- `nendswiths`
- `nbetween`

### Steps To Reproduce

1. create Nestjs-Query example project.

```
pnpm create refine-app@latest --example data-provider-nestjs-query
```

2. implement initial filter with `containss` operator on `src/pages/categories/list.tsx`.

```ts
  const { tableProps, sorters } = useTable<ICategory>({
    initialSorter: [
      {
        field: "id",
        order: "asc",
      },
    ],
    initialFilter: [
      {
        field: "title",
        operator: "containss",
        value: "Refine",
      },
    ],
```

3. run refine app.

```
pnpm dev
```

4. navigate `Categories` menu.

5. following error occurred.

```
Variable "$filter" got invalid value { undefined: "Refine" } at "filter.title";
```

### Expected behavior

GraphQL query is executed with the following filter.

```yaml
filter: {title: {like: "%Refine%"}}
```

### Packages

- @refinedev/nestjs-query

### Additional Context

I have already fixed this issue and will create a PR.

**Comment by BatuhanW** [comment]
Hey @yamadayutaka thanks for the issue and looking forward to your PR! Make sure to check our [Contributing Guide](https://refine.dev/docs/guides-concepts/contributing/) before sending the PR.

**Comment by yamadayutaka** [comment]
Hi @BatuhanW, Thanks for merging my PR!
