### ISSUE TITLE
[BUG] Cannot specify `0` as filter value in the Nestjs-Query Data Provider

### ISSUE THREAD

**Issue by yamadayutaka** [refinedev/refine#6022]
### Describe the bug

Cannot specify `0` as filter value.
Also, `""` cannot be specified.

Because it is excluded by the conditions in the following sections.

https://github.com/refinedev/refine/blob/a8404fc92c856f89b06684de6ad481aa840267be/packages/nestjs-query/src/utils/index.ts#L165

### Steps To Reproduce

1. create Nestjs-Query example project.

```
pnpm create refine-app@latest --example data-provider-nestjs-query
```

2. implement initial filter with a value of `0` on `src/pages/categories/list.tsx`.

```ts
  const { tableProps, sorters } = useTable<ICategory>({
    initialSorter: [
      {
        field: "id",
        order: "asc",
      },
    ],
    filters: {
      initial: [
        {
          field: 'id',
          operator: 'eq',
          value: 0 
        }
      ],
    },
```

3. run refine app.

```
pnpm dev
```

4. navigate `Categories` menu.

5. GraphQL query is executed with no filter specified. (Inspect in the DevTools network panel.)

```ts
filter: {},
```

### Expected behavior

GraphQL query is executed with the following filter.

```ts
filter: {id: {eq: 0}},
```

### Packages

- @refinedev/nestjs-query

### Additional Context

I have already fixed this issue and will create a PR.

**Comment by alicanerdurmaz** [comment]
Hello @yamadayutaka, thanks for the detailed explanation.

Do you want to work on this?

**Comment by yamadayutaka** [comment]
Hi @alicanerdurmaz , I have created a PR, please check it out.

**Comment by BatuhanW** [comment]
Hey @yamadayutaka thanks for the neat PR! It's all approved, we'll release it in our next release cycle.
