### ISSUE TITLE
[BUG] fix(devtools-internal): fix NODE_ENV conditional didn't work

### ISSUE THREAD

**Issue by sanchezcarlosjr** [refinedev/refine#6030]
### Describe the bug

Hello,
@aliemir published the PR https://github.com/refinedev/refine/pull/5992 and it works. However, esbuild doesn't compile as expected. The compiler doesn't generate correctly as you write here https://github.com/refinedev/refine/blob/4654353b90b6a09cbf65e41d4c1fa82553a2a3fa/packages/devtools-internal/src/use-query-subscription.tsx#L13
So, instead of
```js
() => {
        return {};
      }
```
it generates
```
() => ({})
```

### Steps To Reproduce

1. Install @refinedev/devtools-internal or visit the link [@refinedev/devtools-internal npm package code tab](https://www.npmjs.com/package/@refinedev/devtools-internal/v/1.1.11?activeTab=code)
2. Check the below expression in index.cjs and index.mjs.
```
process.env.NODE_ENV!=="development" ? ()=>({})  : ...
```

### Expected behavior

The below expression
```js
process.env.NODE_ENV!=="development" ? ()=>({}): ...
```

must be something similar to
```js
process.env.NODE_ENV!=="development" ? ()=> {
   return {};
}: ...
```
Probably adding a noop function helps.
```js
const noop = () => {
   return {};
}

process.env.NODE_ENV!=="development" ? noop: ...
```

### Packages

- @refinedev/devtools-internal:1.1.11

**Comment by aliemir** [comment]
Hey @sanchezcarlosjr, thank you for explaining the issue here! 🙏 Did you encounter this issue while working with React Native or is there any other platform that has issues with parsing those lines? 🤔

**Comment by sanchezcarlosjr** [comment]
Thank you for your answer, @aliemir. I'm working with traditional React web apps, and they work as expected. The issue only occurs in React Native as far as I know.
