### ISSUE TITLE
[BUG] NextJs 14 and latest versions of package.json: dataProvider is not a function

### ISSUE THREAD

**Issue by vitali-bc** [refinedev/refine#6036]
### Describe the bug

Hi guys, seems very strange...
Basically I'm usine nextjs headless version with refine and updated all packages.json to latest versions (photo 1)
When run dev it shows me error:
![Screenshot 2024-06-11 alle 21 46 19](https://github.com/refinedev/refine/assets/172402530/7950f550-9bf8-471a-9349-7d940f7cf9b2)

![Screenshot 2024-06-11 alle 21 48 49](https://github.com/refinedev/refine/assets/172402530/cf9a145e-0987-42a4-ac42-08b94de5520f)

### Steps To Reproduce

1. run `ncu -u` to update all packages
2. `npm i` to install
3. `npm run dev`

### Expected behavior

All must working correctly

### Packages

refine/core
refine/simple-rest

**Comment by aliemir** [comment]
Hey @vitali-bc, just created a new Refine + Next.js project using `npm create refine-app@latest`:

We have `src/providers/data-provider/index.ts` file which exports the `dataProvider`, it seems like your import is also coming from the same location. Exported `dataProvider` is not a function but an object (a data provider instance).

We also export a `dataProvider` from `@refinedev/simple-rest` (also in other data provider packages) which is a function and can be used like the way you do:

```tsx
import { Refine } from "@refinedev/core";
import dataProvider from "@refinedev/simple-rest";

export function RootLayout() {
  return (
    <Refine
      dataProvider={dataProvider("https://api.fake-rest.refine.dev")}
    >
       ...
    </Refine>
  }
}
```

In your case, updating the import or updating the usage will resolve the issue.

If this happened after freshly created Refine project, can you share your choices so we can track down the issue 🙏

**Comment by vitali-bc** [comment]
Yes it works, but problem persists when you are updating all packages to
latest versions.
Try to, thanks

Il giorno mer 12 giu 2024 alle 12:47 Ali Emir Şen ***@***.***>
ha scritto:

**Comment by aliemir** [comment]
Ciao @vitali-bc! I'm having hard time keeping up with the issue here. Does this pop up right after you create the project or does it pop up after you update the dependencies in a currently working project? Does this line added/edited by you or was it like that all along? I'll be happy to help if you can provide a bit more info 🚀
