### ISSUE TITLE
[BUG] Property 'refineCoreProps' does not exist on type 'UseFormProps

### ISSUE THREAD

**Issue by borisyordanov** [refinedev/refine#6040]
### Describe the bug

When attempting to extend useForm, an unexpected type error apears. TS thinks `refineCoreProps` is missing even though it exists in the actual variable.

### Steps To Reproduce

1. Open this devbox - https://codesandbox.io/p/devbox/l5725k?file=%2Fedit-page.tsx%3A10%2C26
2. Inspect the type error
![image](https://github.com/refinedev/refine/assets/12392666/ea35e982-cb51-42aa-a4cf-0e273e067f3a)

### Expected behavior

Entities exported by refine have unique names.

### Packages

![image](https://github.com/refinedev/refine/assets/12392666/b6da6ca8-da3b-4a16-8d83-2879d5852c88)

### Additional Context

It seems that @refinedev/react-hook-form AND @refinedev/core export a type with the same name `UseFormProps`. Importing it from the former works, but not the latter.

**Comment by aliemir** [comment]
Hey @borisyordanov, We have UseFormProps in both @refinedev/core and @refinedev/react-hook-form. Additionally, we have useForm in both as well. The latter is an extended version of the former. If you're going to extend the one from `@refinedev/react-hook-form` you'll need to use the `UseFormProps` from that package as well. 

I think I understand the confusion here, we might need to rename them to be explicit 🤔 Do you have any suggestion how we can avoid confusion here? 🙏

**Comment by borisyordanov** [comment]
@aliemir Ideally there'd be a lint rule to protect you against duplicate names, but there don't seem to be [any good options](https://github.com/eslint/eslint/issues/6573).

My advice is to adopt a naming convention for each of your packages. Add a prefix or suffix to distinguish between two similar, but separate entities. Example [ButtonBase](https://github.com/mui/material-ui/blob/22c5206a9e8191b2f81131d6978a0958e55b7032/packages/mui-material/src/ButtonBase/ButtonBase.js) and [Button](https://github.com/mui/material-ui/blob/next/packages/mui-material/src/Button/Button.js).

When you have decided on a convention it can be enforced with https://typescript-eslint.io/rules/naming-convention/#prefix--suffix where each one of your packages will have the rule configured differently.

The end result would be that you can safely import:
```ts
// before
import { UseFormProps } from "@refinedev/core";
import { UseFormProps } from "@refinedev/react-hook-form";

// after
import { UseFormPropsCore } from "refinedev/core";
import { UseFormPropsHookForm } from "@refinedev/react-hook-form";
```

I hope you'll be able to come up with a more elegant solution, but this is the best option I can think of atm.

**Comment by aliemir** [comment]
Hey @borisyordanov, thank you for the suggestion. We've discussed with the team and decided not to take any actions for now about the naming conventions. In the future, there may be changes related to how we export things and changes in the naming may cause issues with those. 

Thank you for reporting, closing this issue for now. I'll update here and mention this issue when we have related changes planned/implemented. 🙏

**Comment by ritute** [comment]
I ran into this issue as well. The docs are still out of date for these: https://refine.dev/docs/packages/react-hook-form/introduction/#installation & https://refine.dev/docs/data/hooks/use-form/#parameters

**Comment by benckersens** [comment]
I agree that it might be helpful to be more explicit with the naming.
This is how I'm addressing this:

**`eslint.config.ts`**

```ts
// 🔒 Block easily misleading form imports project-wide (see: https://github.com/refinedev/refine/issues/6040)
{
  files: ['**/*.ts', '**/*.tsx'],
  rules: {
    'no-restricted-imports': [
      'error',
      {
        paths: [
          {
            name: '@refinedev/core',
            importNames: ['UseFormProps', 'useForm'],
            message:
              'For forms, I recommend to import useForm/UseFormProps from @refinedev/react-hook-form instead of @refinedev/core.',
          },
          {
            name: 'react-hook-form',
            importNames: ['useForm', 'UseFormProps'],
            message:
              'In Refine-integrated forms, use @refinedev/react-hook-form. If you truly need RHF directly, alias it explicitly.',
          },
        ],
      },
    ],
  },
}
```
