### ISSUE TITLE
[BUG] Invalid session token on login in Safari DevTools

### ISSUE THREAD

**Issue by lekhok** [refinedev/refine#6047]
### Describe the bug

An "Invalid-session-token" error occurs when trying to log in via devtools in Safari, regardless of using Github or Google for authentication.
<img width="1440" alt="Screenshot 2024-06-13 at 19 32 58" src="https://github.com/refinedev/refine/assets/129063617/19893948-afa2-4e6a-967d-ef0c870060ce">

### Steps To Reproduce

Open your project in Safari.
Access DevTools.
Attempt to login using either Github or Google.
An error displays the "Invalid-session-token".

### Expected behavior

Successful login within Safari DevTools using the chosen authentication method (Github or Google).

### Packages

@refinedev/devtools version "^1.1.32"

@refinedev/cli: "^2.16.21"
@refinedev/core: "^4.47.1"
@refinedev/devtools: "^1.1.32"
@refinedev/kbar: "^1.3.6"
Safari Version: 17.5
Date: June 13, 2024

### Additional Context

The same issue occurs when signing in with Github, resulting in the error message.
Google Signin doesn't provide an error message but redirects back to the login page repeatedly.

**Comment by lekhok** [comment]
Still no access to devtools @refine-bot

**Comment by ithomaslin** [comment]
I can reproduce this on Chrome

**Comment by lekhok** [comment]
> I can reproduce this on Chrome

so have you been able to login yet?

**Comment by ithomaslin** [comment]
No, it always redirect me back to the login page.

**Comment by lekhok** [comment]
> No, it always redirected me back to the login page.

Seems like a major issue then, let's see if anyone can address it out

**Comment by kraigh** [comment]
I also have this issue. Side note- why exactly is login required to access devtools?

**Comment by PrabeenGautam** [comment]
Same, can not open devtools. Using chrome browser.  Whoami can not detect browser.
```
## System:
 - OS: Windows 11 10.0.22631
 - CPU: (16) x64 AMD Ryzen 7 6800H with Radeon Graphics
## Binaries:
 - Node: 20.12.1 - C:\Program Files\nodejs\node.EXE
 - Yarn: 1.22.21 - C:\Program Files\nodejs\yarn.CMD
 - npm: 10.8.1 - C:\Program Files\nodejs\npm.CMD
## Browsers:
 - Chrome: Not Found

## Refine Packages:
 - @refinedev/antd: 5.40.0
 - @refinedev/cli: 2.16.33
 - @refinedev/core: 4.51.0
 - @refinedev/devtools: 1.2.3
 - @refinedev/kbar: 1.3.12
 - @refinedev/nestjs-query: 1.3.0
 - @refinedev/react-router-v6: 4.5.11
```

**Comment by lekhok** [comment]
> Same, can not open devtools. Using chrome browser. Whoami can not detect browser.
> 
> ```
> ## System:
>  - OS: Windows 11 10.0.22631
>  - CPU: (16) x64 AMD Ryzen 7 6800H with Radeon Graphics
> ## Binaries:
>  - Node: 20.12.1 - C:\Program Files\nodejs\node.EXE
>  - Yarn: 1.22.21 - C:\Program Files\nodejs\yarn.CMD
>  - npm: 10.8.1 - C:\Program Files\nodejs\npm.CMD
> ## Browsers:
>  - Chrome: Not Found
> 
> ## Refine Packages:
>  - @refinedev/antd: 5.40.0
>  - @refinedev/cli: 2.16.33
>  - @refinedev/core: 4.51.0
>  - @refinedev/devtools: 1.2.3
>  - @refinedev/kbar: 1.3.12
>  - @refinedev/nestjs-query: 1.3.0
>  - @refinedev/react-router-v6: 4.5.11
> ```

So I guess it's not a Mac specific issue

**Comment by aliemir** [comment]
Sorry for the issue everyone! We've just merged a fix for this issue and it will be released in the next couple hours 🚀  I'll update here when its released and you can validate if its resolved 🙏

**Comment by aliemir** [comment]
Changes are just deployed, you can update your dependencies:

- [@refinedev/cli@2.16.34](https://github.com/refinedev/refine/releases/tag/%40refinedev%2Fcli%402.16.34)
- [@refinedev/devtools@1.2.4](https://github.com/refinedev/refine/releases/tag/%40refinedev%2Fdevtools%401.2.4)

🚀

**Comment by aliemir** [comment]
Closing this for now after #6065, feel free to re-open if the issue continues 🙏

**Comment by lekhok** [comment]
Thank you @aliemir 
I am currently at the hospital as my mom is admitted, will check when I am home! Thank you for the fix
