### ISSUE TITLE
[BUG] errorNotification has invalid argument type

### ISSUE THREAD

**Issue by CRC32EX** [refinedev/refine#6056]
### Describe the bug

`errorNotification` 's 1st argument is `error`.
But, The real type is `Response`,
Please fix it.

![image](https://github.com/refinedev/refine/assets/25629617/6c1aa6ab-91c4-4bd2-b398-a6a0546b6551)

And, please support async / await.
I want write code, like this.

### Steps To Reproduce

```
 refineCoreProps: {
      errorNotification: (error) => {
        console.log("on error notification")

        // const response = error as unknown as Response
        console.log(error)

        const obj = await response.json() as MyErrorType
        return {
          type: "error",
          message: obj.message,
          description: obj.description,
        } as OpenNotificationParams
      },
    },
```

### Expected behavior

- Please fix, the 1st argument type
- Please support async / await 

### Packages

Next.js

**Comment by HussainAther** [comment]
Change the Argument Type: Update the argument type of the errorNotification function to match the actual type (Response).
Support Async/Await: Modify the function to support async/await syntax.
For example, if the function is defined in a TypeScript file, it might look like this:

import { OpenNotificationParams } from 'path/to/type/definition';

async function errorNotification(response: Response): Promise<OpenNotificationParams> {
    console.log("on error notification");
    console.log(response);

    const obj = await response.json() as MyErrorType;
    return {
        type: "error",
        message: obj.message,
        description: obj.description,
    };
}

**Comment by CRC32EX** [comment]
???

**Comment by HussainAther** [comment]
Excuse me, I just wanted to make suggestions. I'll be more thorough if I can get to this later, thanks.
