### ISSUE TITLE
[FEAT]: Typed resources

### ISSUE THREAD

**Issue by JuicyBenjamin** [refinedev/refine#6072]
### Is your feature request related to a problem? Please describe.

1) I'm not getting type feedback on whether my type input of a resource is correct.
2) I'm not getting a return type based on the used resource when using for example "useOne" and have to manually do it. 

### Describe the thing to improve

Would be nice to know that a resource I'm calling exists via types. So I'm getting a type error if I'm calling "product" instead of "products" for example. 

This would be the first implementation I'd really enjoy. 

A bonus implementation, if even possible would be to automagically type the return type of the resources used, right now I'm manually marking them, this solution does work just fine, but it definitely would be more sleek if I didn't have to.

**Comment by alicanerdurmaz** [comment]
Hi @JuicyBenjamin, This is a great idea to improve the developer experience 🚀

**Comment by josiahcoad** [comment]
agreed!!
