### ISSUE TITLE
[FEAT] Update @refinedev/appwrite's Appwrite SDK version

### ISSUE THREAD

**Issue by soranoo** [refinedev/refine#6090]
### Is your feature request related to a problem? Please describe.

A `TypeError: e._formData.get is not a function` error pops up while running nextjs server action in client component which can hugely affect the DX.

#### Related Issues
https://github.com/vercel/next.js/issues/60687

#### Related Pull Requests
https://github.com/appwrite/sdk-generator/pull/834

The Appwrite Team fixed the issue and released the patch.

### Describe the thing to improve

Please update the Appwrite SDK regularly or at least update the SDK to the latest version.

Current @refinedev/appwrite's Appwrite SDK version: 10.0.1
Latest Appwrite SDK version: 15.0.0

**Comment by BatuhanW** [comment]
Hey @soranoo thanks for the detailed report! Would you like to work on this?

**Comment by soranoo** [comment]
Sure, Im happy to do so~

**Comment by soranoo** [comment]
I tried to update to `15.0.0` but failed.
I got
![image](https://github.com/user-attachments/assets/d7df3678-52a3-4482-90a6-6c1c501c7372)

and I have no idea how to deal with it...

**Comment by aliemir** [comment]
SDK is updated to the latest thanks to the efforts from @soranoo 🙏 Now available with `@refinedev/appwrite@7.0.0`
