### ISSUE TITLE
[BUG] use refine with next and antd

### ISSUE THREAD

**Issue by ccdarvin** [refinedev/refine#6110]
### Describe the bug

I try to use refine with next antd y turbobuild

### Steps To Reproduce

change `package.json`

`"dev": "next dev --turbo",` or
`"dev": "cross-env NODE_OPTIONS=--max_old_space_size=4096 refine dev --turbo"`

### Expected behavior

I have this error:

![image](https://github.com/refinedev/refine/assets/52012960/48c0bfad-1b40-4310-918e-95fb9531e4ff)

### Packages

"@ant-design/icons": "^5.0.1",
  "@ant-design/nextjs-registry": "^1.0.0",
  "@refinedev/antd": "^5.37.4",
  "@refinedev/cli": "^2.16.21",
  "@refinedev/core": "^4.47.1",
  "@refinedev/devtools": "^1.1.32",
  "@refinedev/kbar": "^1.3.6",
  "@refinedev/nextjs-router": "^6.0.0",
  "@refinedev/supabase": "^5.7.4",
  "@supabase/ssr": "^0.3.0",
  "antd": "^5.0.5",
  "js-cookie": "^3.0.5",
  "next": "^14.1.0",
  "react": "^18.0.0",
  "react-dom": "^18.0.0"

**Comment by alicanerdurmaz** [comment]
Hi @ccdarvin, thanks for the report. We will reproduce this bug with [turbopack](https://turbo.build/pack/docs) and investigate it.

**Comment by BatuhanW** [comment]
Hey @ccdarvin, I think turbo should ignore installed package's tsconfig file. It could be an issue with turbopack configuration.

**Comment by ccdarvin** [comment]
I think the issue is in the package @refinedev/antd", because when I comment this line `//transpilePackages: ['@refinedev/antd'],` in next.config.mjs, it works well.

**Comment by alicanerdurmaz** [comment]
The problem between Next.js and Ant Design has existed [for a long time](https://github.com/ant-design/ant-design/issues/46053). Since `create refine-app` doesn't create the project with Turbo, I prefer not to remove `transpilePackages`.

Thank you for the issue and solution. From now on, anyone with this problem can easily fix it.

**Comment by jackytank** [comment]
Hi I get same issue as you but after remove @refinedev/antd from transpilePackages now it work well
