### ISSUE TITLE
[FEAT] register("myFormDataField") useForm<MyFormData>()

### ISSUE THREAD

**Issue by jozef-slezak** [refinedev/refine#6111]
### Is your feature request related to a problem? Please describe.

Typescript type checks for refine useForm() similar to what React Hook Form has

### Additional context

React Hook Forms support typescript checking even for register("fieldName")
https://codesandbox.io/s/react-hook-form-typescript-qwk7b?file=/src/index.tsx

### Describe the thing to improve

Please inspire by React Hook Form Types

**Comment by alicanerdurmaz** [comment]
Hello @jozef-slezak, can you give specific examples, please?

For example, if a field name is not specified, `getFieldState` and `resetField` throw type errors.
<image src="https://github.com/refinedev/refine/assets/23058882/f4fcb6cc-ec35-43a5-bd84-faadeab62609" width="100" />

<image src="https://github.com/refinedev/refine/assets/23058882/5c6eb351-e4c5-4aea-9a8f-b63134411ff3" width="100" />

Also, we want to implement type support for `resource` field.

**Comment by aliemir** [comment]
Hey @jozef-slezak. As @alicanerdurmaz explained in the comment above we already have the type support for methods from `useForm`.

I think there's a misunderstanding here about the generics; while `react-hook-form`'s `useForm` uses the first generic for the form values, we use the third generic as the form values. `@refinedev/react-hook-form`'s `useForm` will fetch the data first and try to populate the fields. This is why we have the first two generics `TData` and `Terror`.

If you try to pass the third generic for your form values, type support for the fields will be provided.

Closing this for now. If the issue continues, please do not hesitate to reopen with more info about the issue and a minimal repro 🙏
