### ISSUE TITLE
[BUG] using custom request with different URL changes URL of subsequent requests

### ISSUE THREAD

**Issue by igordonin** [refinedev/refine#6112]
### Describe the bug

I believe there's an unexpected side effect when using a data provider and passing the URL param. It's possible to replicate the issue in the `app-crm` template. 

If you change the `auth.ts` file's URL's, then any subsequent call to the data provider will use the value passed into the `url` param:

```
const { data } = await dataProvider.custom({
        url:`{{change the url here}}`,
        method: 'post',
        headers: {},
        meta: {
          variables: { email },
          gqlMutation,
        },
});
```

### Steps To Reproduce

1. Checkout the `app-crm` template
2. Open the `auth.ts` file
3. Instead of using the API_URL from `data` folder, manually change it to any other URL
4. All subsequent use of data provider will have the new URL

### Expected behavior

I'd expect the URL to be overwritten only for a single specific call

### Packages

- @refinedev/nestjs-query
- graphql-request
- axios

**Comment by alicanerdurmaz** [comment]
Hello @igordonin,

The bug is here. we shouldn't change the client's default URL with `client.setEndpoint`.

Would you like to work on this issue?

**Comment by igordonin** [comment]
I was investigating the issue and I'd need more context on what you're looking to do here. 

One of the things that came up is that, even though you allow for HTTP methods to be specified by the `custom` function, the method is not actually being used to make the request; it always uses `POST`. `graphql-request` itself also only allows for `GET` or `POST`, so all of the other methods allowed by the `CustomParams` interface are pointless and would need to be narrowed down into the allowed methods anyways.

So what is the purpose of the `custom` function? Should clients be allowed to make actual `GET` requests to their GraphQL clients? What about the other HTTP methods? If they are to be allowed, it won't be through `graphql-request`.

**Comment by igordonin** [comment]
This would be the proposed solution to allow only `GET` and `POST`, if that be the case.

```
    custom: async ({ url, method, headers, meta }) => {
      const ALLOWED_METHODS = ["get", "post"];
      const requestUrl = url || (client as any).url;

      if (!ALLOWED_METHODS.some((it) => it === method)) {
        throw Error(`GraphQL does not allow ${method} method.`);
      }

      const validMethod = method as "get" | "post";

      const _client = new GraphQLClient(requestUrl, {
        method: validMethod,
        headers,
      });

      const gqlOperation = meta?.gqlMutation ?? meta?.gqlQuery;

      if (gqlOperation) {
        const response: any = await _client.request<BaseRecord>({
          document: gqlOperation,
          variables: meta?.variables,
          requestHeaders: headers,
        });

        return { data: response };
      }

      if (meta?.rawQuery) {
        const response = await _client.request<BaseRecord>({
          document: meta.rawQuery,
          variables: meta.variables,
          requestHeaders: headers,
        });

        return { data: response };
      }

      if (meta) {
        if (meta.operation) {
          let query;
          let variables;

          if (method === "get") {
            const gqlQuery = gql.query({
              operation: meta.operation,
              fields: meta.fields,
              variables: meta.variables,
            });

            query = gqlQuery.query;
            variables = gqlQuery.variables;
          } else {
            const gqlMutation = gql.mutation({
              operation: meta.operation,
              fields: meta.fields,
              variables: meta.variables,
            });

            query = gqlMutation.query;
            variables = gqlMutation.variables;
          }

          const response = await _client.request<BaseRecord>({
            document: query,
            variables,
            requestHeaders: headers,
          });

          return {
            data: response[meta.operation],
          };
        }
        throw Error("GraphQL operation name required.");
      }
      throw Error(
        "GraphQL needs operation, fields and variables values in meta object.",
      );
    },
```

**Comment by BatuhanW** [comment]
Hey @igordonin idea was to allow users to make custom Graphql **or** custom REST requests to their API. So, custom method should allow **both of them**.
