### ISSUE TITLE
[FEAT] `@refinedev/supabase` missing support for date ranges and "between" filter operator

### ISSUE THREAD

**Issue by VladTabacariu** [refinedev/refine#6119]
### Describe the bug

I'm using the example below with antd and supabase.

https://refine.dev/docs/ui-integrations/ant-design/components/filter-dropdown/#rangepickerfiltermapper

When trying to filter no results are returned by supabase query which looks something like this:

Query string parameters:
select: *
offset: 0
limit: 10
order: created_at.desc
created_at: in.(2024-06-30T21:00:00.000Z,2024-07-03T21:00:00.000Z)

The problem is that is should look something like this:

Query string parameters::
select: *
offset: 0
limit: 10
order: created_at.desc
created_at: gte.2024-06-30T21:00:00.000Z
created_at: lte.2024-07-03T21:00:00.000Z

Another thing that doesn't work is the "defaultFiltertedValue" even if i change the operator from "between" to "in".

it would be nice if we had an example of a working date filter in CodeSandbox on this page or update the existing one to include a Date column.

### Steps To Reproduce

Use the example in the link above

### Expected behavior

It should filter using "gte" and "lte" operators not "in" operator.

### Packages

latest. updated with devtools.
"@refinedev/antd": "^5.42.0",
 "@refinedev/cli": "^2.16.36",
"@refinedev/core": "^4.49.2",
"@refinedev/supabase": "^5.9.2",

**Comment by BatuhanW** [comment]
Hey @VladTabacariu thanks for the report! I think supabase data provider doesn't support `between` filter, adding between support should fix this issue. Are you interested in working on this one?

**Comment by aliemir** [comment]
@VladTabacariu, just checked about the issue on `defaultFilteredValue` but looks like it's working as expected. You can see the live example [here](https://example.crm.refine.dev/administration/audit-log?pageSize=10&current=1&filters[0][field]=user.name&filters[0][operator]=contains&filters[1][field]=createdAt&filters[1][operator]=between&filters[1][value][0]=2024-06-30T21:00:00.000Z&filters[1][value][1]=2024-07-19T21:00:00.000Z) and its source [here](https://github.com/refinedev/refine/blob/22fa4958e5ce6f6051420f8fd76e6aef26d08a1f/examples/app-crm/src/routes/administration/audit-log.tsx#L165-L168).

About the `between` or `in` filter; we map our filters based on what the data provider supports. In this case Supabase doesn't work with `between` or `in` filters to filter out date ranges and they recommend using `gte` and `lte` for this. You can set one of them in the Column and map the filters in the `<DatePicker.RangePicker />` or `<FilterDropdown />` yourself to achieve setting both filters properly. 

We can accept a PR implementing `between` filter for `@refinedev/supabase` that maps values to `gte` and `lte` accordingly. Let us know if you're interested on working on this one 🙏

**Comment by Sergio16T** [comment]
Hi @aliemir! Can you please assign this ticket to me? I've begun working on implementing this enhancement.

**Comment by aliemir** [comment]
Hey @Sergio16T assigned! We're excited to see your contribution 🚀

**Comment by Sergio16T** [comment]
@aliemir PR is ready for review.

**Comment by aliemir** [comment]
This feature is added to the latest version of `@refinedev/supabase` and released thanks to the @Sergio16T 🙏
