### ISSUE TITLE
[FEAT] Add Script for Remix SPA Mode

### ISSUE THREAD

**Issue by YusukeSano** [refinedev/refine#6127]
### Is your feature request related to a problem? Please describe.

In Remix SPA Mode, the scripts differ from those in the regular Remix setup.

```json
"dev": "remix vite:dev",
"build": "remix vite:build",
"start": "vite preview",
```

Currently, the refine CLI only supports Remix SSR Mode.

### Describe alternatives you've considered

Using [npm-run-all](https://www.npmjs.com/package/npm-run-all).

Example: `npm run dev`
```json
"devtools": "refine devtools",
"dev:remix": "remix vite:dev",
"dev": "npm-run-all --parallel devtools dev:remix",
```

### Describe the thing to improve

Whether SPA Mode is enabled can be determined from `vite.config.ts`. While it would be ideal if `getProjectType` could detect this, it seems more reasonable to make it selectable through the platform option, as shown below:

`refine dev -p remix-spa`

**Comment by BatuhanW** [comment]
Hey @YusukeSano thanks for the report! It's a good suggestion, would you like to work on this?

**Comment by swethamanur** [comment]
@BatuhanW , if the issue is unassigned, could I work on this one please?

**Comment by YusukeSano** [comment]
Apologies to @swethamanur, but our team needed this feature, so we created a pull request.
