### ISSUE TITLE
[BUG] Handle empty filters on nestjsx/crud data provider

### ISSUE THREAD

**Issue by dfliess** [refinedev/refine#6146]
Description:

There is an issue in the handleFilter.ts file where filter handling may be improved. The current code does not properly check if the filters variable is a non-empty array, which may lead to unexpected behavior or errors.

Location:
https://github.com/refinedev/refine/blob/b07e95bbb24aaabed320810cd3c25a7132e172b4/packages/nestjsx-crud/src/utils/handleFilter.ts#L39

Proposed Fix:
Update the condition at line 39 in handleFilter.ts to the following:

```javascript
if (Array.isArray(filters) && filters.length > 0) {
```

**Comment by aliemir** [comment]
Hey @dfliess thank you for reporting this. Does this check cause any issues for you? Does passing an empty array of filters cause any unwanted chars in the query or in the request body? 

Do you want to work on this one? We'll be happy to see your PR 🚀 Please check our [Contributing Guide](https://refine.dev/docs/guides-concepts/contributing) to get started 👏
