### ISSUE TITLE
[BUG] Supabase throws 400 (Bad Request) error "unexpected end of input expecting field name (* or [a..z0..9_$])"

### ISSUE THREAD

**Issue by anoninthekop** [refinedev/refine#6177]
### Describe the bug

When my page loads one of the initial queries is 

`https://.supabase.co/rest/v1/works?select=*&offset=0&limit=10&=ilike.%25`

I think the `&=ilike.%25` at the end is causing the error but I cannot figure out how to remove it

As far as I can see the page still loads correctly but it displays the error after a few seconds and I can see the request failing in the developer console.

### Steps To Reproduce

1. Login
2. Go to app index page
3. Wait for a few seconds

### Expected behavior

The page to load correctly without any errors

### Packages

├── @ant-design/compatible@5.1.2
├── @refinedev/inferencer@4.5.17
├── @refinedev/react-router-v6@4.5.5
├── @refinedev/supabase@5.9.2
├── @testing-library/jest-dom@5.17.0
├── @testing-library/react@11.2.7
├── @testing-library/user-event@12.8.3
├── @types/jest@26.0.24
├── @types/lodash@4.14.202
├── @types/node@12.20.55
├── @types/react-dom@18.2.18
├── @types/react@18.2.48
├── @uiw/react-md-editor@3.25.6
├── antd@5.13.2
├── eslint-plugin-react-hooks@4.6.0
├── lodash.debounce@4.0.8
├── moment@2.30.1
├── rc-picker@3.14.6
├── react-dom@18.2.0
├── react-router-dom@6.21.3
├── react-scripts@5.0.1
├── react@18.2.0
├── typescript@4.9.5
└── web-vitals@1.1.2

**Comment by BatuhanW** [comment]
Can you provide relevant code? It's not easy to guess the problem judging by query params.

**Comment by aliemir** [comment]
Hey @anoninthekop, by looking at the output query params, it looks like there's a broken filter item in your code. It may be coming from the URL if you have `syncWithLocation` and it will persist if you don't have it fixed. This broken filter item has an operator (can be `endswith`) and value (probably `25`) but missing `field` value. Can there be an error in your filter removal logic if you're handling it manually, or can there be something broken when you're setting the filter? 🤔 

After checking those, if the issue continues, please provide us with a minimal repro or relevant code to work with 🙏

**Comment by anoninthekop** [comment]
Thanks it was indeed a broken filter 

```
  const [value, setValue] = useState<string>("");
  const [field, setField] = useState<string>("");

  const { refetch: refetchWorks } = useList<IWork>({
      resource: "works",

      filters: [{ field: field, operator: "startswith", value }]
  });
```

I changed it to :

`filters: field != "" ? [{ field: field, operator: "startswith", value }] : []`


and now it works fine
