### ISSUE TITLE
[FEAT] Rename `useSelect`'s `queryResult` to `query`.

### ISSUE THREAD

**Issue by alicanerdurmaz** [refinedev/refine#6179]
### Is your feature request related to a problem? Please describe.

`queryResult` name is long.

```tsx
const { queryResult, defaultValueQueryResult } = useSelect()
```

### Describe the thing to improve

We can delete the result part for the name. this way it will be more readable.

```tsx
const { query, defaultQuery } = useSelect()
```

### Additional context

The following hooks should be refactored too.

- useCheckboxGroup
- useRadioGroup
- useAutocomplete

**Comment by osilviotti** [comment]
I'm not sure about this as a change - `query` and `queryResult` are semantically different. I would expect `query` to refer to  what is being requested (like SQL queries).

If you wanted to shorten it, I think `result` works better and keeps the same meaning
