### ISSUE TITLE
[BUG] Typo in examples/app-crm-minimal code snippets graphql/queries.ts

### ISSUE THREAD

**Issue by ConnorMacDonell** [refinedev/refine#6213]
### Describe the bug

On line 19 of the above mentioned file there is a typo: `DASHBORAD_CALENDAR_UPCOMING_EVENTS_QUERY` should be `DASHBOARD_CALENDAR_UPCOMING_EVENTS_QUERY`

I'd be happy to fix it if I can

### Steps To Reproduce

Go to examples/app-crm-minimal -> README code snippets -> graphql/queries.ts

### Expected behavior

Just a typo

### Packages

This is part of the app-crm-minimal sample

**Comment by aliemir** [comment]
Hey @ConnorMacDonell thank you for reporting this 🙏 Let us know if you want to work on the fix, we'll be happy to see your contribution! 🚀

**Comment by ConnorMacDonell** [comment]
@aliemir thanks for the response. I'll be happy to fix it

**Comment by ConnorMacDonell** [comment]
@aliemir 

After forking the repo and taking a look at it, it appears that the typo is repeated in `examples/app-crm-minimal\src\routes\dashboard\components\upcoming-events\queries.ts` and `examplesapp-crm-minimal\src\routes\dashboard\components\upcoming-events\index.tsx` shall I fix it in those instances as well?

**Comment by aliemir** [comment]
Hey @ConnorMacDonell sorry for the late answer. Yeah, we need to fix this for all instances inside `examples/app-crm` 🙏 Let me know if you can still work on it.
