### ISSUE TITLE
[BUG] Nested CrudFilters values with Supabase not correctly parsed

### ISSUE THREAD

**Issue by pkarc** [refinedev/refine#6239]
### Describe the bug

Filter values on nested queries with `contains`, `containss`, `startswith` and `endswith` filters are not parsed to the respective format with the Supabase dataProvider.

### Steps To Reproduce

Consider the following filter:

```js
const filter: CrudFilter = {
  operator: 'or',
  value: [
    {
      field: 'name',
      operator: 'contains',
      value: 'foo',
    }
  ],
};
```
resolve to (name.ilike.foo) giving no results

### Expected behavior

The filter should resolve to (name.ilike.%foo%) 

### Packages

- @refinedev/supabase

**Comment by aliemir** [comment]
Thank you for reporting @pkarc, we'll review the PR as soon as we can 🚀

**Comment by MayuriShingote** [comment]
hey can I solve this PR i am interested in it
