### ISSUE TITLE
[FEAT] replace `preferred-pm` with `package-manager-detector`

### ISSUE THREAD

**Issue by benmccann** [refinedev/refine#6242]
### Is your feature request related to a problem? Please describe.

preferred-pm pulls in 24 dependencies, which is unnecessary for what it does: https://npmgraph.js.org/?q=preferred-pm

package-manager-detector has no dependencies: https://npmgraph.js.org/?q=package-manager-detector

### Additional context

This code has been battle-tested for a long time in the heavily used `@antfu/ni`. It was recently extracted out into its own library. I am switching Svelte's CLI to use it: https://github.com/svelte-add/svelte-add/pull/535

### Describe the thing to improve

Reduce the number of dependencies

**Comment by BatuhanW** [comment]
Hey @benmccann looks like a good idea, would you like to work on this?

**Comment by aliemir** [comment]
Thanks to @benmccann, this issue is addressed in #6250 for `@refinedev/devtools-server`. `preferred-pm` is also used in `@refinedev/cli` and same changes can be applied to it as well. If anyone is interested on working on this, please let us know 🙏 We'll be happy to see new contributors 🚀
