### ISSUE TITLE
[BUG] Keycloak auth not working, redirecting back to login

### ISSUE THREAD

**Issue by BojanKnezevic** [refinedev/refine#6249]
### Describe the bug

Hello, I have encountered a bug with Keycloak.

I have created a new app with `npm create refine-app@latest`, using Keycloak as auth provider.
The app builds fine, but upon trying to log in, I get redirected back to login page with url params. I will provide screenshots of the process.

1. Refine login page
![Screenshot from 2024-08-12 15-19-59](https://github.com/user-attachments/assets/1feb6399-9c55-482e-98b4-2bfa916039eb)

2. Keycloak login page
![Screenshot from 2024-08-12 15-20-15](https://github.com/user-attachments/assets/241a5813-c772-452b-b2eb-db92bfe9d2c6)

3. Redirected back to Refine login page, with url params
![Screenshot from 2024-08-12 15-20-26](https://github.com/user-attachments/assets/7dafb66f-e643-4714-b486-723b166110cb)

Just to note, this behavior is not observed when creating an example with `npm create refine-app@latest -- --example auth-keycloak`

Another side note, the login credentials in the documentation are not updated, username and password should be refine and not Refine.

### Steps To Reproduce

1. Create a new app with `npm create refine-app@latest`, select Keycloak as auth provider, other options are not relevant
2. Cd to project, run `npm run dev`
3. Click 'Sign in' button
4. Enter login credentials

### Expected behavior

Expected behavior is that with the provided credentials, a user should be logged in, instead, the user is redirected back to the login page with additional URL parameters.

### Packages

"@react-keycloak/web": "^3.4.0",
"@refinedev/antd": "^5.37.4",
"@refinedev/cli": "^2.16.21",
"@refinedev/core": "^4.47.1",
"@refinedev/react-router-v6": "^4.5.5",
"@refinedev/simple-rest": "^5.0.1",

**Comment by BatuhanW** [comment]
Hey @BojanKnezevic thanks for the issue. I think this issue should be fixed at https://github.com/pankod/superplate-core-plugins

Could you create an issue there?
