### ISSUE TITLE
[FEAT] Add support to `and`, `or`, `between`, `null` and `nnull` operators in `@refinedev/appwrite`

### ISSUE THREAD

**Issue by soranoo** [refinedev/refine#6252]
### Is your feature request related to a problem? Please describe.

`and` and `or` are common operators in filtering.

### Describe the thing to improve

Please assign it to me ❤️

**Comment by aliemir** [comment]
Hey @soranoo, thank you for the request. Looks like we're also missing `startswiths`, `endswiths`, can you include them in  your implementation? I'm assigning the issue to you and we'll be looking forward to see your PR 🚀 🚀

**Comment by soranoo** [comment]
Sure!

**Comment by soranoo** [comment]
Just in case, why are we using `Query.search` instead of `Query.contains`?
https://github.com/refinedev/refine/blob/c42a1bd16a003cc85cee198d04dc710aa49c4720/packages/appwrite/src/utils/generateFilter.ts#L18-L19

ref: https://appwrite.io/docs/products/databases/queries
