### ISSUE TITLE
[BUG] Default notificationProvider has duplicate keys issue

### ISSUE THREAD

**Issue by PercivalFigaro** [refinedev/refine#6269]
### Describe the bug

When two notifications of the same kind appear in close progression, the notifications can have same keys, causing both to disappear at once, even though the latest snackbar only just appeared.

### Steps To Reproduce

When you edit a form entry (using useForm and the default notificationProvider), then quickly edit the same form again, then you will get two notification snackbars with the same key, causing unexpected behavior.

![image](https://github.com/user-attachments/assets/ee5b858f-263d-4b36-b4bf-fcab0349b04a)

### Expected behavior

What should happen instead is that both snackbars should have unique keys, so that they do not disappear together when they are closed.

### Packages

    "@refinedev/cli": "^2.16.37",
    "@refinedev/core": "^4.54.0",
    "@refinedev/devtools": "^1.2.7",
    "@refinedev/kbar": "^1.3.12",
    "@refinedev/mui": "^5.20.0",
    "@refinedev/react-hook-form": "^4.9.0",
    "@refinedev/react-router-v6": "^4.6.0",
    "@refinedev/simple-rest": "^5.0.8",

**Comment by BatuhanW** [comment]
Hey @PercivalFigaro can you provide a minimal reproducible example? Are you building notification yourself? It's hard to judge without example.

**Comment by aliemir** [comment]
Hey @PercivalFigaro, we're using predictable keys for notifications based on the type and resource etc. I think triggering a mutation repeatedly with a very close interval is not very common 😅 Also having them unique keys will be an issue if users are using `preventDuplicate` prop of `<SnackbarProvider />` 🤔

I think it will be better to pass the `key` explicitly to the notification props in this case. Assuming you're also experimenting this based on your other issue report 😅 Let me know if we're on the same track here 🙏

**Comment by PercivalFigaro** [comment]
@aliemir Okay, sounds good. I'm fine with leaving this as is. Thanks!
