### ISSUE TITLE
[BUG] installer reports incorrect version of node, but I am using the correct version

### ISSUE THREAD

**Issue by toddrimes** [refinedev/refine#6281]
### Describe the bug

run npm create refine-app@latest
installer starts and asks questions
get the error
note that node --version shows I am using the correct version (screenshot)

### Steps To Reproduce

1. run npm create refine-app@latest
2. installer starts and asks questions
3. get the error
4. note that node --version shows I am using the correct version (screenshot)

### Expected behavior

completed install

### Packages

![Screenshot 2024-08-26 at 7 47 58 PM](https://github.com/user-attachments/assets/e42d2f72-3cc1-4d6f-acb8-9172790d4ebb)

**Comment by BatuhanW** [comment]
Hey @toddrimes I couldn't reproduce the issue.

<img width="1010" alt="Screenshot 2024-08-27 at 14 14 06" src="https://github.com/user-attachments/assets/e72899c1-fe8e-41f4-9c91-2ca58a289fd6">

Which yarn version are you using? And are you using nvm?

**Comment by toddrimes** [comment]
Hi. Yes, I'm using nvm. And you can see my node version at the bottom of the screenshot.
I have yarn 1.22.22.  Would that cause the error I'm seeing?

**Comment by toddrimes** [comment]
Since you can't reproduce it, what should I do?

**Comment by toddrimes** [comment]
I also do not get the error with the refine-vite template.  Please note I chose (and still prefer) refine-nextjs in my initial screenshot.

**Comment by toddrimes** [comment]
Hm - I tried again using npm instead of yarn and it succeeded.  Thank you!

**Comment by toddrimes** [comment]
D'oh!  Now I get the same error when I do 'npm run dev': 
<img width="565" alt="Screenshot 2024-08-27 at 2 49 50 PM" src="https://github.com/user-attachments/assets/05df1b58-09a9-4ffc-b1ed-4f38c36486e2">
