### ISSUE TITLE
[BUG] Something went wrong when trying to get installed `Refine` packages.

### ISSUE THREAD

**Issue by toddrimes** [refinedev/refine#6282]
### Describe the bug

in new refine project, do 'npm run dev'
no errors occur
Note message : "Something went wrong when trying to get installed `Refine` packages."
When I start 'localhost:5001', landing page appears, but error message at top says "No App Connected"
<img width="679" alt="Screenshot 2024-08-27 at 3 47 55 PM" src="https://github.com/user-attachments/assets/03ff1091-59c6-42ac-b217-3c8d89b05be6">
<img width="1426" alt="Screenshot 2024-08-27 at 3 50 48 PM" src="https://github.com/user-attachments/assets/798c0cf8-114b-4089-9db5-4de61bc17058">

### Steps To Reproduce

1. in new refine project, do 'npm run dev'
2. no errors occur
3. Note message : "Something went wrong when trying to get installed `Refine` packages."
4. When I start 'localhost:5001', landing page appears, but error message at top says "No App Connected"
5. <img width="679" alt="Screenshot 2024-08-27 at 3 47 55 PM" src="https://github.com/user-attachments/assets/03ff1091-59c6-42ac-b217-3c8d89b05be6">
6. <img width="1426" alt="Screenshot 2024-08-27 at 3 50 48 PM" src="https://github.com/user-attachments/assets/798c0cf8-114b-4089-9db5-4de61bc17058">

### Expected behavior

1. expected app to run without error message : "Something went wrong when trying to get installed `Refine` packages."
2. expected generated app to be connected to the refine dashboard

### Packages

    "@refinedev/cli": "^2.16.21",
    "@refinedev/core": "^4.47.1",
    "@refinedev/devtools": "^1.1.32",
    "@refinedev/graphql": "^6.4.8",
    "@refinedev/kbar": "^1.3.6",
    "@refinedev/nextjs-router": "^6.0.0",

**Comment by BatuhanW** [comment]
Hey @toddrimes it's because your app is running at 127.0.0.1. This happens if you are running node < 16 version. Please remove all node installations and try again. It seems you are having troubles with node version. Only open issues if you are certain that issue is about Refine, not your local dev environment.
