### ISSUE TITLE
Login Failure with Demo User - Invalid Email or Password

### ISSUE THREAD

**Issue by PabloTroncoso33** [refinedev/refine#6283]
### Describe the bug

I am experiencing an issue when trying to log in with the user demo@refine.dev and the password demo demo. Every time I attempt to log in, I receive a warning message at the top right that says:

Login failed: Invalid email or password.

### Steps To Reproduce

1. Go to the login page.
2. Enter the email: demo@refine.dev.
3. Enter the password: demo demo.
4. Click the "Login" button.

### Expected behavior

I expect to be logged in successfully.
![Captura de pantalla 2024-08-28 055011](https://github.com/user-attachments/assets/d28eaaec-f41a-41ce-ad95-b5d20730d567)
![Captura de pantalla 2024-08-28 055225](https://github.com/user-attachments/assets/56ceaccf-c9c4-45b1-bb60-f22781296c82)

### Packages

"@refinedev/antd": "^5.43.0",
    "@refinedev/cli": "^2.16.37",
    "@refinedev/core": "^4.54.0",
    "@refinedev/devtools": "^1.2.7",
    "@refinedev/react-router-v6": "^4.6.0",
    "@refinedev/strapi-v4": "^6.0.8",
    "antd": "^5.17.0",
    "antd-style": "^3.6.1",
    "axios": "^1.6.2",
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "react-input-mask": "^2.0.4",
    "react-router-dom": "^6.8.1"

### Additional Context

I have tried various troubleshooting steps, but I am unable to resolve the issue. Any guidance would be appreciated.
![Captura de pantalla 2024-08-28 055556](https://github.com/user-attachments/assets/c15352cf-739d-4100-b607-8ae806c185b1)

**Comment by BatuhanW** [comment]
We had an issue with strapi examples, now it should be resolved.

**Comment by BatuhanW** [comment]
Can you try again?

**Comment by PabloTroncoso33** [comment]
"Nothing has happened yet. I'm leaving you screenshots of the home page and when I want to register an account."
![image](https://github.com/user-attachments/assets/e9edafea-5e1e-44d6-a8b3-693ebe4b9509)

![image](https://github.com/user-attachments/assets/d7d9d9e6-391a-4a02-952a-57c7cb3afc74)

**Comment by BatuhanW** [comment]
Oh, overlooked that one. Didn't give permissions for user to account resource. Now it should be resolved.

**Comment by PabloTroncoso33** [comment]
"Perfect, @BatuhanW  . It's working correctly now. Thank you very much.

P.S.: I hope one day I can have as much patience as you. Thank you!"
