### ISSUE TITLE
[DOC] Deprecated `queryResult` Used Instead of `query` in Tutorial

### ISSUE THREAD

**Issue by emrecancorapci** [refinedev/refine#6284]
### Documentation issue

In tutorial, starting from _Routing/Inferring Parameters_ page `queryResult` is used instead of `query` while using `useShow()`. And it keeps going like that in the right section to the end of the tutorial.

https://refine.dev/tutorial/routing/inferring-parameters/react-router/

![image](https://github.com/user-attachments/assets/3727b559-ce14-4220-905c-b62cf9dd8a0f)

After that same thing happens with `useSelect()` in _UI Libraries/Refactoring_ and _UI Libraries/CRUD Components_.

https://refine.dev/tutorial/ui-libraries/refactoring/material-ui/react-router/
https://refine.dev/tutorial/ui-libraries/crud-components/material-ui/react-router/

![image](https://github.com/user-attachments/assets/d15fadad-eacf-4f5b-bcdc-8a560e5d9d04)

### Describe the thing to improve

Updating the `queryResult` in docs with `query`.

Also I would like to be assigned to this issue if it's possible.

**Comment by BatuhanW** [comment]
Hey @emrecancorapci thanks for the issue. Would you like to work on this?

**Comment by BatuhanW** [comment]
Assigned to you, looking forward to your PR 🚀
