### ISSUE TITLE
[BUG] Refine Documentation Development Scripts Not Working

### ISSUE THREAD

**Issue by emrecancorapci** [refinedev/refine#6287]
### Describe the bug

When I try to run development server at documentation I get an error like this:

![image](https://github.com/user-attachments/assets/b402b54c-becc-4357-bf54-4b5d6bbcbacd)

```bash
$ pnpm dev:docs

> documentation@0.0.0 dev:docs D:\**\refine-fork\documentation
> DISABLE_BLOG=true pnpm run dev:lean

'DISABLE_BLOG' is not recognized as an internal or external command,
operable program or batch file.
```

### Steps To Reproduce

1. Fork the `refine` repository.
2. Clone the forked repository.
3. Run `pnpm install` in the main folder.
4. Run `pnpm install` in the `documentation` folder.
5. Run `pnpm dev:docs`.

### Expected behavior

The development server should run successfully.

### Packages

**OS**:		Windows 10 Pro N 22H2 19045.4780
**Node**:	v22.6.0
**pnpm**:	v9.4.0

**Comment by BatuhanW** [comment]
Hey @emrecancorapci thanks for the report. I think we need to use `cross-env` for documentation scripts, as we do it with refine scripts.

We are open to contributions for this one.

**Comment by emrecancorapci** [comment]
@BatuhanW I would like to be assigned to this issue.

**Comment by BatuhanW** [comment]
@emrecancorapci done.

**Comment by aaditya1100** [comment]
Hi, I’d love to work on this as my first contribution. Please assign it to me if it’s available.

**Comment by sajalshh** [comment]
https://github.com/refinedev/refine/issues/6287?utm_source=chatgpt.com

**Comment by sajalshh** [comment]
Hi, I’d love to work on this as my first contribution. Please assign it to me if it’s available.
