### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Villva-vinoth** [refinedev/refine#6290]
### Describe the bug

Button disabled but it is working as it is 

### Steps To Reproduce

![image](https://github.com/user-attachments/assets/5db8235a-5254-4192-af50-5f441a21667e)

here the button is button but its working as its 

### Expected behavior

and this scenerios in case is i have a disabled button on edit but it is navigating and editing 

---> https://example.mui.admin.refine.dev/stores/2/edit 

EditButton in refine/mui --> gives this 

### Packages

{
  "name": "ri-client",
  "version": "0.1.0",
  "private": true,
  "type": "module",
  "dependencies": {
    "@emotion/react": "^11.8.2",
    "@emotion/styled": "^11.8.1",
    "@mui/icons-material": "^5.8.3",
    "@mui/lab": "^5.0.0-alpha.85",
    "@mui/material": "^5.8.6",
    "@mui/x-data-grid": "^6.6.0",
    "@refinedev/cli": "^2.16.21",
    "@refinedev/core": "^4.47.1",
    "@refinedev/devtools": "^1.1.32",
    "@refinedev/kbar": "^1.3.6",
    "@refinedev/mui": "^5.14.4",
    "@refinedev/react-hook-form": "^4.8.14",
    "@refinedev/react-router-v6": "^4.5.5",
    "@refinedev/simple-rest": "^5.0.1",
    "axios": "^1.7.5",
    "dayjs": "^1.11.13",
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "react-hook-form": "^7.30.0",
    "react-router-dom": "^6.8.1"
  },
  "devDependencies": {
    "@types/node": "^18.16.2",
    "@types/react": "^18.0.0",
    "@types/react-dom": "^18.0.0",
    "@typescript-eslint/eslint-plugin": "^5.57.1",
    "@typescript-eslint/parser": "^5.57.1",
    "@vitejs/plugin-react": "^4.0.0",
    "eslint": "^8.38.0",
    "eslint-plugin-react-hooks": "^4.6.0",
    "eslint-plugin-react-refresh": "^0.3.4",
    "typescript": "^5.4.2",
    "vite": "^4.3.1"
  },
  "scripts": {
    "dev": "refine dev",
    "build": "tsc && refine build",
    "start": "refine start",
    "refine": "refine"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },

}

**Comment by GeriFixit** [comment]
If you want to disable button you have to add disabled attribute to the button.
![image](https://github.com/user-attachments/assets/45a7e5d3-77a7-43b0-9675-f804088ddfb5)

yours doesnt seem to have one.
