### ISSUE TITLE
[BUG] UseGetIdentity is not work on App page.

### ISSUE THREAD

**Issue by onrdmr** [refinedev/refine#6293]
### Describe the bug

Hey, I like your project. I have developing this platform but i want to use role based authentication in refine.dev so i have used useGetIdentity hook but it gives following error.

![image](https://github.com/user-attachments/assets/8d8cf088-7e33-41bb-a292-475e0d1ad825)

![image](https://github.com/user-attachments/assets/a0207a3c-397a-46fc-a87b-6fcb11e8d159)

Gives Following Error.
Uncaught Error: No QueryClient set, use QueryClientProvider to set one
    useQueryClient http://localhost:3000/node_modules/.vite/deps/chunk-FPORH5AE.js?v=f8d9dc3e:6111
    useBaseQuery http://localhost:3000/node_modules/.vite/deps/chunk-FPORH5AE.js?v=f8d9dc3e:6220
    useQuery http://localhost:3000/node_modules/.vite/deps/chunk-FPORH5AE.js?v=f8d9dc3e:6268
    $r http://localhost:3000/node_modules/.vite/deps/chunk-FPORH5AE.js?v=f8d9dc3e:8683
    App http://localhost:3000/src/App.tsx?t=1725354551900:60
    renderWithHooks http://localhost:3000/node_modules/.vite/deps/chunk-PPVFY42G.js?v=f8d9dc3e:11568
    mountIndeterminateComponent http://localhost:3000/node_modules/.vite/deps/chunk-PPVFY42G.js?v=f8d9dc3e:14946
    beginWork http://localhost:3000/node_modules/.vite/deps/chunk-PPVFY42G.js?v=f8d9dc3e:15934
    beginWork$1 http://localhost:3000/node_modules/.vite/deps/chunk-PPVFY42G.js?v=f8d9dc3e:19781
    performUnitOfWork http://localhost:3000/node_modules/.vite/deps/chunk-PPVFY42G.js?v=f8d9dc3e:19226
    workLoopSync http://localhost:3000/node_modules/.vite/deps/chunk-PPVFY42G.js?v=f8d9dc3e:19165
    renderRootSync http://localhost:3000/node_modules/.vite/deps/chunk-PPVFY42G.js?v=f8d9dc3e:19144
    recoverFromConcurrentError http://localhost:3000/node_modules/.vite/deps/chunk-PPVFY42G.js?v=f8d9dc3e:18764
    performSyncWorkOnRoot http://localhost:3000/node_modules/.vite/deps/chunk-PPVFY42G.js?v=f8d9dc3e:18907
    flushSyncCallbacks http://localhost:3000/node_modules/.vite/deps/chunk-PPVFY42G.js?v=f8d9dc3e:9135
    flushSync http://localhost:3000/node_modules/.vite/deps/chunk-PPVFY42G.js?v=f8d9dc3e:18987
    scheduleRefresh http://localhost:3000/node_modules/.vite/deps/chunk-PPVFY42G.js?v=f8d9dc3e:20032
    performReactRefresh http://localhost:3000/@react-refresh:267
    performReactRefresh http://localhost:3000/@react-refresh:256
[chunk-FPORH5AE.js:6111:11](http://localhost:3000/node_modules/.vite/deps/chunk-FPORH5AE.js?v=f8d9dc3e)

### Steps To Reproduce

1. I have wrote useGetIdentity hook to App.ts.
2. Gives above error. 

### Expected behavior

Getting User information from my appwrite. it works well on other components but it is not work App.tsx. I want to show which resources is used which user 
![image](https://github.com/user-attachments/assets/2dbdcce9-7a96-45f7-a6f0-bb11697bde56)

### Packages

@refinedev/core

**Comment by onrdmr** [comment]
I have solved with workaround but I guess, my solution is not so correct.
I have used local storage as in examples given [editor](https://codesandbox.io/p/devbox/nice-nova-zk7z4x?embed=1&file=%2Fsrc%2FApp.tsx%3A33%2C1-34%2C1)
[casbin documentation example](https://refine.dev/docs/examples/access-control/casbin/)
const role = localStorage.getItem("role"); 

![hide meta data using localstorage](https://github.com/user-attachments/assets/5bba6f84-8880-4e32-97bf-d680a6828379)

 
![and added role to local storage in authprovider](https://github.com/user-attachments/assets/d22c8ad5-cd30-48b8-a7e8-1bd8a8a99ae1)

**Comment by BatuhanW** [comment]
hey @onrdmr you can use our chatbot in documentation and/or in [our discord](https://discord.gg/refine). We are using issues only for bug reports or improvement ideas.
