### ISSUE TITLE
[DOC] wrong example for base64 upload

### ISSUE THREAD

**Issue by haashemi** [refinedev/refine#6295]
### Documentation issue

*Base64 Upload*'s example in *Advanced Tutorials* is showing a *multipart upload* example and not base64.

- URL: https://refine.dev/docs/advanced-tutorials/upload/base64-upload/#example-1

### Describe the thing to improve

Its example should be replaced with a base64 example.

### Describe the solution (optional)

If I'm not mistaken, its example should be the same as this page:
https://refine.dev/docs/examples/upload/antd/base64/

**Comment by BatuhanW** [comment]
Hey @haashemi thanks for the issue, would you like to work on it?

**Comment by haashemi** [comment]
Yes! please assign me. I'll try.
