### ISSUE TITLE
[BUG] disable normalizeData axiosInstans

### ISSUE THREAD

**Issue by bks-kristin** [refinedev/refine#6296]
### Describe the bug

I use strapi-v4 documentation plugin for creating swagger 3.0 docs, the generated documentation describes responses from strapi in the format: `id?: number;
  attributes?: attributes;`
![Screenshot 2024-09-04 134914](https://github.com/user-attachments/assets/93927e2b-0c4a-455d-9a68-357aaf26098f)

  but in normalizeData in DataProvider I get a different format without attributes
![Screenshot 2024-09-04 133957](https://github.com/user-attachments/assets/24781638-4568-4136-9162-3ab5b3d5e28d)

Because of this I can't use the generated documentation

### Steps To Reproduce

1. setup refine project with strapi v4
2. create strapi project and endpoint with data
3. in strapi project generate docs
4. generate types in refine project with swagger-typescript-api
5. try to use useList to fetch data from strapi
6. check types of data from useList

### Expected behavior

ability to disable normalizeData

### Packages

 "@refinedev/cli": "^2.16.21",
   "@refinedev/core": "^4.47.1",
    "@refinedev/devtools": "^1.1.32",
    "@refinedev/kbar": "^1.3.6",
    "@refinedev/mui": "^5.14.4",
    "@refinedev/nextjs-router": "^6.0.0",
    "@refinedev/react-hook-form": "^4.8.14",
    "@refinedev/strapi-v4": "^6.0.1",
 "swagger-typescript-api": "^13.0.22",
    "typescript": "^5.5.4"
backend-strapi: 
 "@strapi/plugin-documentation": "^4.25.9",
    "@strapi/strapi": "4.25.9",

**Comment by BatuhanW** [comment]
Hey @bks-kristin I guess this is not a bug with Refine. You can pass your generated types. UseList has a generic type, you can pass your own. BaseRecord is used as a fallback. You can also use chatbot in our documentation and/or [discord server](https://discord.gg/refine) for such questions.
