### ISSUE TITLE
[BUG] Antd ThemedSiderV2 Parent access control

### ISSUE THREAD

**Issue by fernando-deka** [refinedev/refine#6312]
### Describe the bug

Currently, the Antd ThemedSiderV2 is rendering the parent, even if all the children resources fail to pass the CanAccess check. This results in an empty parent that does nothing on the sidebar.

### Steps To Reproduce

Create a sample Antd project with an access control provider and a parent and children resource.
Deny access to the children resources.
The parent resource still appears on the sidebar empty.

### Expected behavior

I expect the parent resource to NOT be rendered on the sidebar.

### Packages

- @refinedev/antd

**Comment by alicanerdurmaz** [comment]
Hello @fernando-deka, thanks for the detailed explanation but I have further questions.

In my opinion, checking all of a parent's children and not rendering the parent if there are no children is inefficient. This approach also goes against React's asynchronous nature.

Could you share your use case? Because if a resource doesn’t have permission for all its children, the parent shouldn’t have permission either, am I right?

**Comment by fernando-deka** [comment]
Hi @alicanerdurmaz thanks for your fast reply!

The parent itself is not an actual resource, it is just a dummy resource to be able to group multiple ones on the sidebar. Therefore, the access control does not check it.

Checking on the current implementation, you do not need to check the children access 2 times, you could just check if all of the children components are null, then just omit the parent?

**Comment by fernando-deka** [comment]
I ended up fixing this with css at least until there is a better solution:

```css
.ant-menu-submenu:has(> ul:empty) {
  display: none;
}
```

**Comment by aliemir** [comment]
Hey @fernando-deka, thank you for sharing your solution 🙏 For now, parent elements are also treated as resources go through the access control process themselves. Other than the CSS option you've shared, other options will sacrifice the benefits of JSX and caching the access control checks will be hard to handle. 

We have some improvements and refactors planned for the layouts for the next months. I'll be adding this to our list of improvements and try to ping here when we have any related updates. 

Thanks again for the solution. Closing the issue for now but will keep it updated. Let us know if you have any suggestions and updates 🚀 🚀
