### ISSUE TITLE
[BUG] Menu Button and Heading Overlap in Mobile Preview.

### ISSUE THREAD

**Issue by Harshu29-09** [refinedev/refine#6323]
### Describe the bug

When a user views a preview from refine.dev on a mobile device, the menu button and heading overlap, causing them to collapse. The menu button should be properly positioned within the header section to prevent this.
![Screenshot from 2024-09-12 13-01-28](https://github.com/user-attachments/assets/312f62cc-130f-4530-8c60-0763520c29cc)

![Screenshot from 2024-09-12 12-52-12](https://github.com/user-attachments/assets/d9ab12dd-d010-437d-8dde-bc35232cd5d5)

### Steps To Reproduce

Described in the describe section.

### Expected behavior

menu button should be in the header section.

### Packages

preview section.

**Comment by alicanerdurmaz** [comment]
Hello @Harshu29-09, Thanks for the issue.

Yes, it could be better but we have no plans to implement this soon.
In the meantime, you can customize `<ThemedLayout />` with swizzle.

https://refine.dev/docs/ui-integrations/ant-design/components/themed-layout/#customizing-with-swizzle

**Comment by Harshu29-09** [comment]
> Hello @Harshu29-09, Thanks for the issue.
> 
> Yes, it could be better but we have no plans to implement this soon. In the meantime, you can customize `<ThemedLayout />` with swizzle.
> 
> https://refine.dev/docs/ui-integrations/ant-design/components/themed-layout/#customizing-with-swizzle

Hey @alicanerdurmaz, thank you for your response!

I'd definitely like to proceed with this task, but could you please provide a bit more detail on what steps I need to follow to customize <ThemedLayout /> with swizzle?
