### ISSUE TITLE
[FEAT] Support for MUI v6

### ISSUE THREAD

**Issue by s-jakob** [refinedev/refine#6333]
### Is your feature request related to a problem? Please describe.

no

### Describe the thing to improve

Hi,
Are there any plans to support MUI v6? 
Best

**Comment by alicanerdurmaz** [comment]
Hello @s-jakob, thanks for the issue.

We love MUI and will update it to MUI v6, but I can't give you an exact time.

Do you want to work on this?

**Comment by imHardik1606** [comment]
Hi there, 
If this issue is still unsolved, I would like to take on this issue. Please assign it to me.
