### ISSUE TITLE
[BUG] Filters cannot be multiple of the same field and operator

### ISSUE THREAD

**Issue by sohaibgv** [refinedev/refine#6340]
### Describe the bug

When adding multiple filters, it is not possible to create a filter with the same field and operator twice. It is really vague why this has even been decided. 

Some scenarios where this doesn't make sense are:
I want to filter on a name not being equal to Tom and also not being equal to John. 
I want to filter on dates and have two dates that I do not want to be added to the result set.

Currently these filters are not possible because refine either merges or replaces any fields that have the same field and operator. 

### Steps To Reproduce

1. Ensure that you use a UI library that allows multiple filters, I used MUI DataGrid Pro and filter on the back-end
2. Ensure that filter history is persisted on refreshes in for example the URL by setting syncWithLocation: true
3. Add two filters with the same field and with the same operator
4. Change something in filter 1
5. Change something in filter 2
6. Refresh

The filters are not persisted even with syncLocation. There is a very buggy state as filter 2 points to the same state value as filter 1. It seems that refine is not configured to work with multiple filters with the same operator like this yet. 

### Expected behavior

Both filters to be executed and the back-end should simply be handling this as this filter is valid. 

### Packages

 "@mui/icons-material": "^5.8.3",
    "@mui/lab": "^5.0.0-alpha.85",
    "@mui/material": "^5.8.6",
    "@mui/x-data-grid-pro": "^7.14.0",
    "@mui/x-date-pickers": "^6.16.0",
    "@react-keycloak/web": "^3.4.0",
    "@refinedev/cli": "^2.16.31",
    "@refinedev/core": "^4.49.2",
    "@refinedev/devtools": "^1.2.1",
    "@refinedev/inferencer": "^4.7.0",
    "@refinedev/kbar": "^1.3.10",
    "@refinedev/mui": "^5.15.1",
    "@refinedev/react-hook-form": "^4.8.18",
    "@refinedev/react-router-v6": "^4.5.9",
    "@refinedev/simple-rest": "^5.0.6",
    "@refinedev/ui-types": "^1.22.9",

**Comment by BatuhanW** [comment]
Hey @sohaibgv, you can use `and` or `nin` operators. This is not a buggy behavior, this is a sane behavior. As multiple filters with same field and operator wouldn't be consistent to handle.

**Comment by aliemir** [comment]
As an addition to @BatuhanW's comment I want to state some internal logic here. Operator and field pairs are treated as keys for the filters state and also for syncing with the URL. `merge` behavior will not be possible if this is not implemented this way and it will require an additional field to keep track of the filters.
