### ISSUE TITLE
[FEAT] export useInvalidateAuthStore or provide similar hooks

### ISSUE THREAD

**Issue by pcfreak30** [refinedev/refine#6341]
### Is your feature request related to a problem? Please describe.

I am in need of invalidating the users identity state and force a react query refresh. `useInvalidateAuthStore` is not exposed through.

I would like to see this exported, or create hooks that can be used to invalidate the individual queries it invalidates all at once.

### Describe the thing to improve

export `useInvalidateAuthStore` or provide similar apis

**Comment by alicanerdurmaz** [comment]
Hello @pcfreak30, Thanks for the issue, I think it will be good to export `useInvalidateAuthStore`. 

Would you like to work on this?

**Comment by pcfreak30** [comment]
> Hello @pcfreak30, Thanks for the issue, I think it will be good to export `useInvalidateAuthStore`.
> 
> Would you like to work on this?

I can if needed, though im in the process of trying to build locally to create a patch for myself and it seems to be choking on `Unknown compiler option 'allowImportingTsExtensions'` on only the core pkg.

Any input on that. I have tried to make my node and config setup match your CI.

**Comment by alicanerdurmaz** [comment]
> > Hello @pcfreak30, Thanks for the issue, I think it will be good to export `useInvalidateAuthStore`.
> > Would you like to work on this?
> 
> I can if needed, though im in the process of trying to build locally to create a patch for myself and it seems to be choking on `Unknown compiler option 'allowImportingTsExtensions'` on only the core pkg.
> 
> Any input on that. I have tried to make my node and config setup match your CI.

Can you please give us the full error log?

**Comment by aliemir** [comment]
Hey @pcfreak30 are you still interested in working on this? About the issue you're facing; maybe you can try it like `pnpm install --frozen-lockfile`. We'd love to help if you can provide more detailed logs for the error.

**Comment by pcfreak30** [comment]
> Hey @pcfreak30 are you still interested in working on this? About the issue you're facing; maybe you can try it like `pnpm install --frozen-lockfile`. We'd love to help if you can provide more detailed logs for the error.

I do think this should be done. I currently have patched the package via pnpm, and I have a number of upstream projects I need to get changes in.

So I am fine with someone else doing it as well if I don't do it 1st.

**Comment by sumeet-y** [comment]
hey @aliemir can i work on this issue ?

**Comment by BatuhanW** [comment]
Hey @sumeet-y, it seems your 2nd PR is closed by mistake. It was pointing to `releases/october` branch, we've merged that branch without merging your PR and it's closed. Could you re-open it?
