### ISSUE TITLE
[DOC] Show page path in search results

### ISSUE THREAD

**Issue by ThomasBurgess2000** [refinedev/refine#6344]
### Documentation issue

![image](https://github.com/user-attachments/assets/1dd1b2a0-4b57-42da-adcb-080336f871fc)

This is not a helpful search result. Doesn't tell you which is the view, the button, for which UI integration, etc.

### Describe the thing to improve

Show at least part of the page path/breadcrumb, like this:
![image](https://github.com/user-attachments/assets/2864205e-fdfd-4f38-9a6d-ea758553fe5e)

**Comment by aliemir** [comment]
Hey @ThomasBurgess2000, thank you for reporting this. Algolia's DocSearch has an issue currently in investigation which breaks hierarchy levels and groups in the search results. Check out https://github.com/algolia/docsearch/issues/2294

Just opened up a PR to fix this issue, it will be merged and deployed soon 🙏
