### ISSUE TITLE
[DOC] Building modules

### ISSUE THREAD

**Issue by spacewalkingninja** [refinedev/refine#6373]
### Documentation issue

I've recently encountered issues building the CORE module, which I am modifying in a medusaJS store I will be launching. 

```

user@instance:~/refinedev/store/node_modules/@refinedev/core$ pnpm build --scope @refinedev/core --scope core

> @refinedev/core@4.53.0 build /home/ubuntu/refinedev/store/node_modules/@refinedev/core
> tsup && node ../shared/generate-declarations.js "--scope" "@refinedev/core" "--scope" "core"

No input files, try "tsup <your-file>" instead
 ELIFECYCLE  Command failed with exit code 1.

```

it's constantly giving me this error, and I do not have this shared folder, neither the generate-declarations.js file thing. I didn't find in the doc's where they are, or how to generate them.

The issue is that I simply need to edit the banner you have on top.

### Describe the thing to improve

Find an EASY way to edit the refine banner on top. 
 

### Describe the solution (optional)

Easy way to edit some simple html/css, just like in the good ol' PHP scriptkiddie days

**Comment by BatuhanW** [comment]
Hey @spacewalkingninja I'm not sure why you are trying to build refine inside node modules. If you want to remove the banned, you can search for `<GitHubBanner />` and remove it.

https://refine.dev/docs/guides-concepts/faq/#how-can-i-remove-github-banner
