### ISSUE TITLE
[BUG] Module '"@refinedev/core"' has no exported member 'Link'

### ISSUE THREAD

**Issue by nalakawula** [refinedev/refine#6407]
### Describe the bug

```
src/components/header/index.tsx:3:25 - error TS2305: Module '"@refinedev/core"' has no exported member 'Link'.

3 import { useNavigation, Link } from "@refinedev/core";
                          ~~~~


Found 1 error in src/components/header/index.tsx:3
```

### Steps To Reproduce

Try example invoicer app
```
npm create refine-app@latest -- --example invoicer
```

run build command
```
npm run build
```

### Expected behavior

the invoicer app should sucessfuly builded

### Packages

    "@refinedev/antd": "^5.43.1",
    "@refinedev/cli": "^2.16.38",
    "@refinedev/core": "^4.54.1",
    "@refinedev/devtools": "^1.2.8",
    "@refinedev/react-router-v6": "^4.6.0",
    "@refinedev/strapi-v4": "^6.0.8",
    "antd": "^5.17.0",
    "antd-style": "^3.6.1",
    "axios": "^1.6.2",
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "react-input-mask": "^2.0.4",
    "react-router-dom": "^6.8.1"

### Additional Context

The latest changes on the invoicer app that i try is https://github.com/refinedev/refine/commit/ac31926c2e8701ccaf8d6111ade924df35133aab

**Comment by BatuhanW** [comment]
We've merged the release PR, it should be available soon.
