### ISSUE TITLE
[DOC] Editing modules

### ISSUE THREAD

**Issue by spacewalkingninja** [refinedev/refine#6409]
### Documentation issue

#6380 
@aliemir 
> Hey @spacewalkingninja, I'm not sure what are you trying to achieve here, Refine has 35 packages, 200+ examples and a documentation in the repo. It is unclear that which template you're referencing or why are you editing the `index.mjs`.
> 
> Check out the [Quick Start Guide](https://refine.dev/docs/getting-started/quickstart/) and [Development Guide](https://refine.dev/docs/guides-concepts/development/) to get started with Refine.
> 
> Feel free to re-open when you can define the issues you're facing and the goals you're trying to achieve more clearly.

It is very simple: I am building a medusajs store based on the medusa V1 api, using the SWAG template, and I am trying to edit the SWAG store template which you have developed to work +/- OK on medusajs V1 api.

https://github.com/refinedev/refine/tree/master/examples/store

I have had to mod some files so far, and all of them are in the tsx files, which is easy to develop for, But the issue I am encountering is that there are some things that aren't so straightforward to edit:

I am in refine/examples/store/pages/_app.tsx 

and there is this originally
```

 ...
 return (
    <ManagedUIContext>
      <GitHubBanner />
      <main className={clsx(inter.variable, "font-sans", "bg-gray-lightest")}>
        <Refine
...

```

this github banner is baked in a core module somewhere, which I must edit (No, I DO NOT WANT to create my custom files for this, I like the banner as is, I just want to edit the text and link that appears, so I had to edit the mjs files and created custom banners there).

I am trying to reuse it for "Free shipping on orders above N euros" and I am making it multilanguage because poor medusajs doesnt support multilang in the traditional way so I have to code it from scratch. 

Here is what I am doing right now:

```

    // Get user's browser language if no relevant cookie is found
    const userLang = cookieLang || navigator.language;
    if (userLang.startsWith("pt")) {
      setGitHubBannerComponent(<GitHubBannerPt />);
    } else if (userLang.startsWith("es")) {
      setGitHubBannerComponent(<GitHubBannerEs />);
    } else {
      setGitHubBannerComponent(<GitHubBanner />);
    }

    //... some irrelevant code

  }, []);

  const renderComponent = () => {
    if (Component.noLayout) {
      return <Component {...pageProps} />;
    }

    return (
      <Layout>
        <Component {...pageProps} />
      </Layout>
    );
  };

  return (
    <ManagedUIContext>
      {GitHubBannerComponent} {/* Display the correct GitHubBanner based on language */}
      <main className={clsx(inter.variable, "font-sans", "bg-gray-lightest")}>

```

basically what I am asking for is to make it easier to edit, I don't want to unminify mjs files to edit some simple html/css - makes sense? 
If you have ever modded or written PHP/HTML/CSS you know how easy it is. 
This is something I code on top of my head, that reads https://url.com/index.php?Theme=Dark || Pink || Unset to show how easy something like this MUST be:
```

<html>
<head>
<?php 

if ($_GET['Theme']=="Dark") {
?>
<style>
html {
background:black
}
</style>
<title>DarkVersion</title>
<?php 
}
elseif ($_GET['Theme']=="Pink")
{ ?>

<style>
html {
background:pink
}
</style>
<title>PinkVersion</title>

<?php
}
else
{
?>
<style>
html {
background:#ccc
}
</style>
<title>Default : LightVersion</title>

<?php
}
?>
</head>
<body>
<h1> content goes here </h1>
</body>
</html>
```

### Describe the thing to improve

Since I am just trying to edit a simple banner, **I mustn't be made to jump through so much hoops, my head feels like sonic** writing things for Refine, Medusa, React. 
And yes, I know there are lots of files for organisation purposes but I am not organized and I don't care about organization, I care about writing and seeing code working.

**Comment by aliemir** [comment]
Hey @spacewalkingninja thank you for the explanation. Instead of using the `index.mjs` and trying to un-minify it, you can copy-paste the component from our repo and easily customize it for your needs.

Check out here https://github.com/refinedev/refine/tree/master/packages/core/src/components/gh-banner

You can just copy the `index.tsx` and `styles.ts` to somewhere in your project and import the `GithubBanner` from there instead of `@refinedev/core`. You can also rename it as you wish. 🚀 

Our `<GithubBanner />` component is designed to be used in examples and new projects for promotional purposes. Since this is just a promotional component for us, we haven't needed any props to customize it but for your case its much better to copy it to your project and customize 🎉 🎉

**Comment by spacewalkingninja** [comment]
Thanks, big help!
It's simple stuff like this being made hard that has held me back from these modern solutions. 
Thx again @aliemir
