### ISSUE TITLE
[FEAT] DataProvider should be able to compute the API route from resource

### ISSUE THREAD

**Issue by pcfreak30** [refinedev/refine#6419]
### Is your feature request related to a problem? Please describe.

Ive been digging into the resource system and one thing I have noticed is that providers like simple-rest take the resource id as-is for building a url. However we have 

```
export interface IResourceComponents {
  list?: ResourceRouteComposition;
  create?: ResourceRouteComposition;
  clone?: ResourceRouteComposition;
  edit?: ResourceRouteComposition;
  show?: ResourceRouteComposition;
}
```

It would make a lot more sense if allow the data provider to do so, so that we can better organize the API paths.

I understand that `IResourceComponents` is intended for the client, so I think it can be extended or new types made that target the servers path.

### Describe the thing to improve

Have data providers receive or be able to compute the API route path for a resource for calling an API, based off `IResourceComponents` or similar.

**Comment by BatuhanW** [comment]
Hey @pcfreak30 `IResourceComponents` is belongs to deprecated feature. If I understand correctly, you can add additional meta to your resource definitions, it will be passed to your data provider and you can utilize there.

**Comment by pcfreak30** [comment]
Well part of it was the idea that the router helpers, or a version of them, can be used to help compute vs needing to attach arbitrary meta and DIY.

What deprecated feature are you referring to?

@BatuhanW
