### ISSUE TITLE
[FEAT] Provide support for null values from useList / useTable hook

### ISSUE THREAD

**Issue by noradroid** [refinedev/refine#6423]
### Is your feature request related to a problem? Please describe.

Golang backend APIs return null when service methods return nil. Is it possible for useList / useTable hooks to support handling of null value when an array is expected? For example, if null value is returned, return a empty array instead to prevent this error from appearing:
![image](https://github.com/user-attachments/assets/3a6c5df6-8a3f-4657-9f87-12af48d18cbb)

### Describe the thing to improve

Handling of null return value when fetching lists to prevent .length call on null

**Comment by BatuhanW** [comment]
Hey @noradroid you can handle it in your data provider. Your data provider's `getList` method is expecting an array. You can swizzle and change it according to your needs. https://refine.dev/docs/data/packages/simple-rest/#customizing-the-data-provider-
