### ISSUE TITLE
[FEAT] Add NocoDB support

### ISSUE THREAD

**Issue by SkyfallWasTaken** [refinedev/refine#6434]
### Is your feature request related to a problem? Please describe.

Refine looks awesome, but I'd love to be able to connect it with NocoDB (open-source Airtable clone).

### Describe alternatives you've considered

Migrating to Airtable, but we're already fairly invested into NocoDB.

### Describe the thing to improve

Adding NocoDB as a data source.

**Comment by BatuhanW** [comment]
Hey @SkyfallWasTaken thanks for the issue. Core team isn't adding new data provider integrations but we are open to contributions from the community. 

You can check our tutorial on creating a data provider https://refine.dev/tutorial/essentials/data-fetching/intro/#creating-a-data-provider

Basically, you can swizzle the simple-rest data provider and modify it according to your needs. https://refine.dev/docs/data/packages/simple-rest/#customizing-the-data-provider-

**Comment by BatuhanW** [comment]
Hey @erkanercan assigned issue to you. You can duplicate one of the data providers as a starting point and replace values in package.json, refine.config.js. The most recently updated one is graphql data provider.

**Comment by BatuhanW** [comment]
We don't accept new data/auth provider integrations at the moment to this repository.

If you create an integration on your own repository and publish as a separate npm package, feel free to create a PR here. We'd be more than happy to feature integrations in our documentation and website.
