### ISSUE TITLE
[FEAT] Simplified, Automated and Consistent Forms

### ISSUE THREAD

**Issue by aress31** [refinedev/refine#6444]
### Is your feature request related to a problem? Please describe.

Currently, the Show, Edit, and Create pages/forms need to be implemented manually, which can become cumbersome when dealing with a large number of tables - even if using common layout pages.

### Describe the thing to improve

It would be great to infer column types from data fetched in databases like Supabase and implement a global renderer to maintain a consistent user experience with minimal code.

For example, a foreign key relationship could be represented as a select or autocomplete field, while an int8 type would correspond to a number input, and so forth.

**Comment by BatuhanW** [comment]
Hey @aress31 thanks for the issue. I guess we already have such feature. It's called inferencer. You can check it out here: https://refine.dev/docs/ui-integrations/material-ui/components/inferencer/

**Comment by BatuhanW** [comment]
Closing the issue now. Feel free to re-open it if you see fit.
