### ISSUE TITLE
[DOC] Incorrect naming in sample code 

### ISSUE THREAD

**Issue by 0legmax** [refinedev/refine#6446]
# Describe the issue

Looks like there should be some problem with the name `handleSubmitPostCreate`
https://github.com/refinedev/refine/blob/20a09049ce55720a8c8ff6a495d4a4ae88c79e02/documentation/docs/guides-concepts/forms/index.md?plain=1#L878

**Comment by BatuhanW** [comment]
Hey @0legmax thanks for the issue, feel free to send a PR.
