### ISSUE TITLE
[BUG] Resource Filters Not Applying Despite syncWithLocation: true Setting

### ISSUE THREAD

**Issue by aress31** [refinedev/refine#6455]
### Describe the bug

Here’s how I define my resources:

```js
const createResource = (name, options = {}) => {
  const { parent: parentResource } = options.meta || {};

  const basePath = parentResource
    ? `/:tenantId/${parentResource}/:${singular(parentResource)}Id/${name}`
    : `/:tenantId/${name}`;

  return {
    name,
    list: basePath,
    options,
  };
};

const createProjectFilter = (projectId = ":projectId") => ({
  field: "projects.id",
  operator: "eq",
  value: projectId,
});

const resources = [
  createResource("clients"),
  createResource("projects", { meta: { select: "*, clients!inner(*)" } }),
  createResource("foo", {
    filters: [createProjectFilter()],
    meta: {
      parent: "projects",
      select: "*, projects!inner(*)",
      filters: [createProjectFilter()],
    },
  }),
  createResource("bar", {
    filters: [createProjectFilter()],
    meta: {
      parent: "projects",
      select: "*, projects!inner(*)",
    },
  }),
  createResource("foobar", {
    filters: [createProjectFilter()],
    meta: {
      parent: "projects",
      select: "*, projects!inner(*)",
    },
  })
];
```

And here’s the Refine component setup:

```js
<Refine
      dataProvider={dataProvider(supabaseClient)}
      liveProvider={liveProvider(supabaseClient)}
      routerProvider={routerProvider}
      options={{
        liveMode: "auto",
        syncWithLocation: true,
        warnWhenUnsavedChanges: true,
      }}
      --- SNIP ---
      resources={resources}
    >
      --- SNIP ---
    </Refine>
```

The issue I’m encountering is that when I use useList or useDataGrid, the filters defined in resources don’t seem to apply automatically. Instead, these functions retrieve the entire table data unless I explicitly set filters in the function call.

I've searched the documentation extensively, but haven’t found a solution. I want to keep all filtering logic centralized within the resources configuration, as it's specific to each resource.

### Steps To Reproduce

See above.

### Expected behavior

The filters should be detected and applied when synWithLocation is turned on.

### Packages

```js
  "dependencies": {
    "@emotion/react": "^11.13.3",
    "@emotion/styled": "^11.13.0",
    "@mui/icons-material": "^6.1.6",
    "@mui/lab": "^6.0.0-beta.14",
    "@mui/material": "^6.1.6",
    "@mui/x-charts": "^7.22.1",
    "@mui/x-data-grid": "^7.22.1",
    "@refinedev/core": "^4.55.0",
    "@refinedev/mui": "^5.21.0",
    "@refinedev/react-router-v6": "^4.6.0",
    "@refinedev/supabase": "^5.9.4",
    "@rjsf/core": "^5.22.3",
    "@rjsf/mui": "^5.22.3",
    "@rjsf/validator-ajv8": "^5.22.3",
    "@toolpad/core": "^0.8.1",
    "@uiw/react-md-editor": "^4.0.4",
    "@vitejs/plugin-react": "^4.3.3",
    "angular-expressions": "^1.4.0",
    "docxtemplater": "^3.51.2",
    "firebase": "^11.0.1",
    "firebase-admin": "^12.7.0",
    "mermaid": "^11.4.0",
    "pizzip": "^3.1.7",
    "pluralize": "^8.0.0",
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "react-router-dom": "^6.27.0",
    "uuid": "^11.0.2",
    "vite": "^5.4.10",
    "web-vitals": "^4.2.4"
  },
```

**Comment by aliemir** [comment]
Hey @aress31, `syncWithLocation` syncs the filter, sorter and pagination state with URL query params. As far as I understand from the snippets you've shared, you're trying to pass filters through `meta` fields of the resource definitions, currently this is not supported.

This can be a useful feature, for now as a workaround you can use `useResource` hook to get the inferred resource and use its meta to provide initial filters to the hook.

Our core team has a lot on their plate right now, so we might not be able to prioritize this implementation immediately. However, we’d love to see contributions from the community. You can create a new issue or convert this one into a feature request to start the conversation.

**Comment by aress31** [comment]
Additionally, it would be helpful if route or query parameters, such as `:projectId` were automatically detected and could be overridden, for example, with values like `meta.projectId` on the `useList` directly.

**Comment by BatuhanW** [comment]
> Hey @aress31, `syncWithLocation` syncs the filter, sorter and pagination state with URL query params. As far as I understand from the snippets you've shared, you're trying to pass filters through `meta` fields of the resource definitions, currently this is not supported.
> 
> This can be a useful feature, for now as a workaround you can use `useResource` hook to get the inferred resource and use its meta to provide initial filters to the hook.
> 
> Our core team has a lot on their plate right now, so we might not be able to prioritize this implementation immediately. However, we’d love to see contributions from the community. You can create a new issue or convert this one into a feature request to start the conversation.

@aress31 this is not a bug, would be a nice feature as @aliemir said. We are creating this one, since it's not a bug, we'll create a new FEAT issue.
