### ISSUE TITLE
[BUG] Resources + app router doesn't check access control?

### ISSUE THREAD

**Issue by davidgoli** [refinedev/refine#6486]
### Describe the bug

I might be confused or missing something, but AFAICT there's no code that would make this work.

I've got a Refine app (4.47.1) using Next.js app router. My Refine context:

```ts
        <Refine
          routerProvider={routerProvider}
          authProvider={auth0AuthProvider}
          accessControlProvider={{
            can: async (options) => {
              const { menuItems } = await menuItemsApi.listMenuItems()
              const can = !!menuItems.find(
                (item) => item.name === options.resource,
              )
              return { can }
            },
          }}
          resources={[
            {
              name: 'conversations',
              list: '/conversations',
              show: '/conversations/show/:id',
            },
            {
              name: 'messages',
            },
            {
              name: 'users',
              list: '/users',
              show: '/users/show/:id',
            },
            {
              name: 'moderation_items',
              list: '/moderation-items',
              show: '/moderation-items/show/:id',
            },
          ]
      >
          {props.children}
          <RefineKbar />
      </Refine>
```

1. I have a `Menu` component, pretty much identical to the template's, that uses `useMenu` to build the left-hand menu. I expect for the menu items to be a list of resources filtered by accessControlProvider's `can` method. Instead, I see all resources without filtering.
2. When I log in as a restricted-access user, I expect for my initial route, set by `<NavigateToResource />`, to be the first resource I have access to. Instead, I am redirected to a route to which I do _not_ have access, because it's using the same `useResource()` list that is not filtered by accessControl.
3. An explicit `<CanAccess>` wrapper around pages _does_ work correctly.

Digging through the code, I do not see any mechanism or check for `accessControlProvider.can` to filter the resources. I'm not sure how this is supposed to work - short of me reimplementing everything built on top of `useResource()`?

Bug or documentation defect - I'm not sure!

### Steps To Reproduce

n/a

### Expected behavior

see above

### Packages

- @refinedev/core 4.47.1
- @refinedev/nextjs-router 6.0.0

**Comment by davidgoli** [comment]
> Hello @davidgoli,
> 
> What does `listMenuItems` return?

It performs an API call to our BE which returns a list of resources the user has access to, like:

```
[{ name: 'conversations' }, { name: 'moderation_items' }]
```

**Comment by davidgoli** [comment]
What's odd is, with a log or a breakpoint, I can see that `can` is being called several times on initial render - but it has no apparent effect on the initial page route or the sidebar menu items

**Comment by BatuhanW** [comment]
Hey @davidgoli an explicit `<AccessControl />` component is required to trigger access control. It won't run every resource by default. You need to wrap your pages/components with it.

**Comment by alicanerdurmaz** [comment]
Hello @davidgoli, Thanks for the detailed explanation.


### 1. Scenario
I couldn't reproduce the issue. If you can provide us with a reproducible example we will be happy to debug it.

My example:
```tsx
import { Refine, useMenu, CanAccess, Link } from "@refinedev/core";
import { useNotificationProvider, ThemedLayoutV2 } from "@refinedev/antd";

import dataProvider from "@refinedev/simple-rest";
import routerProvider, { NavigateToResource } from "@refinedev/react-router-v6";
import { BrowserRouter, Routes, Route, Outlet } from "react-router-dom";
import { App as AntdApp } from "antd";

import "@refinedev/antd/dist/reset.css";

const API_URL = "https://api.fake-rest.refine.dev";

const getListMenuItems = async () => {
  // sleep for 1 second to simulate a real-world scenario
  await new Promise((resolve) => setTimeout(resolve, 1000));

  return [
    { name: "home" },
    { name: "posts" },
    // { name: "categories" }
  ];
};

const App: React.FC = () => {
  return (
    <BrowserRouter>
      <AntdApp>
        <Refine
          dataProvider={dataProvider(API_URL)}
          routerProvider={routerProvider}
          accessControlProvider={{
            can: async (options) => {
              const menuItems = await getListMenuItems();

              const can = !!menuItems.find(
                (item) => item.name === options.resource,
              );
              return { can };
            },
          }}
          resources={[
            {
              name: "home",
              list: "/",
            },
            {
              name: "posts",
              list: "/posts",
            },
            {
              name: "categories",
              list: "/categories",
            },
          ]}
          notificationProvider={useNotificationProvider}
          options={{
            syncWithLocation: true,
            warnWhenUnsavedChanges: true,
          }}
        >
          <Routes>
            <Route
              element={
                <ThemedLayoutV2
                  Sider={() => {
                    const { menuItems } = useMenu();

                    return (
                      <div
                        style={{
                          padding: "16px",
                          minWidth: "200px",
                        }}
                      >
                        {menuItems.map((item) => {
                          if (!item.route) return null;

                          return (
                            <CanAccess
                              key={item.name}
                              resource={item.name}
                              action="list"
                            >
                              <Link to={item.route}>
                                <h2 key={item.name}>{item.label}</h2>
                              </Link>
                            </CanAccess>
                          );
                        })}
                      </div>
                    );
                  }}
                >
                  <Outlet />
                </ThemedLayoutV2>
              }
            >
              <Route path="/" element={<h1>Home</h1>} />
              <Route path="/posts" element={<h1>Posts</h1>} />
              <Route path="/categories" element={<h1>Categories</h1>} />
            </Route>
          </Routes>
        </Refine>
      </AntdApp>
    </BrowserRouter>
  );
};

export default App;
```

----

### 2. Scenario

Unfortunately `<NavigateToResource /> doesn’t work with `useCan`. I’ll talk to the core team about adding this feature. Thanks!

**Comment by BatuhanW** [comment]
@davidgoli You can check our Ant Design ThemedLayoutV2 implementation for a similar example. https://github.com/refinedev/refine/blob/master/packages/antd/src/components/themedLayoutV2/sider/index.tsx We are using CanAccess component here to render menu items. Depends on your code, you can also use `useCan` hook, see docs [here](https://refine.dev/docs/authorization/hooks/use-can/)

A suggestion performance wise would be to fetch available menuItems once and use cached version, since for every resource, `can` method of Access Control Provider will be called.

Please let me know if that answers your question.

**Comment by davidgoli** [comment]
@BatuhanW I am not finding much use for the `accessControlProvider` pattern as currently designed, because I'm not in control of the caching, and adding an additional cache layer as you recommend doesn't make much sense. I'd much rather just use React Query, so I probably will. I can trivially implement `useCan` and `CanAccess` on top of RQ. It sounds like `accessControlProvider` doesn't actually give much, because it doesn't work out of the box to filter `useMenu` or many other hooks that rely on `useResource`. The example @alicanerdurmaz gives above is precisely what I was hoping to avoid - _manually_ filtering the resources wherever I need to read them. Its support seems very partial and indeed it isn't compatible with many otherwise recommended components like `NavigateToResource`. So, I will be forgoing it for now. Looking forward to deeper support in the future. Thanks for answering my questions though!

**Comment by alicanerdurmaz** [comment]
Directly adding the access control feature to `<NavigateToResource />` is not ideal, as we aim to keep Refine as atomic as possible and provide users complete freedom without imposing any opinions. Instead, users can wrap `<NavigateToResource />` with `<CanAccess />` to handle access control, as shown below: 

```tsx
import { NavigateToResource } from "@refinedev/react-router-v6";
import { Navigate } from "react-router-dom";

<CanAccess resource="posts" action="list" fallback={<Navigate to="/" />}>
  <NavigateToResource resource="posts" />
</CanAccess>
```

By offering atomic components and hooks like `useCan` and `<CanAccess />`, we allow users to manage access control in a way that best suits their needs.

**Comment by davidgoli** [comment]
@alicanerdurmaz the use case I have in mind is precisely the one where we do _not_ have a specific resource, but instead need to navigate the user to the appropriate landing page given the access control they have. I'm not blocked by this as I've implemented it on my own. I do not think it is essential that `<NavigateToResource>` must use access control, but the access control support for basic use cases like mine IMO is incomplete, and Refine could use a story on what to do - not that component perhaps, but which? what _is_ the recommended technique for handling such common scenarios?
