### ISSUE TITLE
[BUG] Redirect Doesn't Work with `useForm` following the docs

### ISSUE THREAD

**Issue by daninus14** [refinedev/refine#6492]
### Describe the bug

I get this error when trying to add redirect on a `useForm`

```
Object literal may only specify known properties, and 'redirect' does not exist in type 'UseFormProps<BaseRecord, HttpError, FieldValues, {}, BaseRecord, BaseRecord, HttpError>'.ts(2353)
```

### Steps To Reproduce

```tsx
import { useForm } from "@refinedev/react-hook-form";
```

```tsx
  const {
    refineCore: { onFinish },
    register,
    handleSubmit,
    formState: { errors },
  } = useForm({redirect: "show",});
```

### Expected behavior

For it to work per the docs https://refine.dev/tutorial/routing/redirects/react-router/#showing-the-record-after-update

### Packages

- @refinedev/react-hook-form

### Additional Context

Was trying to follow the tutorial here https://refine.dev/tutorial/routing/redirects/react-router/#showing-the-record-after-update

**Comment by alicanerdurmaz** [comment]
Hello @daninus14, 

In the tutorial, we use `useForm` from "**@refinedev/core**", but if you want to use it from "**@refinedev/react-hook-form**", the API might be a bit different.

To make it work, you need to pass the [`redirect`](https://refine.dev/docs/packages/react-hook-form/use-form/#redirect) prop like this:

```tsx
import { useForm } from "@refinedev/react-hook-form";

useForm({
  refineCoreProps: {
    redirect: false,
  },
});
```

**Comment by daninus14** [comment]
Thanks so much for the explanation! 😄
