### ISSUE TITLE
[BUG] AuthPage Issue with Async Login

### ISSUE THREAD

**Issue by aress31** [refinedev/refine#6504]
### Describe the bug

I am facing an issue where the google provider don't wait for me confirming the account and accepting to the term before jumping to the next lines of codes despite stating await with Supabase.

### Steps To Reproduce

```js
const authProvider = {
  login: async ({ email, password, providerName }) => {
    try {
      const { data, error } = providerName
        ? await supabaseClient.auth.signInWithOAuth({
            provider: providerName,
          })
        : await supabaseClient.auth.signInWithPassword({
            email,
            password,
          });

      if (error) throw error;

      console.log({ data, error });

      if (data?.user)
        return {
          success: true,
          redirectTo: "/dashboard",
        };
    } catch (error) {
      return {
        success: false,
        error,
      };
    }
  },
  --- SNIP ---
```

The `console.log` and `return` get triggered straightaway regardless of the `await`.

### Expected behavior

Should pause the code execution until `supabaseClient.auth.signInWithOAuth` gets executed and return something.

### Packages

Latest.

**Comment by BatuhanW** [comment]
Hey @aress31 please use our AI chatbot in documentation for your questions & issues and try to create issues only if you are sure it's about Refine source code itself.
