### ISSUE TITLE
[FEAT] ThemedSiderV2 Persist Collapsed State

### ISSUE THREAD

**Issue by aress31** [refinedev/refine#6508]
### Is your feature request related to a problem? Please describe.

Would be nice to persist out of the box the collapsed state, or add an option to do so, maybe a "peristCollapsed" boolean. This would avoid having to write extra code for this important UX feature.

### Describe the thing to improve

See above.

**Comment by BatuhanW** [comment]
@aress31 thanks for the issue. We've discussed this one and decided to accept `onSiderCollapsed` function to [ThemedLayoutV2](https://github.com/refinedev/refine/blob/master/packages/antd/src/components/themedLayoutV2/index.tsx) component.

Then `onSiderCollapsed` will be passed to [ThemedLayoutContextProvider](https://github.com/refinedev/refine/blob/master/packages/antd/src/contexts/themedLayoutContext/index.tsx)

Here, we should replace existing `setSiderCollapsed` with a wrapper, where we call setSiderCollapsed state action and also `onSiderCollapsed` coming from user.

Here is a pseudo implementation:
![Screenshot 2024-11-20 at 14 16 42](https://github.com/user-attachments/assets/0d7d1d4a-649d-4a17-9656-5ee97e70651c)

This will allow users to persist their collapsed state into localstorage in `onSiderCollapsed` method. And then users can read this from localStorage and pass initial value `initialSiderCollapsed` from here.

We need to do these changes in ThemedLayoutV2 component for
- Ant Design
- Material UI
- Mantine
- Chakra UI

They all have almost exact same code, so it should be straightforward to implement.

We are open to contributions for this one.

**Comment by wannabecsguy2** [comment]
Hey @BatuhanW, can I work on this?

**Comment by OmkarBansod02** [comment]
Hey @BatuhanW, I am up for this.

**Comment by BatuhanW** [comment]
@wannabecsguy2 Assigning issue to you since you were first to ask 🚀 

@OmkarBansod02 If we don't hear back from @wannabecsguy2 you can take this next. We also have other issues that you may want to work on, you can check up for grabs labelled issues ❤️

**Comment by OmkarBansod02** [comment]
hey @BatuhanW it's been a while. can you assign me this issue so i can make PR .

**Comment by OmkarBansod02** [comment]
hey @BatuhanW  I'm getting a TypeScript error: Property `onSiderCollapsed` does not exist on type `RefineThemedLayoutV2Props`. while implementing it in [ThemedLayoutV2](https://github.com/refinedev/refine/blob/master/packages/antd/src/components/themedLayoutV2/index.tsx)  Even though I've declared `onSiderCollapsed?: (collapsed: boolean) => void;` in the `RefineThemedLayoutV2Props` interface, the error still persists.

**Comment by BatuhanW** [comment]
@OmkarBansod02 assigned issue to you. It seems like it should work, you can restart TS server.

**Comment by OmkarBansod02** [comment]
@BatuhanW, Still getting same error even after restarting TS server. i am adding code snippets below kindly check am i on right path .  

1. File : `E:\Refinedev\refine\packages\ui-types\src\types\layout.tsx `

![Screenshot 2024-11-26 184645](https://github.com/user-attachments/assets/35143fc6-c667-40ed-87c9-af66374d9304)

2. File: `E:\Refinedev\refine\packages\mui\src\components\themedLayoutV2\index.tsx ` (in which getting Error )

![Screenshot 2024-11-26 184722](https://github.com/user-attachments/assets/a500f138-57fa-4fa2-92dc-fc819b1018be)

**Comment by BatuhanW** [comment]
@OmkarBansod02 types are separate package. So you need to build it for other packages to see its types.

**Comment by OmkarBansod02** [comment]
Thanks for help @BatuhanW , I have made a PR kindly review it and let me know for any improvement.
