### ISSUE TITLE
[FEAT] Introduce Variants for ThemedSidebar

### ISSUE THREAD

**Issue by aress31** [refinedev/refine#6516]
### Is your feature request related to a problem? Please describe.

It would be great to have a variants prop for the sidebar, providing out-of-the-box styles inspired by popular platforms like Gmail, Outlook, or other well-known websites.

This feature would make a nice addition!

### Describe the thing to improve

See above.

**Comment by zhanwen22** [comment]
Hi, I would like to work on this if possible! Thank you

**Comment by alicanerdurmaz** [comment]
Hello @aress31, 

Currently, we are not planning to make out-of-the-box UI components in the core packages, and Refine does not have an opinion on the UI. The sidebar can be implemented with any UI library using `useMenu`.
