### ISSUE TITLE
[BUG] wrong return type of `useInfiniteList`

### ISSUE THREAD

**Issue by hongfanmeng** [refinedev/refine#6517]
### Describe the bug

The type of `data` in the following code is `GetListResponse<BaseRecord>`, but actually it should not be
```
import { useInfiniteList } from "@refinedev/core";
const { data } = useInfiniteList();`
```

### Steps To Reproduce

1. use `useInfiniteList`
2. the typing is wrong

### Expected behavior

The return data of `useInfiniteList` should contains `pageParams` and `pages`, not `data` and `total`

### Packages

- @refinedev/core

**Comment by BatuhanW** [comment]
@hongfanmeng can you let us know where did you see this issue? I don't see data and total myself.

**Comment by hongfanmeng** [comment]
I finally found out that this was because I installed "@tanstack/react-query": "^5.61.3", there was no problem when I just installed refine itself
