### ISSUE TITLE
[FEAT] React Router v7 Support

### ISSUE THREAD

**Issue by aress31** [refinedev/refine#6520]
### Is your feature request related to a problem? Please describe.

Now that the v7 of react-router is stable and the default, adding support for it is needed, as upgrading to this version of react-router has broken my code - due to various breaking changes introduced in the v7. 

### Describe the thing to improve

See above.

**Comment by BatuhanW** [comment]
Hey @aress31 thanks for the issue, we'll check this in the future.

**Comment by sohaibgv** [comment]
+1
