### ISSUE TITLE
[FEAT] Create an Account Component

### ISSUE THREAD

**Issue by aress31** [refinedev/refine#6533]
### Is your feature request related to a problem? Please describe.

I would love to see an `Account` component similar to https://mui.com/toolpad/core/react-account/ in order to further extend the session management features of Refine and be able to display this component in various places in an application (most common ones being the sidebar footer and header right side).

### Describe the thing to improve

See above.

**Comment by BatuhanW** [comment]
We don't have such plan, but you can publish it as a separate open-source package.
