### ISSUE TITLE
[BUG] Docker COPY failed: stat app/refine/.next/standalone: file does not exist

### ISSUE THREAD

**Issue by syl20lego** [refinedev/refine#6540]
### Describe the bug

When using out of the box example, it doesn't work with the provided Dockerfile. It seems that the docker configuration is expecting next.js to product a production build in "standalone" mode.

We need to manually add output: 'standalone' to the `next.config.mjs`
```
/** @type {import('next').NextConfig} */
const nextConfig = {
  transpilePackages: ['@refinedev/antd'],
  output: 'standalone'
}

export default nextConfig
```

This is maybe a documentation issue or maybe an issue with the example code generated.

### Steps To Reproduce

✔ Choose a project template · refine-nextjs
✔ What would you like to name your project?: · refine-test
✔ Choose your backend service to connect: · data-provider-custom-json-rest
✔ Do you want to use a UI Framework?: · antd
✔ Do you want to add example pages?: · antd-example
✔ Do you need any Authentication logic?: · auth-provider-custom
✔ Choose a package manager: · yarn

cd refine-test

docker build -t refine-test -f ./Dockerfile .

...

Step 14/20 : COPY --from=builder --chown=refine:nodejs /app/refine/.next/standalone ./
COPY failed: stat app/refine/.next/standalone: file does not exist

### Expected behavior

Add   output: 'standalone' to the `next.config.mjs` and rerun 

docker build -t refine-test -f ./Dockerfile .
...
Step 14/20 : COPY --from=builder --chown=refine:nodejs /app/refine/.next/standalone ./
 ---> f959fa4b1b49
Step 15/20 : COPY --from=builder --chown=refine:nodejs /app/refine/.next/static ./.next/static
 ---> 4130fc3ced4d
Step 16/20 : USER refine
 ---> Running in 90c2a7cceb19
Removing intermediate container 90c2a7cceb19
....
Successfully built c7ca2526790c
Successfully tagged refine-test:latest

### Packages

"@ant-design/icons": "^5.0.1",
"@ant-design/nextjs-registry": "^1.0.0",
"@refinedev/antd": "^5.37.4",
"@refinedev/cli": "^2.16.21",
"@refinedev/core": "^4.47.1",
"@refinedev/devtools": "^1.1.32",
"@refinedev/kbar": "^1.3.6",
"@refinedev/nextjs-router": "^6.0.0",
"@refinedev/simple-rest": "^5.0.1",
"antd": "^5.0.5",
"js-cookie": "^3.0.5",
"next": "^14.1.0",
"react": "^18.0.0",
"react-dom": "^18.0.0"

### Additional Context

I would also suggest to include a .dockerignore file that exclude the `.git` and `node_modules` directories this would reduce the docker context transfer size and time.

Also the Dockerfile contains a public folder but the example don't generate one, so we probably need to remove it as well

COPY --from=builder /app/refine/public ./public

**Comment by BatuhanW** [comment]
Hey @syl20lego thanks for the issue. The template is fixed [here](https://github.com/pankod/superplate-core-plugins/pull/414).

We want to keep public because probably it will be used for real applications.
