### ISSUE TITLE
[DOC] Incorrect deleted line in authorization data provider integration

### ISSUE THREAD

**Issue by smichae** [refinedev/refine#6542]
### Documentation issue

https://github.com/refinedev/refine/blob/a94844e4400c56d542e5a2bfbba37047e122d3ec/documentation/tutorial/authentication/data-provider-integration/index.md?plain=1#L88

### Describe the thing to improve

The deleted line in getOne in the tutorial/authentication/data provider integration should reference fetch, not fetcher

**Comment by alicanerdurmaz** [comment]
Hello @smichae, thanks for the issue!

Do you wanna work on this?

**Comment by smichae** [comment]
@alicanerdurmaz I'd be happy to, may just take a few weeks until I have time, so I'll leave it out here if anyone else wants to take it, feel free - just wanted to make sure it was reported since I spotted it. Thanks!

**Comment by OM-HASE** [comment]
Hello @alicanerdurmaz, I am interested and happy to solve this issue.

**Comment by OM-HASE** [comment]
@alicanerdurmaz sir, I have summited the solution and send the pull request.

**Comment by OM-HASE** [comment]
@BatuhanW and @alicanerdurmaz sir, I have summited the solution and send the pull request. 
sorry @BatuhanW sir, I had close pull request where you told some changes and created new pull request. As I am new to the Open Source that why it happened. Next time it will not happened.

**Comment by alicanerdurmaz** [comment]
@OM-HASE no worries. Thanks for improving Refine! 🚀
