### ISSUE TITLE
[BUG] Unnecessary inclusion of disableRowSelectionOnClick in dataGridProps

### ISSUE THREAD

**Issue by aress31** [refinedev/refine#6561]
### Describe the bug

When using the `useDataGrid` hook, the `disableRowSelectionOnClick` property is included in `dataGridProps`, which seems to be an oversight as it has no relevance to the fetching, pagination, or sorting management of the DataGrid. As a result, I need to manually override it.

NOTE: The same applies to the `sx` prop. I don't see why it should be included within `dataGridProps`.

### Steps To Reproduce

```js
  const {
    dataGridProps,
    tableQuery: { isLoading, isFetching, isRefetching } = {},
  } = useDataGrid();
  console.log({
    dataGridProps,
    tableQuery: { isLoading, isFetching, isRefetching },
  });
```

![image](https://github.com/user-attachments/assets/cda0ccaf-9017-4532-8903-e92de3c68a69)

### Expected behavior

`dataGridProps` should include all the current properties, excluding `disableRowSelectionOnClick`.

### Packages

Everything to the latest version.

**Comment by alicanerdurmaz** [comment]
Hello @aress31 

These changes would cause a breaking change, so we can't make them until the next major release.

By the way, we removed `sx` with the [MUI 6 major](https://github.com/refinedev/refine/pull/6490) update.

**Comment by alicanerdurmaz** [comment]
@aress31 I understand, but `useDataGrid` is exported from "@refinedev/mui", and we are not using the clickable feature, so row click is disabled. If you want to use it, you can easily override it like this:
```tsx
<DataGrid {...dataGridProps} disableRowSelectionOnClick={false} />
```

**Comment by aress31** [comment]
@alicanerdurmaz that is exactly what I have done, but still IMHO this prop should not be there - hopefully we see it done in the next major release. :)
