### ISSUE TITLE
[BUG] useDataGrid Sorting and Filtering Seems Broken

### ISSUE THREAD

**Issue by aress31** [refinedev/refine#6563]
### Describe the bug

I switched from `useList` to `useDataGrid` to take advantage of automatic `pagination` and other features, but it seems like `sorting` and `filtering` are not functioning properly.

For example, when I try to sort by **"status"** (with `Supabase` as the data provider), the following request is sent:

```url
https://foo.supabase.co/rest/v1/projects?select=*%2Cclients%21inner%28name%29&offset=0&limit=25&order=status.asc
```

After this, the `DataGrid` refreshes with the overlay, but no sorting occurs. The response from `Supabase` isn't sorted, and the column header arrow doesn't indicate that sorting was applied. I suspect this might be a bug.

See:

https://github.com/user-attachments/assets/006f262d-2b0d-45ad-bf3a-309316f03625

### Steps To Reproduce

```js
  const {
    dataGridProps
  } = useDataGrid();

  <DataGridComponent
    columns={columns}
    {...dataGridProps}
  />
```

### Expected behavior

`useDataGrid` should support `server`-side filtering and sorting as expected.

### Packages

Latest packages.

**Comment by alicanerdurmaz** [comment]
Hello @aress31, I’m a bit confused. In the video, you mentioned ordering by `name`, but the request URL you shared seems to reference `status`.

Could you please clarify a few things?
- How have you implemented the columns?
- Is `name` or `status` defined in the foreign table?
- What does the request URL look like when it’s ordered by `name`?

**Comment by aress31** [comment]
@alicanerdurmaz `name` is not a foreign key, in the video, the foreign key is `Client` - I hope this helps.

**Comment by alicanerdurmaz** [comment]
@aress31 If it isn't a foreign table unfortunately I couldn't reproduce the issue. Can you give us a small reproducible example to debug this issue, please?

**Comment by aress31** [comment]
Sure, I will get troubleshot that more from my end and post more info when I have time.

**Comment by aress31** [comment]
@alicanerdurmaz, ajust a quick update to let you know that I’ve created the following sandbox:

- https://codesandbox.io/p/sandbox/jfm7r2

Everything seems to be working fine in this sandbox, but it uses the `REST API data provider`. Based on this, I suspect the issue with sorting might be specific to the `Supabase provider`, or perhaps its interaction with filters.

To proceed, I need access to a test/demo `Supabase` environment to finalise the sandbox and replicate the issue for further debugging. Let me know if you have any suggestions or resources!

**Comment by aress31** [comment]
@alicanerdurmaz, I've managed to replicate the issue, please see the following sandbox:

- https://codesandbox.io/p/sandbox/jfm7r2**

**Comment by BatuhanW** [comment]
@aress31 your reproduce is not understandable. You are providing hardcoded mocked data and expecting it to get sorted? Also you are using mode server.

**Comment by aress31** [comment]
@BatuhanW, this example is to replicate the behaviour with `Supabase`, I cannot use my own instance for the sandbox, therefore used hard-coded date which exactly replicate the problem faced.

**Comment by BatuhanW** [comment]
Please create a repository that can be downloaded and tested locally. You can create a different supabase or try to replicate using our supabase endpoints.

**Comment by aress31** [comment]
@BatuhanW, if you provide your `Supabase` endpoints and client configuration, I can modify the sandbox to demonstrate the issue with your data, confirming the presence of the bug. :)

**Comment by BatuhanW** [comment]
@aress31 you can check `data-provider-supabase` example. Looking forward to it.

**Comment by aress31** [comment]
@BatuhanW, I’ve identified the root cause of the issue. When conditionally loading the column definitions (e.g., assuming they are computed based on the rows), setting:

```js
columns={loadingData ? [] : muiColumns}
```

causes the sorting functionality to break.

Additionally, I noticed that the loading logic for `useDataGrid` is currently implemented as:

```js
loading: liveMode === "auto" ? isLoading : !isFetched,
```

However, I believe it would make more sense to use:

```js
const loadingData = isFetching || isLoading;
```

Lastly, as you can observe in the [CodeSandbox](https://codesandbox.io/p/sandbox/jfm7r2), when using a `GridToolbar` with `showQuickFilter: true`, the search field doesn’t work with server-side filtering. Could you kindly walk me through how to make this work? **This might also be worth including in the documentation.**

Looking forward to hearing your thoughts!
