### ISSUE TITLE
[FEAT] Support for Inline Filters in select for Aggregated Queries

### ISSUE THREAD

**Issue by aress31** [refinedev/refine#6569]
### Is your feature request related to a problem? Please describe.

Currently, I am making two separate requests to fetch datasets for charts, including total data and period data:

```js
 const {
    data: { data: totalData } = {},
    isFetching: isFetchingTotalData,
    isLoading: isLoadingTotalData,
  } = useList({
    resource,
    meta: { select: "count()" },
  });

  const {
    data: { data: periodData } = {},
    isFetching: isFetchingPeriodData,
    isLoading: isLoadingPeriodData,
  } = useList({
    resource,
    filters: [
      {
        field: "created_at",
        operator: "gte",
        value: filterDate,
      },
    ],
    meta: { select: "count()" },
  });
```

While reviewing the `Supabase` and `supabase-js` documentation, it seems like this could be simplified into a single request. For example:

```js
  const { data, isLoading } = useList({
    resource:,
    meta: {
      select: `totalData:count(*),periodData:count(*).filter("created_at", "gte", "2023-12-09")`,
    },
  });
```

However, this approach results in the following error:

```json
{
    "code": "PGRST100",
    "details": "unexpected '(' expecting letter, digit, \"-\", \"->>\", \"->\", \"::\", \".\", \")\", \",\" or end of input",
    "hint": null,
    "message": "\"failed to parse select parameter (totalData:count(*),periodData:count(*).filter(\"created_at\",\"gte\",\"2023-12-09\"))\" (line 1, column 16)"
}
```

It seems that inline filters are not supported in the `select` property of the `meta` object. And I can't use the `filters` prop for this use-case - otherwise that would only return the period data - this limitation prevents combining these requests.

Would it be possible to add support for `inline filters` within the `select` property to accommodate use cases like this?

NOTE: Another alternative would be to be able to issue a statement like:

```sql
SELECT
COUNT(*) AS total_count,
COUNT(CASE WHEN created_at > '2024-12-09' THEN 1 END) AS period_count
FROM "resource";
```

But again, this yield errors and don't seem to be supported.

### Describe the thing to improve

See above.

**Comment by BatuhanW** [comment]
@aress31 We've tried to send this select to supabase client directly and it doesn't work there too.

```
export const MyComponent = () => {
  useEffect(() => {
    supabaseClient
      .from("blog_posts")
      .select(
        `totalData:count(*),periodData:count(*).filter("created_at", "gte", "2023-12-09")`,
      )
      .then((res) => {
        console.log(res);
      });
  }, []);

  return null;
};
```

```
{
    "code": "PGRST100",
    "details": "unexpected '(' expecting letter, digit, \"-\", \"->>\", \"->\", \"::\", \".\", \")\", \",\" or end of input",
    "hint": null,
    "message": "\"failed to parse select parameter (totalData:count(*),periodData:count(*).filter(\"created_at\",\"gte\",\"2023-12-09\"))\" (line 1, column 16)"
}
```

You can re-open the issue once you prove what you are asking works for supabase.
