### ISSUE TITLE
 [FEAT] Enhance Sider Customizability

### ISSUE THREAD

**Issue by aress31** [refinedev/refine#6580]
### Is your feature request related to a problem? Please describe.

At this point, it is not possible to customise the Sider navigation items due to the items already being styled. See:

![image](https://github.com/user-attachments/assets/6d3aaa31-89b5-4a62-9ec9-8d7cfe25c186)

 This is the value of my render prop:

```js
 render={({ items, logout }) => {
        return (
          <Box>
            {items.map((item, index) => (
              <ListItemButton
                key={index}
                component="a"
                href={item.props.href}
                selected={item.props.selected}
                onClick={item.props.onClick}
                sx={{ borderRadius: 1 }}
              >
                {item}
              </ListItemButton>
            ))}
            {logout}
          </Box>
        );
      }}
```

But as you can see in `node_modules\@refinedev\mui\src\components\themedLayoutV2\sider\index.tsx` - because as mentioned they are already _heavily_ styled, achieving custom style is not possible. I suggest removing the default styling, in the case a custom render prop is being passed.

### Describe the thing to improve

See above.

**Comment by BatuhanW** [comment]
Hello @aress31 if you want to apply your own styles, you can easily swizzle the components and continue with your own styling.

See the relevant docs here: https://refine.dev/docs/ui-integrations/material-ui/components/themed-layout/#customizing-with-swizzle
