### ISSUE TITLE
[BUG] Using GraphQL as the data provider, Refines hooks like useUpdate, onMutationSuccess, onSuccess, etc return undefined data

### ISSUE THREAD

**Issue by maximdolphin** [refinedev/refine#6600]
### Describe the bug

I am trying to make a form submission with Refine, and for some reason anytime I try to receive the data from the mutation, it returns it as undefined but says the mutation was successful. Here's what my backend returns for instance:
{
  "id": 37,
  "title": "schedule",
  "semesterId": "Spring 2025",
  "entries": []
}

### Steps To Reproduce

```
    const {formProps, modalProps, close, mutationResult} = useModalForm({
            action: "create",
            defaultVisible: true,
            meta: {
                select: "*",
                gqlMutation: CREATE_CLASS_SCHEDULE_MUTATION,
            },
        onMutationSuccess: (response) => {
            console.log('Full response:', response);
            const createdSchedule = response?.data?.createClassSchedule;
            if (createdSchedule) {
                console.log('Created schedule:', createdSchedule);
                onFinish(createdSchedule as ClassSchedule);
                close();
                onClose();
            } else {
                console.error('Created schedule data is missing from the response');
            }
        },
            onMutationError: () => {
                throw new Error("Failed to create schedule");
            },
        }
    );
```

### Expected behavior

The data should've returned in that aforementioned style, but yet it keeps returning data undefined and context undefined

### Packages

- @refinedev/antd@5.45.1
- @refinedev/core@4.57.1

**Comment by alicanerdurmaz** [comment]
Hello @maximdolphin, thanks for the issue.

By default, `@refinedev/graphql` gets data from a response like this:
- https://github.com/refinedev/refine/blob/main/packages/graphql/src/dataProvider/index.ts#L159
- https://github.com/refinedev/refine/blob/main/packages/graphql/src/dataProvider/options.ts#L214
```tsx
const key = `updateOne${camelcase(singular(params.resource), {
       pascalCase: true,
})}`;

return response.data?.[key]
```
 
If your backend returns a different format, [you need to give your `dataMapper`](https://github.com/refinedev/refine/blob/main/packages/graphql/src/dataProvider/options.ts#L214) to get your data.

**Comment by maximdolphin** [comment]
@alicanerdurmaz understood, thank you for that. Problem solved
